### ISSUE TITLE
Uhren ansteuern

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#1]
Wir haben in fast jedem Raum eine "Tochteruhr", die einen Impuls von einer Hauptuhr benötigt um zu funktionieren - da scheint aber nichts anzukommen und alle stehen still. Wäre cool, die wieder zum Laufen zu bringen!

Ich habe heute mit Mitja gesprochen und es gibt wohl einen Verteilerkasten vorne beim Sicherungsschrank im Gemeinschaftsraum, auf dem "Uhr" steht.

Henrik hat auch schon etwas recherchiert:

> Es gibt verschiedene Typen welcher genau im Space ist muss man mal schauen. Hab auch ne Website gefunden wo man Steuerungen für solche Uhren bekommen kann. http://www.nebenuhrsteuerung.de/Preise.htm#MinImp

Es haben auch schon mehrere andere Interesse bekundet an den Dingern rumzubasteln, also ist dieses "Issue" hoffentlich ein guter Weg, sich auszutauschen :-)

**Comment by LukasFreeze** [comment]
Da sind die Verteilerdosen:

![inkedimg_20171118_023521_li](https://user-images.githubusercontent.com/19755883/32983079-739d64ae-cc8f-11e7-8c80-4db561b2c24a.jpg)

Sieht mir danach aus als wäre da Netzspannung drauf, vielleicht sollte erstmal ein Elektriker drüberschauen und rausfinden, an welcher Sicherung wir da hängen - @emka, weißt du wann Jan mal wieder vorbeikommt?

**Comment by Henrik99** [comment]
Ich hab mir eben mal die Uhren und die Dose angeschaut. Die Uhren sind Nebenuhren welche jede Minute ein 24V Signal mit wechselnder Polarität bekommen. In der Dose sind die drei Leitungen parallel geschaltet (evtl kommen sie aus einem andern Teil des Gebäudes) Wer weiß wie man herausfinden kann welche Leitungen wo hin führen kann es ja mal versuchen. Es wäre perfekt wen wir alle unseres Uhren parallel anschließen können. Dazu brauchen wir noch eine Steuerung für die Uhren. ![img_20171122_204816](https://user-images.githubusercontent.com/33910698/33146997-84dd9fec-cfc6-11e7-9786-aa9f8916e6f2.jpg)

**Comment by Henrik99** [comment]
Ich werde die Tage mal versuchen eine einfache Steuerung zu bauen.

**Comment by Henrik99** [comment]
Also ich hab jetzt eine Steuerung zusammen gebastelt die funktionieren sollte. Jetzt müssen wir nur noch herausfinden wie die Uhren in der Wand verkabelt sind. @emka Lukas hat gesagt du kennst einen Elektriker. Weist du ob der uns da weiter helfen könnte?

**Comment by LukasFreeze** [comment]
@JohannesGruhler hatte den Einfall, statt einem Profigerät einfach eine Kabeltrommel als Leitung für eine 30-Meter-Durchgangsprüfung mit einem Multimeter zu nutzen und es hat geklappt! Ein Uhrenschaltkreis scheint die "Büroräume" auf der Ostseite des Gebäudes zu versorgen und einer die Werkstätten und den Gemeinschaftsraum.

Wir haben die Uhren dann gestern noch eingestellt und sie liefen mit der Steuerungselektronik von @Henrik99 einwandfrei :-)

Jetzt sollten wir in ein paar Wochen nochmal schauen wie genau es ist und uns vielleicht um eine schönere Anbringung für die Elektronik kümmern (hängt aktuell an einer Schnur).

Dieses "Issue" mach ich aber schonmal zu, weitere Schritte können wir ja vielleicht auf einer Projektseite im Wiki festhalten?

**Comment by LukasFreeze** [comment]
Mittlerweile gehen die Uhren ca. 4 min vor, was wäre die beste Möglichkeit um das zu korrigieren? Wenn der Controller ausgestöpselt wird springt ja der Akku ein, aber die Tasten können nur noch weiter vor...
