### ISSUE TITLE
Schweißausrüstung vervollständigen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#10]
@Pakue95 hat vor einiger Zeit einen Schweißtrafo mitgebracht, um den (und die ansonsten benötigte Ausrüstung!) sollten wir uns bald mal kümmern.

Was mir gerade so einfällt (gerne ergänzen):
- [x] Trafo warten (z.B. Drehstromanschluss - Jan?)
- [ ] schauen welche Elektrodenstäbe da sind und ggf. sortieren
- [x] Schweißvorhänge (vor dem Fenster neben der Tür zur Metallwerkstatt)
  - [x] schwarze Folie ans Fenster kleben - spart einen Vorhang
  - [x] Planen aussuchen, z.B. [hier](https://schweisser-schutz.de/schweissvorhang/)
  - [x] Gestelle bauen (fertige sind verdammt teuer)
  - [x] Planen kaufen, wenn der Rest vorbereitet ist
  - [x] ~~Glasfasergewebe dunkel färben~~ Bühnenvorhänge o.ä. besorgen
  - [x] Vorhänge zur Aufhängung mit Ösen o.ä. versehen
  - [x] Platten für mehr Stabilität unter die Gestell-Füße (Eimer) schrauben
- [x] Schutzkleidung besorgen
  - [x] eine volle Ausrüstung für den Schweißer
  - [x] zweiten Schweißhelm für Einweisungen (bestellt 2018-4-29)
- [x] [Einweisung](https://wiki.comakingspace.de/Arc_Welding_Introduction) definieren

Die Dokumentation gehört natürlich auch wie immer dazu, ich habe schonmal die Seiten [Category:Welding](https://wiki.comaking.space/Category:Welding) und spezifisch fürs "Elektroden-"/Lichtbogenhandschweißen [Shielded Metal Arc Welding](https://wiki.comaking.space/Shielded_Metal_Arc_Welding) angelegt. Jegliche weiteren Infos zum Trafo, Arbeitsschutz, Elektroden, Techniken etc. fehlen aber noch und sind sehr willkommen ;-)

**Comment by Pakue95** [comment]
Man sollte auch schauen welche Elektrodenstäbe da sind und ggf. sortieren.

**Comment by LukasFreeze** [comment]
Wir haben den Trafo gestern mal geöffnet und auf den "assembly table" in der Metallwerkstatt gestellt.

Der Schalter ist irgendwie relativ kompliziert, aber wer sich damit auskennt wird schon klarkommen - @emka, magst du Jan mal fragen ob er das mit dem Drehstromanschluss noch machen will und wenn ja, was er dafür braucht? Wenn das noch länger dauert würde ich vorschlagen, einfach erstmal den vorhandenen 230-V-Anschluss zu benutzen und uns davon nicht weiter aufhalten zu lassen - Upgrade zu einem anderem Zeitpunkt natürlich nicht ausgeschlossen ;-)

@JohannesGruhler hat außerdem den Anschluss an der Masseklemme (?) neu gemacht, der war ziemlich zerfleddert.

**Comment by LukasFreeze** [comment]
Hab ein Drehstromkabel vor dem Schrott gerettet und dazugelegt.

**Comment by emka** [comment]
Ich würde erstmal nicht darauf warten. Andrea hatte das Gerät schon überprüft.

**Comment by LukasFreeze** [comment]
Johannes und ich haben gestern eine Zugentlastung eingebaut und das Gehäuse wieder verschraubt, nachdem entschieden wurde, den Trafo erst einmal nur mit 230 V zu betreiben. Mit dem Drehstrom warten wir, bis die Steckdose nach draußen verlegt ist.

Jan hat uns netterweise eine Schweißerjacke spendiert, die beim Gerät liegt. Ein Automatik-Schweißhelm ist bestellt und sollte diese Woche noch ankommen :-)

**Comment by LukasFreeze** [comment]
Ich habe ein paar Schweißhandschuhe besorgt, sodass das Ganze bald mal ausprobiert und fertig dokumentiert werden kann - vor allem eine Einweisungsseite. Als nächstes brauchen wir dann einen zweiten Satz Ausrüstung und die Vorhänge, um nicht nur alleine mitten in der Nacht schweißen zu können ;-)

**Comment by LukasFreeze** [comment]
Wir haben neulich probeweise ein paar Nähte geschweißt und es klappt schonmal! Es gibt aber immer noch einiges zu tun bevor wir das Gerät regelmäßig nutzen und auch mit Schutzgasschweißen beginnen können...

Hier schonmal der Anfang einer Wiki-Seite zu den Stabelektroden: https://wiki.comaking.space/Material:Welding_Electrodes

Parallel zur Dokumentation sollten wir uns als nächstes intensiver um die Schutzvorhänge kümmern.

**Comment by LukasFreeze** [comment]
der zweite Schweißhelm ist unterwegs! :-)

**Comment by LukasFreeze** [comment]
So, ich versuche den zweiten Schweißhelm morgen mitzubringen und dann ist die grundlegende Schutzausrüstung erstmal da. Wenn wir irgendwo noch eine Lederschürze in die Hände bekommen wäre das natürlich nicht zu verachten ;-)

**Comment by LukasFreeze** [comment]
Meine Wahl für Planen wären diese hier: https://www.amazon.de/dp/B00KRA55TE

Sie sind 2x1.4 m groß, also nicht ganz so gut für den oben beschriebenen "Würfel" geeignet aber ich hatte jetzt auch die Idee einer weniger starren Konstruktion, die erstmal für kleinere Projekte erprobt werden könnte (4 Planen = ca. 160 €, vielleicht aus Spenden vom Benefizkonzert Anfang Juli finanzierbar?) und bei Bedarf (Autoschrauber o.ä.) leicht erweiterbar wäre.

Als Halterung bräuchten wir jeweils etwas senkrechtes an den Säulen (soll ja am Gebäude "dicht" sein) und eine Stange mit schwerem Fuß, die an ihrem oberen Ende ein Drahtseil spannen würde, worauf die Planen gefädelt sind.

So in etwa - was meint ihr?
![grafik](https://user-images.githubusercontent.com/19755883/43268589-50b4d19e-90f1-11e8-8051-2d9e35fdede7.png)

**Comment by LukasFreeze** [comment]
Naja "reinstürzen" würde ich nicht sagen, hier ist nur lange nichts
passiert und ich würde gerne die Planen aussuchen, um mit den Maßen eine
Aufhängung zu bauen und *dann* das Geld für die Plaen auszugeben.

Notwendig sind die Planen aus allen von dir genannten Gründen, außerdem ist
die Metallwerkstatt durch die weißen Wände (Reflexion der UV-Strahlung) und
die Fenster (Gefahr für Neugierige draußen) kein guter Ort zum Schweißen.

An die Nachteile vom Dreieck hatte ich noch gar nicht gedacht, da hast du
sicherlich Recht...was ich danit aber hauptsächlich veranschaulichen wollte
war der Vorschlag von flexiblen Aufhängungen statt starrer Rahmen, da
könnte man leicht zwei statt einer Stange bauen und schon hätte man die
Optionen "Quadrat" und "Trapez" zur Verfügung. Die sollten so gut wie
nichts kosten, ich hatte daran gedacht einfach eine Stange/Rohr in einem
Eimer mit Beton einzugießen.

**Comment by NitramLegov** [comment]
Sorry, "reinstürzen" war falsch ausgedrückt, sollte nicht negativ rüberkommen ;) Prinzipiell erschienen mir hier nur 160€ erst einmal als relativ teuer.
Ich versuche mal, unsere Diskussionen zusammenzufassen:
Prinzipiell habe ich es so verstanden, dass folgende Punkte berücksichtigt werden sollten:
- Brandschutz
- Sichtschutz für "Neugierige" & Gefühl des "Eingesperrtsein"
- Flexibilität / Erweiterbarkeit
- Luftzirkulation (darum draußen)
- Preis

Fangen wir mal oben an:
**Brandschutz**
Wenn ich mir den Schweißvorhang anschaue, steht da "Maximale Hitzebeständigkeit: ca. 80°C". Meiner Meinung nach ist das nicht wirklich viel. Spezielle [Schweißschutzdecken](https://www.amazon.de/dp/B00TSIMY18/) sprechen von 700°C bis 1000°C (was zumindest mal kurzzeitig die versehentliche Berührung mit einem Bauteil aushalten könnte).
Luca hat gestern erwähnt, dass Baumwolle wohl ziemlich Brandfest sein soll. Prinzipiell sollten [Löschdecken](https://www.amazon.de/dp/B01MXPK0LI/) einen besseren Brandschutz für weniger Geld bieten.

**Sichtschutz für "Neugierige" & Gefühl des "Eingesperrtsein"**
Hier geht es darum, dass neugierige Außenstehende durchaus sehen können, was gemacht wird und dass der Schweißer nicht auf vier Seiten von undurchsichtigen Planen umgeben ist und sich entsprechend eingesperrt fühlt. Die von @LukasFreeze vorgeschlagenen PVC Vorhänge hätten den Vorteil, dass sie transparent sind. Feuerlöschdecken haben das entsprechend als Nachteil

**Flexibilität / Erweiterbarkeit**
Find ich einen guten Punkt. Hier müssten wir uns bei Löschdecken etwas eigenes überlegen, die Vorhänge können ja einfach zusammengeklipst werden

**Preis**
Preislich sind die [Vorhänge](https://www.amazon.de/dp/B00KRA55TE) relativ teuer (14,28€ / qm).
Die [Löschdecken](https://www.amazon.de/dp/B01MXPK0LI/) liegen bei 7€/qm. 


### Fazit / tl;dr:
Prinzipiell haben beide Varianten ihre Vor- und Nachteile. Die Vorhänge sind teuer und nicht sehr hitzebeständig. Löschdecken sind günstig, müssen aber selbst zusammengenäht (?) werden und schließen den Schweißer von seiner Umgebung ab. Daher wäre der Vorschlag, den Großteil über Löschdecken abzudecken und zusätzlich einen Vorhang zu kaufen. Damit hat man eine günstigere Lösung, die gleichzeitig den Schweißer optisch nicht abriegelt.

**Comment by LukasFreeze** [comment]
Soweit ich das verstehe sind diese Decken mit hoher Temperaturbeständigkeit
dazu da, Untergründe oder z.B. den Motorraum eines bearbeiteten Fahrzeugs
vor Spritzern zu schützen. Aufhängen würde man die eher nicht, oder? Und
sie sind sehr teuer...

Ich finde die Idee mit den Löschdecken aber super! Gestern hatten wir ja
überlegt, zwei 2x2 m Löschdecken und einen 2x1.4 m Schweißvorhang zu
kombinieren. Der transparente Vorhang wäre dann eine Art "Eingang" und
bietet gleichzeitig etwas Sicht auf die Umgebung als auch "Zuschauern" eine
Möglichkeit, das Schweißen aus sicherer Entfernung zu betrachten. Diese
Seite sollte meiner Meinung nach auf die Gebäudeecke/die Tür der
Metallwerkstatt zeigen, da stünde ja auch bei der Arbeit die Tür offen und
die Schweißer sollten sie grob im Auge haben können. Was die Aufhängung der
Löschdecken betrifft können wir ja notfalls erstmal mit Leimzwingen
anfangen, aber ich glaube ein paar Ösen und Druckknöpfe sind schnell
gesetzt :-)

Preislich lägen wir mit zwei Löschdecken und einem Schweißvorhang jetzt
unter 100 €.


Für die Aufhängung hat Armin gestern schon zwei Stangen mit
"Ruck-Zuck-Beton" in alten Farbeimern eingegossen und ein Drahtseil und
Kleinteile besorgt, das ganze steht mit einem "help the space"-Zettel in
der Metallwerkstatt.



2018-08-02 12:03 GMT+02:00 NitramLegov <notifications@github.com>:

**Comment by NitramLegov** [comment]
Added the commissioning template to the wiki

**Comment by LukasFreeze** [comment]
[Schweißhelme](https://wiki.comakingspace.de/Welding_Helmets) sind soweit es bisher nötig sein sollte dokumentiert! :-)

Ich habe jetzt wie besprochen zwei Löschdecken und einen Schweißvorhang bestellt, damit sollte die "Kabine" im Hof bald fertiggestellt werden können!

**Comment by LukasFreeze** [comment]
Die Löschdecken sind da - leider sind sie weiß und dürften damit problematisch sein, was die Reflexion der UV-Strahlung beim Lichtbogenschweißen angeht :-(

Wir sollten sie also irgendwie einfärben, bevor wir schweißen... weiß jemand, wie das mit Glasfasergewebe gehen könnte? Ich schreibe mal einen [Anbieter von solchen Stoffen](https://www.jostra.de/Glasgewebe/) an, könnte ja klappen. Außer bunten Stoffen haben die auch weißen im Angebot, der mit "Solventtinten" bedruckbar sein soll, vielleicht ein Anhaltspunkt?

**Comment by LukasFreeze** [comment]
Ich habe es vorsichtig mit einem Permanentmarker ("Rex", von Aldi) versucht und das klappt überraschend gut! Ähnliche Tinte gibt es hoffentlich günstig irgendwo "lose" zu kaufen, macht ja keinen Sinn zigtausend Marker zu verschwenden...hat jemand Ideen zu Bezugsquellen? 1 Liter Edding-Tinte kostet 60 € :-/

**Comment by Pakue95** [comment]
Vielleicht würde wasserfeste Tusche zum Schreiben auch funktionieren? Die bekommt man in Dosen bzw. Airbrush Farbe könnte auch gehen.

**Comment by LukasFreeze** [comment]
Tusche habe ich bisher leider auch noch nicht unter 50 € pro Liter gefunden :-(

Vielleicht probieren wir erstmal doch einfach Sprühlack? Ich kann auch absolut nicht einschätzen, wie viel flüssige Farbe das Gewebe aufsaugen würde...

**Comment by NitramLegov** [comment]
Doofe Zwischenfrage: müssen wir uns Gedanken darüber machen, ob die Farbe brennbar ist?
Nicht dass wir unsere löschdecken färben und die auf einmal brennen wie Zunder...
________________________________

**Comment by LukasFreeze** [comment]
Ich denke nicht dass sie komplett unbrennbar sein muss, hauptsächlich sind sie ja zur Abschirmung der Strahlung. Wenn die wirklich Hitze abkriegen, wurde seltsam geschweißt...

Wir können natürlich trotzdem erstmal ein Teststück machen und mit nem Feuerzeug drangehen, wäre blöd wenn die Farbe nach ein paar Metallspritzern schon abfackeln würde.

**Comment by LukasFreeze** [comment]
André schaut mal, ob er uns nächsten Mittwoch Tinte mitbringen kann. Die Glasfaserdecken bräuchten am besten auch noch Ösen, um sie am Drahtseil aufzuhängen.

**Comment by LukasFreeze** [comment]
Ich hab mal begonnen, unsere Pläne auch im Wiki zusammenzufassen: https://wiki.comakingspace.de/Welding_Enclosure

@JohannesGruhler hatte außerdem die Idee, einen Schraubstock auf den zukünftigen Schweißtisch ("Ghetto-Kreissäge" neben der Tür zur Metallwerkstatt) zu schweißen. Armin hat uns mal einen gegeben, ich weiß aber nicht ob wir den dauerhaft anbringen dürfen - sonst könnten wir den abschrauben, der in der Holzwerkstatt auf der Werkbank vor den Schraubenschlüsseln/Scheren/Raspeln steht, und den von Armin da hinschrauben. Also sollte ihn mal jemand fragen :-)

**Comment by LukasFreeze** [comment]
War André nochmal da? Sonst würde ich ihm nochmal schreiben, wenn das mit der Tinte nix wird müssen wir ja nicht unnötig warten...

Aber außer dem Färben gibt es ja eh noch weitere Schritte zu bearbeiten, falls jemand helfen möchte!

**Comment by Pakue95** [comment]
Ja, er war da. Hat aber keine Tinte mitgebracht.

**Comment by LukasFreeze** [comment]
Hat er es denn schon versucht oder noch vor? Hmm...

**Comment by Pakue95** [comment]
Ich glaube er hat nur nicht daran gedacht. Werde ihm mal schreiben.

**Comment by Pakue95** [comment]
Er bringt welches mit. Die im Labor haben nur nicht immer welches übrig.

**Comment by LukasFreeze** [comment]
Super, ich hatte nur Angst dass wir es aus den Augen verlieren könnten

**Comment by LukasFreeze** [comment]
Wir schauen jetzt mal nach alten Bühnenvorhängen, die sollten blickdicht und schwer entflammbar sein.

Micha M. hat eventuell eine Quelle, ich frage außerdem mal in "Free Your Stuff"/"Free Your Advice" auf Facebook (schadet eh nicht, den Space da mal wieder zu erwähnen)

**Comment by LukasFreeze** [comment]
Michas Kontakt hatte leider doch nichts anzubieten, ich würde jetzt 4 m [3 m breiten Bühnenmolton](https://www.moltonexpress24.de/buehnenmolton-schwarz-9999-meterware-300cm-breite-300g-m?action_ms=1) bestellen, damit es weiter gehen kann. Damit können wir die Schweißkabine als Trapez mit ca. 2-3-3-2 m Seitenlängen aufspannen, was für den Anfang meiner Meinung nach locker reicht.

Der Stoff ist schwer entflammbar und "B1" zertifiziert, d.h. nach Entfernung der Hitzequelle "löscht" er sich selbst. Außerdem nach Verkäuferangabe blickdicht (der leichtere "Dekomolton" auf der gleichen Seite scheinbar nicht), sobald das Paket ankommt können wir das ja überprüfen und ggf reklamieren.

**Comment by LukasFreeze** [comment]
Die Bühnenvorhänge sind angekommen und liegen bei den anderen Teilen auf der Fensterbank der Metallwerkstatt :-)

Beim Abholen im Paketshop (Autowerkstatt um die Ecke) hab ich mich direkt noch nach einem Schweiß-erfahrenen Mitarbeiter durchgefragt, der sich unser Setup an einem der nächsten Mittwoche mal angucken kommt und den Plan schonmal solide fand (puhh..)

**Comment by LukasFreeze** [comment]
Die Kabine steht! Danke @lmnl99 und später auch @Johannes09 für die Hilfe heute Abend (hatte spontan in der WhatsApp-Gruppe dazu aufgerufen) :-)

Ich habe das Ganze kurz ausprobiert um zwei Rollen an den künftigen Schweißtisch zu schweißen, bevor aber an irgendwelche privaten Projekte oder generell eigenständiges Schweißen von Mitgliedern zu denken ist muss noch die Einweisung definiert werden! Ich habe da schon länger Notizen gesammelt und schreibe sie bei nächster Gelegenheit mal zusammen, um mit Leuten mit Schweißschein drüberzuschauen. Nicht mehr lange...

**Comment by LukasFreeze** [comment]
Wir sind gestern Abend mit der Einweisung sehr viel weiter gekommen, das "commissioning" des Schweißgerätes hab ich auch gerade aktualisiert :-)

Es sollte dann bald losgehen - hier schonmal die Warteliste "vorab" als Belohnung fürs Issues lesen ;-) 
https://wiki.comakingspace.de/Arc_Welding_Introduction/Waiting

Was im Moment noch an Wiki-Doku fehlt wird dann hoffentlich bald "im laufenden Betrieb" ergänzt, vor allem etwas mehr zu den Schweißhelmen (erstmal liegen ja Handbücher dabei, aber die verschwinden sicher früher oder später...), mehr Erfahrungen zu den [Elektroden](https://wiki.comakingspace.de/Material:Welding_Electrodes) und vor allem Bilder und Infos zum [Schweißtrafo selbst](https://wiki.comakingspace.de/Welding_Transformer)

**Comment by FHuchinson** [comment]
Sooooo jetzt kann ich endlich mal mit Fachwissen brillieren!

**Decken**
Die Decken sollten so bald wie möglich ersetzt werden. Baumwolle bietet keinen ausreichenden Schutz gegen das ausgestrahlte Licht (ich hab durch zwei Lagen Kleidung schon nen Sonnenbrand auf dem gesamten Bauch gehabt. Gibt angenehmeres) Leder eignet sich eigentlich super, ist aber teuer. Ich hab Ideen, werde aber, bevor ich die publik mache, definitiv nochmal die SLV konsultieren. Wenn jemand Ahnung hat, dann die.

**Brandschutz und Co.**
Ist eigentlich nicht das größte Problem. Natürlich sollten Metallbrandlöscher, Löschdecken und dergleichen für den Ernstfall an bekannten nahen Orten sein (v.a. wegen der Versicherung). Gefährlicher ist aber der Lichtbogen. Daher darf auch nichts durchsichtiges an der Kabine sein!!! Einmal blöd direkt in den Lichtbogen geguckt und man sieht mindestens ein paar Tage fleckig. Wenn man Glück hat... Die Spritzer bestehen hauptsächlich aus Schlacke. Dazu ist die Spritzmenge von der Ummantelung abhängig, da die Ummantelung für die Tropfengröße hauptverantwortlich ist. Aber das ist gut abgekühlt, bis das auf irgendwem landet. Tut etwas weh, aber selbst ein noch heißer Topf ist schlimmer. 

Ich gebe gerne Kurse oder sowas (auch wenn ich wenig Erfahrung habe) mit dem Wissen, den ich von meinem letzten Schweißlehrgang noch habe. Scheint ja irgendwie doch nicht zu wenig sein. Dass ich bereit wäre dafür Tutor zu werden ist Lukas ja bekannt. Es verlangt Arbeit, aber das wird super. Schweißen ist geil!

Oh Gott bin ich froh, dass ich das mal gelernt hab :D

**Comment by LukasFreeze** [comment]
Wie schon gesagt sorry für die verspätete Antwort @FHuchinson, aber ich hatte mir vorgenommen richtig Urlaub zu machen :-)

> Decken
> Die Decken sollten so bald wie möglich ersetzt werden. 

Das sehe ich nicht so - hier müssen wir uns nochmal vor Augen führen, wofür die Decken da sind: Schutz der möglicherweise draußen rumlaufenden Leute vor dem Lichtbogen. Die Entfernung ist deutlich größer als beim Schweißer selbst, der Stoff *mindestens* so dicht wie mehrere Lagen Kleidung und auch die Dauer der Exposition zur Reststrahlung so gering, dass ich mir da absolut keinen Sonnenbrand vorstellen kann. 
Nichtsdestotrotz wäre ich natürlich gespannt, wass du noch in Erfahrung bringen kannst! Leder ist im (nassen) Außenbereich auch nicht als Vorhangmaterial geeignet, aber zum Schutz des Schweißers selbst wollte @LarsKumbier glaube ich mal eine Schürze besorgen?

> Gefährlicher ist aber der Lichtbogen. Daher darf auch nichts durchsichtiges an der Kabine sein!!!

Da gebe ich dir völlig recht! Wo die Schweißkabine definitiv endlich mal wieder etwas Liebe bräuchte sind die Aufhängungen (zwei oder drei Ösen leider schon ausgerissen afaik) und die Ecken, wo sich zwei Decken treffen - hier können sich bei einem hastigen Aufbau aktuell leider noch viel zu leicht Löcher auftun, durch die dann irgendein Pechvogel geblendet werden könnte.

> Die Spritzer bestehen hauptsächlich aus Schlacke. [...] Aber das ist gut abgekühlt, bis das auf irgendwem landet. Tut etwas weh, aber selbst ein noch heißer Topf ist schlimmer.

Da wird Iggy dir aber widersprechen, der hatte schonmal böse Erfahrungen mit einem Spritzer im Schuh :-P In solchen Fällen gehen wir lieber immer vom schlimmsten aus und warnen in der Einweisung gut vor der Gefahr

> Ich gebe gerne Kurse oder sowas (auch wenn ich wenig Erfahrung habe) mit dem Wissen, den ich von meinem letzten Schweißlehrgang noch habe. Scheint ja irgendwie doch nicht zu wenig sein. Dass ich bereit wäre dafür Tutor zu werden ist Lukas ja bekannt. Es verlangt Arbeit, aber das wird super. Schweißen ist geil!

Sehr cool! Tutor werden ist geil ;-)
Dann schauen wir auf jeden Fall mal dass du zügig die Einweisung kriegst, und wenn du dich mit unserem Equipment etwas vertraut gemacht und wieder mehr Erfahrung gesammelt hast können wir dich mal auf neue Lehrlinge loslassen :-D


Da dieses Issue schon sehr alt ist und der letzte fehlende Punkt in der Beschreibung - Elektrodenstäbe checken/sortieren - mittlerweile auch [einigermaßen erledigt](https://wiki.comakingspace.de/Material:Welding_Electrodes) ist (mehr Inhalt natürlich wie immer sehr willkommen!) würde ich jetzt hier auch mal zumachen, falls wir über die Vorhänge nochmal diskutieren müssen wäre das vielleicht in einem neuen Issue übersichtlicher :-)
