### ISSUE TITLE
Cnc router sounds odd

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#100]
Last week when I was using the cnc router, it sounded a bit scary when moving along the x-axis.
It didn't sound like something broke but rather like it would be unhealthy to keep using the router (especially for bigger jobs like the upcoming #51)

When looking at the axis, it looked dirty to me. So it might already help to thoroughly clean the router. However, somebody with more clue might want to have a look in order to double check what I just said..

**Comment by LukasFreeze** [comment]
I heard it this Wednesday and think one or two wheels on the x-axis are
stuck. This could be due to incorrect pressure, as Patrick suggested in the
Telegram group, or perhaps we should oil the bearings now and then?

Pressure should definitely be checked (and adjusted, if necessary) first.

**Comment by LukasFreeze** [comment]
I meant oil the ball bearings (if present), not the wheels or the profiles
of course :-)

**Comment by NitramLegov** [comment]
So the issue here was that unfortunately the belt of the X-Axis was moving to the front and therefore caused issues with the wheels.

In order to fix it, we applied the same principle as in the bandsaw: We adjusted the angle of the motor. First manual tests look like it fixed the issue. The reason for "manual test" will be described in a new issue.
