### ISSUE TITLE
CNC probleme mit der Referenzfahrt

### ISSUE THREAD

**Issue by Johannes09** [comakingspace/do-something#101]
Die CNC führt den Referenzfahrt Befehl nicht richtig es wird nur die Z Achsen Endstop wird abgefahren. 
Ich vermute es könnte was mit dem letzten Software update zu tun hat. @Narquadah  @NitramLegov

**Comment by NitramLegov** [comment]
Hmmm, das software update sollte damit nichts zu tun haben. Da ging es ja nur um das control panel. Und es wurde auch nur da etwas geändert.

Ich hatte das aber auch schonmal. Bei mir war da irgendein Problem mit den endstopps. Die fräse dachte also, dass sie die endstopps schon getriggert hatte... Was geholfen hatte war, die endstopps mal manuell zu drücken und die fräse komplett aus und wieder einzuschalten.
Wichtig beim aus und wieder einschalten ist nur, dass man auch den pi von der fräse trennt oder runter fährt. Sonst versorgt der den Controller weiterhin mit Strom.
________________________________

**Comment by LukasFreeze** [comment]
@Johannes09 das Problem war am Freitag nicht mehr da, oder? Also bevor #104 aufgetreten ist...dann könnten wir hier wieder zumachen. Wenn das öfter auftritt und @NitramLegov s Tipp geholfen hat, sollte es allerdings in die [Einweisung der CNC-Fräse](https://wiki.comakingspace.de/CNC_Router_Introduction) aufgenommen werden, findet ihr nicht?
