### ISSUE TITLE
Bohrmaschinenhalter

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#102]
In letzter Zeit bietet sich leider häufig der Anblick von auf dem Boden liegenden Bohrmaschinen, weil es schwierig ist die Maschinen samt Kabel sicher auf den momentan sehr simplen Halter zu legen. Und selbst dann fällt oft etwas runter, sobald es an der Säulenbohrmaschine mit mehr Vibrationen zugeht (große Bohrer, Raspeln etc).

Ich habe die Maschinen am Mittwoch dann liegen gelassen, da wir das Problem hoffentlich heute Nacht bei den "do-something hours" schon angehen können und in der Zwischenzeit das Liegen sicherlich besser für die Geräte ist als das Fallen :-P

Mein Vorschlag wäre, erst einmal den jetzigen Halter zu behalten, aber an die Spitzen jedes Dübelpaars eine begrenzende Platte zu montieren. Hoffentlich reicht das schon!

**Comment by NitramLegov** [comment]
Wie wäre es mit sowas?
[Bild]

________________________________

**Comment by NitramLegov** [comment]
Wie wäre es mit sowas?
![image](https://user-images.githubusercontent.com/7809163/54828544-b79f3780-4cb4-11e9-8c55-2905acc5b47c.png)

**Comment by LukasFreeze** [comment]
Wer immer sich Zeit dafür nimmt kann gerne kreativ werden, ich würd meine einfache Lösung vorziehen ;-)

Akkuschrauber haben einen ganz anderen Schwerpunkt als Bohrmaschinen, es müsste also auf jeden Fall erstmal experimentiert werden wie das Brett für Bohrmaschinen (ggf mit zwei Griffen) aussehen müsste

**Comment by NitramLegov** [comment]
Also als provisorium haben wir gestern kleine Holzstücke vorne hingeklebt. Die halten nicht viel aus, aber hoffentlich genug.

Ob man das hier zumacht oder erstmal auslässt, bis wir eine vernünftige Halterung haben überlass ich euch..

**Comment by LukasFreeze** [comment]
reicht wahrscheinlich erstmal, wenn da jetzt aber jemand wieder dran rumreißt (ähem) würde ichs nochmal richtig aufziehen
