### ISSUE TITLE
Stereoanlage braucht Schönheitsreparaturen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#103]
Unsere [Stereoanlage](https://wiki.comakingspace.de/Sound_System) (genauer gesagt der Verstärker, "Dual CR 5950 RC") hat ein paar Macken, die zwar durch diverse Workarounds gerade nicht ins Gewicht fallen aber doch mal gesammelt angegriffen werden könnten, wenn jemand sowieso etwas dran machen will:

- 1 von 4 channels defekt (also können wir keine 4 Lautsprecher anschließen) - evtl wegen eines Leistungstransistors?
- das Signal der Fernbedienung kommt nicht mehr an - defekter IR-Receiver?
- der Radioempfang funktioniert nur noch sehr selten, irgendwo scheint im Innenraum das Signal verloren zu gehen - kalte Lötstelle oder trockene(r) Elko(s)?

**Comment by Pakue95** [comment]
Ich kann mir mal die Innereien anschauen und durchmessen, vielleicht ist es etwas offensichtliches. 

Für die gute alte Hardware gibt es noch ausführliche Service Dokumente mit Schaltplan und Layout:
[hfe_dual_cr_5950_rc_service_en_de.pdf](https://github.com/comakingspace/do-something/files/3008632/hfe_dual_cr_5950_rc_service_en_de.pdf)

Der AM input hat idR keine Elkos die kaputt gehen können; das ist eher ein Fehler der bei der Stromversorgung auftritt. Tendenziell würde ich auf den Vorverstärker tippen, bei dem über die Jahre die Kondensatoren in ihren Werten gedriftet sind, oder die Transistorgrundschaltung des J-FETs die für schlechte Verstärkung sorgt.

**Comment by Pakue95** [comment]
Den IR Empfänger (Part IC 841) habe ich gestern gegen einen einfachen Empfänger von Pollin ausgetauscht und die Fernverbindung funktioniert nun wieder. 

Johannes und ich haben auch noch probiert beide Channels gleichzeitig zum laufen zu bringen. Das Problem liegt nicht an der Anlage, sondern an den Kabeln der kleineren Boxen, die etwas schlechten Kontakt machen. Das Kabel der linken großen Box hat auch eine gelegentlich höhere Impedanz, was man bei Gelegenheit austauschen kann. 

Jetzt laufen alle Boxen gleichzeitig (die kleinen etwas lauter, aber das liegt an deren Impedanz). Wir werden heute oder nächste Woche noch Crimps an die Kabel machen um den Kontakt zuverlässiger zu machen.  

Den schlechten Radioempfang zu debuggen wäre ein größeres Unterfangen und da wir sowieso den extra Empfänger haben sehe ich keinen Grund dazu.
