### ISSUE TITLE
CNC Router Broken

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#104]
1) please describe the problem:
Unfortunately, the [CNC Router](https://wiki.comakingspace.de/CNC_Router) is currently broken.
As a result of fixing #100 during the do-something hours, the CNC-Router had to be moved manually. Unfortunately, when we wanted to try the router after the repairs, the Z-Axis resisted to move properly. Therefore, the Router was not even able to complete a homing cycle and cannot be used.
The current assumption is that the motor drivers on the controller board got fried by the movement. If this is the case, we will need to have a look for a new controller board. Therefore, we should do some research on possible boards. Ideally, we find one with the possibility to also control the router itself (for future upgrades)

2) please make this issue visible after opening it to "warn" others about the downtime and perhaps recruit helpers for a quick repair:
- [ ] send a quick note over the [mailing list](https://wiki.comakingspace.de/Mailing_List)
- [x] link the issue from the tool's wiki page
- [x] apply issue labels (on the right), e.g. "electronics" if you think people with electronics skills are needed to fix this

**Comment by Pakue95** [comment]
If the board is broken it can be a total loss and we have to buy a new (equivalent) one, or just the stepper driver released the magic smoke. In that case it might be repairable by just replacing the IC.

Can somebody check what board/which drivers ICs are used? Buying and installing a replacement should be doable.

Alternatively we can get the same board again if it is still sold. The currently [available Workbees](https://ooznest.co.uk/product/workbee-cnc-full-kit/) models use a Duet (2?) controller board, but I don't think that this is the same board as we currently have. That board is [around £120-£130](https://ooznest.co.uk/product/duet2/) new and may need reprogramming to run Grbl (not sure if that works over an ethernet connection only).

I've also heard good things about the Smoothieboards. It has also 5 stepper drivers on board with an extensive IO selection to control spindles speed etc. The interfaces are USB and Ethernet.

Prices:
* [£130-£140](https://ooznest.co.uk/product/smoothieboard-5xc/)
* [186-194€](https://www.filafarm.de/collections/elektronik/products/smoothieboard)

**Comment by NitramLegov** [comment]
It  should be confirmed by somebody who´s at the space this week, but I am fairly positive we are using the CNC xPro v3 controller board (this website sells it for $129.98):
https://www.circuitspecialists.com/cnc-xpro-controller-v3.html

Ooznest currently sells the xPro v4 for £142.50:
https://ooznest.co.uk/product/cnc-xpro-controller-v4/


According to curcuitspecialists, the xPro v3 uses DRV8825 as the stepper driver.
According to Mouser, these are available in different versions (PWP and PWPR):
https://www.mouser.de/Search/Refine?Keyword=DRV8825

According to the BOM of version 2 (https://github.com/Spark-Concepts/xPRO/blob/master/Assembly/CNCxPro_2V1_BOM.pdf) it should be the PWPR edition...

**Comment by Pakue95** [comment]
PWP(R) is the same IC just either delivered on a reel for automated assembly (R) or in low quantity in a tube. The package is easy to solder, so if it is the correct board we should replace the driver before buying a new board. 

[Arrow](
https://www.arrow.com/en/products/drv8825pwp/texas-instruments) has the IC with free shipping.

**Comment by NitramLegov** [comment]
I ordered the ICs from arrow.
Estimated Delivery Date
Monday, 04/01/2019

Maybe somebody else will need to get it from the packstation at hauptbahnhof

**Comment by Pakue95** [comment]
Regarding the replacement of the IC; do we have some Kapton tape available at the space? As far as I remember there are a lot of screw terminals and other plastic connectors on the board that may not like to be heated with a hot air soldering station. Usually its good practice to cover those areas with some Kapton tape to protect them a little.

**Comment by LukasFreeze** [comment]
yup, a wide roll on the filament shelf.

**Comment by NitramLegov** [comment]
Quick update of what happened this week:
The Replacement ICs arrived and @Pakue95 replaced the Z-MotorDriver with a new one. Unfortunately, this did not help.
Since the behaviour of the router is kind of odd, we were thinking of maybe the microcontroller being the issue. Therefore, we first tried to flash a new firmware on it. Unfortunately, this did not work.
Since the microcontroller is an Atmega328, we tried the firmware flashing logic with a spare arduino nano and it worked.
Therefore, we discussed that possibly the microcontroller might be broken. @Johannes09 is planning to replace it with the one from the aforementioned arduino nano. Hopefully, this works.

**Comment by Pakue95** [comment]
@Johannes09 replaced the atmega but there seems to be no progress.
Yesterday we also noticed, that the P-Mosfet, that is used for the reverse-polarity protection on the input, gets hot. Maybe that got also damaged due to an over voltage. I have some that could serve as a drop in replacement. I'll try to install it during the opening hours tomorrow.

**Comment by Johannes09** [comment]
Die Fräse geht wieder!
die GRBL board Version zurzeit ist 1.1f 
Die current Potis sind auf die Mittlere position gestellt 

Fehler wahren
- ein Kaputter Motortreiber (durch verfahren der z-Achse mit der Hand)
- Einstellungen die nicht richtig vom Pi zum GRBL board übertragen wurden

![IMG_20190414_200012202](https://user-images.githubusercontent.com/22060480/56097108-83ecb180-5ef0-11e9-9ca5-9abd8a3804a1.jpg)
