### ISSUE TITLE
KingCraft Router in Router Table broken

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#105]
Einer der Kabelbinder ist gebrochen, sodass ein Plastikteil der Spindelverriegelung gebrochen ist. Ich habe versucht das Plastikteil zu kleben und das Metallgehäuse wieder mit Kabelbinder zusammen zu halten. Das geklebte Plastikteil habe an die Maschine geklebt und an den Platz für defekte Werkzeuge gestellt.

Auf dem Heimweg kam mit die Idee, ob es eventuell möglich ist das defekte Metallgehäuse und den Mechanismus der Spindelverriegelung komplett zu entfernen, das Gewinde am vom Fräser entfernten Teil an zwei gegenüberliegenden Seiten mit einer Feile abzuflachen, sodass das Gewinde beim Fräserwechsel mit einem Schraubenschlüssel festgehalten werden kann.

Christoph

_Originally posted by @drei85 in https://github.com/comakingspace/do-something/issues/64#issuecomment-475990715_

**Comment by LukasFreeze** [comment]
Schade, aber als ich das mit den Kabelbindern gemacht hab war ja klar, dass
es nur ein Aufschub sein würde...

Also ist die Fräse gerade defekt oder war dein Klebeversuch erfolgreich?

Die Idee mit dem Gehäuse-entfernen-und-Rumfeilen finde ich prinzipiell
interessant, wir haben aber eine noch kaputtere und etwa baugleiche Fräse
an der wir das zuerst probieren sollten.

**Comment by drei85** [comment]
Aktuell steht die Fräse auf der Leiter bei den defekten Werkzeugen. Ob der Klebeversuch erfolgreich war, kann ich nicht sagen, da der Kleber 24h zum aushärten braucht habe ich das Teil am Sonntag geklebt und an die Maschine gehängt. 
Ich habe erste wieder am Samstag Zeit in den Space zu kommen, kann da dann gerne mal ein Test an der defekten FERM starten. 

Gründe die gegen den vorgeschlagenen Reparaturversuch sprechen könnten:
- abgeflachte Flächen werden nicht parallel zueinander > Spiel zwischen Schraubenschlüssel und Spindel > abrunden der Flächen > kein Griff mehr mit dem Schraubenschlüssel
- Spindel verformt sich aufgrund der ungleichmäßigen Hitzeentwicklung
(- beim Fräserwechsel "vergessener" Schraubenschlüssel kann für Verletzungsgefahr sorgen)

**Comment by NitramLegov** [comment]
Auch wenn ich finde, dass der versuch zur Reparatur an Erster Stelle stehen sollte, sollten wir uns glaube ich auch eingestehen, dass die kingcraft und die ferm fräsen einfach nichts taugen...

Möchte parallel dazu jemand eine taugliche fräse raussuchen?

Vielleicht können wir das ja mal als Versuch nutzen, mit einem konkreten (sowohl monetär als auch bzgl. des Verwendungszwecks) Ziel spenden zu sammeln?
________________________________

**Comment by LukasFreeze** [comment]
Die Klebung war leider wie ich schon erwartet hatte erfolglos, diese Teile sind aus nicht klebbarem Kunststoff (wahrsch. PP). Aber die Idee, den Kragen einfach abzubauen, war super! Diese Fräse hatte sogar direkt schon abgeflachte Seiten, wo das normale Teil greifen sollte :-)

Etwas gefeilt hab ich trotzdem - man braucht einen 14er Schlüssel und wir hatten zig 13er, also hat die Fräse jetzt einen "privaten" passenden Schlüssel. So groß wie die Schraubenschlüssel sind schätze ich auch die Verletzungsgefahr sehr gering ein, und selbst wenn man mal einen übersehen sollte wird das Gerät einfach nicht anspringen (kaum 1/5 Drehung vor Kollision mit der ersten Säule).


Für eine langfristige Verbesserung bin ich aber auch auf jeden Fall! Habe schon vor einer Weile die HolzWerken-Spezialausgabe "Oberfräse" gekauft (kann man sich gerne bei mir borgen) und da hat die [Triton TRA 001](https://www.toolstation.de/shop/Elektrowerkzeuge/d40/Fr%C3%A4smaschinen/sd460/Triton+TRA001+Oberfr%C3%A4se/p54513) den Preis-Leistungs-Preis gewonnen. Preis: ca. 300 € - Leistung: einzige Einschränkung, dass sie im Handbetrieb zu wünschen lässt, weil sie so sehr für Frästische optimiert ist :-D

**Comment by LukasFreeze** [comment]
noch ein Foto zur Vollständigkeit (ich habe nichts weiter zerbrochen, der Kragen **war** so kaputt):

![IMGP4483 (Medium)](https://user-images.githubusercontent.com/19755883/55171234-42ca7280-5178-11e9-8b06-4c4d43f676b4.JPG)

**Comment by drei85** [comment]
Danke fürs Reparieren!
Ich war heute am Frästisch und die Variante mit dem Schraubschlüssel hat sehr gut funktioniert.

Falls angedacht ist eine robustere Fräse für den Tisch zu kaufen und ein wenig mehr Geld in die Hand zu nehmen, wäre ich ebenfalls für Triton TRA 001. Glaubt man der Vielzahl an Youtubern bewährt sie sich im Einsatz im Frästisch.
