### ISSUE TITLE
SD-Kartenleser vermisst

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#106]
Sehr großer Mist: ich musste gerade dringend und spontan was drucken ohne meinen Laptop dabei zu haben und dann fehlt einfach der SD-Kartenleser vom PC im 3D- und Elektronikraum.

Falls den sich irgendwer "geliehen" hat bitte sofort zurückbringen! Das Teil ist für viele Leute notwendig, um drucken zu können, und sollte IMMER an diesem PC bleiben :-(

Ich habe jetzt notgedrungen mein Handy als Kartenleser missbraucht und mehr Zeit verloren als der Druck eigentlich insgesamt gedauert hätte, das ist verdammt ärgerlich!

Falls es nicht bald wieder auftaucht, werden wir diese von netten Mitgliedern gespendeten Teile wohl ersetzen müssen...

**Comment by NitramLegov** [comment]
Antwort von @sbillaudelle  auf der Mailinglist:

> Hallo Lukas,
> 
> das mussten Luca und ich leider am Wochenende schon feststellen. Mittags habe ich mit der Karte noch gedruckt, abends war sie dann spurlos verschwunden. Sowas ist echt ärgerlich!
> 
> Vielleicht tauchen die Sachen ja wieder auf…
>

**Comment by sbillaudelle** [comment]
Ich müsste zuhause noch eine kleine SD-Karte haben, die könnte ich sponsern. Einen alten Leser habe ich aber wahrscheinlich nicht.

**Comment by LukasFreeze** [comment]
@Johannes09 hat die SD-Karte wohl auf dem Boden wiedergefunden...leider immer noch keine Spur vom Leser.
Sieht aus als sollten wir den ersetzen, ich rede aber auch nochmal mit allen die an dem Tag da waren :-/

**Comment by LukasFreeze** [comment]
@lokowandg hat uns leihweise einen Kartenleser dagelassen, braucht ihn aber irgendwann wieder.

Falls jemand demnächst also Elektronik kauft, bitte daran denken! Ich beteilige mich/übernehme auch gerne die Kosten, wenn es daran scheitern sollte, hab nur selbst gerade keine Zeit...

**Comment by LukasFreeze** [comment]
Der Ersatz von Patrick (Pollin) funktioniert leider nicht (außer vllt bei direkt eingesteckten microSDs? Bitte testen!)

Georg hat seinen Leser schon zurück, also sind wir erstmal wieder bei "bring your own"...

**Comment by ErikSchatz** [comment]
SD (und mehr)-Kartenleser (hama, blau) von mir gespendet, und er funktioniert!!! Test seit Juni!

**Comment by NitramLegov** [comment]
Dann machen wir hier erstmal zu.
