### ISSUE TITLE
Zing laser cutter accuracy

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#107]
Gregor and I noticed today that the Epilog Zing laser cutter we are currently using is not accurate enough for some technical parts.

Example measurements with the same Vernier caliper:
- 20 mm part in design = 19.7 mm result in Y direction (factor 1.015)
- 5 mm part in design = 4.75 mm result in X direction (factor 1.053)
- 4.9 mm hole in design = 4.6 mm result (factor 1.085)
- kerf approx. 0.025 mm (changing the line thickness in Visicut did not have an effect)

What definitely sticks out is that there is always a similar *amount* missing, not a *factor* (0.35 mm missing, or 0.175 mm per cut).

we already determined that
* inkscape line width doesn't matter
* X or Y orientation produces the same error
* Visicut resolution doesn't matter (tested 200 vs 1000 dpi)
* exact size displayed in Visicut doesn't seem to matter (looked like rounding errors at first)

Any ideas what we might be missing?

**Comment by Pakue95** [comment]
What did you cut to measure the sizes? Can you cut some paper or engrave something to see if it is not some material-related issue?

**Comment by LukasFreeze** [comment]
It's independent of materials, we measured an older piece from a few weeks ago and it also had that error (just wasn't noticed due to a much larger scale).

Also note that the hole size and part size both have the same error - if the cause was just material burning away, holes should become bigger while parts become smaller :-/

**Comment by Pakue95** [comment]
That sounds like there is some backlash in the XY drive of the cutter. Maybe one of the pulleys came a little loose and is causing the loss of the 1/4mm.

**Comment by NitramLegov** [comment]
Since we will be giving back the Laser tomorrow: Can we close this? ;)

**Comment by Pakue95** [comment]
Laser is gone, so let's close this.
