### ISSUE TITLE
Gehäuse für die CNC-Fräse

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#108]
Das Thema kam schonmal auf, ein fertiges Konzept hatten wir bisher nicht.

Ooznest hat gerade angekündigt, dass man jetzt bei ihnen einen Bausatz kaufen kann:
https://ooznest.co.uk/product/workbee-enclosure/

**Comment by NitramLegov** [comment]
Wenn  ich das richtig verstehe kommt man mit diesem Bausatz nur noch von vorne an die Fräse ran, richtig?

Das fände ich persönlich ungeschickt. Das bedeutet jedes Mal wenn man fräsen will folgendes:
1. Fräse anschalten
2. Fräse homen
3. Fräse nach vorne fahren lassen
4. Fräser einbauen
5. Fräse homen (könnte sich ja verschoben haben)
6. Werkstück anfahren, nullpunkte setzen, etc.
7. Fräsen

Das würde bei hohen Werkstücken außerdem die Möglichkeit nehmen, mal eben das Werkstück unter die Spindel zu halten, einen Fräser reinzuhalten und zu sehen, ob das noch passt oder nicht.

**Comment by Johannes09** [comment]
Ich sehe das auch nicht als so sinnvoll. Wir haben doch einen geschlossenen Raum

**Comment by Pakue95** [comment]
Könnte auch Probleme geben größere Platten in die Fräse zu legen.

Das Controller board mit einem Gehäuse zu schützen fände ich aber eine gute Idee. Als wir Board für die Reparatur ausgebaut hatten war es voll mit Holzstaub. Es muss nicht völlig abschließen (was wegen der Kühlung auch nicht gut wäre) aber zumindest den Staub der von oben herunterkommt würde weniger werden.

**Comment by NitramLegov** [comment]
Bisher scheint die Idee auf wenig Unterstützung zu stoßen (inklusive des Eckpaten, der dagegen ist). Daher mache ich hier erstmal zu. Falls jemand noch weiter Argumente anbringen möchte bitte einfach das issue wieder öffnen.
