### ISSUE TITLE
Bahnstadtfest

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#110]
As mentioned in the April Plenum, let´s plan for attending the Bahnstadtfest.
It will take place on Saturday, July 20 from 14:00 to 23:00 (we don't need to stay that long). Lukas registered us.

Main goals:
- visibility
- possible new members
- show off what can be done

We will need people in the morning, in the afternoon and in the evening for representing the space.
In addition, we would need somebody to help out the rest of the event (e.g. volunteer for the run or for the food stands).

- preparation/planning of exhibits and activities in advance
yes: 
 Martin
 Lukas: Will bring some Öko-lighters
 Patrick
 Johannes
maybe:
??
- transportation/setting up the stand in the morning (we should probably get there before 13:00)
yes:
 Martin, Lukas, Kim, Patrick
maybe:
Keno
- presentation/talking to visitors during the day and getting them excited about Making and our Space
yes:
 Martin, Lukas, Kim, Patrick
maybe:
Keno
- helping out with the overall event: two volunteers for the run in the afternoon and two for food stands in the afternoon/early evening
yes:
 Kim, Johannes
maybe:
 Lukas
- transportation/cleaning up in the evening
yes:
 Kim, Lukas
maybe:
??

This List will be updated!

Exhibits:
old Hobelbank
Lukas: Öko-Lighters to generate donations(if ready), hand tools, self-made tools, festival radio (if ready)
Kim: Lamp (red)
Johannes: Word clock (if ready)

**Comment by NitramLegov** [comment]
Let´s also start a discussion about what projects / Tools / etc. we would like to show.
Once we confirm them, let´s check the box!
My first suggestions would be:
-[] Electrictral Skateboard from @Pakue95 (can we have it?)
-[] Raspberry Pi with Emulators (@Pakue95 can we have the display again?)
-[] The MusicBox from @NitramLegov 
-[] Pictures from our Project Wall
-[] The small CNC Router (if we bring small pieces of wood, we could enable people to actually make/engrave something)
-[] Wood Tools from @LukasFreeze 
-[] Toys and games people made (@LukasFreeze?)
-[] Printed Cookie Cutters (shall we make cookies with our logo beforehand?)

**Comment by LukasFreeze** [comment]
I think it would be good if we had not only stuff to show, but activities for the visitors to try out or at least watch. Some ideas:

- [ ] Luzian's [OpenScan](https://wiki.comakingspace.de/Project:OpenScan)
- [ ] Micha B. might like to do a woodturning demo if he can come (needs to be behind safety barrier!)
- [ ] some simple carving or fretsaw work for kids?
  - [ ] and/or toner transfer to wood (needs laser printer + laptop if people should design their own pattern; I am working on a how-to)

other updates/thoughts:
- Korbi wanted to use the [EleksMill ("small CNC", also suggested by Martin above)](https://wiki.comakingspace.de/CNC_Mill#EleksMill) for something, if he makes it usable before the event it would definitely be cool to bring it
- Georg would give us a photo of [his Nerf Wall](https://wiki.comakingspace.de/Project:Stand_for_Nerf_weapons) and a single gun + holder as eyecatchers, but can't come to the event
- it would be awesome if we had a roll-up poster by then (#113)

**Comment by Pakue95** [comment]
The Counter PCB Kits would also be a nice activity. We can take one or two soldering stations up with us.

**Comment by NitramLegov** [comment]
I like the Open Scan idea! At the Makerfaire, the guy scanned a key, printed it and let you open a lock with the printed key. That was pretty amazing, so maybe we can do something similar.

Regarding the Nerf Gun: We would need to tell all those little kids that they can´t have it to run around and shoot some nerf darts.

Regarding the Eleks Mill: Why is it not usable? I thought it works, but just has the disadvantage of not having endstops? I´ll open a new issue for adding endstops.

**Comment by LukasFreeze** [comment]
I'm not too excited about the Nerf gun idea to be honest, it could send the
wrong message to arm the kids and the display wall is a project one could
do without a Makerspace :-P

The EleksMill *should* work, but it takes an experienced user, perhaps new
workholding options and ideally some solid documentation to use it at an
event. That's what I meant Korbi could improve in advance (or anyone who'd
like to get familiar with the machine)

**Comment by LukasFreeze** [comment]
wir sollten morgen im Plenum mal checken, wie es mittlerweile mit der Verfügbarkeit weiterer Leute aussieht und ob in diesem Issue vielleicht die Sprache vom Diskutieren abschreckt (niemand englischsprachiges scheint ja Zeit zu haben, also könnten wir auch auf Deutsch weiter planen...)

**Comment by NitramLegov** [comment]
Idee aus dem Plenum:
man könnte versuchen, die kleine Fräse dazu zu nutzen, um in Münzen oder ähnliches reinzufräsen.

**Comment by Pakue95** [comment]
These engraving bits would work fine I think. 
http://vi.raptor.ebaydesc.com/ws/eBayISAPI.dll?ViewItemDescV4&item=254240732144&category=110814&pm=1&ds=0&t=1559185654000&ver=0&cspheader=1

**Comment by LukasFreeze** [comment]
Es kam gerade eine Mail vom Orga-Team:

>Wie in jedem Jahr treffen sich alle Beteiligten im Vorfeld. In diesem Jahr wird es nur ein Vortreffen geben. Dieses findet am 1.Juli 2019 um 18.30h im Bürgerhaus Gadamerplatz 1 statt.

>Es wäre wichtig, dass jede Gruppe mit mindestens einem Vertreter vor Ort ist.

>Bei diesem Treffen werden wir die wichtigsten Informationen weitergeben und werden auch die Standorte der einzelnen Stände besprechen.

Wer hätte Zeit? Ich müsste mir das freihalten können.

**Comment by LukasFreeze** [comment]
@NitramLegov @Pakue95 @Johannes09 @Narquadah @kenomaerz  es wurden doodles mit den Helferschichten für den Bahnstadtverein rumgeschickt, ich habe euch die Mail weitergeleitet - bin nicht so sicher ob es erwünscht wäre, die hier öffentlich zu machen.

Hätte sonst noch jemand Lust auf ein paar Stunden Engagement für die Gesamtveranstaltung? Einfach melden und ihr kriegt die Links!

**Comment by NitramLegov** [comment]
Ich muss mich leider aus dem aufräumen Abends wieder austragen, da ich Abends noch einen anderen Termin bekommen habe :(
Dafür habe ich mich aber als flexiblen Helfer eingetragen..ich bin davon überzeugt, dass das den Organisatoren am meisten hilft.

**Comment by NitramLegov** [comment]
Heute war das Bahnstadtfest Planungstreffen.  Unten sehr ihr den Plan. Der rot umkringelte Stand sind wir.
![2019_07_01 19_02 Office Lens](https://user-images.githubusercontent.com/7809163/60457973-b085af00-9c3d-11e9-8b90-9f8487f4cbd8.jpg)

@LukasFreeze @Pakue95 @Narquadah @kenomaerz Wir können den Stand zwischen 11 und 14 Uhr aufbauen. Wir treffen uns also gegen 11:30 im Space, packen zusammen und fahren dann die Hobelbank hoch. Das sollte locker reichen. Falls jemand ein Auto zur Verfügung stellen kann: Das war letztes Jahr ziemlich nützlich.

**Comment by Narquadah** [comment]
Ich kann mein Auto zur Verfuegung stellen

**Comment by LukasFreeze** [comment]
@NitramLegov hat gestern den OpenScan soweit aufgebaut. @Johannes09 hast du bei der EleksMill etwas erreicht?

Zur Liste mit Ausstellungszeug habe ich noch mein "Festival Radio" hinzugefügt und wir könnten einfach ein paar coole 3D-Drucke aus der Vitrine im Druckerraum borgen. Die *Idee* mit den Grillanzündern aus Wachs und Hobelspänen steht weiterhin, allerdings wird das wohl höchstens nächste Woche was :-P

**Comment by NitramLegov** [comment]
Den OpenScan hat vor allem @Titan-OX aufgebaut! Ich habe nur noch die Rückwand hinzugefügt und andere Kabel angelötet!

Für die EleksMill hat @Pakue95 und gestern einen neuen Arduino zum testen gegeben. Den hat @Johannes09 gestern vorbereitet, das muss jetzt entsprechend ausprobiert werden. Ich bereite demnächst einen pi dafür vor.

**Comment by emka** [comment]
Ich kann wahrscheinlich beim Aufbau helfen, wann soll ich beim space sein?

**Comment by LukasFreeze** [comment]
Treff 11:30, dann sind wir hoffentlich um 12 unterwegs.

**Comment by LukasFreeze** [comment]
Ich habe keine Zeit mehr für die Grillanzünder-Idee, habe mich aber stattdessen um die Drechsel-Sachen gekümmert. Sie liegen größtenteils auf dem Rolltisch, den wir auch dafür nutzen wollen, jetzt muss ich aber nach Hause...

**Comment by NitramLegov** [comment]
Das event ist vorbei, ich mach hier mal zu.
