### ISSUE TITLE
Fördermöglichkeit BASF "Tor 4" - nur noch bis 30.4.!

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#111]
BASF hat eine regionale Kulturförderung ins Leben gerufen und ich glaube, wir könnten in die zweite Runde "Wie geht Freiheit wirklich?" passen! **Mindest-** Fördersumme 5000 € -> https://www.basf.com/global/de/who-we-are/organization/locations/europe/german-sites/ludwigshafen/gesellschaftliches-engagement/woran-wir-arbeiten/arts-and-culture/Tor4/wie-freiheit.html

Wie genau schreibe ich hier so öffentlich vielleicht lieber erstmal nicht, bevor wir etwas eingereicht haben, aber wäre jemand interessiert beim Antrag zu helfen? Neben einigen Textbausteinen müssen wir uns einen Finanzierungsplan und den Ablauf der geförderten Aktivitäten überlegen.

Bitte so bald wie möglich melden, dann können wir ein Google Doc aufmachen und uns möglichst auch treffen...nur noch zwei Wochen bis Bewerbungsschluss :-P

**Comment by kenomaerz** [comment]
Bin dabei

**Comment by NitramLegov** [comment]
Bin auch dabei. Nächstes we kommen die Feiertage ganz gelegen. Ansonsten müsst ihr euch halt überlegen, wie weit ich euch virtuell unterstützen kann ;)

**Comment by LukasFreeze** [comment]
Wir sind übrigens schon dran, weitere Hilfe ist aber sehr willkommen! Sprecht uns auch gerne "nachher" beim Grillen an :-)

**Comment by LukasFreeze** [comment]
Die letzten paar Tage laufen - wir sind mittlerweile so weit, dass wir wissen welche Gerätetypen wir gerne beantragen möchten, könnten aber dringend Hilfe bei der genaueren Recherche gebrauchen! Wer kennt sich aus und/oder hätte gerne ein bestimmtes Gerät? Bitte bei allen Vorschlägen kurz einen Link, Preis und besondere Vorteile posten :-)

- Kappsäge
- Hobelmaschine (Kombination Dickenhobel und Abrichte)
- Lasercutter
- Luftfilter
- Tischkreissäge
- Oberfräse für Tischbetrieb

**Comment by LukasFreeze** [comment]
Mein aktueller Laser-Favorit:
[Laserscript LS6090](https://www.laserscript.net/product/ls6090-laser-engraving-cutting-machine/) - £6300 incl. VAT [von HPC Laser](https://hpclaser.co.uk/index.php?main_page=product_info&cPath=1&products_id=11)
- pro: groß, kraftvoll, vergleichsweise spottbillig, in Europa zertifiziert
- con: (gegenüber vielfach teureren Epilogs) Glas- statt Metallröhre, Wasser- statt Luftkühlung; wir kennen die Marke noch nicht

Vorschlag für die Oberfräse, wie auch schon in #105 erwähnt:
[Triton TRA 001](https://www.toolstation.de/shop/Elektrowerkzeuge/d40/Fr%C3%A4smaschinen/sd460/Triton+TRA001+Oberfr%C3%A4se/p54513) - 299 €
- pro: Preis-Leistungs-Preis der HolzWerken-Spezialausgabe "Oberfräse"; von zahlreichen YouTubern empfohlen (hoffentlich ehrlich)
- con: lässt wohl im Handbetrieb zu wünschen übrig, weil sie so sehr für Frästische optimiert ist - kann uns egal sein!

**Comment by LukasFreeze** [comment]
Vorschlag für eine gute, aber trotzdem kompakte Tischkreissäge: [Bosch GTS 10XC](https://www.bosch-professional.com/de/de/products/gts-10-xc-0601B30400). Die Fangemeinde ist sehr groß und sie bietet alle Vorzüge unserer jetzigen Säge bei besserer Verarbeitung, außerdem eine zweite Absaugmöglichkeit am Blattschutz und werkzeuglos versenkbaren Spaltkeil.
- Forumsdiskussion zu dieser Säge und einer vergleichbaren Makita [>](http://www.holzwurmtreff.de/viewtopic.php?t=938)
- günstigstes Angebot laut idealo: [659 € inkl Zubehör, aber ohne Tisch](https://www.etrona.de/bosch-professional-gts-10xc-elektro-tischkreissaege-0601b30400.html?number=GTS10XC) (UVP 1039 € zzgl MwSt)

Moritz hat am Mittwoch außerdem noch für die Tischzugsäge von Festool geworben - die ist zwar deutlich teurer, aber könnte wenn ich das richtig sehe eine Kappsäge völlig unnötig machen! Mehr Details benötigt...

**Comment by Pakue95** [comment]
Noch ein (kurzfristiger) Vorschlag: Einen (besser sogar 2) Akkubohrer fände ich auch wichtig. Der wird öfter benötigt als jedes andere el. Werkzeug und würde das Antragsbudget nicht sprengen.

Ich habe bisher guter Erfahrungen mit den Makitas (Brushless) gemacht und würde den hier im Set vorschlagen:
* [DDF485 + 3x 5Ah Akkus für 290€](https://www.svh24.de/makita-18v-akku-bohrschrauber-ddf485rtj3-3x-akku-5.0-ah-925735?fs=2128894380)
* [ + DDF481 ohne Zubehör für 170,87€](https://www.svh24.de/makita-18v-akku-bohrschrauber-ddf481z-ohne-akku-ohneladegeraet-656655?fs=2898851524) (Der hat enorm viel Drehmoment was für Forstnerbohrer ganz cool ist.)

**Comment by LukasFreeze** [comment]
Danke, die kriegen wir sicher noch unter! Zu viel "Kleinkram" würde ich vermeiden wollen, aber das ist bestimmt noch im Rahmen.

**Comment by LukasFreeze** [comment]
So, jetzt nochmal zwei dicke Brocken! Wäre sehr cool wenn das alles heute Abend von den Anwesenden diskutiert würde :-) Ihr könnt meine Kommentare gerne einfach editieren um mehr Infos/Meinungen hinzuzufügen, wenn das die Berechtigungen zulassen.

**Tischzugsäge:** 
[Festool CS 70](https://www.festool.de/produkte/halbstationaeres-arbeiten/tischzugsaegen/574782---cs-70-ebg-set)
- pro: mehr Sicherheit bei kleinen Werkstücken; ersetzt Tischkreissäge **und** Kappsäge -> Platzgewinn, besseres Gerät für beide Einsatzfälle
- con: ziemlich teuer (im Set mit allen sinnvollen Accessoires, s. Link oben: 2720 € zzgl MwSt)
- alternativ könnte man die ["kleinere Schwester" CS 50](https://www.festool.de/produkte/halbstationaeres-arbeiten/tischzugsaegen/574772---cs-50-ebg-set) nehmen, die kostet mit Zubehör aber immer noch über 2000 € und hat ein deutlich kleineres Sägeblatt als die CS 70 oder die [zuvor erwähnte](https://github.com/comakingspace/do-something/issues/111#issuecomment-487048216) blaue Bosch. Da spart man denke ich an der falschen Stelle, Ziel ist ja gerade ein möglichst vielseitiges Gerät zu haben!
- +1 von @LukasFreeze 

**Abricht- und Dickenhobelmaschinen:**
1) [Holzmann HOB ](https://www.handwerkershop.eu/Hobelmaschine-Abricht-Dickenhobel-Holzmann-HOB-305PRO-mit-4-Messerwelle)
- 1,5 m Tischlänge (größer sollten wir nicht werden, muss auch in die Werkstatt passen!), 305 mm Abrichtbreite, 300 mm Dickenhobelbreite mit Höhenbereich 3-220 mm, 255 kg schwer
- pro: vergleichsweise günstig (1699 € inkl MwSt)
- con: ["Chinaware", mangelhafte Qualität?](https://www.werkzeug-news.de/Forum/ftopic1147.html)

2) [Hammer A3 31](https://www.felder-group.com/de-de/produkte/hobelmaschinen/abricht-dickenhobelmaschine-a3-31.html)
- 1,4 m Tischlänge, 310 mm Abrichtbreite, 306 mm Dickenhobelbreite mit Höhenbereich 4-225 mm, 290 kg "bei durchschnittlicher Ausstattung"
- pro: Budget-Marke von Felder, einem renommierten Hersteller; etwas mehr Kapazität als die Holzmann bei kleinerem Footprint
- con: etwas teurer - [2420 € zzgl MwSt](http://fms.felder-group.com/Kataloge/2018/Hammer/HA18_Gesamtkatalog_DE_GER_EUR2/45/) (damit aber immer noch unter unserer vorübergehenden Schätzung von 3.5k!)
- +1 von @LukasFreeze

**Comment by LukasFreeze** [comment]
**Luftfilter:**
[Record Power AC400](https://neureiter-shop.at/produkte/werkstattausstattung/luftfiltersysteme/record-power-ac-luftfiltersystem.html)
- pro: beliebt in der "Maker-Szene", zeitgesteuerte Abschaltung (nach dem Arbeiten hängt ja der Staub noch in der Luft)
- con: stößt bei unserer Deckenhöhe eventuell an seine Leistungsgrenze (für ca. 110 m³ ausgelegt) - gleich zwei davon?
- 199 € inkl MwSt
  - 398 € für 2 Stück - "notfalls" einer für den CNC-Raum, falls OP (+1 von @LukasFreeze )

**Mobilität für die Hobelmaschine**
1) Hubwagen (Original-"Ameise": ca. 300 €)
- pro: Mobilität für die Hobelmaschine, sicher auch generell praktisch - schreiben wir den spontan noch rein?
- con: Palette erhöht Arbeitshöhe der Hobelmaschine, Wagen braucht "Parkplatz", Wagen gibt es bestimmt öfter mal gebraucht günstiger

2) selbstgebauter Unterbau [(Prinzip an Hammer A3 26 bewährt)](https://holzprojekte.blogspot.com/2017/09/fahrwerk-hobelmaschine.html)
- pro: keine Erhöhung der Maschine, keine Vergrößerung des Footprints, geht nie "verloren"
- con: etwas Aufwand, maschinengebunden
- Material (um die 100 € für Schwerlast-Lenkrollen und etwas Holz, Angebote TBD aber nicht im Detail im Antrag nötig) würde @LukasFreeze spenden (dann stehen auch mehr eigene Mittel im Antrag!)
- +1 von @LukasFreeze

**Comment by LukasFreeze** [comment]
okay, da es nicht so aussieht als kämen hier noch Vorschläge und die Deadline immer näher rückt schreibe ich jetzt "meine" Maschinen in den Antrag.

**Comment by LukasFreeze** [comment]
So, es fehlt nur noch der letzte Schliff! Wie auch gerade in der Telegram-Gruppe erwähnt wäre es sicher nicht schlecht, auch noch ein paar zugesagte Spenden zum Projekt eintragen zu können - wir beantragen ca. 18000 €, wenn jemandem die Geräteliste so gut gefällt dass man mit einer kleinen Entlastung vielleicht die Erfolgschancen erhöhen könnte sagt bitte Bescheid :-)

Ich habe zum Beispiel schonmal "gepledged", den Versand des Lasercutters zu übernehmen wenn wir das Gerät an sich bewilligt bekommen und @NitramLegov hat auch schon einiges angeboten. Noch ein paar Leute mehr und es dürfte eine ganz nette Summe werden!

Falls der Antrag doch nicht durchkommen sollte habt ihr natürlich keine Verpflichtungen, aber wie gesagt - wenn ihr Lust habt, das Vorhaben zu unterstützen, sagt bitte schonmal Bescheid in welcher Form (gerne auch privat, lukas [ät] comaking.space - Hauptsache bis morgen früh!)

**Comment by LukasFreeze** [comment]
Das Ding ist raus! Danke an alle die schon Unterstützung zugesagt haben, wir sind fast in den vierstelligen Bereich gekommen :-)

Falls wir Erfolg haben werden zumindest die Geräte-Links hier nochmal wichtig, aber bis dahin mache ich mal zu :-)
