### ISSUE TITLE
Neue Website bauen

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#114]
Wie im Februar Plenum besprochen, arbeiten @Narquadah und ich aktuell an einer neuen Website für den Space.

Die soll auf GitHub pages basieren, damit sie bei Bedarf von allen angepasst werden kann.
Hier brauchen wir Leute, die Vorschläge für Texte, Inhalt, etc. machen können.

Dieses Issue dient vor allem der Dokumentation ;)

**Comment by LukasFreeze** [comment]
Ich würde erstmal vorschlagen, den jetzigen Inhalt weitestgehend zu
übernehmen und "live" zu gehen - dann sollte auf lange Sicht daram
gearbeitet werden, mit der Website besser als Community rüberzukommen und
nicht kommerz (was Besucher immer wieder erzählen und dann sehr positiv
überrascht sind, wie es wirklich ist)

**Comment by NitramLegov** [comment]
bezüglich der Texte hast du sicherlich erstmal Recht. Zumindest einen großteil können wir da direkt übernehmen.
Bezüglich des Designs ist es einfacher, neu anzufangen. Und ich würde auch direkt die Blogging-Option mit einbinden. Die ist prinzipiell soweit fertig.

Das wichtigste ist gerade tatsächlich ein Designvorschlag.

Und eine Frage: Brauchen wir die gesamte Webseite tatsächlich in zwei Sprachen? Meiner Meinung nach nicht...

**Comment by LukasFreeze** [comment]
Spätestens beim Blog muss die Zweisprachigkeit aufhören, das ist einfach nicht machbar. Die eher statischen Seiten finde ich prinzipiell aber schon gut auch auf Englisch zu haben (About/Join Us).

Zum todo "Join Us mit Komm vorbei übersetzen" - warum denn nicht einfach "Mach mit", wie jetzt auch? Beinhaltet auch mehr "machen" ;-)

**Comment by LukasFreeze** [comment]
Der aktuelle Stand der Website ist mittlerweile im [Verzeichnis "comakingspace.github.io"](https://github.com/comakingspace/comakingspace.github.io/) zu finden, dort gibt es auch einen [eigenen Issue Tracker mit detaillierten Schritten](https://github.com/comakingspace/comakingspace.github.io/issues)!

**Comment by LarsKumbier** [comment]
Ergebnisse auf dem letzten Meeting
```
- Gemeinschaft
- "Kann ich nicht daheim"
  - Geräte nicht da
  - Raum nicht da
  - Fähigkeiten fehlen / Zweites Paar Augen
- Ideen und Projekte umsetzen

- KEINER: "Kannst Du mir das mal reparieren?"
  => Wollen wir auch nicht


==========
ZIELGRUPPE
==========
- Self-Made 
- selber basteln 
- kreieren 
- designen 
- DIY
- Heimwerken
=> Projekte. TUN. THAT'S WHAT WE DO.


==========
ANTI-TYPEN
==========
- "Reparier' mir das mal" => Schmarotzer
- Leute, die nichts zurück geben
- Leute, die Zeitdruck haben

- Sowohl "Schlenderer" als auch "Jäger" als Zielgruppe


1. "Should I stay or should I go?"
  => Above-the-fold (das, was ohne scrollen sichtbar ist)
2. INFORMIEREN
3. Call-to-Action 
  => KOMM VORBEI, Werde Mitglied, Spende



=========
WAS WOLLEN WIR? => INFORMIEREN
=========
- informieren über
  - was wir tun
  - was wir haben
  - warum wir es tun: Satzungsziele / Mission statement
- Seminare verkaufen
- Interessenten sollen zu den offenen Zeiten kommen
  (damit wir sie da überzeugen können, Mitglieder zu werden)
- "Adopt a machine"


==========
SCRATCHPAD
==========
- Gutschein / Erlebnistag / Mitgliedschaft


======================
MINIMAL VIABLE PRODUCT
======================
- Header
  - Logo
  - Menü
- Projekte - ZIEL: WE DO DIFFERENT STUFF!
  - Foto
  - Titel
  - One-liner (optionally)
  - Link to Wiki-Page
- Events / nächste Öffnungszeiten
------ below the fold ------
- What we do
  - 6 Points
  - headline, icon, one-liner
- Call-to-Action
- Footer
  - Impressum
  - Datenschutz
  - TMG
  - Kontaktdaten
  - Spendenkonto


=================
NEXT ACTIONS
=================

- Neues Template finden [Lars]
- auf Jekyll umziehen [Kim]
- Landing Page beleben (MVP only!) [Lukas]
- Online stellen [Ciaran]
```

**Comment by NitramLegov** [comment]
Done - Die neue website ist jetzt live unter https://www.comakingspace.org/
