### ISSUE TITLE
Metallwerkstatt verbessern

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#115]
*`Das ist eins von ein paar internen Issues, die wir schon länger auf dem Schirm hatten, die aber auch von interessierten Mitgliedern vorangebracht werden können. Ich werde die Tage noch mehr in den Issue Tracker hier posten.`*

In der Metallwerkstatt sind noch ein paar kleine Dinge, die schon länger erledigt gehören. Das sind alles keine komplexe Projekte deshalb packe ich die hier alle in ein Issue.

* [ ] (Wand-)Halterung für die Feilen, die momentan noch alle auf dem Tisch liegen.
* [ ] Kleinteile Sortiment an einen geeigneten Ort an die Wand montieren.
* [ ] (neue) Photos fürs Wiki machen.

**Comment by LukasFreeze** [comment]
Ideen für Feilenhalter wurden auch schonmal in #6 kurz angerissen

**Comment by NitramLegov** [comment]
Closed, since this task will most likely change when the space gets moved
