### ISSUE TITLE
Fusion seminar Sa. 25.5

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#116]
As discussed during the [last plenum](https://wiki.comakingspace.de/Plenum/Meeting_minutes/2019-05-03) I'll be doing another Fusion 360 seminar this month. If somebody wants to chime in to help feel free!

**Name**: Fusion 360 seminar

**Presenter & helpers**: @Pakue95 

**Date & time**: 25.5. 13-16:00

**Description**: see [wiki page](https://wiki.comakingspace.de/Fusion_360_Seminar)

**Rooms**: Common Room

**Tools & materials**: Beamer

**No. participants**: 10

## Advertisement ToDo:
* [x] create Eventbrite entry (needs to be done by a [manager](https://wiki.comakingspace.de/Management))
  * [Link](https://www.eventbrite.de/e/fusion-360-seminar-tickets-61472342431)
* [x] event [wiki page](https://wiki.comakingspace.de/Fusion_360_Seminar)
* [x] calender entry ([manager](https://wiki.comakingspace.de/Management))
* [x] announce via Members mailing list
* [x] announce via Telegram group
* [x] [Meetup](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/) group
  * [link](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/events/261245531)
* [ ] Instagram ([manager](https://wiki.comakingspace.de/Management))
* [x] Facebook ([link](https://www.facebook.com/events/421635621950776/))
* [ ] Twitter ([manager](https://wiki.comakingspace.de/Management))

**Comment by LukasFreeze** [comment]
Facebook-Event ist erstellt, bitte fleißig teilen wenn ihr da aktiv seid: https://www.facebook.com/events/421635621950776/

**Comment by LukasFreeze** [comment]
Ich habe das Event auf Facebook nochmal in ein paar Gruppen geteilt um die Sichtbarkeit zu erhöhen, hoffentlich bringt es was :-)
Je mehr FB-Nutzer es auch noch privat teilen desto besser!

**Comment by LukasFreeze** [comment]
Event vorbei, also mach ich zu - wie lief's?

**Comment by Pakue95** [comment]
Lief ganz gut. Es waren 5 Leute von den angemeldeten 7 (?) da.
