### ISSUE TITLE
Tellerschleifer bauen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#119]
Der Tellerschleifer in der Metabo-Bandsäge ist aus mehreren Gründen unpraktischer als gedacht (#69) und die Arbeit für einen Schleiftisch dafür wäre besser in eine andere, ganz neue Lösung investiert.

Mein Vorschlag wäre, einen Aufsatz für die Güde-Drechselbank zu bauen. Da hätten wir schon einen Motor mit verschiedenen Geschwindigkeiten, die Drehrichtung passt damit man vorne komfortabel schleifen kann, und wenn wir uns irgendwann eine bessere Drechselbank zulegen können wäre das ganze schnell adaptiert oder (ohne das lange Drechsel-Bett, nur mit dem nicht mehr gebrauchten Motor) als reiner Tellerschleifer anderswo aufgebaut.

Eine andere Option wäre, einen Tellerschleifer mit irgendeinem Motor ganz von Grund auf zu bauen und in die Schleifecke zu stellen, aber da ist es imho schon voll/chaotisch genug ohne noch ein stationäres Gerät aufzustellen. Und geschliffen wird an einer Drechselbank sowieso am Ende jedes Projekts, also lohnt es sich da ohnehin über eine Absaugung nachzudenken.

Instructables als Inspiration:
- https://www.instructables.com/id/12-Inch-Lathe-Disk-Sander/
- https://www.instructables.com/id/Lathe-Mounted-Disc-Sander/

**Comment by LukasFreeze** [comment]
Ich würde 250 mm als Durchmesser anpeilen, dann können wir zwar die paar vorhandenen 200-mm-Schleifscheiben für die Bandsäge nicht voll ausnutzen aber soweit ich weiß werden Tellerschleifer bei zunehmender Größe nur praktischer.

In 250 mm gibt es [selbstklebende Scheiben von Proxxon bei Bauhaus](https://www.bauhaus.info/schleifen-trennen/proxxon-schleifscheibe-no-28970/p/11297434), ich würde allerdings eine Klettlösung bevorzugen und dann eben online bestellen. Sonst artet jeder Körnungswechsel in ziemlich viel Arbeit aus (die [Silikon-Unterlage von Proxxon klebt wohl nach einiger Zeit besser am Schleifpapier als am Schleiftisch](https://www.amazon.de/Proxxon-SK-Silikonfilm-f%C3%BCr-Aufbe-28968/product-reviews/B001DXEDR4/ref=cm_cr_dp_d_show_all_top?ie=UTF8&reviewerType=all_reviews), ist also auch nicht unbedingt die Lösung). "Meine" [Klettauflage scheint dagegen echt gut zu funktionieren](https://www.amazon.de/Klettauflage-250-f%C3%BCr-Tellerschleifer-selbstklebend/product-reviews/B002LWH706/ref=cm_cr_dp_d_show_all_top?ie=UTF8&reviewerType=all_reviews).

Kaufvorschläge: 
- ["Erstausrüster-Set" mit Klettauflage und 16 kompatiblen Schleifscheiben diverser Körnungen](https://www.holz-metall.info/shop1/artikel8842.htm?liefer_land=DE&selectedVariation%5B8149%5D=505&anzahl=1&artID=8842&cid=&formAction=detailArt)
- später dann nach Bedarf [weitere Schleifscheiben dieses Herstellers](https://www.holz-metall.info/shop1/artikel5897.htm?liefer_land=DE&selectedVariation%5B5994%5D=498&selectedVariation%5B7212%5D=778&anzahl=1&artID=5897&cid=&formAction=detailArt), wenn die Qualität stimmt

Was meint ihr?

Also würde ich heute Abend den Teller bauen und plandrehen und dann, wenn das geklappt hat und hier vielleicht auch noch Feedback kommt, die bevorzugte Klebung/Klettung stiften. Weitere Geräteteile (Gehäuse, Schleiftisch) würde ich erst bauen, wenn die erste Schleifscheibe drauf ist, damit man direkt alles richtig einstellen kann.

**Comment by LukasFreeze** [comment]
Ging ganz gut mit dem Teller! Ich habe dazu ein Stück Räuchereiche mit einem M18-Gewinde versehen und direkt auf der Spindel rundgedreht. Dann eine Buchenplatte grob mit der Stichsäge ausgeschnitten, angeschraubt/verleimt und ebenfalls so gut wie möglich begradigt.

![IMGP4946](https://user-images.githubusercontent.com/19755883/57866033-ecd08d80-77fe-11e9-8bec-f2ab5d05ef97.JPG)
![IMGP4949](https://user-images.githubusercontent.com/19755883/57866331-76805b00-77ff-11e9-8039-f5f1c9fc2721.JPG)

Bei der höchsten Geschwindigkeit flattert es noch etwas und ich glaube das kommt hauptsächlich von der Unwucht auf der Tellerrückseite, darum und um ein letztes Abschleifen der Vorderseite kümmere ich mich dann spätestens wenn die Schleifscheiben da sind (bestelle ich jetzt)

**Comment by LukasFreeze** [comment]
Der Teller funktioniert soweit, wenn jemand noch Bock hat den weiter auszuwuchten kann man das sicher irgendwann noch machen aber als nächstes wäre jetzt erstmal der Tisch dran :-)

![IMGP5484 (Large)](https://user-images.githubusercontent.com/19755883/60274488-6aa4b000-98f8-11e9-80c7-372a7e9e2fec.JPG)

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by LukasFreeze** [comment]
@SebMakesThings das hier verlinkte "[Erstausrüster-Set](https://www.holz-metall.info/shop1/artikel8842.htm)" (Maschinenhandel Meyer, je nach Durchmesser ab 12,50 € für 16 Schleifscheiben + Klettgrundplatte) kann ich auch für das Upgrade vom Holzmann-Tellerschleifer empfehlen :-)

**Comment by SebMakesThings** [comment]
@LukasFreeze @kenomaerz Das Set sieht gut aus, Kosten inkl. Versand 32€ für die 200mm Variante. Kann ich übernehmen, am liebsten mit Spendenquittung - was ist da der einfachste Weg mit wenig Aufwand? Betterplace?

**Comment by Pakue95** [comment]
Wenn es der Space kauft, können wir uns die MwSt sparen. Kann es als Bedarf bei Betterplace später reinstellen, dann ist das mit der Spendenquittung auch recht einfach.

**Comment by SebMakesThings** [comment]
Topp, erledigt, kann bestellt werden.

**Comment by LukasFreeze** [comment]
Hier muss niemand mehr Zeit reinstecken, denn wir haben ja mittlerweile einen "echten" Tellerschleifer und ich würde das Projekt zuhause weiterverfolgen, wenn die neue Drechselbank #264 so gut ist wie erwartet und ich diese hier wieder mitnehmen muss ;-)
