### ISSUE TITLE
Akkuschrauber (DEWALT)

### ISSUE THREAD

**Issue by Johannes09** [comakingspace/do-something#12]
Der Akkuschrauber funktuinirt einbanfrei nur die akkus sind kaput ich würde forschlagen einen 3S Li-po einzubauen

EDIT Lukas (vorgeschlagene nächste Schritte):
- [x] testweise einen Akkupack mit LiPo-Zellen neu bestücken
- [x] Ladeelektronik bauen
- [x] wenn alles geklappt hat: die anderen beiden Akkupacks wiederbeleben!
- [ ] Wiki Doku: 
  - [ ] [Gerät an sich](https://wiki.comakingspace.de/Cordless_Drills)
  - [ ] [Projektseite](https://wiki.comakingspace.de/Project:DeWalt_Battery_Replacement)

**Comment by LukasFreeze** [comment]
Akkuschrauber und drei (kaputte) Akkupacks liegen unter der Elektronik-Werkbank, wer sich damit auskennt würde sich sehr beliebt machen ;-)

**Comment by LukasFreeze** [comment]
Wie ist hier der Status? Ich habe schon mindestens ein neues Akkupack und ein Ladegerät irgendwo rumliegen sehen...

**Comment by Pakue95** [comment]
Dem Li-Ion Akku wurde jetzt ein BMS verpasst und funktioniert soweit mit dem Schrauber. Es muss jetzt nur noch ein Gehäuse für den Akku gebaut (3D gedruckt) werden.

**Comment by LukasFreeze** [comment]
Mein Bosch-Akkuschrauber wird uns nicht mehr lange nützen, der Akku wird immer schlechter und ich brauche ihn bald zuhause.

Damit hier mal wieder etwas passiert schlage ich vor, den Akkuschrauber mit Beschreibung des letzten Schrittes ("Gehäuse für den neuen Akku drucken - #12" oder so) zumindest mal ins Reparatur-Regal (#38) zu bringen. Er liegt gerade noch im CoMaking-Raum rum, wenn ich mich nicht irre?

**Comment by Pakue95** [comment]
Der Akku hat jetzt ein neues Gehäuse 3D-gedruckt bekommen und funktioniert. Momentan steht er bei den anderen Akkuschraubern damit man ihn mal testen kann. Wenn ich mich richtig erinnere haben wir ja noch mehrere Akkupacks, die man ja auch noch auf Lithium umbauen kann.

Die 3D Daten sind in unserem [CommonFiles](https://github.com/comakingspace/CommonFiles/tree/master/3DPrintingFiles/DeWalt_Battery) repo.

Die Wiki [Doku](https://wiki.comakingspace.de/Project:DeWalt_Battery_Replacement) fehlt momentan noch.

**Comment by Henrik99** [comment]
@LukasFreeze ja ich hab das noch. Einen CC Buck converter hab ich auch noch, @Johannes09 du musst also keinen Käufen, ich kann dir einen mitbringen.

**Comment by LukasFreeze** [comment]
Saugut :-)

@Johannes09 du hast das Ladegerät gestern noch zusammengebaut, oder? Funktioniert es jetzt?

**Comment by Johannes09** [comment]
Für den zweiten Akku fehlt nur noch ein weiterer Lipo Akku (Luka hat gesagt er wurde einen mitbringen)

**Comment by NitramLegov** [comment]
Der Akkuschrauber steht immernoch auf Commissioning und hat vor allem die Security und Test steps auf pending...
Die Projektseite hat auch noch keine Doku (vorgehen, schaltplan, akkuspezifikationen, etc.).
Ich mach hier also erstmal wieder auf...
