### ISSUE TITLE
Kunststoff Schredder 

### ISSUE THREAD

**Issue by Johannes09** [comakingspace/do-something#121]
fehlende Teile:

- [x] ein Gehäuse für die Elektronik (Metall oder knststoff)

- [ ] 3D gedruckte Klauen Kopplungen

- [x] eine Grundplatte zum befestigen

was kann gemacht werden: 

1. - [ ] Auseinandernehmen des Schredders Kopfes 
2. - [ ] Nachbearbeitung der Welle 
    - [ ] Herten der Schneiden
3. - [ ] alles Zusammenbauen
4. - [ ] erster Testlauf

**Comment by LukasFreeze** [comment]
Ich bringe heute Abend das Getriebe mit, es ist am Freitag endlich
angekommen!

**Comment by NitramLegov** [comment]
@Johannes09 Ist der Meinung, dass man die Schneiden nicht zwingend härten muss :-)

**Comment by LukasFreeze** [comment]
Ich glaube die Idee mit dem Härten kam damals von Johannes, wenn sich das nach den praktischen Tests geändert hat bin ich damit auch voll zufrieden :-)

**Comment by NitramLegov** [comment]
Das Gerät funktioniert, ist aus dem Commissioning raus und kann jetzt in anderen issues weiter verbessert werden :)
