### ISSUE TITLE
Noise protection for the CNC Room

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#123]
Since the CNC Router is quite loud, we should think about adding some noise protection onto the door which leads to the common room.

@Johannes09 had some ideas which he might want to share in here :)

**Comment by LarsKumbier** [comment]
I've got some mineral wool left which we could put on the door. But we should shield it by an old bed sheet and sandwich the wool between door and the sheet (e.g. by stapling it there). Mineral wool really sucks when touched.

Alternatively, I could get some Styrofoam sheets?

**Comment by NitramLegov** [comment]
We got some styrofoam sheets from amazon. THey should arrive within this week :)

**Comment by NitramLegov** [comment]
We put some of these onto the door:
https://smile.amazon.de/gp/product/B00CTWPYTE

Let´s see if it helps. I´m closing this issue now. In case anybody wants to do more, feel free to open a new one.
