### ISSUE TITLE
"neuen" Küchenschrank fertigstellen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#124]
@Johannes09 und @NitramLegov haben neulich einen Unterschrank zum Hängeschrank umfunktioniert, sodass wir jetzt Platz für einen Gefrierschrank haben. Allerdings fehlen noch zwei Schritte, damit der Schrank nicht beim 100. Türschließen plötzlich seitlich von der Schiene rutschen kann:

- [x] Platte zuschneiden, mit der der Schrank oben verschlossen werden kann
- [ ] über diese Platte den ganzen Schrank festschrauben (Winkel oben und an der Wand)

**Comment by NitramLegov** [comment]
Der Schrank hat jetzt eine Platte oben. Angeschraubt an der Wand ist er noch nicht. Das mache ich noch, eigentlich ist es aber unnötig. Nach rechts wird die Bewegung durch die steckdosen beschränkt, nach links durch den Kühlschrank. Man muss schon mutwillig drangehen um das Ding von der Wand zu bekommen ;)

**Comment by LukasFreeze** [comment]
Glaube ich nicht - es reichen ja schon 5 cm, damit er auf einer Seite von
der Schiene rutscht. Dann dürften auf der anderen Seite sofort die
Schrauben ausreißen und scheiße wars...

**Comment by NitramLegov** [comment]
Schrank hängt und ist an der Wand festgeschraubt
