### ISSUE TITLE
KiCad Seminar PR

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#125]
**Name**: KiCad seminar

**Presenter & helpers**: @Pakue95 

**Date & time**: 22.06 13-18:00

**Description**: see [wiki](https://wiki.comakingspace.de/KiCad_Seminar)

**Rooms**: Common room

**Tools & materials**:  Beamer

## Advertisement ToDo:
* [x] create [Eventbrite entry](https://www.eventbrite.de/e/pcb-design-101-from-idea-to-finished-circuit-board-tickets-62618733317) (needs to be done by a [manager](https://wiki.comakingspace.de/Management))
* [x] event [wiki page](https://wiki.comakingspace.de/KiCad_Seminar)
* [x] calender entry ([manager](https://wiki.comakingspace.de/Management))
* [x] announce via Members mailing list
* [x] [Meetup](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/) group
* [ ] Instagram ([manager](https://wiki.comakingspace.de/Management))
* [x] Facebook ([manager](https://wiki.comakingspace.de/Management))
* [x] Twitter ([manager](https://wiki.comakingspace.de/Management))

*optional (for larger seminars with lead time)*

* [ ] Poster (to be hung up by the city)
* [ ] announce in the next newsletter (@LukasFreeze)

**Comment by LukasFreeze** [comment]
please share this if you're on facebook!

event: https://www.facebook.com/events/346033612774593/

**Comment by LukasFreeze** [comment]
meetup event: https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/events/262234258/

**Comment by Pakue95** [comment]
KiCad Seminar was last week and 11 people showed up. The seminar files will soon be on the repo.
