### ISSUE TITLE
Install Prusaslicer on the slicing Computer

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#126]
Prusa released PrusaSlicer (formerly known as Slic3r Prusa Edition or Slic3r PE): https://www.prusa3d.de/prusaslicer/

This should get installed on the computer in the electronics room, which is used for slicing.

It should be checked whether the existint profiles from Slic3r PE should get transferred over to the new version.

**Comment by LukasFreeze** [comment]
before uninstalling the old one, we should also migrate all useful
material/printer settings!

**Comment by Pakue95** [comment]
The last time when we upgraded it asked for an old save file. I’d expect it to do the same. 

> Am 04.06.2019 um 21:46 schrieb Lukas <notifications@github.com>:
> 
> before uninstalling the old one, we should also migrate all useful
> material/printer settings!
>

**Comment by NitramLegov** [comment]
This time it is not an in-place upgrade but rather a new installation. It will not remove any profiles and stuff, but they have to be imported again after installation. The prusaslicer page contains an explanation:
https://blog.prusaprinters.org/prusaslicer-2-release/#_ga=2.14123636.2120555640.1559677387-1180536945.1559677387

**Comment by LukasFreeze** [comment]
@Narquadah took care of the parallel installation before Wednesday's plenum already, migration pending

**Comment by Narquadah** [comment]
Mirgration is complete, I will remove the older Slic3r PE version next week unless somebody wants to keep it.

**Comment by NitramLegov** [comment]
Unfortunately, it seems like Slic3r is still installed on the computer :(

**Comment by LukasFreeze** [comment]
There was some confusion on the mailing list today, so I guess the deinstall has been taken care of now?

We should still update the [Slic3r wiki page](https://wiki.comakingspace.de/Slic3r) with the new policy of maintaining only Prusaslicer on the shared computer, and also write a short Prusaslicer page while we're at it ;-)
