### ISSUE TITLE
Maus-Türöffnertag

### ISSUE THREAD

**Issue by LarsKumbier** [comakingspace/do-something#127]
## Maus-Türöffnertag

I've been watching the german "Sendung mit der Maus" (kind-of "How-its-made" for kids) for the past 32ish years - especially since I got three forks of my own. Every year on October 3rd, there's the Maus-Türöffnertag[1], where kids can register and come to do something exciting with (or without) their parents. I'd love to get the CoMakerspace into the program, which would also generate some publicity.

We'd have to provide some projects for that, suitable for kids of a specific age range (e.g. 6-10 or 8-12). Ideas:
* Building small robots from a toothbrushhead, a battery and a vibration motor (age 6+)
* Bending and welding little robot figurines from thick wire, threaded rods, washers and nuts (bending for 6+, welding 10+ with assistance or only from helpers?)
* Soldering small kits like a mini-tesla-coil: https://www.ebay.de/itm/401634796641
* Sowing ugly animals (kids draw a fantasy animal, which is then cut and sown from leftover materials)
* Whatever you can think of

Let's talk in the plenum on benefits, cost and risks - e.g. insurance? Is it possible to make the space semi-childsafe for the target group?

-----

[1] https://www.wdrmaus.de/extras/tueren_auf.php5

*(if at the Space) is there permission from the [management](https://wiki.comakingspace.de/Management)?*
yes

*is there a fixed date and time yet?*
yes: October 3rd

*is there a registration deadline (if yes, please include a link to the form)?*
yes, June 30th

*how many people are needed to organize it on the day of the event?*
One responsible for supervision (Martin volunteered thankfully), one per project

*are there any concrete tasks to be done in advance?*
yes: Find projects to organize

*what part of the work would you take over?*
Organization, possibly a project

**Comment by NitramLegov** [comment]
We could also think about making 3D Printed Cookie Cutters like in the past:
https://wiki.comakingspace.de/Project:Cookie_Cutters

We could also ask Michael from robot-workshop.de whether he´s willing to give us some input or even help? He´s from close to Darmstadt and I know he loves to work with kids! For example, he hosted a workshop at make darmstadt where he built robots for the hebecon with kids:
https://github.com/merlanura/robat/blob/master/documentation/robat_anleitung_v03.pdf

**Comment by NitramLegov** [comment]
Regarding the registration:
https://wdr.blob.core.windows.net/tueroeffnertagmaus-245/tueroeffnertagmaus.html

It seems like the deadline is September 3rd 2019.
It also seems like we need to provide a video!

**Comment by LukasFreeze** [comment]
Idee für ungefährlichen Löt-Bausatz statt Tesla-Spule: https://wiki.comakingspace.de/Project:Counter_Board

Ich könnte noch so einen "Kreidekreisel" drechseln wenn das jemand cool findet, geht super schon mit sehr kleinen Kindern und macht nicht so viel Müll wie die Rutschroboter: https://www.youtube.com/watch?v=ZcJ-wKN9iLY

Beim Event selbst bin ich leider schon verplant...

**Comment by LukasFreeze** [comment]
Ich habe von einer Maker Faire noch einige dieser Blinkies, die sehr kinderfreundlich sind:

![1560581836409](https://user-images.githubusercontent.com/19755883/59548499-a92d8880-8f50-11e9-9acd-3bcd6dcbde83.jpg)

Bisher habe ich keinen ausprobiert (das sollten wir noch machen und daraus eine bebilderte Anleitung erstellen), aber dem Anschein nach werden LEDs als Augen eingelötet und hinten irgendwo der Schalter, ein Batteriehalter und ein Ansteck-Pin :-)

Interesse (wer auch immer Löten betreuen wird)? Unsere [Counter](https://wiki.comakingspace.de/Project:Counter_Board) könnten wir ggf trotzdem für größere Kinder anbieten, allerdings geht da auch der Materialaufwand deutlich hoch (6 € statt "gratis")

**Comment by LarsKumbier** [comment]
Next meetup for this topic has been moved from June 19th to June 26th, 19:00.

**Comment by LarsKumbier** [comment]
Meeting Minutes

* @Pakue95 macht einen Prototypen für einen elektronischen Würfel mit Gehäuse für 3D-Druck fertig
  * eventuell müssen die Platinen zum Teil vorgelötet werden
* @LukasFreeze  macht einen großen Kreisel für Farbexperimente fertig
  * Kreidezirkel
  * Chromatographie
* Erik bereitet Ideen für Experimente mit 4-8 Jährigen vor. Bisherige Ideen
  * Chromatographie auf dem Kreisel oder direkt auf Löschpapier
  * Ente / Elefant / Maus als Zieh-Spielzeug selber anmalen und zusammenbauen
  * Magnet-Experimente (Eisenspäne in Box, in Flüssigkeit, etc.)
  * Verschiedene Schichten in einem Glas und Gegenstände versenken
  * Flügelformen: Was ist die beste Form für einen Papierflieger? => Flugtheorie
 
Offene Punkte

* Kaffeemaschine
* Kuchenspenden

**Comment by Pakue95** [comment]
Ich habe mal etwas wegen der Würfelplatine herumgesucht und gebastelt. Die Komponentenliste liegt nun bei:

* 555 timer ic
* CD4017B Decadenzähler
* 7 10mm LEDs (das sind die ganz großen, man kann aber auch kleinere verwenden)
* 3 NPN Transistoren (2N3904)
* 1 PNP (2N3906)
* 12mm Knopf
* 1 Batterieschalter
* Batteriegehäuse (4x AA)
* 1x 1nF Kondensator
* 1x 1k Widerstand
* 9x 10k Widerstand
* 5x 100 Ohm Widerstand
* (optional) Vibrationssensor, mit dem man den Würfel auch durch schütteln oder auf den Tisch tappen zum neu würfeln bekommen kann.

Die meisten Teile habe ich schon billig auf Ali gefunden und bestellt für eine Stückzahl von ca 50. Mit Platinen (ca 25€ + shipping) sollte das immer noch deutlich unter 2€ pro Board sein.

Die Platine ist momentan 70x70mm mit M4 Schraubenlöcher um sie in ein Gehäuse einzubauen.

![image](https://user-images.githubusercontent.com/19751734/60344146-24ae2180-99b6-11e9-8b6d-d56ccc500c33.png)

**Comment by NitramLegov** [comment]
Bezüglich Kuchenspenden: Ich hab bei mir in der Familie mal gefragt und kann schon mindestens einen Kuchen zusichern ;)

**Comment by ErikSchatz** [comment]
das mit dem Maus-Türöffnertag habe ich mir mal genauer angeschaut:
die Veranstaltung soll zu einem Thema / einer Fragestellung sein und nicht eine Kinderbespaßung mit einem Sammelsurium an Aktivitäten.
Mein Vorschlag:
Fragestellung: Was ist ein Makerspace?
Antwort: Eine offene Werkstatt, in der du das, das, … und das machen kannst.
(von Low-Tech bis High-Tech)  => unsere Aktivitäten
Löten passt, 3D-Druck passt, Programmieren passt, CAD passt, Holzarbeiten passen, … ; 
Weitere Vorschläge?

**Comment by NitramLegov** [comment]
Nachdem sich hier lange niemand drum gekümmert hat, habe ich mal ein Google Drive Dokument angefangen:
https://docs.google.com/document/d/1d7WMw6h56p5sZzo9V31-YQqf6586qjLgFhQESVnD4oM/edit?usp=sharing
Das ist öffentlich, da kann also jeder dran Mitarbeiten. Effektiv muss man hier aktuell nochmal die Formulierungen anpassen (bitte unterscheiden zwischen dem, was nach draußen gehen soll und was nur intern für den WDR ist). Danach muss man nochmal kurz mit unseren Managern klären, wer von ihnen dem WDR gegenüber als Ansprechpartner dienen soll. Von der Aufgabenverteilung her wäre das @beanobeano. Allerdings schlage ich vor, dass das jemand macht, der schon weiß, dass er an dem Tag kann. @emka @LukasFreeze @Pakue95 Wie seht ihr das? Vielleicht kann ja auch @beanobeano  :)

Und wir brauchen noch ein Bild! Denkt an die Vorraussetzungen (kein Firmenlogo, etc.). Am besten sprichst du das heute Abend mal bei @kenomaerz an. Der kennt das Thema.

**Comment by kenomaerz** [comment]
Ich hab den Text mal ergänzt, viel ist es ja wirklich nicht. 
- Wichtig zu klären: Wer macht den Ansprechpartner? -> Ich würde mich bereit erklären, bin aber auch nicht böse, wenn das jemand anders macht (@beanobeano ?)
- Was ist unsere Altersempfehlung? -> ich denke wir können eine relativ große Bandbreite abdecken.
- Wer kümmert sich um das Bild?
- Wer kümmert sich um die Einreichung?
Wäre super, wenn sich hier Leute melden würden =)

**Comment by kenomaerz** [comment]
Ich würde Mobile bauen anbieten, und zwar mit der CNC gefräst. Ablauf:
Vor dem Tag:
1. Fräsen von den Trägerelementen, mit mehreren Löchern zum Balancieren
2. Vorbereiten von Rohlingen und Rohlinghalterung an der CNC, damit zügig gearbeitet werden kann
3. Nylon kaufen
4. Einige Vorgefertigte mobile-elemente Fräsen
 
Am Tag:
1. Kinder suchen 3-4 Silhouetten aus dem Internet
2. Betreuer startet den Fräsauftrag
3. Gemeinsam beim Fräsen zuschauen
4. Aus den selbstgemachten und vorgefertigten Teilen wird ein Mobile gebaut.

**Comment by kenomaerz** [comment]
Außerdem würde ich alle bitten, die DEFINITV ein Projekt anbieten, sich hier einzutragen:
https://docs.google.com/document/d/1V5Z8RAlXFT8CvQQy5ubRhIb--E7RUTbw9fpOL-Xlrc8/edit?usp=sharing

**Comment by ErikSchatz** [comment]
Hallo,

habe mich mit "Löten von einfachen elektronischen Bausätzen" eingetragen.

Für besonders begabte und interessierte Kinder kann Anspruchsvolleres

wie Wechselblinker (habe ich) und elektronischer Würfel vorgehalten werden.

 

Wenn jemand anderes das übernehmen wollte,

könnte ich "Programmieren eines Mikrocontrollers" machen.

Mit dem micro:bit (habe ich) und der OnlineIDE https://makecode.microbit.org/#

klappt das richtig gut. (Grafisches Programmieren)

 

Wer macht etwas mit CAD und 3D-Druck?

Oder "normale" Holzarbeiten? (Sägen, Bohren, Schrauben, ...)

 

Die damals angedachten Experimente passen meiner Meinung nach

nicht zu unserer Werkstatt, sondern in ein Labor.

 

Viele Grüße, Erik

 

Gesendet: Freitag, 30. August 2019 um 17:51 Uhr
Von: "kenomaerz" <notifications@github.com>
An: comakingspace/do-something <do-something@noreply.github.com>
Cc: ErikSchatz <erik.schatz@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [comakingspace/do-something] Maus-Türöffnertag (#127)


Außerdem würde ich alle bitten, die DEFINITV ein Projekt anbieten, sich hier einzutragen:
https://docs.google.com/document/d/1V5Z8RAlXFT8CvQQy5ubRhIb--E7RUTbw9fpOL-Xlrc8/edit?usp=sharing

**Comment by ErikSchatz** [comment]
schaut mal folgendes aus Karlsruhe (3 Angebote) an:
https://www.wdrmaus.de/tuer_oeffner_tag/2019/index.php5?detail=705593
https://www.wdrmaus.de/tuer_oeffner_tag/2019/index.php5?detail=705595
https://www.wdrmaus.de/tuer_oeffner_tag/2019/index.php5?detail=701644
Heidelberg hat bisher nur ein Angebot (Reit- und Fahr-Verein).
https://www.wdrmaus.de/tuer_oeffner_tag/2019/index.php5?detail=702029
**Die Zeiten kann man anscheinend selbst festlegen.**
Wie wärs: Wir melden uns unter **"Makerspace"** an?
angelehnt an Keno die Beschreibung für die Kinder: (sie passt, 500 Zeichen, habe es ausprobiert!)
Wir haben eine "offene Werkstatt", in der die Werkzeuge von allen Mitgliedern benutzt werden können. Wie baue ich Dinge selbst zusammen? Kann man Gegenstände drucken? Wie macht man eine elektronische Schaltung? Wie wird Elektronik programmiert? Was kann ich aus Holz bauen? Wenn du das und mehr wissen und machen willst, sind wir heute für dich da! Wir bauen mit dir Dinge aus Holz, helfen beim 3D-Druck und zeigen, wie man mit herkömmlicher und moderner Technik tolle Sachen selbst herstellt.

**Comment by ErikSchatz** [comment]
Ich habe noch die interne Beschreibung etwas geändert, bitte anschauen!
Kann als Bild eine Kollage ähnlich zu unseren Plakaten verwendet werden?
Wer kann das Pixel-genau machen?

**Comment by NitramLegov** [comment]
Ich habe heute mal ein paar Sachen zusammengelegt und ein paar Bilder gemacht:
https://drive.google.com/folderview?id=1VSO9PGKT0AjFeJXWKM7_PogTUqThC5uX

Schaut mal rein, ob euch das schon ausreicht. Ansonsten hätte ich noch Bilder aus der Werkstatt im Angebot.

**Comment by NitramLegov** [comment]
Bezüglich Kenos fragen:
- Wichtig zu klären: Wer macht den Ansprechpartner? -> Ich würde mich bereit erklären, bin aber auch nicht böse, wenn das jemand anders macht (@beanobeano ?)
Ich würde mich hier auch bereit erklären. Aber vielleicht will das auch einer der Manager machen.

- Was ist unsere Altersempfehlung? -> ich denke wir können eine relativ große Bandbreite abdecken.
Ich denke auch, dass unsere Bandbreite recht groß sein kann. Jünger als 8 Jahre finde ich in der Werkstatt schwierig, aber nach oben können wir bestimmt bis 14 gehen.
- Wer kümmert sich um das Bild?
Siehe oben. Gebt mir gerne Feedback. Falls ihr die Bilder scheiße findet dürft ihr das auch genau so sagen! 
- Wer kümmert sich um die Einreichung?
Kann ich machen. Ist ja aber eh nur hochladen, also kein Aufwand.


Bezüglich der Beschreibungen halte ich die jetzt schon für gut. Daher ist für mich am dringendsten der Ansprechpartner und das Bild. Den Rest kriegen wir hin 👍

**Comment by ErikSchatz** [comment]
Hallo Martin, danke für die Bilder, Bild 0745 finde ich am Besten.
Bild: Querformat (jpg-Datei, mind. 516x318 Pixel/72dpi) haben wir damit.
Es könnte zwar noch etwas "holziges" dabei sein, muss aber nicht wirklich.
Jedes Kind weiß wie Holzspielzeug aussieht.

Alter: 8 bis 14 Jahre finde ich O.K.
Zeiten: 10 - 12:30 , Mittagspause&Puffer , 13:30 - 16:00 ???

**Comment by beanobeano** [comment]
Unfortunately, I’m swamped and am unable to be involved in this project.

**Comment by LukasFreeze** [comment]
Ich kann an dem Termin leider wie gesagt nicht, biete aber weiterhin an, den Kreidekreisel bis dahin fertig zu machen - damit das fest als Projekt eingetragen werden kann, müsste dann aber noch jemand diese Station betreuen. Inspiration: https://www.youtube.com/watch?v=ZcJ-wKN9iLY

Zum Foto: ich finde es ehrlich gesagt etwas voll :-P Die Platine hat ja (bisher) mehr mit dem tatsächlichen Programm zu tun als der ganze 3D-Druck, aber auf dem Bild springt sie mir leider gar nicht so ins Auge. Etwas besseres habe ich leider gerade nicht anzubieten und ich weiß das mittlerweile auch nicht mehr viel Zeit ist, wollte aber zumindest noch Feedback geben... heute Abend ist möglicherweise vor der Bandsägeneinweisung etwas Zeit falls noch ein anderer Vorschlag gewünscht wird, ansonsten bin ich mit der Meinung auch gerne alleine...

**Comment by NitramLegov** [comment]
Die Foto Vorschläge sind das Ergebnis von "oh, wir haben noch kein Foto, jetzt aber schnell" am Samstag. Die sind absolut nicht perfekt (merke: kreative Sachen sollte man nicht mir überlassen, da kommt nichts gutes bei raus ^^). Falls du heute Abend noch Zeit hast kannst du also sehr gerne noch andere Fotos liefern!
Bezüglich der Platine: Denk dran, dass auf den Fotos KEIN Firmenlogo zu sehen sein darf! Darum ist die so vom Elch verdeckt ;)

"Anmeldeschluss für die Teilnahme als Veranstalter am diesjährigen Türöffner-Tag ist der 3. September 2019."

Ich hoffe, dass das den 3. September inkludiert ;)

**Comment by LukasFreeze** [comment]
Wie wär's hiermit? ![2019-09-02 17 20 37](https://user-images.githubusercontent.com/19755883/64123952-02fe5b80-cda6-11e9-97fc-d6c1adf719f3.jpg)

Oder mit etwas mehr Holz-/Werkstattbezug:
![2019-09-02 17 27 00](https://user-images.githubusercontent.com/19755883/64124284-e4e52b00-cda6-11e9-90bf-400c300eb877.jpg)

Ich bin fürs zweite, danke Simon für kreativen Input :-)

**Comment by NitramLegov** [comment]
Anmeldung ist abgegeben. Ich stehe als Ansprechpartner für die Redaktion drin, Keno steht als Empfänger für Pakete drin :)

Als Bild hab ich das zweite Bild von Lukas genommen.

Die Anmeldung wird geprüft und dann veröffentlicht. Ich krieg per Mail nochmal Bescheid und melde mich dann nochmal.

**Comment by LukasFreeze** [comment]
Super, dann sollte es ja auf jeden Fall rechtzeitig gewesen sein :+1:

**Comment by kenomaerz** [comment]
Danke für's managen, Martin!

**Comment by NitramLegov** [comment]
Da gibts nichts zu danken! Danke eher an die, die Projekte anbieten. Und jetzt müssen wir uns auch erstmal noch dran machen, dass wir den Tag komplett fertig planen (wer ist wann da & betreut welche Station?).

@LukasFreeze Das mit dem Kreidekreisel fänd ich glaube ich cool :)
@Pakue Sind von den elektronischen Würfeln genug Platinen da? Sind das immer ganze Bausätze, sind also auch die notwendigen Komponenten jeweils da? :)

**Comment by Pakue95** [comment]
Von den Platinen habe ich nochmal eine V2 geordert, die einfacher zu löten ist. Komponenten sind genug da. 4xAA Batteriehalter sollten noch 15-20 kommen.

**Comment by NitramLegov** [comment]
Patrick bestellt noch bleifreies Lötzinn für die Kinder

**Comment by LukasFreeze** [comment]
Kreide ist da, den Kreisel schaffe ich hoffentlich am Mittwoch :-)

Bevor ich den Newsletter schreibe - ist es Absicht, dass es eine Öffnungszeit von 9-12 Uhr (3 h) und eine von 14-16 Uhr (2 h) gibt?

**Comment by NitramLegov** [comment]
Absicht ist das nicht, aber ich fürchte das ist mir durchgegangen. Sorry!
Ich kann aber versuchen, denen nochmal zu schreiben, dass das 14-17 Uhr sein sollte.
Haben wir denn schon Anmeldungen?

**Comment by LukasFreeze** [comment]
Nee, hab nur gerade auf der Seite gesucht obs schon einen Link für uns gibt

**Comment by NitramLegov** [comment]
Gibt es:
https://www.wdrmaus.de/tuer_oeffner_tag/2019/index.php5?id=706013
________________________________

**Comment by NitramLegov** [comment]
Unsere Veranstaltung scheint ordentlich Anklang zu finden. Wir sind komplett ausgebucht! 🙂

Jetzt geht es noch um ein bisschen PR:
Wir haben einen Starschnitt der Maus zum selbstausdrucken und basteln zur Verfügung gestellt bekommen. Will den jemand drucken und auf Pappe kleben? Dann kann ich gerne den Link schicken.

Ansonsten gibt es noch weiteres PR Material, das man ausdrucken kann. Inklusive Plakate, Wegweisern, etc. Wer kann das am Tag davor übernehmen? Wenn wir Plakate drucken wollen müssen wir das demnächst tun!


________________________________
Von: Martin Vogel <martin_vogel@live.com>
Gesendet: Montag, 9. September 2019 21:23
An: comakingspace/do-something <reply@reply.github.com>; comakingspace/do-something <do-something@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Betreff: Re: [comakingspace/do-something] Maus-Türöffnertag (#127)

Gibt es:
https://www.wdrmaus.de/tuer_oeffner_tag/2019/index.php5?id=706013
________________________________

**Comment by LukasFreeze** [comment]
Ich wäre gegen Plakate - kosten nur Geld für einen Stapel Altpapier und sie locken in diesem Fall höchstens Leute an, die dann gar keinen Platz bekommen...

Wegweiser finde ich gut, statt Maus-spezifische könnten wir aber einfach mal ein paar stabile Pfeile mit "CoMakingSpace" basteln die wir dann für alle möglichen Events wiederverwerten können :-) Das Aufhängen könnte ich am 2.10. nach dem Plenum übernehmen.

**Comment by kenomaerz** [comment]
Das Care Paket ist angekommen!

**Comment by NitramLegov** [comment]
Ich übernehme mal die issue hygiene......
