### ISSUE TITLE
Mobile layout for the wiki

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#128]
The wiki does not really adjust to mobile screens currently. As far as I know, there are possibilities to make it more responsive. Can we check these and possibly install them? :)
@emka I´m assigning you, because as far as I am aware, you´re the one that can install stuff in the wiki, correct?

**Comment by emka** [comment]
If you provide a link to the extension that is most suitable, I can install it.

**Comment by NitramLegov** [comment]
Hmmm, I would recommend checking this extension:
https://www.mediawiki.org/wiki/Extension:MobileFrontend/de

This should Install the following skin as well:
https://www.mediawiki.org/wiki/Skin:Minerva_Neue

As far as I understand, this would basically give us the mobile interface of wikipedia. And what´s good enough for wikipedia should be good enough for us as well.

**Comment by emka** [comment]
Done. MobileFrontent requires configuring a mobile skin.

Manually installed Minerva Neue and configured
```
wfLoadSkin( 'MinervaNeue' );
$wgMFDefaultSkinClass = 'SkinMinerva';
```
