### ISSUE TITLE
Make the wiki editor look more nicely

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#129]
Can we check out the VisualEditor extension for our wiki?
https://www.mediawiki.org/wiki/Extension:VisualEditor

I think it would make editing wiki content more user friendly and thus more easy.
@LukasFreeze any opinion / objection?
@emka I´m assigning you as our wiki server admin :)

**Comment by emka** [comment]
Two objections:
- The extension is not stable yet.
- The extension requires installing an additional service running on Node.js

This additional service would need to run isolated, and be run by us or a DSGVO compliant provider. I am unable to invest the time required for that.

**Comment by NitramLegov** [comment]
Well,
1. The extension is stable enough to be used in Wikimedia projects. I would personally say this is most likely stable enough to be used in a small wiki as ours as well.
2. As far as I know, we have our own server. This should hopefully be capable of running a nodejs application....
3. If you do not have time, we should discuss how we can put the workload for these things on more shoulders.
4. I did not ask for an immediate implementation, but for checking the extension. Just closing the issue based on "no time" is not an appropriate reaction. If this is not the right extension to choose, we can possibly discuss others as well.

**Comment by LukasFreeze** [comment]
Ich fänd sonst auch schon [WikiEditor](https://www.mediawiki.org/wiki/Extension:WikiEditor) nett, damit hat man mindestens so viele Shortcuts wie hier im GitHub-Editor (zB Listen, Einrückungen, scheinbar sogar ein Tabellen-Tool)

**Comment by emka** [comment]
For point 2. my requirement is that the service is running as isolated process, we don't have the proper infrastructure yet.

For point 3. I would suggest to prepare Ansible playbooks that set up a server running Fedora/Debian/Ubuntu with automatic updates, nginx and Mediawiki. The playbook should be able to install Mediawiki extensions including updates, and handle Mediawiki upgrades, as well as create local database backups. Once that is working on a test server, I can use it to migrate the data to a production instance. Everyone can then contribute via pull requests.
Setting this up would be a lot of work, but is a clean way to distribute the administration task.

Would you be happy with the extension Lukas suggested? Feel free to re-assign me once the discussion concluded.

**Comment by NitramLegov** [comment]
Generell ist WikiEditor schon ganz nett. Allerdings müsste die extension an sich bei uns schon aktiviert sein (ist ein default ab mediawiki 1.18, wir sind auf 1.32.2). Insofern haben wir das schon. Das ist die kleine Toolbar, die bei uns im edit mode gezeigt wurde (meiner Meinung nach war die gestern vor dem Upgrade auf 1.32 noch da, aber das upgrade hat eh einiges am Interface geändert..)

Daher müsste man nun schauen, ob da unter Umständen auch die extension mit rausgeflogen ist / nachinstalliert werden muss.
Was uns tendenziell so oder so noch fehlt ist das customizing, damit es die gleichen Funktionen bietet wie in der Wikipedia. Dazu ist tendenziell mindestens customizing in der Datei extensions/WikiEditor/modules/jquery.wikiEditor.toolbar.config.js notwendig. Ich habe noch nichts gefunden, wie wikipedia die Sachen genau eingestellt hat.
Wer es aber ausprobieren will, kann das zum Beipiel hier tun:
https://test.wikipedia.org/w/index.php?title=Bavosa_d%27alga&action=edit

Aber Achtung: Da sind auch Sachen wir der Template Wizard aktiv. Auch eine ziemlich coole extension.


@emka Ich geb dir Recht, dass das nichts ist, was wir mal eben schnell machen. Aber ich glaube hier würde sich anbieten, den Umzug auf einen V-Server zumindest mittelfristig anzugehen (das hier hat ja aktuell nicht die höchste Prio). Dann könnte man die einzelnen Services containerisieren und damit voneinander trennen und sie auch aktuell halten. Dann müssten wir irgendwann über die Rahmenbedingungen diskutieren und darüber, was da alles laufen soll. Aber prinzipiell wäre da ja einiges denkbar. Das ist aber natürlich ein größeres Thema.

**Comment by LukasFreeze** [comment]
Seit dem Update vom Wochenende scheint etwas mit unserem bisherigen Editor kaputt zu sein - da waren zumindest mal rudimentäre Buttons (fett, kursiv, Links...)!

![grafik](https://user-images.githubusercontent.com/19755883/59439438-96527100-8df5-11e9-8178-7e4e7d748a5c.png)

@emka weißt du, ob wir wirklich schon den "WikiEditor" hatten? Dann könnten wir den im Zuge der Reparatur gleich etwas umfangreicher konfigurieren, wie Martin vorgeschlagen hatte.

**Comment by emka** [comment]
Weiß ich leider nicht, zumindest habe ich nichts aktiv entfernt. Jetzt ist sie jedenfalls nicht bei Special:Version gelistet, dann muss die wohl wieder nachinstalliert werden.

**Comment by NitramLegov** [comment]
Dann wäre mein Vorschlag, erstmal den WikiEditor zu aktivieren und uns anzuschauen, wie der aussieht.

Je nachdem können wir dann noch in Customizing investieren und ggf. den TemplateWizard auch noch implementieren (ich persönlich bin da dafür, Lukas ist eher skeptisch)

**Comment by emka** [comment]
WikiEditor ist jetzt aktiviert.

**Comment by NitramLegov** [comment]
Sieht gut aus. Lasst uns damit erstmal anfangen und dann schauen, ob wir in der config noch was anpassen wollen oder ähnliches. Danke+

**Comment by NitramLegov** [comment]
Visual Editor ist jetzt aktiv
