### ISSUE TITLE
Umstrukturierung & Semantic Info für Ausrüstungs-Wikiseiten

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#130]
@NitramLegov hat mal ein bisschen mit unserer neuen Wiki-Erweiterung "Semantic MediaWiki" rumgespielt und manchen Werkzeugen und Geräten einen "location"-Parameter mitgegeben, sodass sie jetzt automatisch abgelistet werden können: https://wiki.comakingspace.de/index.php?title=Wood_Workshop&type=revision&diff=6687&oldid=1914

Ich finde das auch ziemlich praktisch, es zeigt sich aber jetzt schon, dass wir ein paar Sachen überarbeiten sollten:
- [x] Neudefinition der [MachineInfoBox](https://wiki.comakingspace.de/Template:MachineInfoBox) zu "alles mit Stecker"
  - wir müssen eigentlich nicht zwischen "Maschine" vs "Elektrogerät" unterscheiden, diese Vorlage ist damals im wesentlichen entstanden weil wir z.B. Felder wie "Software" für 3D-Drucker ermöglichen wollten und noch nicht wussten, wie wir die optional machen ("normale" Werkzeugboxen wurden durch die ungenutzten Felder unübersichtlich)
- [x] Änderung der Infoboxen aller ["Power Tools"](https://wiki.comakingspace.de/Category:Power_Tools) zur MachineInfoBox
  - bei der Gelegenheit kann direkt ["Location::" eingefügt](https://wiki.comakingspace.de/index.php?title=Bandsaws&diff=6689&oldid=5313) werden!
- [ ] in ToolInfoBoxen die ["Location::" und ggf. "Tutor::"-Parameter einpflegen](https://wiki.comakingspace.de/index.php?title=Chisels_(Woodworking)&diff=6798&oldid=6796)

Das wäre schonmal ein guter Start :-)

**Comment by NitramLegov** [comment]
habe alle Tools die meiner Meinung nach Machines sind zu Machines umgewandelt und Location:: sowie Tutor:: eingefügt.

Bei denen, bei denen ich dran gedacht habe habe ich auch Die Access Requirements umformuliert und "personal introduction" rausgenommen

Jetzt muss man nochmal über alle Machines drüber, dass da auch die Location:: und Tutor:: Parameter gesetzt sind...

**Comment by LukasFreeze** [comment]
Ich habe mal die Kategorien "Machines" und "Tools" mit den neuen Definitionen versehen und "Power Tools" zu "Machines" und "Hand Tools" zu "Machines" weitergeleitet.

Auf den InfoBox-Seiten müssten auch gerade noch leicht falsche Beschreibungen stehen...der Haken ist also erstmal wieder weg ;-)

**Comment by NitramLegov** [comment]
Außerdem muss man noch über die Seiten mit ToolInfoBox drüber und dort entsprechend das Location:: Attribut pflegen.

**Comment by LukasFreeze** [comment]
Hier sind alle "Tool"-Seiten: https://wiki.comakingspace.de/Category:Tools

Ich habe sie schonmal bis einschließlich "Circlip Pliers" aktualisiert, [hier ein Beispiel](https://wiki.comakingspace.de/index.php?title=Chisels_(Woodworking)&diff=6798&oldid=6796) :-)

**Comment by reisners** [comment]
Anstatt auf jeder Tool-Seite im location-Parameter des ToolInfoBox-Templates explizit [[Location:: ...]] zu schreiben, könnte man die Location-Property auch _im_ ToolInfoBox-Template automatisch setzen. Der Vorteil wäre, dass sofort alle Location auch semantisch verfügbar wären. Der Nachteil wäre, dass man dann keinen abweichenden Link-Text hätte (z.B. [[Location::Wood Workshop|wood workshop]], sondern immer den Seitennamen as-is.

**Comment by NitramLegov** [comment]
Das würde doch aber im umkehrschluss bedeuten, dass man beim ausfüllen darauf achten müsste, die location nicht als link hinzuzufügen, richtig? Außerdem könnte man dann keine Kommentare oder ähnliches in klammer schreiben, oder? Also zum Beispiel
"Chop saw station (right side, next to xyz)"
Oder ähnliches.
________________________________

**Comment by LukasFreeze** [comment]
ich bin für Freitext, hab eben auch das feste "Status::" in der
MachineInfoBox wieder entfernt weil es schon Probleme gemacht
hat...insgesamt haben wir ja auch nur eine überschaubare Seitenzahl und die
meiste Arbeit ist schon getan :-)

**Comment by reisners** [comment]
Ok, macht Sinn. Ich wollte nur auf die Möglichkeit hinweisen.

**Comment by LukasFreeze** [comment]
Bestimmt macht es irgendwo auch nochmal Sinn! "Tutor" geht leider auch
nicht, weil da (idealerweise) immer mehrere Leute stehen

**Comment by emka** [comment]
Manche Funktionen, z.b. `len` waren nicht verfügbar. Laut https://www.mediawiki.org/wiki/Extension:StringFunctions muss man dafür `$wgPFEnableStringFunctions = true;` setzen, das habe ich nun getan.

**Comment by LukasFreeze** [comment]
https://wiki.comakingspace.de/Metal_Workshop/Gallery

Ich hab mal "Has image::" automatisiert in die MachineInfoBox eingebaut, gegen mehrfache Werte auf einer Seite muss man in den überschüssigen Boxen etwas tricksen...Anleitung dazu s. MaterialInfoBox-Doku, sagt Bescheid wenn das unklar ist :-)

Bevor die Gallerie sichtbarer gemacht wird sollten wir da noch etwas an der Gestaltung tüfteln, siehe [SMW Doku](https://www.semantic-mediawiki.org/wiki/Help:Gallery_format)

**Comment by LukasFreeze** [comment]
So, noch eine lange Autofahrt später und alle ToolInfoBoxen sollten aktualisiert sein! Category:Hand Tools ist auch komplett nach Category:Tools migriert.

Jetzt fehlt eigtl nur noch, alle Geräte aus [Category:Power Tools](https://wiki.comakingspace.de/index.php?title=Category:Power_Tools&redirect=no) zu entfernen! Für weitere Vorhaben machen wir am besten neue Projekte/Issues auf

**Comment by LukasFreeze** [comment]
"Power Tools" ist abgeschafft :-)

Ich bin gespannt, was noch so alles für Funktionen kommen! Und demnächst schonmal @reisners Seminar?
