### ISSUE TITLE
Upgrade Printer Firmware

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#131]
Prusa Released a new Firmware Version for our printers:
https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.2.3

I would suggest we install it :)

**Comment by emka** [comment]
@lmnl99 was trying to find the rambo board version, it is 1.3 (see #13)

**Comment by lmnl99** [comment]
Ich habe heute die Firmware auf dem Prusa P1 die Firmware upgedatet. Bitte testet diesen Drucker gern und schreibt eure Erfahrungen auf. Zur Info die neue Firmware hat laut Prusa neue tolle Features, für Infos müsst ihr auf der Prusa Homepage nachlesen.

**Comment by Johannes09** [comment]
Ich habe jetzt den letzten Drucker (P2) geupgradet!
