### ISSUE TITLE
Maker Flohmarkt

### ISSUE THREAD

**Issue by lmnl99** [comakingspace/do-something#132]
Wie in der WhatsApp-Gruppe angeregt wollen wir einen "Maker-Flohmarkt" im CoMakingSpace veranstalten. Das ganze soll nicht kommerziell sein, sondern den Leuten in unserer Community eine Möglichkeit geben, überschüssige Bauteile an andere Maker abzugeben und am besten auch selbst fündig zu werden!

- Ort: CoMakingSpace - Gemeinschaftsraum & ggf. draußen
- Datum: 17.8.2019 (laut [Doodle mit "Ausstellern"](https://doodle.com/poll/cwng2sh87hev2zw4) eine gute Option)
- Uhrzeit: **???**
- Gesamtorganisation, Vorbereitung: @lmnl99, ???
- Organisation während der Veranstaltung: @lmnl99, @NitramLegov 
- nötige Vorbereitungen (grob):
  - [ ] Aufbau-Team finden
    - [ ] planen, wo Tische stehen sollen und was sonst noch aufgebaut werden sollte
    - [ ] Aufbau - am Vortag oder direkt vor Beginn?
  - [ ] Ankündigung(en) - Ideen unter https://wiki.comakingspace.de/Event_Ideas#Organize_an_Event
  - [ ] **was fehlt noch??**
- wer hat weitere Ideen oder wäre gerne dabei?

*to make sure your idea is visible, you should also share this "issue" via the [Mailing List](https://wiki.comakingspace.de/Mailing_List) and ask for help there!*

**Comment by lmnl99** [comment]
Ich habe mich gestern am 20.06.19 als Organisator für den Maker Flohmarkt bereit gestellt. Ich habe geschaut am 17 und 24 August haben sich die jeweils 4 Leute eingetragen. Ich lege den Termin jetzt auf den 17.08.19 fest. Ich werde eine Liste erstellen was wir alles benötigen diese werde ans Issue hängen, dort soll dann jeder bitte Kurz schreiben was bereit er stellen kann und was er verkauft. Diese Liste wird früh möglichst erstellt. Jeder der Ideen hat gern ins Issue schreiben, ich bedanke mich schon mal für eure Hilfe.

**Comment by Pakue95** [comment]
Bisher hat sich hier noch nichts weiter getan. Wir hatten es heute kurz im Plenum angesprochen und waren der Meinung das Issue zu schließen.
