### ISSUE TITLE
Wiki Main Page and the new mobile skin don´t go together very well

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#133]
Leider sieht die Hauptseite des Wiki (Speziell die Galerie, die die Bilder der Workshops durchwechselt) nicht sonderlich gut aus mit dem neuen mobilen Skin.
Da müssen wir ran.

Ich darf die Main Page nicht editieren, das müssen also unsere Manager machen ;)

**Comment by LukasFreeze** [comment]
Da hast du auf jeden Fall recht, die Slideshow wurde ja einfach nur als untereinander stehende Bilder angezeigt... 

Hier wird beschrieben, wie man in solchen Fällen vorgehen sollte: https://www.mediawiki.org/wiki/Mobile_Gateway/Mobile_homepage_formatting

Ich [habe die Slideshow in der mobilen Ansicht jetzt einfach mal ausgeblendet](https://wiki.comakingspace.de/index.php?title=Main_Page&diff=6837&oldid=2954), leider kriege ich aber die unsichtbare Box nicht weg ("| width=300px |"). Einen statischen Ersatz an der gleichen Stelle, zB prominenter Verweis auf die Projektseite oder ein supertolles Foto von irgendeiner Werkstatt mit Leuten drin, habe ich mangels Einstellungsmöglichkeit für "nodesktop" jetzt auf die Schnelle auch noch nicht hinbekommen.

Als Hotfix finde ich das akzeptabel, aber wenn du noch bessere oder weitere Ideen hast immer her damit! Zum Testen könntest du doch eine Sandbox-Seite mit dem gleichen Inhalt wie die Mainpage erzeugen, oder?

**Comment by LukasFreeze** [comment]
Es gibt jetzt die Möglichkeit von "mobile-only", damit ist der obere Bereich schonmal recht gut umzusetzen: [meine Sandbox dazu](https://wiki.comakingspace.de/index.php?title=User:Lukas/Sandbox&oldid=7344&mobileaction=toggle_view_mobile)

Wenn wir jetzt also eine Mainpage für Desktop und eine andere Version für Mobilgeräte bauen wäre die Frage, was jeweils drauf soll. Die Tabelle ist mobil nicht allzu gut, vielleicht da stattdessen etwas klappbares? Also zB Zwischenüberschriften? Oder gibt's sonst noch Vorschläge?

Generell nervt mich am Mobile Frontend allerdings das (scheinbare?) Fehlen der ganzen Sidebar-Funktionen (recent changes, eMail user, ...) und "show history", deshalb nutze ich fast immer die Desktop-Ansicht. Oder hat diese Funktionen schon jemand entdeckt?

**Comment by LukasFreeze** [comment]
Hab den Intro-Teil jetzt schonmal geändert, wenn noch jemand Ideen hat können die gerne auch in meiner Sandbox getestet werden!

**Comment by LukasFreeze** [comment]
Seit zwei Updates gibt es keine mobile Ansicht mehr, hier kann also gerade nichts getan werden...
