### ISSUE TITLE
Ethernet für den 3D-PC

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#134]
Es gab ja immer mal wieder Rufe nach Kabelanbindung für den "Slicer-PC" im Elektronikraum, jetzt ist es in greifbarer Nähe :-)

@NitramLegov und @Johannes09 haben gestern ein langes Kabel bis fast in den Raum gelegt, an das bald ein "Raspberry Pi Lab" auf der e-Bench angeschlossen werden soll. Wenn da jetzt jemand einen einfachen Switch spendiert, wäre der PC gleich mit anzuschließen!

Hat jemand noch einen rumliegen oder könnte einen besorgen (am besten auch gleich noch einen SD-Karten-Leser?)

**Comment by NitramLegov** [comment]
Kurzes Update: Das Raspberry Pi Lab steht erstmal in Version 1 und hat Ethernet. Wie Lukas geschrieben hat muss jetzt nur noch jemand einen switch organisieren und den PC anschließen.

**Comment by NitramLegov** [comment]
Closed, since this task will most likely change when the space gets moved
