### ISSUE TITLE
3D printer P4 is clogged

### ISSUE THREAD

**Issue by sbillaudelle** [comakingspace/do-something#135]
Printer P4 is clogged. I already tried to reload the filament.

**Comment by Pakue95** [comment]
I've taken apart the hotend assembly and cleaned the inside of it. There was a block just underneath the PTFE tube from carbonised plastic that was heated for too long and started to clog up. 

As the hotend was already disassembled, I took the liberty to change out the nozzle. The old one has seen some better days...
