### ISSUE TITLE
neue Tischkreissäge einpflegen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#139]
Wir haben eine Elektra Beckum PK 255 gespendet bekommen! Das P steht für Präzision 😎

Wie üblich muss die aber "commissioned" werden, je mehr Leute helfen desto schneller können wir sie freigeben:
- [x] [Checkliste (EN) im Wiki](https://wiki.comakingspace.de/Table_Saw#Coming_Up:_Elektra_Beckum_PK_255) erledigen

Was hardwareseitig sonst noch zu machen wäre, damit sie gleich von Beginn mindestens den gleichen Funktionsumfang wie unsere jetzige hat:
- [x] @LarsKumbier möchte einen Schiebeschlitten bauen
- [x] [Stromkabel](https://kvm-switch.de/images/product_images/popup_images/12533_Product.jpg) besorgen (Länge??)
- [x] Staubabsaugung
   - ca. 1 m Schlauch mit 100 mm Durchmesser für Verbindung Sägeblatt -> Ausführung am hinteren Fuß
   - kleines Stück dieses Schlauchs außen an die Ausführung, damit die Bamato-Absauganalge dranpasst
   - Staubsaugeradapter (Festool) für die Spanhaube drucken (#24) 

Wer dafür etwas am Gerät tun muss wird gerne ins Lager gelassen 😉

**Comment by LukasFreeze** [comment]
Oops, assignees gingen eben mobil irgendwie nicht - jetzt aber:

@Pakue95 (inventory manager)
@LarsKumbier @LukasFreeze (tutors)

Weitere Hilfe, vor allem Leute die sich vorstellen könnten noch Tutoren zu werden, ist natürlich absolut willkommen!

**Comment by LukasFreeze** [comment]
Das mit dem Drehstrom war Quatsch, hatte nur in der Eile des Entgegennehmens nicht genau in den Anschluss geschaut - wir brauchen nur ein ganz normales Schuko-Verlängerungskabel (habs oben auch korrigiert).

@LarsKumbier hat gestern direkt mit dem Schiebeschlitten angefangen und sich angeschaut, wie das mit der Staubabsaugung wohl gedacht ist, und wir müssen noch einen passenden Schlauch kaufen.

**Comment by LukasFreeze** [comment]
Wir haben jetzt auch noch den Gehrungsanschlag bekommen, sobald die Staubabsaugung funktioniert sollte die Säge also eigentlich die jetzige ersetzen können! Leider steht dieser Teil nicht in der Anleitung und wir müssen Schlauch kaufen...

@LarsKumbier was hattest du denn neulich nochmal gemessen? 1 m Länge, 10 cm Durchmesser wenn ich mich richtig erinnere?

**Comment by LarsKumbier** [comment]
Habe ich leider nicht mehr genau im Kopf - könnte aber hinkommen.

sent briefly from mobile

Lukas <notifications@github.com> schrieb am Do., 8. Aug. 2019, 12:53:

**Comment by LukasFreeze** [comment]
Beim Durchmesser bin ich mir sicher und würde vorschlagen, gleich etwas mehr Schlauch zu kaufen (Reste können wir dann für #77 verwerten) und hab auch noch die passenden Schlauchklemmen rausgesucht:

- [5 m Absaugschlauch, 100 mm ∅](https://smile.amazon.de/dp/B002R675PS)
- [10 Schlauchschellen, 94-100 mm](https://smile.amazon.de/dp/B07DHQ1R1B)

Das wären zusammen etwa 50 €, kann gut sein dass es anderswo auch nochmal günstiger wird.

Ansonsten werden wir dann vermultlich noch einen Steckadapter für die Bamato-Anlage drucken müssen, wenn wir nicht jedes Mal an einer Klemme schrauben wollen, und brauchen einen "normalen" Staubsaugerschlauch von der Anschlussstelle in Bodennähe zur Spanhaube über dem Sägeblatt. Falls der halbkaputte Sauger im Lager sich nach dem letzten Reinigungsversuch immer noch nicht erholt hat würde @beanobeano ihn vielleicht dafür freigeben?

**Comment by LukasFreeze** [comment]
Gabs hierzu noch Einwände oder ist der Schlauch bestellt?

**Comment by Pakue95** [comment]
Schlauch und Schellen sind bestellt. Hab die noch wo anders billiger gefunden; kriegst jetzt aber 10m ;-)

**Comment by LukasFreeze** [comment]
@Johannes09 hat gestern den nötigen Adapter für die Bamato-Staubabsaugung gedruckt und @Pakue95 konnte ihn mit etwas Heißluft anbauen - damit ist die Absaugung möglich! Für die Verbindung zur Haube konnten wir einen alten Staubsaugerschlauch recyclen.

Dann hat Lars seinen Schlitten beschient und eingesägt - das Ergebnis war sehr geil! 5 Schnitte á 10 cm mit nur 0.15 mm Gesamtabweichung :-D

Die Säge ist allerdings weiterhin NOCH NICHT NUTZBAR, bis das "commissioning" im Wiki abgeschlossen ist! Da kann gerne geholfen werden ;-)

**Comment by LukasFreeze** [comment]
Säge steht, läuft und ist nutzbar :-)

Wie immer natürlich bitte Bescheid sagen oder direkt im Wiki ergänzen, wenn euch bei der Benutzung noch irgendetwas auffällt!

Ideen zur weiteren Entwicklung des Schlittens stehen auch schon im Wiki.
