### ISSUE TITLE
improve screw storage

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#14]
We need a better way of storing screws (and similar metal parts). I installed the green metal shelf next to the sink in the wood workshop for wood fasteners and moved the metric screws/nuts/etc. to the common room as they are required for many different projects, not so much for woodworking.

**wood screws & similar (green shelf in the wood workshop):**
- [x] add suggested donations to the [list of available wood screws in the wiki](https://wiki.comaking.space/Available_Wood_Screws)
- [ ] make/find boxes that fit into the green shelf and fill them with the loose (bagged) wood fasteners
  - @emka brought some white pipette tip boxes fit nicely (just not very long)
- [ ] label boxes with sizes and suggested donations

**metric screws/nuts/washers (shelf in the common room):**
- [ ] move loose (bagged) parts from shelf to small parts cabinets
- [ ] label drawers with sizes and suggested donations (see lists in the wiki, e.g. [Available Metric Screws](https://wiki.comaking.space/Available_Metric_Screws))

**Comment by LukasFreeze** [comment]
Luca and I started with some of the M3 and M4 parts this weekend - the labels from the "Schraubenking" zipper bags work very well if you carefully peel them off, cut them to size and stick them onto the plastic drawers!

**Comment by NitramLegov** [comment]
Regarding the white pipette boxes:
right now, we do have 28 of these boxes. I started printing holders which can be screwed onto a piece of wood. The plan would be to put a board to the wall at the place of the current screw storage. Then we screw the holders onto that board and hang up the pipette boxes in order to fill them with screws.

Afterwards, we can hopefully remove the green shelve from the wood workshop.

If this works out well, @Johannes09 allready mentioned he might be interested in a similar system for the  electronics room.

**Comment by LukasFreeze** [comment]
Nice, I should have some label paper when it comes to marking the boxes -
I'd say the diameter, length and suggested donation should definitely be
written on each box, perhaps also the material?

On Nov 5, 2018 4:38 PM, "NitramLegov" <notifications@github.com> wrote:

Regarding the white pipette boxes:
right now, we do have 28 of these boxes. I started printing holders which
can be screwed onto a piece of wood. The plan would be to put a board to
the wall at the place of the current screw storage. Then we screw the
holders onto that board and hang up the pipette boxes in order to fill them
with screws.

Afterwards, we can hopefully remove the green shelve from the wood workshop.

If this works out well, @Johannes09 <https://github.com/Johannes09>
allready mentioned he might be interested in a similar system for the
electronics room.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/comakingspace/do-something/issues/14#issuecomment-435920027>,
or mute the thread

**Comment by NitramLegov** [comment]
I would definitely put the bit to use onto it as well.

**Comment by LukasFreeze** [comment]
Sure, why not - all the information is already collected in the wiki table
at "Available Wood Screws" anyway :-)

Maybe we can clean that up a bit and program an automatic lable
constructor? Or would that be too much work?

**Comment by NitramLegov** [comment]
![dsc_0455](https://user-images.githubusercontent.com/7809163/48307414-6e8fe780-e54c-11e8-826c-e1113429bead.JPG)
Ich denke hier kann man zumachen

**Comment by NitramLegov** [comment]
Das mit den Gewindeschrauben war nicht als Teil dieses Issues gedacht ^^

Nur zum Abschluss:
Die 3D Druck Daten können in den CommonFiles gefunden werden:
https://github.com/comakingspace/CommonFiles/tree/master/3DPrintingFiles/ScrewStorage

Die Label für die Boxen ebenso:
https://github.com/comakingspace/CommonFiles/tree/master/Printouts
