### ISSUE TITLE
P1 3D printer has a broken PINDA probe.

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#140]
The P1 printers PINDA probe has a broken cable roughly in the middle that leads to intermittent connection (and crashes if It happens during the levelling).
[This](https://create3dshop.nl/shop/prusa-p-i-n-d-a-probe/) store has a replacement part for 13€ and also spare thermistors, that we could buy as well (P4s thermistor has seen better days).

As a short-term fix, a new cable can be soldered to the sensor, but I'd suggest to replace the part all together once we have a new unit.

**Comment by Narquadah** [comment]
Then we should order the parts!

**Comment by Pakue95** [comment]
I've ordered 3 thermistors and PINDA probes.

**Comment by Pakue95** [comment]
During the hackathon this weekend Ciaran and I replaced the sensor and the leveling seems to work fine. 
Please make sure to check if the first layer height is still set optimally set once you print. It could have moved a bit during transportation.
