### ISSUE TITLE
://webweek

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#141]
Wir sind ja schon mehrmals als etwas weit außerhalb liegende Exoten bei der Make Rhein-Main gewesen, jetzt wurden wir gefragt ob wir bei der "[://webweek](https://make-rhein-main.de/webweek-rhein-main-2019/)" (dezentrale Eventreihe statt Messe-Format) vom 4. bis 10. November mitmachen möchten.

Mein Vorschlag wäre, einfach den Freitagabend ein Stück weit unter dieses Motto zu stellen und so zumindest den Eintrag im Programm mitzunehmen, wenn jemand Bock hat etwas gesondertes zu organisieren wäre das aber noch besser! Ich weiß leider nicht wie lange die Anmeldung möglich ist, deshalb einfach jetzt schonmal die Frage ob es überhaupt Interesse gibt...

**Comment by emka** [comment]
Es sieht ja aus als wäre ein Maker-Bezug durchaus erwünscht. Da bietet sich doch ein IoT-Thema gut an, z.B. der Klassiker ESP32 mit Temperatursensor oder die Particle-Boards, mit denen wir noch gar nicht so viel gemacht haben.

**Comment by NitramLegov** [comment]
Die Anmeldung ist bis 1. September 2019 23:59 möglich.

Bezüglich Content: Da kann man ggf. das PlatformIO oder das KiCad Seminar recyclen. Prinzipiell könnte man auch direkt Beispielcode für einige der Sensoren aus dem Sensor package das in der E-Bench liegt.

Wäre denke ich schon cool, da mitzumachen. Ich habe den Eindruck, dass die Rhein-Main Leute eine recht große Zielgruppe erreichen. Das wäre für uns PR-technisch sicher auch gut.

**Comment by LukasFreeze** [comment]
Wir bräuchten dann natürlich auch Leute, die sich mit solchen Themen
auskennen und ein Event zu einem dieser Themen betreuen könnten. Nicht
unbedingt alleine, aber als Hauptverantwortliche...könntet ihr euch das in
der Woche vorstellen?

**Comment by LukasFreeze** [comment]
Erik möchte die LoRaWan-Gruppe und jemanden von der Karl-Kübel-Schule Bensheim fragen, ob sie Events mit uns organisieren möchten.

**Comment by LukasFreeze** [comment]
Die Anmeldung geht doch noch bis zum 15. September (habe nochmal einen Aufruf per Mail bekommen), aber auch das ist sehr bald.

Ist denn schon etwas konkreteres geplant? Einer von den Veranstaltern meinte ansonsten, dass wir direkt unsere Meetup-Events ins Programm packen könnten...

**Comment by ErikSchatz** [comment]
Das ist gut so, kann die Leute von der TTN community Rhein-Neckar erst nächste Woche treffen.
Habe schon Kontakt, sie wollen mitmachen: Zitat
Hallo Erik,
da bin ich gern dabei… 8.-10.11. geht in Ordnung… bevorzugt Sonntag.
Du kannst etwas zum Thema LoRaWan anmelden…Details können wir nächstes WE klären.
Viele Grüsse,
Daniel

**Comment by LukasFreeze** [comment]
Ich habe in der Mittagspause mit den Organisatoren telefoniert und kann unsere Veranstaltungen alle gesammelt eintragen. Also bitte einfach finale Infos **hier rein** (am besten diese Woche noch) und ich kümmere mich :-)

Durch den digitalen Anteil bei der Planung/Ankündigung geht wohl auch schon unsere normaler Mittwoch ohne besondere Zusatzaktionen, aber es wäre natürlich trotzdem nett den eventuell auftauchenden Leuten dann etwas verstärkt die Elektronik präsentieren zu können...

Was bisher steht (meetup-Events):
- ["Woodworking Wednesday"](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/events/dfjhvqyzpbjb/) - könnte man für die Woche auch einfach mal anders nennen
- ["Friday PiDay"](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/events/mppbdryzpblb/)
- *<bitte laufend ergänzen, zB TTN @ErikSchatz >*

**Comment by LukasFreeze** [comment]
Der Mittwoch ist jetzt "Wiki Wednesday" und ich würde gerne - wann immer mich niemand dringend braucht oder wenn es eine unterstützende Aufsichtsperson gibt - Demos von Grundlagen, Vorlagen und unseres Wikis generell auf die Leinwand werfen. @reisners vielleicht wäre das auch eine gute Gelegenheit für eine erste kleine SMW-Session?

**Comment by ErikSchatz** [comment]
Hallo Lukas, Daniel hat sich nicht gemeldet, also melde bitte an:
Sonntag 10.11.2019, 13:00 bis 17:00 Uhr
"IoT-Nachmittag mit LoRaWAN++"
Das ist offen formuliert, und ein Minimal-Programm bekomme ich hin. Gruß, Erik

**Comment by LukasFreeze** [comment]
Danke, ist eingetragen! Ich versuche dann, als Unterstützung dabei zu sein :-) Beim [meetup-Event](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/events/265014865/) hast du Bearbeitungsrechte, mein Text ist jetzt erstmal sehr minimal weil ich nicht wusste was genau du gerne ankündigen würdest. Hast du vielleicht auch noch ein Foto von irgendeinem IoT-Projekt oder -Bauteil?

Den "Wiki Wednesday" melde ich jetzt erstmal so an, habe aber mittlerweile gemerkt dass ich da zu einem Pressetermin für unsere Fördermittel muss...also findet sich hoffentlich noch jemand anderes!

**Comment by LukasFreeze** [comment]
Jetzt steht auch endlich alles im Online-Programm :-)

https://make-rhein-main.de/programm/

**Comment by LukasFreeze** [comment]
Eriks LoRaWAN-Crashkurs kam gut an! Einen webweek-Effekt konnten wir allerdings nicht wirklich feststellen, die Leute haben wir wohl selbst erreicht.
