### ISSUE TITLE
Neue Software für die Music Station

### ISSUE THREAD

**Issue by Johannes09** [comakingspace/do-something#142]
Ich habe ein Stückchen Software in den Tiefen des Internettes gefunden. Die es uns in Zukunft erleichtern wird, Musik von Spotify, ohne lästige Bluetooth Verbindung und ohne das sich jemand mit einem Spotify Account auf dem Pi anmelden muss, abzuspielen.

https://github.com/dtcooper/raspotify

Hiermit gebe ich diese Aufgabe feierlich an die IT-abteilung weiter. 
@Narquadah @NitramLegov

**Comment by kenomaerz** [comment]
Raspotify ist super easy, aaaaaaber dafür brauchen wir einen pro Account. Raspotify unterstützt momentan keine free Accounts.

Ergo: nur wer Spotify pro hat, kann anschließend auch den pi fernsteuern.

Ansonsten benutze ich das auch für die Jukebox, zwinker, zwinker


On Aug 5, 2019 17:19, Johannes <notifications@github.com> wrote:

Ich habe ein Stückchen Software in den Tiefen des Internettes gefunden. Die es uns in Zukunft erleichtern wird, Musik von Spotify, ohne lästige Bluetooth Verbindung und ohne das sich jemand mit einem Spotify Account auf dem Pi anmelden muss, abzuspielen.

https://github.com/dtcooper/raspotify

Hiermit gebe ich diese Aufgabe feierlich an die IT-abteilung weiter.
@Narquadah<https://github.com/Narquadah> @NitramLegov<https://github.com/NitramLegov>

**Comment by NitramLegov** [comment]
Naja, raspotify sollten wir sowieso nur als zusätzliche Option installieren. Dann passt das denke ich auch, wenn das nur Leute mit Spotify Pro nutzen können 🙂
Meine Befürchtung war bisher, dass wir für raspotify einen spotify pro account auf dem pi einrichten müssen. Das scheint aber nicht der Fall zu sein.

Insofern find ich das ne gute Idee. Kann man bei der nächsten Gelegenheit denke ich umsetzen.
________________________________
Von: kenomaerz <notifications@github.com>
Gesendet: Montag, 5. August 2019 17:25
An: comakingspace/do-something <do-something@noreply.github.com>
Cc: NitramLegov <Martin_Vogel@live.com>; Mention <mention@noreply.github.com>
Betreff: Re: [comakingspace/do-something] Neue Software für die Music Station (#142)

Raspotify ist super easy, aaaaaaber dafür brauchen wir einen pro Account. Raspotify unterstützt momentan keine free Accounts.

Ergo: nur wer Spotify pro hat, kann anschließend auch den pi fernsteuern.

Ansonsten benutze ich das auch für die Jukebox, zwinker, zwinker


On Aug 5, 2019 17:19, Johannes <notifications@github.com> wrote:

Ich habe ein Stückchen Software in den Tiefen des Internettes gefunden. Die es uns in Zukunft erleichtern wird, Musik von Spotify, ohne lästige Bluetooth Verbindung und ohne das sich jemand mit einem Spotify Account auf dem Pi anmelden muss, abzuspielen.

https://github.com/dtcooper/raspotify

Hiermit gebe ich diese Aufgabe feierlich an die IT-abteilung weiter.
@Narquadah<https://github.com/Narquadah> @NitramLegov<https://github.com/NitramLegov>

**Comment by NitramLegov** [comment]
Done
