### ISSUE TITLE
große Säulenbohrmaschine

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#143]
Wir haben eine neue Säulenbohrmaschine bekommen! Sie ist ausdrücklich noch nicht benutzbar, steht aber schon einmal in der Metallwerkstatt damit sie fertig gemacht werden kann - es gibt nämlich leider neben dem üblichen "[commissioning](https://wiki.comakingspace.de/Category:Commissioning)" im Wiki noch ein paar Baustellen :-P

- [x] Platz überlegen/diskutieren, dann solide festschrauben (kippelt sonst)
- [ ] Hersteller/Modell rausfinden!! - Anhaltspunkte: "TB 16", "Typ ZJ5116", Baujahr 1996, Gesamthöhe 160 cm, Spindelhöhe 127 cm (jeweils vom Boden)
![IMG_20190808_152955](https://user-images.githubusercontent.com/19755883/62715747-609ac480-ba01-11e9-82a5-fafb12716de1.jpg)
- [x] sauber machen
- [x] alle Schrauben anziehen, ggf. ersetzen: zurzeit kann sich z. B. noch der obere Teil auf der Säule drehen!
- [x] Zahnstange zur Höhenverstellung des Tisches anständig befestigen
- [x] Präzisionsproblem: Spindel scheint nicht ganz rund zu laufen (mit "mitgeliefertem" und einem anderen, in der Metallwerkstatt rumliegenden, Morsekegelfutter getestet - oder waren dummerweise beide Futter unrund?)
  - Vorschlag vom Spender (wenn es wirklich an der Spindel liegt): ausbauen und von innen leicht neu drehen (Kegel tiefer versenken)

Hoffe das ist soweit verständlich, ansonsten einfach fragen! Bin gespannt, wie gut wir das Teil hinkriegen...im schlimmsten Fall ist sie jetzt schon so präzise wie die kleine aber es passt mehr drunter :stuck_out_tongue_winking_eye: 

Assignees:
@Pakue95 (Inventar-Manager), @kenomaerz (Eckpate), @Johannes09 (hatte sich im Plenum für eine bessere Bohrmaschine ausgesprochen

**Comment by Johannes09** [comment]
Ich habe mal angefangen das Ding auseinander zu nehmen und durch zu reinigen.
Dinge die wir nachbestellen sollten:
- [ ] 1x Kugellager 6204 Z
- [ ] 1x Kugellager 6203 Z

**Comment by LukasFreeze** [comment]
Cool! Denkst du sie hat Potenzial?

**Comment by Pakue95** [comment]
Kugellager sind bestellt.

**Comment by Pakue95** [comment]
Ich bin mal dazu gekommen die Lager einzubauen und scheint auch ganz gut zu laufen. Zu den oben genannten Checkpunkten:

Platz: Würde ich am liebsten rechts neben den Bohrtisch stellen. Den Tisch muss man etwas nach links verschieben und sich eine bessere Lösung für die Schraubendreher überlegen, aber das sollte kein großes Problem darstellen.

Hersteller: No Idea...

Sauber: Done.

Schrauben festziehen: Alle die ich finden konnte sind fest. Der Kopf ist mit einer M8 (?) Madenschraube fixiert und ist meiner Meinung nach fest genug, wenn man mit Kraft gegen den Kopf drückt lässt sich dieser immer noch drehen (sehe kein Problem dabei).

Zahnstange: Dass die beweglich ist soll so, damit sich er Tisch drehen lässt. Ist zwar etwas verbogen, aber das beeinträchtigt nichts.

Präzision: Denke das ist so gut wie man es von so einer Maschine erwarten kann. See:

https://user-images.githubusercontent.com/19751734/133418598-f5ce6c41-1eb2-4919-ba00-92fa066df088.MOV

**Comment by Pakue95** [comment]
@SebMakesThings und ich haben gestern die Bohrmaschine an ihren Platz gestellt und im Boden verankert (mehr oder minder im Wasser ^^). Infos sind im Wiki und intern eingetragen (kann man gerne noch erweitern) und die Einweisung ist auch noch gleich zu den kleineren Säulenbohrmaschinen. 

Hersteller/Bedienungsanweisung habe ich leider noch nicht gefunden, wobei man sich da an der von der Scheppach orientieren kann.

Wenn keine anderen Einwände kommen würde ich die so nutzbar machen.
