### ISSUE TITLE
3D-Printer P2: hotend blocked

### ISSUE THREAD

**Issue by ErikSchatz** [comakingspace/do-something#145]
1) please describe the problem:
- filament cant be loaded successfully
- perhaps hotend is clogged

- nozzel is not blocked, tried with needle

2) please make this issue visible after opening it to "warn" others about the downtime and perhaps recruit helpers for a quick repair:
- send a quick note over the [mailing list](https://wiki.comakingspace.de/Mailing_List)
- link the issue from the tool's wiki page

**Comment by ErikSchatz** [comment]
will disassemble the printers head at Friday evening 16.08.2019

**Comment by NitramLegov** [comment]
Assigned the Area Patrons to make them aware :)

**Comment by Pakue95** [comment]
The printer seems to be unclogged now, but nobody bothered to update the issue. 

If you fix it, please also update the issue.
