### ISSUE TITLE
Kleine CNC Fräse

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#147]
Wir haben ja jetzt eine kleine CNC Fräse als Leihgabe von Micha bekommen.

Aktuell steht die in der Metallwerkstatt, da sollte sie (IMHO) nicht bleiben, bis sie nicht tatsächlich nutzbar ist. Aktuell steht sie in Einzelteilen da und wenn ich das richtig verstanden habe ändert sich das auch frühestens in zwei Monaten.
Daher sollte sie meiner Meinung nach ins Lager, sobald die neue Tischkreissäge in der Holzwerkstatt steht.

Ich würde das issue hier gerne auch nutzen, um zu dokumentieren, wie das mit dem Zugang, den Einweisungen, etc. für die neue Fräse in Zukunft läuft / laufen soll. @Pakue95 kannst du hier Licht ins dunkel bringen?

**Comment by Pakue95** [comment]
In der Metallwerkstatt steht die momentan so nicht gut und sollte auch ins Lager sobald #139 fertig ist. Generell muss bei der Fräse noch einiges umgebaut werde bevor man die zugänglich machen kann. Hierzu würde ich zählen:

* Schild/Gehäuse aus PC bauen um Staub aus und Spähe in der Fräse zu halten
* Richtige Montage der Elektronik (e.g. alles unter den Tisch montieren um den footprint klein zu halten)
* Stecker an der Spindel auswechseln
* Generelles Kabelmanagement, was nicht nur aus losen Lüsterklemmen besteht

Zu Nutzungsdetails kann ich noch nicht viel sagen, bis Micha Zeit hatte mir genau den Workflow und Sonderheiten der Maschine zu zeigen. Generell würde ich Personen den Zugang zu der Fräse erst nach ausgiebiger Einweisung und Training an der Workbee freigeben. An der Workbee passieren immer mal Unachtsamkeiten nachdem Leute frisch eingewiesen wurden, die bei der geringen Leistung der Maschine nicht weiter tragisch sind. Bei der Fräse von Micha, aber doch gefährlich werden können.

Als Standort würde ich gerne den Tisch neben der Sandstrahlkabine frei machen, sobald Fortschritte an der Fräse gemacht werden. Das Precious Plastic Equipment kann dann meiner Meinung nach ins Lager, bis Leute wieder Zeit haben daran weiter zu arbeiten.

**Comment by Blacksheep70** [comment]
Die Arbeit an der Fräse beginnt jetzt. Wir haben heute die ersten Tasks erstellt und legen am Mittwoch los. Ich gehe davon aus das die Fräse, sofern die Planung so funktioniert wie wir uns das vorgestellt haben in 2-3 Wochen einsatzbereit ist (inklusive Dokumentation im Wiki und Einführung für die Orga).

Es wäre gut wenn wir temporär einen fixen Platz bekommen könnten wo wir die Fräse aufbauen können und wo sie bis auf weiteres stehen bleiben kann.

**Comment by Pakue95** [comment]
Schön dass das Fortschritt macht!

Wie du wahrscheinlich schon mitbekommen hast haben wir gegen Ende des Jahres unseren Umzug anstehen, daher kann ich nicht garantieren bis dahin viel Zeit in Fräse zu stecken.

Bei den Materialien fürs Gehäuse gib mir bitte mal einen groben Kostenvoranschlag bevor du anfängst einzukaufen. Das ganze muss auch in Budget Planung für den Umzug.

**Comment by NitramLegov** [comment]
Obsolete as of #158 , #159 and #160
