### ISSUE TITLE
Tag der offenen Tür zum zweijährigen

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#148]
*Diese Beschreibung bitte immer mal wieder aktualisieren, so haben wir eine einigermaßen brauchbare Zusammenfassung!*
----

Am 15. September 2019 werden wir unser zweijähriges Jubiläum im CoMakingSpace feiern! Dazu möchten wir einen Tag der offenen Tür veranstalten.

Wir haben schon überlegt, dass der Gemeinschaftsraum zur Ausstellung von Projekten und vielleicht für kleine Workshops genutzt werden könnte und die Werkstätten in Begleitung von Mitgliedern besichtigt werden können. Je nach Wetter könnten auch ein, zwei Tische vor die Tür gestellt werden, unsere Fassade ist ja nicht gerade die schönste...

Habt ihr Lust, im Vorfeld oder am Tag selbst mitzuhelfen? Hier schonmal ein paar Ideen wo man sich einbringen könnte, aber die Liste kann natürlich auch gerne noch erweitert werden (der Makerspace Rhein-Neckar in Ludwigshafen hatte neulich zum Beispiel auch sein Einjähriges mit interessantem Programm):

- [x] Poster gestalten (Abgabe Deadline der Stadt 30.08.)
- [ ] Aussteller/Maker organisieren
  - [x] Lötkurs? -> @Johannes09 & Erik??
  - [ ] Vorträge?
  - [ ] Projekt Aussteller (Liste von Mitgliedern/externen Maker, die gerne etwas zeigen würden, und wie viel Platz sie bräuchten)
      - @NitramLegov - Musikbox
      - @LukasFreeze - diverse Spiele, ca. halber Tisch
      - Jochen: Prototypen der Schachfiguren
      - Patrick: Longboard & der fancy Werkzeugwagen
      - Johannes: Wordclock & LED Cube
      - einer der Camper?
      - Das Elektro-Auto?
      - Michas Holzarbeiten?
 - [x] Aufräumen/Vorbereiten (do-something day am 14.09.)
- [ ] Artikel in RNZ/Stadtblatt/Bahnstadt-Info
- [x] PR in social media, Newsletter etc.
     - [x] LinkedIn 
     - [x] Facebook
     - [x] Twitter
     - [x] Newsletter
     - [x] Meetup
     - [x] heise
     - [x] Stadt Heidelberg

**Comment by Pakue95** [comment]
Poster sind bestellt (75st.), hier die Datei:
[Poster_Open_Day_2019.pdf](https://github.com/comakingspace/do-something/files/3538581/Poster_Open_Day_2019.pdf)

**Comment by ErikSchatz** [comment]
Lötkurs gerne wieder!

**Comment by NitramLegov** [comment]
Falls die Plakate noch rechtzeitig kommen hier nochmal die Faltanleitung:
https://www.heidelberg.de/hd/HD/Rathaus/Kultursaeulen+_+kostenloses+Plakatieren.html
Die Plakatgröße beträgt maximal DIN A1.  Kleinere Formate sollten grundsätzlich vermieden werden. Querformate sind ausgeschlossen.

Für die Plakatierung werden 44 Plakate benötigt.

Bitte beachten Sie, dass die Plakate gefaltet sein müssen. Dazu legen Sie das Plakat mit der bedruckten, lesbaren Seite vor sich und falten das Plakat von unten so weit nach oben, bis ein ca. 5 cm großer Rand verbleibt. Danach falten Sie das Plakat von rechts nach links und zwar ebenfalls so, dass links auch ein ca. 5 cm großer Rand verbleibt. Ein DIN A2 großes Plakat wird nur einmal von unten nach oben gefaltet bis oben ein ca. 5 cm breiter Rand verbleibt.

Und der Abgabeplan:
Die Plakate sind an den im Dekadenplan angegebenen Terminen beim

Bürger- und Ordnungsamt
Frau Judith Keilbach
Zimmer 1.05
Bergheimer Straße 69
69115 Heidelberg

abzugeben.

https://www.heidelberg.de/site/Heidelberg_ROOT/get/documents_E113693418/heidelberg/Objektdatenbank/15/PDF/Plakatierung/15_pdf_Dekadenterminplan.pdf

**Comment by LukasFreeze** [comment]
Ich kann dieses Mal vermutlich leider nicht dabei sein, stelle aber gerne wieder meine Spiele und/oder andere Projekte zur Verfügung.

**Comment by NitramLegov** [comment]
Nachdem die Poster gestern angekommen sind, haben @Pakue95, @Titan-OX und ich gestern Abend die Poster gefaltet. Danke für die Hilfe!
Heute morgen hat @Narquadah die Poster bei der Stadt abgegeben, die werden also bald auf den Kultursäulen hängen :) Auch dafür Danke!

Als nächstes steht nun ein bisschen PR (Facebook, twitter, meetup, etc.) an. Zum nächsten Plenum (06.09.) sollten wir möglichst viele Leute für den vorgelagerten do-something Tag organisieren und möglichst viele Ausstellungsstücke planen.

Bei heise und bei der Stadt Heidelberg habe ich uns jeweils im Kalender gelistet.

**Comment by emka** [comment]
Ihr seid super!

**Comment by kenomaerz** [comment]
Ich bin vorsichtig optimistisch, dass die Box an dem Tag funktioniert, also würde ich meine Jukebox vorstellen. Sollen wir noch z. B. Würste grillen?

**Comment by beanobeano** [comment]
Meetup done

**Comment by emka** [comment]
Wrote a first tweet, could be done again in a week or so.

**Comment by FHuchinson** [comment]
Ich bin intensiv am überlegen, wie ich das Auto präsentieren kann. Bis dahin werd ich leider kein Gott in CAD. Aber Gedankenansätze und Konzepte gehen bis dahin sicher. Vielleicht ne Präsentation über Prezi oder so...

**Comment by beanobeano** [comment]
LinkedIn done.
Sent email to journalist in RNZ that did last article.

**Comment by beanobeano** [comment]
Our RNZ journalist is not available but said...
“Am besten ist es, wenn Ihr den Termin direkt an die Stadtredaktion mailt unter 
Stadtredaktion@rnz.de
Die Stadtredaktion der RNZ kann dann entscheiden, ob sie eine Ankündigung dazu machen möchte, also eine Meldung. 

Es braucht diese Angaben:
Wer
Was
Wann
Wo
Warum
Welche Aktionen 
Welche Bedingungen: kostenlos und so etwas 
Kontakt 
Und was Euch sonst noch wichtig ist.”

Can anyone draft this in German so that I can send it in.

**Comment by LukasFreeze** [comment]
Facebook-Event, bitte teilen: https://www.facebook.com/events/495369234582562/

Zum Newsletter komme ich hoffentlich auch noch, @beanobeano s Vorschlag mit der RNZ ist aber wahrscheinlich dringender! Für beides würde ich allerdings noch abwarten, was nachher im Plenum geplant wird.

Noch ein kleines Update: Micha möchte wohl am 13. ein paar Exponate vorbeibringen, kann aber am Wochenende selbst nicht da sein - @FHuchinson weiß evtl mehr.


> Sollen wir noch z. B. Würste grillen?

Darüber haben wir auch am Mittwoch kurz geredet: letztes Jahr waren über den gesamten Tag verteilt ca. 30 Leute da, warme Verpflegung lässt sich da nicht sehr effektiv gestalten - und wenn doch mehr kommen, wissen wir das vorher nicht. Darum bietet sich eher Kuchen o.ä. an, der unkompliziert rumstehen kann und den Helfern auch ein paar Tage später noch schmeckt, oder einfach gar kein Essen (haben wir ja auch nicht beworben).

Für die anwesenden Mitglieder ist Grillen aber sicher eine nette Option ;-)

**Comment by NitramLegov** [comment]
@beanobeano sorry for the late reply. Here´s my proposal (I wrote it rather formal):

> Sehr geehrte Damen und Herren,
> 
> der CoMakingSpace Heidelberg (www.comakingspace.org) feiert am 15.09.2019 zweijähriges Bestehen. Zu diesem Anlass planen wir einen Tag der offenen Tür in unserer Werkstatt, zu dem Sie selbstverständlich auch herzlich eingeladen sind.
> 
> Von Ihrer Kollegin xxx xxx haben wir den Vorschlag erhalten, uns an Sie zu wenden, um die Veranstaltung in der RNZ zu veröffentlichen. Um unser Jubiläum erfolgreich zu machen, bitten wir Sie daher, eine Ankündigung über die Veranstaltung zu veröffentlichen:
> Wer? CoMakingSpace Heidelberg
> Was? Tag der Offenen Tür
> Wann? Sonntag, 15.09.2019, 10:00 - 18:00
> Wo? CoMakingSpace Heidelberg, Czernyring 15, 69115 Heidelberg
> Warum? 2 jähriges Bestehen der offenen Werkstatt in Heidelberg
> Welche Aktionen? Es wird eine Ausstellung der Arbeiten unserer Mitglieder geben. Außerdem bieten wir einen Einsteigerkurs ins Löten an. Eine Anmeldung ist nicht erforderlich.
> Welche Bedingungen? Die Veranstaltung ist komplett kostenlos. 
> 
> Bei Fragen können Sie selbstverständlich gerne auf diese Mail antworten. Ansonsten stehen wir Ihnen und Ihren Lesern unter info@comaking.space zur Verfügung.
> 
> Vielen Dank,
> xxxxxxx

**Comment by Pakue95** [comment]
Vielleicht anstatt

> Zu diesem Anlass planen wir einen Tag der offenen Tür in unserer Werkstatt, zu dem Sie selbstverständlich auch herzlich eingeladen sind. 

[...], zu dem alle Interessierten aus Heidelberg und Umgebung herzlich eingeladen sind.

Dann passt es besser zu der Veröffentlichung, weil wir laden ja nicht nur die RNZ ein zu kommen. 

Sonst finde ich es gut 👍

**Comment by beanobeano** [comment]
Thanks Martin and Patrick. 
I incorporated  the suggestion and sent it in.  
Fingers crossed that we get a mention in the RNZ this week.

**Comment by LukasFreeze** [comment]
Newsletter geht heute Abend raus! Habe auch gerade nochmal über "makers" für den Do-Something Day getrommelt.

**Comment by LukasFreeze** [comment]
Ich habe noch unsere Kontakte in der Stadt angeschrieben, vielleicht mag da ja jemand kommen...

**Comment by lmnl99** [comment]
Ich würde am Tag der offenen Tür wieder den 3D Druck übernehmen. Falls jemand ein fertiges Modell hat das nur gedruckt werden muss kann er mir gern die STL Datei zukommen lassen. Dann druck ich es als Demo Projekt zum zeigen was unsere Drucker können.

**Comment by LukasFreeze** [comment]
Meine Spiele liegen auf dem Tisch, den wir auch für die Vorbereitung des Bahnstadtfests bemutzt haben. Außerdem könnt ihr euch bei meinem Werkzeug bedienen, falls da was schick genug aussieht :-)

Bitte denkt am Sonntag daran, den Bench-Raum genau wie die Werkstätten geschlossen zu lassen wenn gerade keiner zum Zeigen darin ist. Da liegt ja auch alles mögliche gefährliche/empfindliche rum!

Ansonsten haben @Pakue95 und ich die Einfahrt von der Sauerei unserer Nachbarn befreit und das Zaun-Schild ist für Sonntag auch wieder gut sichtbar :-) 🌿✂

**Comment by Pakue95** [comment]
Der Tag der offenen Tür war sehr erfolgreich; es kamen durchweg interessierte Besucher (viele mit Kind) und viele Member haben mit angepackt. Vielen Dank nochmal dafür!

@kenomaerz hat sich bereit erklärt ein paar Zeilen für die MAKE über den Tag zu schreiben.

**Comment by LukasFreeze** [comment]
@NitramLegov hatte in der Telegram-Gruppe nach Fotos gefragt - hat zufällig jemand welche gemacht?

Und was schätzt ihr so, wie viele Leute gekommen sind?

**Comment by ErikSchatz** [comment]
Geschätzt 40 -50.
Gruß, Erik
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 17.09.19, 18:46, Lukas <notifications@github.com> schrieb:
@NitramLegov hatte in der Telegram-Gruppe nach Fotos gefragt - hat zufällig jemand welche gemacht?

Und was schätzt ihr so, wie viele Leute gekommen sind?



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/comakingspace/do-something/issues/148?email_source=notifications\u0026email_token=AM447QIA5WTB4RG2GVLKILLQKECVJA5CNFSM4IPKCMLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD65FAVA#issuecomment-532303956",

"url": "https://github.com/comakingspace/do-something/issues/148?email_source=notifications\u0026email_token=AM447QIA5WTB4RG2GVLKILLQKECVJA5CNFSM4IPKCMLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD65FAVA#issuecomment-532303956",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by LukasFreeze** [comment]
Fotos werden wohl leider nicht mehr kommen - nächstes Mal müssen wir dran denken, welche zu machen (und idealerweise direkt Nutzungserlaubnisse einholen, auch wenn das immer schwer ist).

Insgesamt scheint es ja echt ein gelungenes Event gewesen zu sein, ich freue mich aufs nächste Jahr :-)
