### ISSUE TITLE
Lagerfläche / neue Spinde

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#149]
Nachdem es in letzter Zeit vermehrt zu Fragen und Diskussionen darüber gekommen ist, was man wo im space lagern könnte und wie mit Sachen umgegangen werden soll, die seit Monaten niemand mehr angefasst hat, würde ich das Thema gerne "ordentlich" klären.

Zum Thema Lagerfläche schwebt mir ein Konzept vor, das in anderen Makerspaces (z.B. In der Dingfabrik in Köln) bereits erfolgreich ist: es soll einen offenen Schrank mit 4 Fächern geben.
In das ganz linke Fach (Fach 1) darf jeder Zeug einlagern.
Nach einer Woche kommt alles aus dem ganz linken Fach in das Fach rechts daneben (Fach 2)
Nach einer weiteren Woche kommt alles in Fach 3
Nach einer weiteren Woche kommt es in Fach 4. Wichtig: Sachen in Fach 4 sind "free for all". Da kann sich jeder bedienen der möchte. 
Nach einer weiteren Woche fliegt das Zeug weg / wird meistbietend verkauft / dem recycling Kaufhaus gegeben.

Über die genau Regelung bezüglich Fach 4 kann man sicher nochmal sprechen. Wichtig ist mir, dass nach 4 Wochen lagerung das Zeug weg kommt.
Wenn nun eine aufräumaktion im space ansteht, bei der Sachen entsorgt werden sollen, schlage ich vor, diese entsprechend in Fach 1 zu legen und ggf. Eine Info in die Telegram Gruppe & die ML zu stellen. Dadurch hat dann jeder genug Zeit für Einspruch / um Zeug abzuholen.

Als Platz für das ganze schwebt mir die Wand im common room vor, an der gerade das Regal mit den metallschrauben steht. Wenn wir die Schränke dort loswerden ist da mehr als genug Platz.
Und wenn wir schon einen neuen Schrank bauen, können wir auch direkt noch einen neuen spind daneben bauen. Genug Platz haben wir. Das ganze könnte grob so aussehen (man beachte, wie awesome das Bild bearbeitet wurde 😅 - hatte leider gerade nur powerpoint zur Verfügung):
![Neue Spinde](https://user-images.githubusercontent.com/7809163/63670227-6dc6fa00-c7dc-11e9-8b5f-1ab49860f7b0.png)

Das ganze muss definitiv noch mit @LukasFreeze diskutiert werden, aber es wäre cool, wenn wir uns hier fix dranmachen könnten :)

**Comment by Johannes09** [comment]
Ich finde es ist eine gute Lösung. Für alle herrenlose Gegenstände/Geräten, die keinem gehören, die nicht im Wiki dokumentier wurden und nie benutzt werden.

**Comment by LukasFreeze** [comment]
Überraschung - ich hab ne Meinung dazu ;-) Teile das aber mal in die Grundvorschläge auf:

1) mehrstufiges Lagersystem:

finde ich generell gut! Vor der Entsorgung von generell brauchbaren Sachen bin ich aber trotz allem stark für eine kurze Mitteilung über unsere üblichen Kanäle - zum Bespiel beim Übergang von Fach 3 in Fach 4. Aufräumen und auch mal ausmisten ist ja nett, aber wir haben immer wieder mal kleine undokumentierte Leihgaben/Spenden die die Leute dann vielleicht zurückhaben wollen, wenn der Space sie doch nicht braucht. Wenn es nur über das Regal geht riskieren wir, Leute zu verprellen die nicht häufig kommen können.
> Wenn nun eine aufräumaktion im space ansteht, bei der Sachen entsorgt werden sollen, schlage ich vor, diese entsprechend in Fach 1 zu legen und ggf. Eine Info in die Telegram Gruppe & die ML zu stellen. Dadurch hat dann jeder genug Zeit für Einspruch / um Zeug abzuholen.

Das wäre natürlich ideal!

2) Regal mit Gewindeschrauben soll weg:

Wo sollen die Schrauben denn hin? Ich finde immer noch, dass sie im Gemeinschaftsraum ganz gut aufgehoben sind, da sie öfter mal für Reparaturen oder 3DP-/Elektronik-Projekte von Leuten gebraucht werden, die noch keinen Werkstattzugang haben. Außerdem können wir den Platz in der Metallwerkstatt imho deutlich besser nutzen...
Das soll jetzt kein "Veto" sein (Inventar macht ja außerdem hauptsächlich Patrick), sondern wie gesagt nur meine Meinung ;-) Falls etwas hinter neue Zugangsbarrieren geräumt wird, muss das jedenfalls im Gegensatz zum letzten Mal *vorher* kommuniziert werden.

3) direkt auch neue Spinde bauen:

Halte ich nicht für sinnvoll bis wir wissen, ob wir nächstes Jahr noch in diesem Gebäude sind. Klar sind die einzelnen Spindeinheiten relativ transportabel, aber wir wissen nicht wie groß der nächste Gemeinschaftsraum werden kann. Erfahrungsgemäß werden in den nächsten paar Monaten eh noch keine 6 neuen Spinde benötigt und wir können hiermit noch gut warten.

4) "was nicht im Wiki steht, kann weg"

Ist jetzt zwar etwas überspitzt zitiert, aber wenn wir das so machen hätte ich Angst wenn jemand die e-Bench "ausmistet"...
Also im Ernst: ich bin natürlich absolut dafür, dass langfristig so gut wie alles im Wiki steht, aber wir sind noch weit davon entfernt und die Hauptarbeit machen meistens die gleichen zwei, drei Nasen. Wir kriegen oft neuen Kleinkram von Mitgliedern, die leider nicht so doku-affin sind, und das landet dann auch noch auf der To-Do-Liste von diesen wenigen Wiki-Schreibern, wenn sie die Sachen retten wollen? Den Spendern vorzuschreiben, dass sie jetzt gefälligst auch noch ins Wiki schreiben müssen bevor sie ihr Werkzeug da lassen dürfen, klappt in der Praxis nicht, also habe ich lieber undokumentierte Spenden als gar keine. Wer Bock auf Aufräumen hat, sollte in diesen Fällen lieber die Doku verbessern und die Dinge besser verfügbar machen statt sie für unbrauchbar zu erklären...

5) "was nie benutzt wird, kann weg"

Es gibt sehr praktische Sachen, die vielleicht selten oder nur von manchen Leuten benutzt werden, aber dennoch wichtig sind und in den allermeisten Fällen kaum Platz wegnehmen. Da die Aufräumenden das aber natürlich nicht alles wissen können wäre mein Vorschlag wieder, dass in Fach 1 geräumtes anständig über ML/Telegram kommuniziert wird.

----

tl;dr: Ich wäre erstmal für
- Schraubenregal noch ein paar Monate da stehen lassen
- noch keine neuen Spinde bauen
- "4-Wochen-Regal" ausprobieren
  - wer was reinlegt, sollte zumindest schnell ein Foto über die ML schicken (*optional* zusätzlich Telegram)
- Aufräumen/Dokumentieren/Reparieren ist meistens besser als Ausmisten
- gemeinsame, angekündigte Aktionen sorgen generell für weniger Irrtümer

**Comment by LukasFreeze** [comment]
oh, und ich glaube ein Lagersystem mit vier horizontalen Regalbretten wäre deutlich einfacher zu bauen (hab noch einige von diesen [leicht verstellbaren Winkeln/Wandleisten](https://cdn.eazyauction.de/b6/b675936b55a6f6492530025c9288d53d2ee1665064bcb5805743c08c2c3bbf2e656227c03f8120d92a27d8d6ce6c3769/img/1500x1500_8dfcd29043776c8ba7b05edd5b8c6c8e68c93ba7.jpeg)) und auch besser zu nutzen, da in den seltensten Fällen etwas großes oder hochkant zu lagerndes aussortiert werden dürfte

**Comment by NitramLegov** [comment]
Uuund ich hab zu deiner Meinung auch eine Meinung ;)

Ich antworte dir mal in der gleichen Struktur.
1. Mehrstufiges Lagersystem
Wie gesagt, gerade bei Aufräumaktionen sollte natürlich eine Info über die ML erfolgen. Bei kleineren Leihgaben, die da reinkommen sehe ich kein größeres Problem: Die liegen insgesamt 4 Wochen im Lagersystem, bevor sie wegkommen. In dieser Zeit sollte mindestens ein mal ein Manager da sein, der das sieht. Und bei Sachen, die Leute einfach im Space lassen: Da läuft das für mich unter "sorry, you loose". Ich denke hier an Beispiele wie den 3D Drucker der ewig einfach im E-Room Stand, diverse Lampen auf den Spinden, Tigerenten, Registrierkassen, etc...Da steht einfach viel Müll rum, der da eigentlich nicht stehen dürfte.

2. Regal mit Gewindeschrauben soll weg
Wo das hin soll finde ich recht einfach: Dahin, wo die Schrauben gebraucht werden. Als Lagersystem habe ich zwei Sortimo Boxen gekauft, die dann ähnlich bestückt werden können wie die Sortimo Box für die Holzschrauben. Davon kann eine in die Metallwerkstatt. Die andere kann in den E-Room oder wir hängen im E-Room die Kleinteilemagazine an die Wand. Der Anteil der Mitglieder, die bei uns Elektronik reparieren wollen und weder zum E-Room noch zur Metallwerkstatt Zugang haben sollte gegen 0 gehen. Und die haben dann andere Probleme als den Zugang zu Schrauben (zum Beispiel den Zugang zu Werkzeug)...

3. direkt auch neue Spinde bauen:
Gut, der Vorschlag basiert auf verschiedenen Überlegungen:
- Wenn wir eh schon etwas bauen geht es schneller, direkt noch Spinde zu bauen als später nochmal anfangen zu müssen
- Durch den Spind nutzen wir den kompletten Platz an der Wand. Das ist meiner Meinung nach einfach "sauberer"
- Solange die Spinde nicht genutzt werden finden wir sicherlich eine andere Verwendung für die Fächer.

4. "was nicht im Wiki steht, kann weg"
Ich muss hier zuerst auf das wiki verweisen: [Johannes, was macht die Doku?](https://wiki.comakingspace.de/Johannes,_was_macht_die_Doku).
Und jetzt im Ernst: Ich bin prinzipiell bei dir, dass nicht alles weg sollte, was nicht im Wiki steht. Allerdings sollten wir auch nicht jeden Kleinscheiß als Leihgabe annehmen. Und auch nicht jedes selbstgebastelte Werkzeug sollte einfach im Space herumstehen (ich denke da zum Beispiel an diese Schleifeinrichtung, die auf einmal in der Holzwerkstatt stand). Das bedingt nämlich das Risiko, dass Leute das nutzen. Versicherungstechnisch ist das denke ich schwierig, wenn da mal was passiert...

5. "was nie benutzt wird, kann weg"
Prinzipiell bin ich bei dir, mir fallen allerdings auch Beispiele ein, bei denen ich das anders sehe. Daher bin ich wieder völlig bei dir, wenn es darum geht, das entsprechend einfach zu kommunizieren. Wir können nicht jeden bauchpinseln, der einmal in 6 Monaten in den Space kommt und dann Werkzeug liegen lassen will, aber wir sollten jedem die Chance geben, sein Zeug auch wieder mitzunehmen. Ich denke da an Sachen wie dieses Bosch Ixo Spielzeug: Lag ewig rum, will keiner reparieren. Und selbst wenn: Die Dinger sind einfach unnütz.

Deinem tl;dr kann ich größtenteils zustimmen (bis auf das mit den Spinden, die fände ich wirklich gut, wenn man schon mal arbeitet)



Bezüglich eines horizontalen Systems:
Ich befürchte, dass ein System aus horizontalen Regalbrettern sehr dazu einlädt, dass da Chaos herrscht (dann stellt jemand was auf den Boden, etc.). Daher befürworte ich einen "Schrank" als Lösung. Ich gebe dir Recht bezüglich großen, auszumistenden Sachen. Allerdings darf man dabei nicht vergessen: Das Ganze ist auch als offizielle Lagermöglichkeit gedacht. Ich denke da an den Ikea Schrank von Eileen, etc....
Daher denke ich, dass eine vertikale Lösung sinnvoll ist, in die noch extra Regalbretter eingezogen werden können :)

**Comment by LukasFreeze** [comment]
> "was nicht im Wiki steht, kann weg"
Ich muss hier zuerst auf das wiki verweisen: Johannes, was macht die Doku?.
Und jetzt im Ernst: Ich bin prinzipiell bei dir, dass nicht alles weg sollte, was nicht im Wiki steht. Allerdings sollten wir auch nicht jeden Kleinscheiß als Leihgabe annehmen. Und auch nicht jedes selbstgebastelte Werkzeug sollte einfach im Space herumstehen (ich denke da zum Beispiel an diese Schleifeinrichtung, die auf einmal in der Holzwerkstatt stand). Das bedingt nämlich das Risiko, dass Leute das nutzen. Versicherungstechnisch ist das denke ich schwierig, wenn da mal was passiert...

Da hab ich "Leihgabe" vielleicht falsch benutzt - ich meinte nicht die offiziellen und eigtl immer größeren Sachen, sondern eher die die eigentlich als Spenden gedacht waren, aber dann von den ehemaligen Besitzern wieder aus dem Schrott gefischt werden dürfen. Da gibt es viele kleine Handwerkzeuge, Messgeräte etc. die statt Wegräumen einfach mal 5 min Wiki-Arbeit bekommen könnten und dann im wesentlichen dokumentiert wären.
Potenziell gefährliche Geräte sollen natürlich nicht einfach rumstehen, ohne genutzt werden zu können, aber auch da könnte man ja eher ein Issue aufmachen damit sich unser Inventar-Manager besser drum kümmern kann als zu sagen "in 4 Wochen kommts weg wenn die üblichen Deppen nichts ins Wiki schreiben"^^

> "was nie benutzt wird, kann weg"
Prinzipiell bin ich bei dir, mir fallen allerdings auch Beispiele ein, bei denen ich das anders sehe. Daher bin ich wieder völlig bei dir, wenn es darum geht, das entsprechend einfach zu kommunizieren. Wir können nicht jeden bauchpinseln, der einmal in 6 Monaten in den Space kommt und dann Werkzeug liegen lassen will, aber wir sollten jedem die Chance geben, sein Zeug auch wieder mitzunehmen. Ich denke da an Sachen wie dieses Bosch Ixo Spielzeug: Lag ewig rum, will keiner reparieren. Und selbst wenn: Die Dinger sind einfach unnütz.

Meine Hauptaussage hier sollte sein, dass die Aufräumer im Zweifel nicht wissen (können), was "nie benutzt" wird. Nachweislich lange Zeit kaputte Sachen sind sicherlich eine Ausnahme, aber da gibt es normalerweise ja auch ein Issue (Ixo: #48) was endlich mal mit dem geplanten "Rauswurf" des Gerätes geupdated werden könnte (@Johannes09 )

> Bezüglich eines horizontalen Systems:
Ich befürchte, dass ein System aus horizontalen Regalbrettern sehr dazu einlädt, dass da Chaos herrscht (dann stellt jemand was auf den Boden, etc.). Daher befürworte ich einen "Schrank" als Lösung. Ich gebe dir Recht bezüglich großen, auszumistenden Sachen. Allerdings darf man dabei nicht vergessen: Das Ganze ist auch als offizielle Lagermöglichkeit gedacht. Ich denke da an den Ikea Schrank von Eileen, etc....
Daher denke ich, dass eine vertikale Lösung sinnvoll ist, in die noch extra Regalbretter eingezogen werden können :)

Für große Mitgliederprojekte können wir nie genug Platz schaffen, wenn da was zu großes anfällt bin ich eher für individuelle Vereinbarungen als einen möglichst großen Lagerplatz, der dann die meiste Zeit leer ist.
Und auf horizontale Bretter passt auch eine Menge...
Hauptargumente für meinen Vorschlag: alle Materialien schon da (Winkel und Melamin-Regalbretter), viel leichter in der Größe zu variieren falls ein Fach mal "mitwachsen" muss, und auch das Zumüllen dürfte durch den wöchentlichen Wechsel (bei dem man die Bretter auch schnell mal feucht abwischen kann, im Gegensatz zu Fächern mit Kanten und voraussichtlich wesentlich gröberem Holz) kein allzu großes Problem sein.

**Comment by NitramLegov** [comment]
- Leihgaben / Werkzeuge
Ich gebe dir vollkommen Recht, dass sowas nicht einfach so weggeworfen werden sollte. Daher der Vorschlag mit der Kommunikation. Ich denke da sind wir auf einer Linie, müssen das nur mal bei Gelegenheit zusammenschreiben (im Wiki dann)

- Wenig benutzte Werkzeuge
 Auch hier schlage ich klare Kommunikationsregeln vor. Im Endeffekt weiß niemand im Space wirklich, was von anderen vielleicht ab und zu benutzt wird. Und den Konflikt zwischen Leuten, die eher mehr wegwerfen und Leuten, die eher weniger wegwerfen werden wir nicht grundsätzlich lösen können. Allerdings kann er durch klare Kommunikation tendenziell entschärft werden. Und vielleicht kann man @Johannes09 noch ein bisschen pushen, dass er endlich mal rumschickt, was er gerne loswerden möchte (drucker, ixo, etc.)

- Horizontal/vertikal & Spinde dazu ja oder nein
Das sehe ich aktuell noch als größten Diskussionspunkt (zumindest zwischen uns beiden, bis sich jemand anderes zu Wort meldet). Was sagen denn die "üblichen Verdächtigen"? @Johannes09 @Pakue95 @kenomaerz @LarsKumbier 
Ein Argument für den vertikalen Aufbau ist für mich, dass wir damit eine Wand bekommen, die einheitlich ist: Lagerflächer, Spind, Spind. Und alles ist ähnlich aufgebaut. Wenn wir allerdings keinen extra Spind bauen sollen (Ich persönlich würde einen bauen, weil ich finde, dass man das immer brauchen kann. Man muss es ja nicht als Spind nutzen. Im Zweifel ist es erstmal zusätzliche "Parkfläche"...), ist das Argument natürlich hinfällig.

Ich halte nach wie vor ein Regalsystem für Chaos-anfällig. Ich finde man sieht das beim Schraubenregal und beim Ladder-shelf ganz gut: Da wird angefangen, überall, wo ein bisschen Platz ist irgendwelchen Kram hinzustellen den vielleicht mal jemand brauchen könnte (in 100 Jahren oder so...).

Beim horizontalen Ansatz sehe ich auch die Schwierigkeit, dass das Brett für Woche 4 in einiger Höhe sein müsste (mindestens 2 Meter). Ich hab da kein problem damit, aber wir haben auch kleinere Leute. Da Woche 4 ja aber das Fach ist, aus dem sich jeder Zeug rausnehmen darf (free for all), halte ich das für schwierig.


- Aufwand & bereits vorhandene Materialien:
Kurze grundsätzliche Aussage: Für mich ist "alles schon da", etc. nicht ausschlaggebend: Ich will das sauber machen, nicht basierend auf dem was wir halt haben. Falls wir Holz kaufen müssen (je nachdem, was noch im Lager ist) kann das auch gern aus meiner Tasche kommen. Da ist genug zurückgelegt für sowas. Der Aufwand schon eher, ich plane und koordiniere da aber auch gerne einen do-something day (in dessen Zusammenhang wir gerne auch direkt die Müllecke machen können. Dann ist die Ecke komplett).

**Comment by Pakue95** [comment]
Als Regal Orientierung finde ich vertikal besser, da dann jede Woche gleich gut “sichtbar” ist. 

Einen extra Spind hatte ich Martin vorgeschlagen, da wir momentan nur noch ein(?) Fach zum mieten frei haben. Falls wir umziehen macht ein Spind mehr oder weniger auch keinen Unterschied.

**Comment by NitramLegov** [comment]
Closed, since this task will most likely change when the space gets moved
