### ISSUE TITLE
Build cyclone dust separator for CNC

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#15]
Our CNC router produces lots of dust that will quickly fill up tha vaccum cleaner bag.
This can be avoided using a cyclone dust separator to collect the dust in a separate box, we just need to finish building it.

* [x] build box small enough to carry and empty into a trash bag
* [x] buy plastic part (cyclone separator)
* [x] determine how much flexible hose we need
* [x] buy flexible hose
* [x] buy closing mechanism for top lid
* [x] finish building removable top lid (closing mechanism + holes) and attach plastic part
* [x] add window insulation on top edge of box (below removable lid)
* [x] attach flexible hose to cyclone separator side and router attachment
* [x] design and build adapter to attach vacuum cleaner to cyclone separator outlet on top

**Comment by emka** [comment]
We probably need 6m.

**Comment by johannesgo** [comment]
welcher Durchmesser?

**Comment by LukasFreeze** [comment]
Durchmesser des Zyklonstutzens: ID 50, OD 56 mm

**Comment by LukasFreeze** [comment]
Ich bin stark dafür, den kleinen "Shop Vac" für die CNC-Absaugung zu nutzen und nicht wie bisher den guten Festool-Sauger. Sonst fehlt letzterer dauernd in der Holzwerkstatt, wo er zu vielen Geräten passt...

Vorausgesetzt die Saugleistung reicht aus könnte man am "Auspuff" des kleinen noch einen Feinstaubfilter einbauen, um das abzufangen was durch Zyklon und Papierfilter geht.

**Comment by LukasFreeze** [comment]
Micha hat heute an der Box gebastelt, sie ist jetzt abgedichtet und verschraubbar. Der neue Schlauch passt an den Zyklon auch dran, aber nicht an die Fräse - und der Staubsauger passt noch nicht an den Zyklon.

Wir haben also Bedarf an Adaptern ;-) Ich habe mal gemessen:

- [ ] neuer "dust shoe" (an der Fräse), an den der 60-mm-Schlauch passt
- [ ] Adapter Shop Vac (ID 27.5, OD 31) <-> Zyklon (ID 49, OD 55)

**Comment by NitramLegov** [comment]
Habe angefangen, einen Adapter zu designen:
https://github.com/comakingspace/CommonFiles/blob/master/3DPrintingFiles/Adapter_Staubsauger_v2.stp

Den werd ich am Mittwoch mal drucken. Wenn der soweit passt werde ich ihn im Wiki bei den Staubsaugern verlinken - inklusive Werten für unsere beiden Staubsaugern (das design ist parametrisiert, lässt sich also einfachst anpassen)

**Comment by NitramLegov** [comment]
Der Adapter ist gedruckt und passt.
@Pakue95 hat gestern auch den adapter für den dust shoe neu gedruckt. Damit ist erstmal alles erledigt für dieses issue.
Jetzt muss man noch ausprobieren, ob es wirklich funktioniert (hat der Staudbauger genug Leistung?). Der Übersicht halber mach ich hier mal zu...

**Comment by LukasFreeze** [comment]
Falls es am dust shoe noch undicht ist, könnte man da noch eine Schicht von
dem rosa Styropor-Packmaterial einbauen.

Ich hab gerade auch mal ein paar Infos über den ganzen Aufbau ins Wiki
geschrieben
