### ISSUE TITLE
neue Oberfräse(n)

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#151]
Es war ja immer mal wieder im Gespräch, etwas Geld in eine neue Oberfräse zu investieren - da die geliehene Bosch jetzt endgültig in der Höhenverstellung festzusitzen scheint, hier meine Vorschläge zur Nachfolge:

1) sofort: handgeführte Akku-Oberfräse, die mit unseren vorhandenen Akkus betrieben werden kann
- [Makita DRT50ZJX2](https://www.makita.de/produkte/akku-programm/akku-multifunktionsfraese-drt50zjx2/) -> zB 230 € [Büromarkt Böttcher](https://www.bueromarkt-ag.de/oberfraese_makita_drt50zjx2_akku_18v,p-drt50zjx2.html)
- Vorteile: wechselbare Körbe, vor allem zur Kantenbearbeitung einfacher und sicherer nutzbar als größere Modelle, inkl. MAKPAC-Systainer, relativ leise (@Manu444 hat eine sehr ähnliche kabelgebundene - richtig?)
- Nachteil: für manche Anwendungen evtl. zu schwach (800 W), die kommen aber bei uns kaum vor und es gibt ja auch noch die Ferm FBF-1050E (1050 W)

2) wenn die Fördermittel da sind (Ende Oktober): leistungsstarke Tisch-Oberfräse als Ersatz für die KingCraft KBF-1050E
- Triton TRA 001 (wie auch in #105 und #111 erwähnt) + Spannzangen, 6 und 8 mm
- Vorteile: Preis-Leistungs-Preis der HolzWerken-Spezialausgabe "Oberfräse"; von zahlreichen YouTubern empfohlen (hoffentlich ehrlich)
- Nachteile: lässt wohl im Handbetrieb zu wünschen übrig, weil sie so sehr für Frästische optimiert ist - kann uns egal sein!

Warum mit der zweiten noch warten?
- es wäre gut, wenn die Sachen fürs geförderte Projekt wirklich von diesem Geld angeschafft werden falls doch jemand nachfragt und die Daten plötzlich keinen Sinn machen
- kann gut sein, dass die KingCraft im Tisch eh mit ein paar Handgriffen zu reparieren ist wenn sie bis dahin nochmal jemand braucht (siehe #120 - springt nur nicht mehr an, wenn der Schalter am Gerät dauer-an ist und man den Tischschalter nutzen möchte)
- wir haben vage noch eine Fräse von einem Tischler in Aussicht, der uns auch schon die schicke Tischkreissäge (#139) beschert hat - falls die wirklich demnächst kommt und gut ist, sich aber als geeigneter für den Tisch- als den Handbetrieb herausstellt, sollten wir von dem Fördergeld lieber noch eine starke Handoberfräse kaufen (HolzWerken-Testsieger: Festool OF 2200 EB Plus, besonders gut ist wohl die Absaugung aber sie ist auch richtig teuer und wiegt knapp 8 kg... halb so teuer und im Test nur 0.1 Notenpunkt drunter wäre die **Trend T11 EK Euro**, daher ist die mein Favorit)

Was meint ihr? Hat noch jemand Erfahrungen mit der Makita oder ähnlichen Geräten?

**Comment by Pakue95** [comment]
Zu 1. gäbe es auch noch die [Festool OF 1010](https://www.festool.de/produkte/fraesen/oberfraesen/574335---of-1010-ebq-plus)(460€ je nach Zubehör), die auch noch recht handlich aussieht und etwas mehr Leistung hat als die Makita. Die passt auch auf die Schiene der Festool Tauchsäge.

**Comment by LukasFreeze** [comment]
Hmm, ich wäre nicht für so eine - die Festool-Fräse ist schon nochmal deutlich klobiger, eher ähnlich wie die gerade kaputt gegangene Bosch oder die noch vorhandene Ferm. Ich finde den Griff bei dieser Reihe auch nicht gut (wurde damals im DAI angeschafft), durch den hohen Ansatz und weiter außen liegende Hand kommt man da leichter ins Kippeln.

Der Vorteil bei der vorgeschlagenen Makita liegt aber gerade darin, dass sie durch den Akku und die Bauform so extrem handlich ist. Kanten bearbeiten geht mit so einem "palm router" im Einhandbetrieb oft noch leichter als am Frästisch, und die etwas geringere Leistung sollte gar kein Problem sein :-) Auf die Makita ist meine Wahl vor allem wegen des schon vorhandenen Akkusystems gefallen, ansonsten gibt es [ähnliche Modelle auch von anderen Marken](https://www.youtube.com/watch?v=MKZG1kAByfU)

An die Führungsschiene hatte ich auch kurz gedacht, mir ist aber ehrlich gesagt keine Anwendung eingefallen wofür ich die Fräse damit benutzen wollte. Und wenn doch, ist jede beliebige gerade Latte ja genauso einfach aufgespannt...

Last but not least reden wir bei der Festool-Fräse gleich über doppelt so viel Geld.

**Comment by Pakue95** [comment]
Ok, dann würde ich aber noch einen extra Akku für die Makita vorschlagen, weil wir sonst keinen Spare zum laden haben.

**Comment by LukasFreeze** [comment]
Jau, das wäre dann bestimmt praktisch - gleich 5 oder 6 Ah?

**Comment by Pakue95** [comment]
5Ah klingt gut. 6Ah ist nicht so gängig wie 5Ah und kostet 50% mehr.

**Comment by kenomaerz** [comment]
Klingt für mich schlüssig hergeleitet, und die VEerwendung der Fördermittel für die Fräse ist IMHO auch gut argumentierbar.

**Comment by FHuchinson** [comment]
Generell für Neuanschaffungen gibt es zur Zeit bei eBay 10% (max.50€) mit nem Gutscheincode (PMACHER19). Vielleicht gibt es die da ja auch erschwinglich. Könnte sich rentieren. Patrick wurde schon informiert

**Comment by Pakue95** [comment]
Ok, da keine weiteren Vorschläge rein kamen würde ich die Makita mit Akku am Wochenende bestellen.

Während des Plenums gestern kam jedoch noch der Wunsch auf eine netzbetriebene Oberfräse mit der Tor4 Förderung anzuschaffen. Ich würde das dann nochmal ansprechen sobald wir die Finanzierung haben.

**Comment by Pakue95** [comment]
Ist bestellt. 

PS: @FHuchinson Die Aktion ist nur bei ausgewählten Händlern und die waren alle teurer als die 10% soweit ich das überschauen konnte.

**Comment by Pakue95** [comment]
Die Makita Oberfräse ist inventarisiert und nutzbar. Der 5Ah Akku ist auch mittlerweile da.

**Comment by LukasFreeze** [comment]
die große Oberfräse müssen wir vorerst doch nicht kaufen - wir haben eine gespendet bekommen!

"Commissioning" läuft wie üblich übers Wiki - [Routers#Makita 3612BR](https://wiki.comakingspace.de/Routers#Makita_3612BR), bei Bedarf können wir ja auch noch ein Issue aufmachen :-)
