### ISSUE TITLE
Google Maps: Parkplatz im Space...

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#152]
Für alle die mal eine Minute Zeit haben: bitte meldet auf Maps, dass der neuerdings direkt auf dem Space eingezeichnete "DB BahnPark Parkplatz Hauptbahnhof" ein Duplikat vom echten Parkplatz ist -.-

![grafik](https://user-images.githubusercontent.com/19755883/64476772-505a3e80-d193-11e9-8d95-d71531c6735e.png)

Warum wir dagegen immer noch keinen Pin bekommen haben, verstehe ich nicht...

**Comment by emka** [comment]
Man kann unter "Änderung vorschlagen" den Standort korrigieren. Das habe ich gerade getan. Wurde zwar als "übernommen" markiert, aber ich sehe noch keine Verbesserung.

**Comment by LukasFreeze** [comment]
Genau, das meine ich - korrigieren oder gleich als Duplikat vom korrekt
platzierten Parkplatz melden.

Ich hab das schon vor zwei Wochen versucht und es hat sich trotz
Bestätigung nichts getan, deshalb dachte ich jetzt es könnte was bringen
wenn mehrere meckern

**Comment by NitramLegov** [comment]
Habe es auch mal gemeldet. Vielleicht hilft es ja, dass ich local guide bin...

**Comment by HannaMuenne** [comment]
![image](https://user-images.githubusercontent.com/55091399/64530834-558fc880-d30e-11e9-818f-a1bd4ce1fee4.png)
Bei mir wird und wurde das CoMakingSpace bei Google Maps immer korrekt angezeigt...

**Comment by LukasFreeze** [comment]
@HannaMuenne cool, bei mir gibts leider immer noch keinen Pin wenn ich incognito surfe :-P

Aber der Parkplatz ist auch bei mir weg! Irgendwas hat geholfen :-)
