### ISSUE TITLE
Printer P3 should be checked

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#155]
Today, P3 had the issue that the belt of the x-axis skidded down.

I put the belt back on and tightened it. Afterwards, I ran a calibration cycle of the xyz axis. However, I did not yet set the first layer height!

While the calibration did run through successfully, the printer sounded a little bit odd (to me). This should be double checked either by the area patrons (@Narquadah , @reogaro ) or by the inventory manager @Pakue95

**Comment by LukasFreeze** [comment]
@Pakue95 (I think?) calibrated it and we did a auccessful test print yesterday.
