### ISSUE TITLE
Alpha tools "Flex" angle grinder broke

### ISSUE THREAD

**Issue by Titan-OX** [comakingspace/do-something#157]
the Alpha Tools WS 960  https://wiki.comakingspace.de/Disc_Grinders#Alpha_Tools_WS_960.2F125
 the spindle locking button fell of which caused die locking pin to fall in to the running spindle bending the pin and breaking a part of the cast case.
- is there anything helpful in the manual (link in the corresponding wiki infobox, if available)? one dose not simply read the manual. but I'm guessing "don't use if broken" 
I turned a new pin before i noticed that the case (the inside is completely covered in shmue) was had a chunk missing. due to the broken case the new locking pin isn't held in place firmly rendering it unreliable. 

I would suggest to come up with a new locking mechanism and only use it for brushes and get a new angle grinder for cutting wheels, the aren't expensive.

**Comment by LukasFreeze** [comment]
Good idea! We saw on Wednesday that the axis could be locked with a thin
wrench if the guard is not installed.

Are we sure wire brushes can be used without the guard? No chance of wires
coming loose or sparks flying around?

Please don't throw anything away yet in either case, we have an angle
grinder in the office that could be commissioned if we add the guard from
this one :-)

**Comment by LukasFreeze** [comment]
New locking mechanism implemented & documented [in the wiki!](https://wiki.comakingspace.de/Disc_Grinders#Alpha_Tools_WS_960.2F125)

While we were at it, @Lmnl99 and I put a screw into the empty locking pin hole and replaced the shitty screws holding the gearbox together with new ones.
