### ISSUE TITLE
Türknäufe für das Buzzer-System

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#16]
Für das neue Buzzer-System (s. eMail vom 24.4.) brauchen wir ein paar Türknäufe - bisher haben wir leider nur einen, der passt. Vielleicht können wir erstmal versuchen, welche in 3D zu drucken?

Die Türen und Schlösser sind potenziall alle verschieden, wir müssen also genau ausmessen wo Löcher und die Klinke sind...

- [x] Gemeinschaftsraum zu Holzwerkstatt (Originalknauf)
- [x] Flur zu Holzwerkstatt
- [x] CNC-Raum
- [x] Elektronik-/3D-Raum

Fest einbauen werden wir die Knäufe dann, sobald alle vier Buzzer funktionieren :-)

**Comment by JohannesGruhler** [comment]
das ist die erster version des Türknäufes
[version1.0.zip](https://github.com/comakingspace/do-something/files/1968735/version1.0.zip)

**Comment by LukasFreeze** [comment]
^^für die Tür zum CNC-Raum - schon montiert und bislang stabil, aber noch
etwas kurz :-)

**Comment by emka** [comment]
Alle Knäufe sind gedruckt (danke @JohannesGruhler), beim Elektronik-Raum fehlt noch der Buzzer, bevor der Knauf montiert werden kann.

**Comment by LukasFreeze** [comment]
Der Knauf vom CNC-Raum ist an der Fassung für die Mutter gebrochen - ich habe eine neue Schraube in das untere Loch geschraubt damit man nicht plötzlich die Klinke in der Hand hat, aber hier sollten wir nochmal das Design verbessern und neu drucken. So in etwa:

- [ ] Knauf-Design etwas verlängern, damit mehr aus der Tür rausguckt
- [ ] Knauf-Design etwas verstärken, damit die Mutter besser hält
- [ ] neu ausdrucken

**Comment by NitramLegov** [comment]
Nur als reminder auch hier: Es gibt jetzt ein repository "common files" mit einem Ordner für 3D-Druck Dateien:
https://github.com/comakingspace/CommonFiles/tree/master/3DPrintingFiles

Da könnte man die Türknäufe auch reinhängen, sobald das Design überarbeitet wurde.

**Comment by JohannesGruhler** [comment]
Dies ist die datei zu allen Türknäufen außer dem cnc raum
[knauf 1.2 v3.f3d.zip](https://github.com/comakingspace/do-something/files/2207204/knauf.1.2.v3.f3d.zip)

**Comment by JohannesGruhler** [comment]
das ist die Datei vom Knauf für den CNC Raum: 
[knauf 1.2 cnc-raum v4.f3d.zip](https://github.com/comakingspace/do-something/files/2217209/knauf.1.2.cnc-raum.v4.f3d.zip)
ich habe den Knauf schon ausgedruckt und werde ihn dann am Mittwoch mitbringen

**Comment by LukasFreeze** [comment]
Cool, vielen Dank! :-D

**Comment by NitramLegov** [comment]
Ich hab die Dateien mal in das [Common Files Repository](https://github.com/comakingspace/CommonFiles) hochgeladen ;)
