### ISSUE TITLE
Rote Zora CNC - Future plans

### ISSUE THREAD

**Issue by Blacksheep70** [comakingspace/do-something#160]
Once the machine is released for "public" use there are further plans to enhance the machine:

- Add a inrush current limiter to the controller unit to avoid fuse trigger on power on (toroidal transformer)
- Vacuum cleaning (wood dust, metal chips)
- Add a touch probe
- Replace the threaded rods with spindle ball bearings
- Fluid cooling for workpieces

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by Johannes09** [comment]
Soweit icb weiß ist die Rote Zora nicht mehr im space
