### ISSUE TITLE
bed leveling error on 3D printer "P5"

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#162]
The bed leveling on P5 fails at the second probe point (front center): after "touching down" for the first time, the head travels up again and leveling is stopped with the error message "probe triggered too high"

The G-code ran fine on another printer, have not tried anything else yet. Do we know this problem? What could be done about it?

Perhaps also related to this: on Friday, a job on this printer had to be aborted because the nozzle lowered itself into the print around Z=20 mm

**Comment by Narquadah** [comment]
Fixed the issue, the z axis was not properly calibrated.
