### ISSUE TITLE
Türen für den neuen Space

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#165]
Die Trockenbauwände auf unserer Baustelle müssen gerade nicht nur auf eine Materiallieferung warten, sondern vor allem auf eine Festlegung der Türmaße.

Es stand immer wieder im Raum, anzufragen ob wir Türen aus dem jetzigen Space bekommen könnten, aber wer hätte genug Ahnung um die einzubauen? Das fängt damit an, dass wir passende Zargen für unsere neuen Wände finden müssten (Wandstärke 124 mm).

Ansonsten müssen wir neue kaufen und ich wäre sehr froh, wenn jemand bei der Recherche helfen könnte :-) Vor allem der Schallschutz von [einfachen Zimmertüren](https://www.bauhaus.info/zimmertueren/zimmertuer/p/24772381) bereitet mir noch Kopfzerbrechen, kennt sich da vielleicht jemand aus oder würde etwas Zeit investieren und sich einarbeiten? Die Wände bringen hoffentlich >40 dB Schallreduktion, zumindest die Tür zur Werkstatt sollte sich da meiner Meinung nach in einem ähnlichen Bereich bewegen wenn wir etwas bezahlbares finden.

- [x] Entscheidung: alte oder **neue** Türen?
- [x] Entscheidung: Türmaße, um die Wandöffnung planen zu können
- [x] Vorschläge für geeignete Türen sammeln (hier oder [Wiki -> Trockenbau](https://wiki.comakingspace.de/Trockenbau))
- [x] Türen bauen/kaufen

**Comment by LukasFreeze** [comment]
Patrick und ich haben uns gerade nochmal vor Ort beraten und es sieht echt so aus als wären die alten Türen zu aufwendig.

Breitere Türen (98.5 cm) bieten deutlich mehr Platz als die "normalen" Zimmertüren (86 cm), deshalb würden wir die einplanen. Damit sind wir [laut dieser Tabelle](https://media.bahag.com/assets/14/13/1413295_22601684.pdf) bei einem **Maueröffnungsmaß von 1010 x 2005 mm**, das wir beim Trockenbau anlegen würden.

Zeit für Einspruch bleibt noch bis Freitag ;-)

**Comment by LukasFreeze** [comment]
Korrektur: nur für die Verbindungen vom Gemeinschaftsraum zum E-Room und zur Werkstatt wären die breiten Türen gedacht, alle anderen reichen mit 860er Breite (Maueröffnungsmaß 885 mm)

**Comment by LukasFreeze** [comment]
Nochmal eine kurze Zusammenfassung, was wir suchen:

- 2 relativ einfache Türen mit 860er Breite (Büro, Lager) - oder Lager doch schalldichter?
- 1 relativ einfache Tür mit 985er Breite (Gemeinschaftsraum zu e-Room)
- 1 möglichst schalldichte Tür

**Comment by LukasFreeze** [comment]
im Gespräch mit @NitramLegov kam letztens die Frage auf, wie kompliziert es denn wirklich wäre, Türen selbst zu bauen - ich glaube das ginge schon, aber selbst wenn wir den Arbeitsaufwand vernachlässigen sollten wir uns über die erwarteten Kosten im Klaren sein.

Laut [bau-wiki.de](https://www.bau-wiki.de/tuer-und-torwiki/tueren/funktionstueren/schallschutztueren/) kann eine einfache Schallschutztür aus zwei Schichten stabilem Material und einer Zwischenlage Mineralwolle bestehen, also zum Beispiel:
- 2 Platten Multiplex, ca. 1x2 m -> 12 mm Stärke kosten [bei Bauhaus im Zuschnitt](https://www.bauhaus.info/multiplexplatten/multiplexplatte-nach-mass/p/20093017) knapp 40 € pro m², also 160 € pro Tür
- Mineral- bzw Glaswolle ist weniger teuer, z. B. [8 m (4 Türen) für 82,10 €](https://www.bauhaus.info/steinwolle/ursa-pureone-untersparrenfilz-usf-31/p/25630978)

Das sind jetzt sicher noch nicht die günstigsten Materialpreise (gerne mitrecherchieren!), aber es sollte zeigen dass auch eine selbstgebaute Tür schnell teuer werden kann :-P

Alternativ könnten wir auch drüber nachdenken, "normale" Türen nachzurüsten, was nur die halbe Menge an Multiplex benötigt und keine Detailarbeit am Falz notwendig macht. Hier eine Anregung aus dem ["Drummerforum"](http://www.drummerforum.de/forum/40798-t%C3%BCre-d%C3%A4mmen-jetzt-mit-bauanleitung-f%C3%BCr-eine-schallschutzt%C3%BCr.html):
> Wir haben auf eine normale Holztüre ein Gerüst aus Dachlatten geschraubt. An jeder Seite eine und dann in der Mitte jeweils im 60cm Abstand noch eine um ein Fach für die Steinwollplatten zu machen. Danach wurde jede kleine Ritze mit Silikon verdichtet, weil wo keine Luft mehr raus kann, kann es der Schall auch nicht. Jetzt haben wir die Steinwolleplatten zurechtgeschnitten in Malerfolie verpackt und dann mit Gaffa zugeklebt. Als alle drei Platten in der Kiste verstaut waren kam eine 8mm Sperrholzplatte als letzte Schicht oben drauf. Sie wurde wie alle anderen Holzteile verleimt und geschraubt.
Die Gesamtkonstruktion hat jetzt ohne Türe eine Stärke von 5cm.
Jetzt muss ich nur noch die Fugen an der Türe einigermaßen dicht bekommen und mein Problem ist gelöst. So eine Türe kann ich jedem empfehlen der nicht viel Geld ausgeben will und trodtzdem etwas effektives haben will. Im Gesamten hat die Türe etwas mehr als 40€ Gekostet, was meiner Meinung nach für so ein Vorhaben immernoch sehr günstig ist.

**Comment by NitramLegov** [comment]
Die Idee, Türen selbst zu bauen kam teilweise auch deshalb, weil das Material ja schon vorhanden sein sollte und sich dadurch die Kosten reduzieren lassen sollten. 

OSB und mineralwolle sind da. Würde halt eine 12cm Tür ergeben, da müsste man schauen, welche Konsequenzen das hat. Andere Selbstbaumethoden bedeuten aber tendenziell eine Lücke im Schallschutz.

Aber klar: auch Eigenbau gibt's nicht umsonst

**Comment by LukasFreeze** [comment]
Hmm, da hätte ich mir schon etwas stabileres vorgestellt als unsere
OSB-Verlegeplatten...und da gibt's auch nur Stücke mit 675er Breite, lieber
ein massives Türblatt als ein Flickenteppich oder?

Wenn wir eine günstige Tür kaufen und darauf aufbauen würde ich schon eher
die Reststücke von der Wandbeplankung nehmen.

Was wir übrigens auch noch bedenken sollten, steht hier glaub ich noch gar
nicht drin: in den beiden breiten Türen (zu Werkstatt und e-Room) wollten
wir auch noch Scheiben für eine Sichtverbindung haben!

**Comment by LukasFreeze** [comment]
Wenn die Wände soweit stehen kann ich versuchen, eine 860er-Probetür zu entwerfen (auf eigene Kosten bis es wirklich klappt) die wir dann im Erfolgsfall zwischen e-Room und CNC montieren könnten oder wenn sie zwar schließt, aber nicht sonderlich schalldicht ist, zum Büro.

@NitramLegov hat eventuell eine Spendenquelle für Dreischichtplatten gefunden, sonst wäre ich wahrscheinlich immer noch beim Multiplex oder zumindest Seekiefer-Sperrholz wie in unseren Spinden.

e-Room "Nord" als Testwand bietet sich an, weil die sowieso als erste schallschutzrelevante Wand fertig werden muss.

Eine Zarge würde ich trotzdem fertig kaufen, erspart an der Stelle unnötige Arbeit und gibt ja auch die Maße der Tür vor.

**Comment by LukasFreeze** [comment]
Fürs Büro haben @Pakue95 und ich gestern mit einer einfachen Standardtür (die "Aktions-Zimmertür" für 26,50 zusammen mit der günstigsten Zarge von Bauhaus) angefangen, morgen Abend kann sie hoffentlich fertig montiert werden und damit zeigen, ob wirs kapiert haben ;-)

Backup-Position für eine schlechte Eigenbau-Tür in 860er Breite wäre dann der Durchgang zum Lager, deshalb habe ich erstmal keine zweite Tür gekauft.

Zargen sind teuer (ab ca 70 €) und können nicht umgetauscht werden, deshalb ist es beim aktuellen Erfahrungsstand noch nicht sinnvoll die fehlenden alle zu kaufen.

**Comment by LukasFreeze** [comment]
Iggy und @Pakue95 haben die Bürotür heute fertig eingebaut und es sieht sehr gut aus!

Also können als nächstes die weiteren Zargen und eine breite Tür für den eRoom gekauft werden:
- 2 Zargen 860er Breite, 124er Wandstärke ("125" sollte passen, aber schaut auf jeden Fall nochmal auf den genauen Einstellbereich!)
- 2 Zargen 985er Breiter, 124er Wandstärke
- günstige Zimmertür 985er Breite, Anschlag/DIN **rechts**

Zum Einpassen der schmalen Zargen kann die Bürotür verwendet werden, bitte noch keine weiteren Türen kaufen bis der Eigenbau fortschreitet!

**Comment by LukasFreeze** [comment]
durch die nahenden Feiertage sah der Lagerbestand ganz schön mies aus und @NitramLegov musste die ganze Umgebung abklappern, aber jetzt müssten alle Zargen da sein :-)

Ich hoffe, am 27.12. eine erste Schallschutztür bauen zu können. Gibt es jemanden, der vorher ein Auge auf meinen Entwurf werfen möchte, oder spare ich mir lieber die Aufhübschungsarbeit?

**Comment by LukasFreeze** [comment]
Die Schallschutztür scheint zu funktionieren wie gehofft, richtig fertig machen kann ich sie aber leider erst im Januar (8. hoffe ich)!

![IMG_20191228_035439](https://user-images.githubusercontent.com/19755883/71543539-493e8280-2974-11ea-9642-f2a3fae9c848.jpg)

Nur dass ihr's schonmal wisst und euch entspannt um die anderen Baustellen kümmern könnt, die für den Gemeinschaftsraum baue ich dann auch asap ;-)

Also konkret gerade zu machen:
- Zargen (schon gekauft) einbauen
- einfache Türen für eRoom (985er Breite, DIN rechts, soll Fenster bekommen?!) und Lager (860er links, Bauhaus "Aktionstür" für 26,50 € reicht) kaufen

**Comment by LukasFreeze** [comment]
Die 860er Tür steht im Gang bereit, für die breite muss aber jemand zum Fachhandel fahren - [Holz Schwab in Hockenheim](https://www.holzschwab.de/) hat hoffentlich etwas vorrätig!

**Comment by LukasFreeze** [comment]
Die zweite Schallschutztür ist auch fertig! Sie schließt nicht ganz so weit wie ichs gerne hätte - drückt man dagegen, wird es nochmal etwas leiser - aber das lässt sich vielleicht irgendwann mit einer zweiten Gummilippe noch verbessern. Erstmal nicht das dringendste :-)

**Comment by LukasFreeze** [comment]
@Narquadah hat gestern die letzte Tür geholt, und die Zarge haben wir gestern noch eingesetzt - fast fertig :-)

**Comment by LukasFreeze** [comment]
Die "CNC-Tür" hat auf der Werkstattseite jetzt zwar einen gedrechselten Knauf, es kann allerdings sein dass die versteckten Schrauben nochmal ausreißen weil sie nur ein kurzes Stück in ungünstiger Faserrichtung drin greifen.

Wenn das passiert hat @Pakue95 vorgeschlagen drei sichtbare Schrauben von der Knaufseite her einzudrehen, erstmal hielt er am Mittwoch aber 🙈

Die anderen Knäufe (eRoom, Gang) bekommen am besten ein Innengewinde passend zum jeweiligen Wechselstift, das sollte nicht nur besser halten sondern ist auch nötig, um die Klinken auf der anderen Seite zu fixieren (diese Tür hatte leider nur einen normalen Vierkant, dafür eine anschraubbare Klinke)

**Comment by NitramLegov** [comment]
Für das Office, den E-Room und die Tür zum Lager gibt es schicke 3D gedruckte Knäufe.
Der zum Lager muss noch an die Tür geschraubt werden, ansonsten ist das hier denke ich fertig :)

**Comment by LukasFreeze** [comment]
Ganz so einfach war das mit dem Lager nicht, weil ja eigentlich ein Innengewinde in den Knauf gehört hätte, aber @Johannes09 hat sich gestern Abend um einen Workaround aus einem Stück Kupferrohr gekümmert und es sollte passen :-)

Türschließer fehlen noch, sind aber nicht so dringend und kriegen vielleicht besser ein eigenes Issue - mach ich gleich mal auf!
