### ISSUE TITLE
Lasercutter auswählen & bestellen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#166]
Wir können uns endlich einen Lasercutter leisten und sollten ihn langsam bestellen, damit wir nach dem Umzug bald loslegen können :-)

In #111 hatte ich den [Laserscript LS6090](https://www.laserscript.net/product/ls6090-laser-engraving-cutting-machine/) (£6300 incl. VAT) von [HPC Laser](https://hpclaser.co.uk/index.php?main_page=product_info&cPath=1&products_id=11) vorgeschlagen. Wie findet ihr den, spricht etwas dagegen?

Zur Abluftfilterung könnten wir anstelle [dieses Filterschranks](https://hpclaser.co.uk/p/bofa-ad500-laser-fume-filter/) von HPC, den wir uns nicht unbedingt leisten können, über einen Eigenbau nachdenken. Die Absaugung ist schon im Lasercutter integriert, wir bräuchten also nur eine abgedichtete Box mit Filtermedien wie sie das [Fablab Neuenstadt gebaut zu haben scheint](https://www.fablabs.io/machines/sabko-6040). Die sollten wir dann einfach mal nach Erfahrungen und Bauplänen fragen!

Alternativvorschläge sollten sich bitte preislich in einem ähnlichen Rahmen bewegen und ebenfalls in Europa als Lasergerät Klasse 1 zertifiziert sein - immer her damit ;-)

**Comment by NitramLegov** [comment]
Spontan spricht dagegen, dass der Laser laut Datasheet die Software "Lasercut 5.3" benötigt und als Operating system Support "Windows XP, 7, 8, 10" angibt. Damit wären unsere MacOS und Linux user erstmal raus oder wir müssten einen extra "LaserPC" hinstellen (fände ich blöd)

Wie wichtig ist Laser Klasse 1? Meines Wissens nach benötigen wir einen Laserbeauftragten erst ab Laser Klasse 3. Wäre daher ein Laser der Klasse 2 in Ordnung? Dann könnte zum Beispiel der hier als Alternative angeschaut werden:
https://www.fabcreator.com/fabpro

**Comment by LukasFreeze** [comment]
Also der FabPro hätte auch einen extra PC, nur soll der schon mitgeliefert
werden :-P Mit proprietärer (chinesischer) Software werden wir uns in dem
Preissegment vermutlich anfreunden müssen und einen guten Workaround
finden, aber ich persönlich habe selbst einen Epilog noch nie mit der
Original-Software genutzt...

Vor allem habe ich den FabPro aber nicht vorgeschlagen, weil er immer noch
nicht verfügbar ist und auch noch kein Release festzustehen scheint - wir
sollten aber allerspätestens im April das Gerät bei uns stehen haben, und
dann kann es immer noch sehr knapp werden mit der Einarbeitung vorm
geplanten Workshop.

Der CO2-Laser sollte komplett im Gehäuse gefangen sein (Klasse 1), oft gilt
aber der kleine Ziel-Laserpointer auch bei diesen Geräten als Klasse 2, da
er mit offenem Deckel an bleibt. Wie das beim FabPro sein soll ist mir
leider nicht ersichtlich, aber wenn wirklich der starke Laser nur Klasse 2
hat bräuchten wir einen separaten Raum und Laserschutzbrillen soweit ich
weiß :-/

Nochmal zu Software/PC, vielleicht eine dumme Frage - könnte man da nicht
auch einen Pi dranhängen und den Laser wie eine Art Drucker im Netzwerk
ansprechen? Gibt's "Pi-Windows" und wäre das ansonsten extrem viel Aufwand?

**Comment by Pakue95** [comment]
Trivial ist das sicher nicht, da das wahrscheinlich kein Standard ist was über USB an den Laser geschickt wird. Man könnte mal nachfragen ob die das Protokoll zugänglich machen wollen.

**Comment by NitramLegov** [comment]
**Software Fabcreator:**
Das letzte mal als ich einen der fabcreator Laser gesehen hatte lief der mit CNCjs. Auf dem PC, der da mitgeliefert wird läuft Lightburn. Das ist aus verschiedenen Gesichtspunkten Software seitig besser:
- Der größte Punkt ist, dass es ein mitgelieferter PC ist, den wir einmal einstellen. Wir haben also keinen Stress mit fehlerhaften PC Konfigurationen
- Wir können uns immernoch entscheiden, Lightburn nicht zu nutzen. Lightburn unterstützt effektiv ein paar standard controller. Da bin ich zuversichtlich, dass wir auch andere finden. Ich könnte mir sogar vorstellen, dass der Laser immernoch mit grbl läuft und somit per cncjs angesprochen werden kann :)

Ein pi ist bei dem vorgeschlagenen Laser keine Option, da da maximal Windows on ARM läuft und das nicht binärkompatibel ist.

**Verfügbarkeit Fabcreator**
Falls der Fabcreator in Betracht kommt würde ich die einfach mal anschreiben oder anrufen. Soweit ich das der Website entnehmen konnte müssten die kurz vor Marktstart stehen und anscheinend liefern sie auch schon erste Geräte. Fragen kostet nichts

**Software Laserscript LS6090 **
Dass wir unter Umständen uncoole Software nutzen müssen ist wohl ein Kompromiss, den wir ggf. eingehen müssen. Aber Software, die Mac und Linux User ausschließt sollten wir tatsächlich nur dann einsetzen, wenn wir einen PC zur Verfügung stellen, auf dem die Software dann entsprechend läuft und den diese Leute nutzen können.
_Es gibt wohl Leute, die das Controller Board ersetzt haben. Das könnten wir theoretisch auch. Aber an einem so teuren und ggf. gefährlichen Gerät würde ich nur ungern rumbasteln wollen._

**Laserklasse 2**
Ich habe mal ein paar Infos zum Thema zusammengesucht:
https://www.baua.de/DE/Angebote/Publikationen/Praxis/A37.pdf?__blob=publicationFile

https://www.bghm.de/fileadmin/user_upload/Arbeitsschuetzer/Gesetze_Vorschriften/BG-Vorschriften/bgvb2_Laserstrahlung_BGM.pdf

**Alternative Laser**
Kurze Frage: Was sind die für uns wichtigen Parameter? Dann könnte man da nochmal ein bisschen Recherche betreiben.

**Comment by NitramLegov** [comment]
Noch eine Frage, die mir heute unter der Dusche gekommen ist: Wollen wir wirklich in der aktuellen politischen Lage ein Gerät wie einen Lasercutter aus Großbritannien bestellen?

**Comment by NitramLegov** [comment]
Noch ein Zusatz zur Software bezüglich WINE:
Apple hat mit Catalina den 32 Bit support eingestellt. Aktuell sieht es afaik nicht danach aus, dass wine 32 bit Applikationen auf einem aktuellen Mac ausführen kann. Daher sind Nutzer des aktuellen MacOS auch mit Wine außen vor und auf den dedizierten PC angewiesen.

**Comment by reogaro** [comment]
Wegen den Laserklassen: Der CO2-Laser ist niemals Klasse 1 oder 2. Um damit Schneiden zu können ist ein Klasse 4 Laser benötigt, ich bin mir also ziemlich sicher dass das "Klasse 2" oder "Klasse 1"-Rating nur auf eine kleine Positionierungs-Diode bezogen ist und die CO2-Röhre dank ausreichender Schutzmechanismen diesbezüglich außen vor ist. (Laserklassen: https://www.lasermet.com/resources/classification_overview.php)

**Comment by LukasFreeze** [comment]
Doch, wenn er komplett umhaust ist und es Schutzmechanismen gegen eine
Zündung bei geöffneten Klappen gibt - und das brauchen wir unbedingt bei
öffentlicher Nutzung :-)

**Comment by Pakue95** [comment]
Die Klassen sind während Betrieb beschrieben. Bei den Lasern ist es nicht möglich den CO2 Laser mit offenem Deckel zu betreiben, daher Klasse 1/2.

**Comment by NitramLegov** [comment]
Ich habe heute auch mal die Leute von FabCreator angeschrieben. Sobald ich eine Antwort habe berichte ich natürlich :)

**Comment by NitramLegov** [comment]
Fabcreator hat mir heute eine Antwort gegeben. Der FabPro kommt leider für uns aus preislichen Gründen nicht in Frage. Es würde uns höchstens noch der fabcore bleiben. Das ist halt nur ein 40Watt laser 😕

**Comment by LukasFreeze** [comment]
> Es würde uns höchstens noch der fabcore bleiben. Das ist halt nur ein 40Watt laser 😕
40 W schneiden auch schon einiges, was mich am [FabCore](https://www.fabcreator.com/fabcore) allerdings stört ist die geringe Größe - vor allem höhere Werkstücke kriegt man in so ein Desktop-Gerät einfach nicht rein, für mich kommt das nicht infrage.

> Wollen wir wirklich in der aktuellen politischen Lage ein Gerät wie einen Lasercutter aus Großbritannien bestellen?
Sehe ich nicht so kritisch, natürlich können wir uns aber gerne beeilen und noch vor der nächsten Abstimmung bestellen :-P
Ich habe trotzdem mal mit einem Support-Menschen geschrieben: HPC sucht auch gerade nach einem Vertriebspartner in Deutschland, wenn wir Angst vor komplizierteren Ersatzteilbestellungen haben könnte sich das also sowieso bald erledigen.

Ansonsten habe ich nochmal etwas zum Board nachgefragt, nachdem mir aufgefallen war dass VisiCut auch zwei "HPC"-Profile mit dem LAOS-Board hat: leider wäre das nicht unser Board, die Laserscript-Geräte können mit LEETRO oder Ruida ausgeliefert werden. Letzteres wird auch von [LightBurn](https://lightburnsoftware.com/) unterstützt, was für @NitramLegov ein Argument für die FabCreator-Geräte war. **Findet jemand noch Vorzüge des LEETRO-Boards?**

Zur standardmäßigen "Lasercut 5.3"-Software gabs diese Auskunft:
> 5.3 will run fine with any windows OS from XP to 10. We have customers using it on Mac using parallels and VMWare.
> Best to design on mac, save the files in dxf format and then deliver to the laser machine using a PC running Lasercut 5.3 - just a cheap laptop connected to the machine is fine

Egal wie wir das nachher im Detail lösen können bin ich jedenfalls eher für ein starkes Gerät mit verbesserungsfähiger Software als für ein benutzerfreundliches Spielzeug :-P

Ich habe auch Kontakte zu HPC-Kunden in Deutschland bekommen und werde da als nächstes mal zwei Schulen und einen Makerspace nach ihren Erfahrungen fragen.

Bitte nicht falsch verstehen, ich fokussiere mich deshalb weiter auf meinen Originalvorschlag weil ich ihn immer noch am geeignetsten finde, nicht aus Sturheit ;-) **Wenn jemand weitere [im Rahmen liegende Maschinen](https://github.com/comakingspace/do-something/issues/166#issuecomment-555226974) findet, immer her damit!**

**Comment by NitramLegov** [comment]
@LukasFreeze ich bin völlig bei dir, dass wir lieber ein ordentliches Gerät mit uncooler Software kaufen als ein Spielzeug, das sich aber geil bedienen lässt :)

Kannst du bei HPC nochmal nachfragen, ob die den angedachten Laser tatsächlich mit Ruida Board ausliefern? Und falls ja, mit welchen? Zu LaserCut 5.3 findet man leider nur wenige Informationen. Teilweise scheint es so, dass die Software von Leetro entwickelt wurde, die dann aber natürlich nur ihre eigenen boards als kompatibel angeben:
http://www.leetro.com/english/down/productcatalog2015/Data%20Sheet/Accessories&Software.pdf

Liefert HPC die Geräte mit Ruida Board trotzdem mit LaserCut Software aus?

**Comment by LukasFreeze** [comment]
Dass der angedachte Laser mit beiden Boards kommt war ja schon die erste Aussage, aber ich hab nochmal nachgefragt welche genau und ob Lasercut-kompatibel :-)

**Comment by LukasFreeze** [comment]
Vorm Wochenende gabs noch Feedback zu den Boards, aber dann kam mir der Umzug dazwischen ;-)

- etabliert ist nur das Leetro-Board mit Lasercut 5.3
- Ruida-Boards mit LightBurn oder RD Works als Software-Optionen *sollen* bis Februar verfügbar sein, "wenn die Tests wie erwartet verlaufen"

Februar finde ich - wenns überhaupt klappt - ganz schön spät, da bin ich eher für das erprobte Setup.

**Comment by LukasFreeze** [comment]
Die etablierte Standardausführung gefällt uns - dann kümmere ich mich jetzt als nächstes Mal um ein richtiges Angebot und idealerweise gleich die Bestellung, bin ja eh schon im Kontakt mit HPC :-)
