### ISSUE TITLE
Wasser für die neue Küche

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#167]
Am Wochenende hat @Narquadah bereits die erste Voraussetzung für eine schicke neue Küche geschaffen: eine Wasserleitung unter dem Hallenboden!

![IMG-20191124-WA0005](https://user-images.githubusercontent.com/19755883/69626838-c0b58500-1049-11ea-8d5c-38d5179e27e2.jpg)

Jetzt hätten wir allerdings am liebsten professionelle Hilfe, um diese Leitung auch am Bestand (überm Waschbecken in der Werkstatt) anzuschließen - hat jemand Ideen, wo wir fragen könnten, damit sich das zumindest jemand unverbindlich ansieht oder sogar Arbeitszeit spenden würde (das können wir bescheinigen!)?

- [ ] mögliche Sanitärunternehmen sammeln (ideal sogar persönlich bekannt, dann bitte eine kurze Notiz worüber)
  - [...]
- [ ] nettes Anschreiben verfassen
- [ ] rausfinden, wo der "Haupthahn" für unseren Anschluss in der Werkstatt ist
- [ ] Entscheidung: wollen wir bei der Gelegenheit auch wieder einen Gartenschlauch-Anschluss für draußen? Erfüllt die jetzige seltsame Konstruktion (hoch in die Regenrinne) eine Funktion als Überdruckventil oder kann das weg?

**Comment by LukasFreeze** [comment]
Eine Sanitär-Fachkraft konnte ich bisher noch nicht fragen, habe aber mit unserem Feinmechaniker an der Uni gequatscht und wurde darin bestärkt, das doch einfach selber zu machen.

Also wenn sich nichts cooleres mehr ergibt könnte ich das anbieten sobald ich einen Nachmittag nur dafür freihalten kann, den Haupthahn müssen wir trotzdem ausfindig machen und die Türen (#165 ) sind aber deutlich dringender

**Comment by LukasFreeze** [comment]
Helmuth kennt ein paar Installateure und fragt mal rum, ob uns jemand helfen würde!

**Comment by LukasFreeze** [comment]
Ich sehe gerade, dass hier ein wichtiges Update fehlt das die scheinbare Untätigkeit erklärt 😅
Als ich es Anfang des Jahres selbst angehen wollte wurde klar, dass selbst die Vermieter nicht wissen wo das Wasser abgestellt werden kann...yippieh!

Es muss daher zumindest zum Einfrieren des Rohres eine Fachkraft her, erst wenn wir ein Absperrventil in unseren Räumen haben würde ich irgendwas anderes anrühren. Allzu dringend war das ganze dieses Jahr durch die Küchensperrung natürlich auch nicht mehr.

Naja, jedenfalls gibt es eine neue Entwicklung: eine Kollegin von mir hat einen Onkel, der *vielleicht* helfen würde - schauen wir mal...

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by LukasFreeze** [comment]
Ich würde Bauteile auf 100-200 € schätzen, und nochmal 100 für eine
Fachkraft falls es endgültig nicht über Kontakte klappt.

Also vielleicht 250 als eher pessimistischen Bedarf?

**Comment by Johannes09** [comment]
Also 
Ich habe mich mal ein wenig informiert 
Kosten:
- Rohr-Einfriergerät 45€/Tag  mitfix heidelberg
- Reduzier Stück Verzinkt 3/4x1 Zoll 1,30€ bauhaus
- Rohrnippel 3/4" x 60mm 1,39€ bauhaus
- Kugelhahn 2/4 zoll 10,95€ bauhaus
- HDPE-Übergangsstück 2,95€ bauhaus
Abeitszeit: max. 3h

**Comment by NitramLegov** [comment]
@Johannes09 das klingt gut, Das wären in Summe 61,59€ und ein paar Stunden Aufwand.

https://www.mietfix.de/mietgeraete/rohr-einfriergeraet/
Ich nehme an, dass du dieses Gerät bei mietfix meinst, korrekt?

Selbst wenn wir den üblichen Maker Optimismus einkalkulieren hält sich das ja kostentechnisch in Grenzen. Da finden wir bestimmt Leute, die sich beteiligen / das übernehmen (ich wäre da zum Beispiel mindestens dabei)!

Jetzt stellt sich mir noch die Frage, wer das machen kann. Kann das jemand von uns mit diesem Gerät übernehmen oder brauchen wir da eine Fachkraft? @LukasFreeze @Pakue95 was meint ihr?

**Comment by LukasFreeze** [comment]
Sorry für die späte Antwort, ich hab nochmal bei einer weiteren privaten Option nachgehakt aber das wird wohl auch wieder nichts.

Selbst einfrieren ist mir persönlich zu heikel, was Johannes da gefunden hat ist auf jeden Fall gut wenn es jemanden gibt der sich das zutraut und im Zweifel dafür geradesteht aber ich bin das nicht 🙈

Alles *nach* einem zugänglichen Kugelhahn würde ich machen, aber mit diesem Einfriergerät habe ich noch nie gearbeitet und hätte Angst, damit nichts mehr stoppen zu können wenn das Wasser im schlimmsten Fall erstmal rauscht. Mittlerweile würde ich für diesen ersten Schritt (Steigrohr Einfrieren, altes Rohr durchtrennen, Kugelventil möglichst direkt an unserem Abzweig) lieber jemanden bezahlen und dann erst selbst weitermachen...

Damit wir mal wissen um welche Kosten es da wirklich geht werde ich mal Betriebe raussuchen und anfragen.

Was aber genauso dringend ist und schon auf eigene Faust weiter gebaut werden kann, vielleicht ja beim "do-something day" kommenden Samstag: der Abfluss für die Küche ;-)
Ob ich kommen kann bezweifle ich leider noch, würde aber vorher vorbeibringen was immer ich noch an nützlichen Bauteilen habe...

**Comment by NitramLegov** [comment]
Update: Nach unserer unschönen Erfahrung am Wochenende gibt es jetzt einen neuen Wasseranschluss:
![image](https://user-images.githubusercontent.com/7809163/125335941-6b78d500-e34d-11eb-8396-610df57fbf55.png)

Hier kann es jetzt also weitergehen :)

Was ist denn dann der weitere Plan?

**Comment by LukasFreeze** [comment]
Wir haben gestern ein bisschen überlegt: Johannes, der den Wasserschaden
zugehalten hatte und sich so einen direkten Eindruck vom anliegenden Druck
machen konnte, hat meine Bedenken weitestgehend zerstreut. Außerdem hatte
Kim in weiser Voraussicht sämtliche Verbindungsstellen des Schlauchs in den
zugänglichen Schächten angelegt, wir sollten Lecks also schnell finden
können :-)

Nächster Schritt könnte dann ein direkter Anschluss sein - bräuchte nur ein
paar einfache Verbinder, ich glaub Johannes wollte die holen - und Druck
sollte für die erste Zeit nur unter Aufsicht auf die Leitung gegeben
werden. Klappt das nicht, könnte leicht noch ein Druckminderer nachgerüstet
werden.

**Comment by Pakue95** [comment]
Auf welchen Druck sind den die Kunststoffleitungen ausgelegt? Kann ggf. ein Drucksensor an die Leitung hängen und nachmessen.

**Comment by LukasFreeze** [comment]
Die Leitungen selbst schaffen wohl 12,5 bar (hatte Kim auf slack
geschrieben), das ist sicher genug - ich hatte nur Angst was die
Verlängerungs- und Winkelverbinder angeht

**Comment by LukasFreeze** [comment]
Hier ist in den letzten Wochen ja einiges passiert, ich hab heute nur noch die letzten zwei Meter übernommen :-)

![Uploading IMG_20210811_232322.jpg…]()


Druckminderer auf 2 Bar lässt eine schöne Menge Wasser durch, und die Verbindungen der Kunststoffleitung scheinen bisher alle dicht zu halten. Das hatten @Narquadah und @Johannes09 auch schon mit ordentlich Druckluft getestet 💪

Ohne Aufsicht muss das Wasser aber bitte weiterhin aus bleiben und es gibt evtl nochmal Nacharbeitsbedarf bei den Anschlüssen unter der Küchenspüle. Ich habe da alles mit Hanf statt Teflon überarbeitet, aber jetzt keine Zeit mehr für längere Tests...

Fun fact: dreht man das Ventil in der Werkstatt ab, läuft der Küchenwasserhahn noch gut 5 min nach bis die Leitung leer ist 🙈 dafür ist das Wasser mittlerweile schon klar und scheint trinkbar.

**Comment by LukasFreeze** [comment]
Nicht dass ich wüsste - ich hab mich nur auf unseren Vormieter verlassen
und mal zwei Schlucke probiert, als von der Leitung keine Trübung oder
Geruch mehr zu bemerken war. Nichts belastbares ^^

**Comment by LukasFreeze** [comment]
Dank gebührt übrigens auch @Titan-OX und Anagha fürs Abbauen des alten Druckluftrohres - und wir haben im Schacht zwei seit dem Umzug verschollene Werkzeuge gefunden 😎

**Comment by LukasFreeze** [comment]
Am Freitag war der nächste beaufsichtigte Test erfolgreich, danach haben wir das Wasser gleich angelassen.

Als bis zum nächsten Tag immer noch keine Tropfen sichtbar waren haben @Johannes09 und @NitramLegov die Spülmaschine getestet - auch ohne Probleme - also haben wir ab jetzt Wasser!! 🚀🚿

**Comment by LukasFreeze** [comment]
Nachtrag: der Abfluss hatte noch ein klitzekleines Problem, weil das Rohr ungefähr auf Höhe der Unterkante der Gully-Abdeckplatte endete. Die hat gut was aufgesaugt...

Jetzt geht ein Stück Rohr bis mind. 20 cm unter die Platte und das sollte kein Problem mehr sein! Außerdem habe ich das freiliegende Rohr mit Holzstücken gegen versehentliche Tritte oder groben Kontakt mit Getränkekisten abgeschirmt :-)
