### ISSUE TITLE
Neue Spinde bauen

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#17]
Alle Spinde sind belegt, spätestens jetzt sollten wir die nächsten Spinde bauen.
Moritz und Lukas haben schon ein überarbeitetes Konzept, Material ist auch da. Fehlt nur noch die Umsetzung mit Helfern ;-)

**Comment by NitramLegov** [comment]
Habt ihr das Konzept aufgeschrieben und könnt das hier oder im Wiki mal online stellen?
Wenn alles da ist kann ich da gern helfen.

**Comment by LukasFreeze** [comment]
Moritz hat mir Mittwochabend seine Skizze dagelassen und ich möchte das
auch bald priorisieren - zur Aktualisierung der Projektseite sind wir
leider länger nicht gekommen, darum fürchte ich dass ich dabei sein muss um
den Plan zu erklären :-P

Ich schreib dir mal zur Terminfindung auf Whatsapp...

**Comment by LukasFreeze** [comment]
Wir würden am Donnerstag loslegen, wenn noch jemand an seinen Möbelbaukünsten arbeiten möchte bitte melden ;-)

**Comment by LukasFreeze** [comment]
Wir haben heute alle Teile außer den Türen und Zwischenböden zugeschnitten, geschliffen und an den Kanten etwas mit einem Hobel angefast.

Für den Zusammenbau war leider keine Zeit mehr, die Bretter stehen aber schon an der Stelle wo das ganze nachher hin soll. Moritz' Skizze (mit aktualisierten Maßen, da drei statt vier Spinde breit) liegt oben auf dem blauen Metallschrank.

Nächster Termin TBD - will noch jemand mitmachen?

**Comment by LukasFreeze** [comment]
Ich hätte diesen Freitag (15.6.) wieder Zeit, falls sich jemand zum Mitmachen findet.

**Comment by NitramLegov** [comment]
Wie siehts aus? Finden wir nochmal einen Termin oder einen weiteren Helfer? :)

**Comment by LukasFreeze** [comment]
Ich plane diesen Freitag eine Nachtschicht, falls das jemandem passt :-)

**Comment by NitramLegov** [comment]
Nach der Grillparty?

Von: Lukas [mailto:notifications@github.com]
Gesendet: Dienstag, 24. Juli 2018 14:00
An: comakingspace/do-something <do-something@noreply.github.com>
Cc: NitramLegov <Martin_Vogel@live.com>; Comment <comment@noreply.github.com>
Betreff: Re: [comakingspace/do-something] Neue Spinde bauen (#17)

Ich plane diesen Freitag eine Nachtschicht, falls das jemandem passt :-)

**Comment by LukasFreeze** [comment]
Genau, so ab 10/halb 11 vielleicht?

**Comment by emka** [comment]
Je nachdem wie spät es wird kann ich auch mithelfen.

**Comment by LukasFreeze** [comment]
Ich bin leider nicht mehr ganz fertig geworden nachdem ihr gegangen seid, die Spindeinheit liegt also noch auf dem Boden :-/

Wenn sie im Weg ist kann man sie zu zweit bestimmt aufrichten, zur Fertigstellung fehlt noch ein Stück Rückwand, zwei Zwischenböden und die Türen.

**Comment by LukasFreeze** [comment]
Michael und Mitja haben am Samstag weiter gebaut, nur das mit den Topfscharnieren hat nicht geklappt - die hätten wir ausprobieren sollen bevor wir die Türen zugeschnitten haben, jetzt sind die Türen ca. 1 cm zu schmal und doch wieder mit Klavierbändern befestigt :-P

Als nächstes müssten noch die Schließen (Winkel an der Tür + Lochblech an der Spindinnenwand) fertig gebaut werden, Winkel sind zwar dran aber bei so gut wie allen Türen noch nicht weit genug versenkt.

**Comment by LukasFreeze** [comment]
Update: Topfscharniere können mit "Unterlagen" von ca. 5 mm verwendet werden, ohne dass neue Türen nötig sind (s. Tür von Luzian/Johannes).

Hat da jetzt jemand den Anspruch, überall Topfscharniere zu verbauen? Ali wird nämlich einen der neuen Spinde beziehen und ich wüsste gerne, ob sein Schließblech für das aktuell verbaute Klavierband oder für die schickere Option angepasst werden sollte.

**Comment by NitramLegov** [comment]
Ich würde sagen, dass jeder, der einen Spind bezieht eine Tür bekommt und sich aussuchen kann, ob er die mit Klavierband oder mit Topfscharnier verbaut. Die Möglichkeiten sind ja da.

Dann könnten wir hier auch zumachen ;)

**Comment by LukasFreeze** [comment]
stimmt, es sind dann im Moment noch 3 Spinde frei wenn ich mich nicht irre.

Bevor wir wieder neue auf Vorrat bauen können wir uns erstmal um wichtigeres kümmern, so gefragt wie gehofft sind die Spinde ja doch nicht.
