### ISSUE TITLE
neue Anfahrtsskizze gestalten

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#170]
Ich fänd's cool, wenn wir für die Siemensstraße wieder eine Anfahrtsskizze [wie für den Czernyring](https://wiki.comakingspace.de/File:Map_of_CoMS.png) hätten, um sie auf Websites, Flyer, Plakate etc zu packen :-)

@Pakue95 wie hattest du die damals designed? Gab es dieses schlichte Kartenmaterial schon irgendwo oder musstest du es selbst nachzeichnen?

Auf der letzten Skizze war ja vor allem der Weg um die Baustellen wichtig, vielleicht können wir dieses Mal die verschiedenen [Fußwege von Bus- und Bahnhaltestellen](https://wiki.comakingspace.de/Category:Facilities#Public_Transportation) einzeichnen?

**Comment by Pakue95** [comment]
Hatte einen Screenshot von gmaps in Illustrator nachgezeichnet.

**Comment by Titan-OX** [comment]
I'm working on the design

**Comment by Titan-OX** [comment]
all the major things are done. 
needs proofing

**Comment by NitramLegov** [comment]
Nice. Can you give us something we can proof? :)

**Comment by Titan-OX** [comment]
![Businesscards](https://user-images.githubusercontent.com/22505956/77236108-93be4c80-6bbb-11ea-8974-432026b890e4.png)

**Comment by LukasFreeze** [comment]
Danke! Ich finds schon sehr schick. Die Ausrichtung hat mich kurz
irritiert, aber ist natürlich gut die Fläche so effektiv zu nutzen :-)

Zwei Vorschläge hätte ich trotzdem noch:
- kann Kompass-Pfeil vielleicht etwas größer und in einer der sowieso
verwendeten Farben gezeichnet werden?
- passen die Namen der Haltestellen noch jeweils daneben ohne dass es
unübersichtlich wird, vielleicht sogar kleine Kringel mit den Bahn- und
Buslinien?

**Comment by NitramLegov** [comment]
My two cents:
Allgemein finde ich dir Karte auch gut :) Einige Vorschläge habe ich dennoch auch:
- Ich würde die Karte gerne nach Norden ausgerichtet sehen. Meiner Meinung nach wiegen die Irritationen den geringeren Platzbedarf nicht aus. Muss man aber ausprobieren
- Die drei verschiedenen Wege wären denke ich in unterschiedlichen Farben cool. Dann kann man ja in die Ecke in der jeweiligen Farbe schreiben "Ab Ochsenkopf", "Ab Pfaffengrund/Wieblingen", etc :)

**Comment by Titan-OX** [comment]
![V2](https://user-images.githubusercontent.com/22505956/78686521-6da2e700-78f3-11ea-9886-19b12c6b9f77.jpg)
Die Farben heben die haltestellen namen noch mal von den straßennamen ab, war eine gute idee @NitramLegov

**Comment by LukasFreeze** [comment]
Sieht super aus :-)

**Comment by NitramLegov** [comment]
Ich finds auch gut, Danke dir!
Kannst du die SVG zur Verfügung stellen?

**Comment by Titan-OX** [comment]
do we still want arrows?

**Comment by NitramLegov** [comment]
Arrows? What for? I like it the way it is :)

**Comment by Titan-OX** [comment]
![image](https://user-images.githubusercontent.com/22505956/79462707-2c4bbf00-7ff8-11ea-8d09-7e033f14e2a8.png)
like this?

**Comment by Titan-OX** [comment]
GitHub doesn't take .svg so I Uploaded it to the wiki. the shadow effect on the buildings is gone because the buildings would have been rasterized, but it wasn't very viable to begin with 
https://wiki.comakingspace.de/images/c/c7/Businesscard_Map.svg

**Comment by Titan-OX** [comment]
![Businesscard_map](https://user-images.githubusercontent.com/22505956/79465368-88fca900-7ffb-11ea-8647-eb6e1e21bfcb.png)

**Comment by NitramLegov** [comment]
Added to GitHub: https://github.com/comakingspace/CommonFiles/blob/master/Printouts/Businesscard_Map.svg

Or, if you want to display it, use the raw link:
https://raw.githubusercontent.com/comakingspace/CommonFiles/master/Printouts/Businesscard_Map.svg


I liked the version without arrows better though :)

**Comment by Titan-OX** [comment]
I can also upload a version without them. They were really fiddly to get in because affinity only supports arrows at the tips of curves. So the arrows are text with an arrow font.
Also the buildings lost their opacity rendering them lighter.

**Comment by LukasFreeze** [comment]
I also like it better without the arrows, looks cleaner :-)

**Comment by Titan-OX** [comment]
https://github.com/comakingspace/CommonFiles/blob/master/Printouts/Businesscards%26Flyers/Businesscard%20Arrowless.svg

**Comment by LukasFreeze** [comment]
Besten Dank @Titan-OX , ich mach dann mal zu :-)

**Comment by NitramLegov** [comment]
Wisst ihr, was ein wenig peinlich ist?

Auf der neuen Anfahrtsskizze ist die falsche Postleitzahl vermerkt und keiner hats gemerkt 😳😅

@Titan-OX kannst du das ändern? Die richtige Adresse der Werkstatt ist:

Siemensstraße 40
69123 Heidelberg

**Comment by Titan-OX** [comment]
Kann ich machen

**Comment by NitramLegov** [comment]
@Titan-OX Hattest du schon die Gelegenheit, hier etwas zu machen?

**Comment by Titan-OX** [comment]
[Businesscards.pdf](https://github.com/comakingspace/do-something/files/8142560/Businesscards.pdf)
willst du noch andere Formate haben? und wohin kann ich es in der nextcloud hochladen?

**Comment by Titan-OX** [comment]
Ich hab garnicht gemerkt das es die vektoren im pdf gerastert hat. Sollte jetzt besser sein (nicht mehr als pdf)

**Comment by NitramLegov** [comment]
Sweet, Danke!

Bei der Version mit Pfeilen sind aus den Pfeilen sind jetzt kleine "N" geworden 🙈
https://raw.githubusercontent.com/comakingspace/CommonFiles/master/Printouts/Businesscards%26Flyers/Businesscard_Arrows.svg

**Comment by Titan-OX** [comment]
Yes and no. On my PC it looks just fine but not on my phone

**Comment by Titan-OX** [comment]
https://github.com/comakingspace/CommonFiles/tree/master/Printouts/Businesscards%26Flyers
fixed it with curves only versions so it should be font independent 
https://raw.githubusercontent.com/comakingspace/CommonFiles/master/Printouts/Businesscards%26Flyers/Businesscards%20arrows%20converted%20to%20curves.svg
