### ISSUE TITLE
Tor 4 Workshopvorbereitung - Urban Gardening 

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#172]
tl;dr: Die Tor 4 Workshops stehen an. Ihr könnt helfen. Bei Fragen meldet euch bei Keno/Lukas/Martin

Wie ihr alle mitbekommen habt und wie es auch letzte Woche im Plenum erwähnt wurde haben wir eine Förderung bekommen, um im ersten Halbjahr 2020 einige Workshops durchführen zu können.

Einer dieser Workshops ist "Urban Gardening"

**Worum geht es im Workshop?**
Im innerstädtischen Bereich haben viele Menschen heutzutage leider keinen Garten mehr und dadurch nicht mehr die Freiheit, zumindest einen Teil ihrer Kräuter oder ihres Gemüse selbst anzubauen. Viele haben allerdings einen (wenn auch manchmal kleinen) Balkon, der dafür genutzt werden kann.
Im Workshop wollen wir ein System bauen, mit dem man auf dem Balkon Pflanzen in der vertikalen anbauen kann. Im Anschluss wollen wir die Möglichkeiten von Urban Gardening und Vertical Farming diskutieren. 
Wann der Workshop stattfindet ist gerade in der letzten Abstimmung, ich update dann das issue entsprechend.

**Was ist der (grobe) Plan?**
Der Workshop wird zwei Tage gehen.
Am ersten Tag werden wir Anfangs mit den Teilnehmenden das oben genannte System bauen. Das wird aus Holz gebaut und somit größtenteils in der Holzwerkstatt stattfinden. Wir werden Bretter zusammensägen, schleifen, einölen/anmalen, etc.
_Falls wir genug Helfer haben könnten wir noch ein platzsparenden Regalsystem für die angebauten Lebensmittel bauen (Stichwort Jar Jar Shelf)_

Anschließend werden wir im Gemeinschaftsraum eine offene Diskussionsrunde haben, an der mehr Leute teilnehmen können als am praktischen Teil morgens. Themen / Fragestellungen _könnten_ sein: Was ist Vertical Farming?
Welche Bedeutung wird es für die Gesellschaft haben? 
Welchen Einfluss hat die Urbanisierung auf die Gesellschaft und die Freiheit des einzelnen?
Welche Auswirkungen hat das fehlen privater Gärten jetzt schon auf die Natur und die Gesellschaft (Stichwort Bienensterben und so?) Was kann man dagegen tun?
_Könnten_ deswegen, weil ja vielleicht noch jemandem etwas einfällt :)

**Wie kann man helfen?**
Im Prinzip braucht es noch Helfer für alles. Die folgende Aufgabenverteilung kann als erster Wurf dienen:
- Planung / Vorbereitung
- [ ] Redner/Moderatoren suchen für Diskussionsrunde
- - ggf. kann @Chris0812 etwas zum Thema Pilzzucht sagen.
- - @LukasFreeze hat mal nachgefragt, ob es seitens BASF Möglichkeiten gibt
- - Ich kann allgemein etwas zum Thema "Vertical Farming" und "Urban Gardening" erzählen
- [ ] Themen der Diskussionsrunde festzurren
- [ ] Poster erstellen zur Plakatierung in Heidelberg (Diskussionsabend)
- [ ] [Eventbrite-Seite](https://www.eventbrite.de/e/you-can-make-it-handwerk-fur-alle-urban-gardening-tickets-93544125999) zur Anmeldung erstellen (Kursteil)
- - Liegt aktuell bei @LukasFreeze, der hier schon aktiv ist :)
- [ ] Eventseite(n) zum Diskussionsabend erstellen und bewerben
  - [ ] [Facebook](https://www.facebook.com/events/170825464253368/)
  - [ ] Meetup
  - [ ] [Eventbrite](https://www.eventbrite.de/e/diskussionsabend-urban-gardening-tickets-99090206475)
  - [ ] ....
- [x] Baupläne detaillieren
- [x] Testbau durchführen und genauen Materialbedarf ermitteln
- [x] Wiki Seite erstellen (auf deutsch)
https://wiki.comakingspace.de/Urban_Gardening_Workshop
- [x] Praktischen Workshopteil detaillieren

- Am Workshop Tag selbst
- [ ] Sägenstation betreuen (falls wir einzelne Betreuer brauchen)
- [ ] Bohr & Schraubstation betreuen (falls wir einzelne Betreuer brauchen)
- [ ] Schleifstation betreuen (falls wir einzelne Betreuer brauchen)
- [ ] Einweisungen geben in die verwendeten Werkzeuge
- [ ] Gäste betreuen, die zum schauen vorbeikommen

Helfer für den Workshop Tag sind bisher:
- Rolf
- Patrick
- Johannes
- Ich natürlich :)

Falls ihr flexibel helfen wollt sagt am besten mir Bescheid, wir finden etwas sinnvolles für jeden :)
Ein Hinweis noch: Es wird noch zwei weitere Workshops geben. Diese werden von Keno und Lukas geplant. Falls ihr da helfen wollt sagt am besten einem der beiden Bescheid.

**Comment by LukasFreeze** [comment]
Sollen wir den praktischen Teil mit diesem Text ankündigen?

> Im innerstädtischen Bereich haben viele Menschen heutzutage leider keinen Garten mehr und dadurch nicht mehr die Freiheit, zumindest einen Teil ihrer Kräuter oder ihres Gemüse selbst anzubauen. Viele haben allerdings einen (wenn auch manchmal kleinen) Balkon, der dafür genutzt werden kann.
Im Workshop wollen wir ein System bauen, mit dem man auf dem Balkon Pflanzen in der Vertikalen anbauen kann. Im Anschluss wollen wir die Möglichkeiten von Urban Gardening und Vertical Farming diskutieren.

Fehlt noch was, oder sollte etwas geändert werden?

**Comment by LukasFreeze** [comment]
Ich hatte ja versprochen, noch Fotos von meiner "vertikalen Farm" rauszusuchen - vielleicht sind die noch nützlich für die PR des allgemeinen Teils? @LarsKumbier fürs Poster (#173) zum Beispiel?

![IMGP4980](https://user-images.githubusercontent.com/19755883/75518441-32162280-5a01-11ea-9d37-d2767b01580d.JPG)

![IMGP4981](https://user-images.githubusercontent.com/19755883/75518449-35111300-5a01-11ea-8cd3-bcd9f929f952.JPG)

Den Hintergrund sollten wir vielleicht irgendwie unschärfer machen, man kann zwar nicht wirklich in die Fenster gucken aber es lenkt auch einfach ab...

**Comment by LukasFreeze** [comment]
Gibt es schon etwas spruchreifes zum Abendprogramm, um da etwas ankündigen zu können?

**Comment by Chris0812** [comment]
Heyhey, 
Sieht gut aus. Habe nur leider kein lebendiges Anschauungsmaterial da aber für ne PPP mit Bildern hätte ich Kapazitäten ;) 

Am 2. März 2020 19:46:37 MEZ schrieb Lukas <notifications@github.com>:
>Gibt es schon etwas spruchreifes zum Abendprogramm, um da etwas
>ankündigen zu können?>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/comakingspace/do-something/issues/172#issuecomment-593556210

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by LukasFreeze** [comment]
Ich habe den ["Diskussionsabend" auf FB](https://www.facebook.com/events/170825464253368/) jetzt mit einem Ausschnitt von [Patricks Poster-Enwurf](https://github.com/comakingspace/CommonFiles/blob/master/Posters/Tor4-2020/Tor4-Vertical_Farming.jpg) bebildert mit diesem kurzen Text versehen, kann gerne noch korrigiert werden...aber da musste endlich was hin:

> Interessiert ihr euch für Gärtnern auf kleinstem Raum? Dann kommt vorbei und diskutiert mit Gleichgesinnten und Vortragenden zu Themen wie...
> - Vertical Farming
> - Pilzzucht im Wohnzimmer
> - Nachhaltigkeit und Bienenschutz
> - Automatisierung - Möglichkeiten und Grenzen
> 
> Der Eintritt ist frei und verdursten muss auch niemand!

**Comment by NitramLegov** [comment]
Nachdem die anderen Veranstaltungen jetzt geplant sind möchte ich auch diese gerne wieder Planungstechnisch angehen.

Allerdings bin ich der Meinung, dass diese Veranstaltung so wie sie bisher geplant war zur aktuellen Jahreszeit nicht sinnvoll ist. Für die Veranstaltungen haben wir Zeit bis Ende März, das halte ich auch für einen guten Zeitpunkt, um die Veranstaltung durchzuführen (da wird langsam wieder warm und die Leute denken wieder an ihren Balkon).

Daher folgende Terminvorschläge:
Samstag und Sonntag, 6. & 7. März 2021
Samstag und Sonntag, 20. & 21. März 2021

Was meint ihr dazu?

**Comment by ErikSchatz** [comment]
Hallo Martin,

persönlich würde ich den späteren Termin vorziehen.

 

VG, Erik

 
 

Gesendet: Samstag, 10. Oktober 2020 um 14:36 Uhr
Von: "NitramLegov" <notifications@github.com>
An: "comakingspace/do-something" <do-something@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: Re: [comakingspace/do-something] Tor 4 Workshopvorbereitung - Urban Gardening (#172)


 

Nachdem die anderen Veranstaltungen jetzt geplant sind möchte ich auch diese gerne wieder Planungstechnisch angehen.

Allerdings bin ich der Meinung, dass diese Veranstaltung so wie sie bisher geplant war zur aktuellen Jahreszeit nicht sinnvoll ist. Für die Veranstaltungen haben wir Zeit bis Ende März, das halte ich auch für einen guten Zeitpunkt, um die Veranstaltung durchzuführen (da wird langsam wieder warm und die Leute denken wieder an ihren Balkon).

Daher folgende Terminvorschläge:
Samstag und Sonntag, 6. & 7. März 2021
Samstag und Sonntag, 20. & 21. März 2021

Was meint ihr dazu?

**Comment by LukasFreeze** [comment]
Ich finde den März auch auf jeden Fall sinnvoller als ein Garten-Thema in
den Winter zu quetschen :-)

Ob der spätere Termin noch früh genug ist sollten wir aber nochmal mit
Anita von Tor 4 besprechen, "Ende März" hieß glaube ich nicht dass wir bis
zum 31. Zeit haben und ist sowieso als "gerade noch in Ordnung" gedacht
soweit ich weiß, also würde man sich dort sicher über den früheren Termin
freuen.

**Comment by NitramLegov** [comment]
Alles klar, dann machen wir das so.

Die Termine waren nicht als entweder-oder gedacht sondern ich würde gerne beide Termine anbieten.

Prioritätsseitig würde ich dann aber mit der Argumentation von @LukasFreeze den ersten Termin mal höher stufen.

@LukasFreeze Kannst du mit Anita klären, ob der Termin 6. & 7. März für sie in Ordnung ist? :)

**Comment by LukasFreeze** [comment]
Hab gefragt - es sind doch noch beide Termine im Rahmen :-)

**Comment by LukasFreeze** [comment]
Hier wird es langsam richtig dringend: wir brauchen als absolutes Minimum zwei Wochen Vorlauf, lieber drei, um die Veranstaltung auch bewerben zu können - und es kommen nur noch Juli und August infrage, bevor die BASF-Förderung in die nächste Runde geht und alles alte abgeschlossen sein sollte 😱 

@NitramLegov weißt du schon, welche Termine von dir aus gehen könnten?

**Comment by NitramLegov** [comment]
Sorry, ich hatte nicht auf den Schirm, dass das zwingend spätestens im August sein muss. Macht aber Sinn.

Ich kann am 14./15. Und am 21./22. :)
Das können wir so ins Auge fassen

**Comment by LukasFreeze** [comment]
Beide Termine? 😍
Ich bin am 14./15. verplant, beim zweiten WE könnte ich vielleicht helfen. Und vorher natürlich!
Sollen wir die Diskussionsrunde an einen der Workshop-Tage anschließen lassen oder lieber einzeln?

**Comment by LarsKumbier** [comment]
Würde ich direkt anschließen - die Leute sind dann ja direkt da. Wird es eine vor-Ort-Veranstaltung oder virtuell?

**Comment by NitramLegov** [comment]
Das klingt doch auch schonmal gut.
@ErikSchatz wie sieht es denn bei dir aus? Wärst du hier dabei? Und welcher termin würde bei dir besser passen (ist ja beides in den Sommerferien)?

**Comment by ErikSchatz** [comment]
Hallo,wenn es mit Corona nicht zu schlimm wirdbin ich da an der Atlantik-Küste vonSüdfrankreich. VG, Erik-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

**Comment by LukasFreeze** [comment]
Diese Termine werden es jetzt wohl:
- Workshop 21. & 22.8., *tagsüber* (TBD)
- Diskussionsabend 21.8., 16-20 Uhr

Ich würde damit als nächstes die abgesagten Eventbrite-Seiten wiederbeleben, die wir dann der BASF weitergeben und ordentlich bewerben müssen. @NitramLegov sitzt auch schon an einer Aktualisierung des [Posterentwurfs](https://github.com/comakingspace/CommonFiles/blob/master/Posters/Tor4-2020/Tor4-Vertical_Farming.pdf), soweit ich weiß :-)

offene Fragen, bestimmt kommen aber noch mehr:
- wer hilft vor Ort alles mit - Tageweise, stundenweise oder durchgängig?
  - @NitramLegov durchgängig (oder?)
  - @LukasFreeze durchgängig
  - @khaos8rood hatte auf slack Interesse angemeldet - auch an diesem Termin?
  - ...?
- nutzen wir wieder die kostenlose Plakatierungsoption auf den "Kultursäulen" der Stadt oder zahlen wir für eine kleine Kampagne? Etwas Budget wäre dafür eingeplant, muss aber natürlich auch jemand organisieren können.
- welche besonderen Gäste (mit Vorträgen) können wir abends einladen? Gibt es da noch tiefergehende Planungen vom ursprünglichen Termin @NitramLegov ?
- welche Organisationen/Netzwerke könnten wir zusätzlich kontaktieren, um viele Interessierte zu erreichen?
- soll der Diskussionsabend vor Ort, virtuell oder (trotz aller Probleme beim letzten Mal) hybrid stattfinden? Wer könnte die technische Seite in den beiden letzteren Fällen übernehmen?

**Comment by NitramLegov** [comment]
Workshop hat erfolgreich stattgefunden
