### ISSUE TITLE
Tor 4 Workshopvorbereitung: Upcycling

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#175]
Auch von mir schonmal kurz ein Umriss des dritten geplanten "Tor 4"-Workshops - wenn ihr euch hier nicht so im Thema fühlt oder keine Zeit habt, aber gerne helfen würdet das Gesamtprojekt erfolgreich werden zu lassen, schaut mal bei Martins (#172) oder Kenos (#174) Planungen rein :-)

**Wann?** 
Wochenende 17./18. Oktober ODER 31. Oktober/1. November - je nachdem, was mehr Helfern passt!

- Kurs (begrenzte Plätze) Sa 10-16 Uhr, So 10-14 Uhr
- Diskussionsrunde (offener) Sa 16-20 Uhr

**Was?**
- Paletten zu Bilderrahmen und/oder Kistchen machen
  - auseinandernehmen, Metall restlos entfernen
  - Hobeln/Anschleifen (je nach Geschmack)
  - Sägen/Fräsen/ggf bohren
  - Leimen/Oberflächenbehandlung
- *evtl. Schneidebrettchen aus Restholzstreifen*
  - Sägen, Abrichten, Leimen, Hobeln
  - Oberflächenbehandlung
- *evtl. Flaschenschneider*
  - müsste erst gebaut werden, kann dann aber als nettes "Warteprogramm" dienen um Stau an den Großgeräten zu vermeiden

**Wie könnt ihr euch einbringen?**
- vor, während oder nach dem Kurs in der Werkstatt helfen, z. B. "Stationen" betreuen
- Ideen einbringen
- einen Vortrag vorbereiten
- oder zum Beispiel:

- [ ] Anmeldungsseite erstellen
   - [ ] kurzer, aber deskriptiver Text, was wir tun werden
- [ ] Helfer finden!
- [ ] Material besorgen
   - Paletten
   - evtl. auch etwas Hartholz, *falls es irgendwo als Rest anfällt*
- [ ] angedachten Kurs durchtesten, ggf fehlendes Werkzeug besprechen & einkaufen
- [ ] Poster & weitere PR

sagt bitte Bescheid (hier oder per Mail) wenn ihr Bock habt mitzumachen, dann können wir das Ganze im Team weiterplanen!

Neben dem praktischen Teil gilt es auch noch einige Gedanken in den Samstagabend zu stecken, vielleicht wird das noch ein eigenes "Issue":
- [ ] **Diskussionsrunde & Vorträge planen, Redner finden**

**Comment by LukasFreeze** [comment]
Simon und ich werden am **14.3. ab 13 Uhr** im Space sein um einen Bilderrahmen-Testbau zu machen und andere Vorbereitungen anzugehen.

Wir würden uns sehr über weitere Mitstreiter freuen!

**Comment by LukasFreeze** [comment]
Sooo....nach dem Shutdown muss es auch hier bald wieder weitergehen!

Wer möchte mitmachen, und welcher dieser Termine passt euch besser: 17./18. Oktober oder 31. Oktober/1. November?

**Comment by ErikSchatz** [comment]
Ich kann mitmachen, als Helfer oder Teilnehmer. Der erst Termin ist vielleicht nicht so "kalt", wobei das bei weniger  "körperlichen" Workshops wichtiger wäre.

**Comment by LukasFreeze** [comment]
Als Helfer bitte! Cool dass du mitmachst :-)

Als Teilnehmer wollen wir mit der Kursreihe ja Anfänger von außerhalb
erreichen, die (bisher) mit "Making" und Handwerk noch nichts am Hut haben
- als Helfer musst du aber trotzdem noch nicht alles vorher können, das
genaue Projekt entwickeln und lernen wir bald gemeinsam ;-)

**Comment by LukasFreeze** [comment]
Der Frästisch sollte startklar sein, fehlt "nur noch" die Abrichte und wir können den Ablauf proben :-)

**Comment by LukasFreeze** [comment]
Der frühere Termin passt mir jetzt leider doch nicht, da ich dann jemanden im Labor einlernen muss und wieder kein richtiges Wochenende hab 🙈

Dann läuft es also auf den 31.10. und 1.11. hinaus, haltet euch das bitte frei! Ich assigne mal alle, die sich hier oder via slack gemeldet hatten :-)

**Comment by LukasFreeze** [comment]
hiervon werden wir im vorgegebenen Zeitraum wohl leider doch keine weiteren Wiederholungen mehr schaffen.
