### ISSUE TITLE
neue Kappsäge

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#178]
Die Herkules-Kappsäge gibt gerade den Geist auf - vermutlich ein Problem mit den Kohlebürsten?

Für die Tor-4-Kurse brauchen wir eine anständige, aber zum Glück haben wir dadurch auch Mittel für eine Neuanschaffung :-)

Es gibt wohl eine interessante Option mit Gelenkarm statt Gleitschienen von Bosch, @Pakue95 weiß mehr dazu!

**Comment by NitramLegov** [comment]
Ich nehme an, dass die Option von @Pakue95 die Bosch GCM 12 GDL ist:
https://www.bosch-professional.com/de/de/products/gcm-12-gdl-0601B23600
Dazu gibt es hier einen Erfahrungsbericht: https://www.dds-online.de/technik/maschinen-anlagen/kappsaege-im-haertetest/

Simon hat in Telegram erwähnt, dass er ggf. eine Bosch GCM 8 SJ als Dauerleihgabe hat. Da müssen wir aber nochmal nachfragen, welche er genau hat.
Es gibt die GCM 800 SJ: https://www.bosch-professional.com/de/de/products/gcm-800-sj-0601B19000
Oder die GCM 8 SJL: https://www.bosch-professional.com/de/de/products/gcm-8-sjl-0601B19100

Zum besseren Vergleich starte ich mal eine kleine Tabelle:
| Gerät  | Herstellerlink | Preis (inkl. Link) | Leistung | Sägeblatt | Besonderes |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Bosch GCM 12 GDL  | [Bosch](https://www.bosch-professional.com/de/de/products/gcm-12-gdl-0601B23600) | [721,97 (inkl. MwSt)](https://www.bueromarkt-ag.de/kapp-gehrungssaege_bosch_gcm_12_gdl_paneelsaege,p-0601b23600,l-94511215,pd-b2c.html?vpid=aed84065d16ba0eca875da316f0a7ab7) | 2000W |  305mm | Gelenkarm (Platzsparend!)

**Comment by simonRednas** [comment]
Den Bildern nach zu urteilen ist es weder die GCM 800 SJ noch die GCM 8 SJL.
Es steht nur "GCM 8SJ" drauf. Sie schafft leider nur 8 cm Sägetiefe, hat mich aber noch nie im Stich gelassen. Die kann ich definitiv als Leihgabe einbringen.

Passend dazu hätte ich noch den Arbeitstisch [GTA 3800](https://www.bosch-professional.com/de/de/products/gta-3800-0601B24000)

**Comment by Pakue95** [comment]
Sehr cool dass du die Säge zur Verfügung stellen willst! Ich persönlich fände es trotzdem sinnvoll, wenn der Space eine *eigene* besitzen würde da die Kappsäge zu den häufiger genutzten Geräten in der Werkstatt gehört; besonders wenn wir jetzt das Funding dafür hätten. Es kann ja immer mal passieren, dass du deine wieder Zuhause brauchst. 
    Ggf könnte man deine Kapsäge auch auf die Leihliste im Wiki packen, damit sich andere Mitglieder bei dir melden können falls mal ein Schnitt Zuhause gemacht werden muss?

Wir haben die *Bosch GCM 12 GDL* mal ins Visier genommen, da man durch den Gelenkarm die Säge praktisch ganz an die Wand stellen kann, ohne den Arbeitsraum einzuschränken. Das bietet sich ganz gut an so wie momentan die Kappsägen-Station gelegen ist.

Zudem wäre die Hoffnung, dass die Gelenke auf lange Sicht besser den Staub und Schmutz in der Werkstatt aushalten als die Linearführungen von den anderen Modellen. Zumindest bei den grünen Maschinen von Bosch sind die nicht gut gegen Staub abgedichtet und blockieren dann.

**Comment by LukasFreeze** [comment]
Also ich finde die GCM 12 GDL mit Gelenkarm auch sehr interessant, aber nach dem aktuellen Stand bin ich noch nicht überzeugt da @NitramLegov verlinkter Testbericht letztlich negativ ausfällt :-(

Findet jemand noch andere Beurteilungen zu diesem Gerät?

**Comment by Pakue95** [comment]
Martin und ich waren am Samstag bei OBI und haben uns die Säge vor Ort angeschaut. Soweit wie wir das beurteilen konnten sieht die 12 GDL ganz vernünftig aus. Lediglich die Tiefe der Säge darf man nicht unterschätzen und die Gehrungsarretierung ist etwas schwergängig.

**Comment by NitramLegov** [comment]
Ähnlich wie Patrick finde ich, dass es sinnvoll ist, wenn der Space tatsächlich eine eigene Kappsäge besitzt. Zumal ja aktuell das Funding für Geräte, die wir für die Workshop brauchen vorhanden ist.

Da wir beim Vor-Ort Test erstmal nichts negatives entdecken konnten bin ich dafür, dass wir die Säge mit Gelenkarm kaufen. Gibt es da Gegenstimmen? :)

**Comment by hubirolf1** [comment]
Habt ihr euch schon mal die Kapex 120 von Festol angeschaut?  Mit diesem Gerät arbeiten die Profis zum Beispiel Laden Bauer  / Schreiner.  Ok der Preis dafür ist schon höher als für die Bosch aber die Qualität sicher auch. Gerne kann ich bei Interesse aus meiner privaten Werkstatt die Maschine einmal mitbringen und erklären. Ein paar probeschnitte in Holz oder Aluminium sagen mehr als 1000 Worte.

**Comment by Pakue95** [comment]
Angeschaut ja, aber funktionell ist mir kein Grund aufgefallen, der den höheren Preis rechtfertigt. Sind halt auch nochmal 400-500€ mehr, die man ggf in andere Tools stecken kann. Wenn du deine mal mitbringen kannst schaue ich mir die dennoch gerne mal an.

**Comment by hubirolf1** [comment]
Bist du Freitag im Space? Ich habe vor zu kommen und würde die Maschine dann mitbringen. 


Gesendet mit meinenm iPad

Am 20.02.20 um 18:39 schrieb Patrick

> Angeschaut ja, aber funktionell ist mir kein Grund aufgefallen, der den höheren Preis rechtfertigt. Sind halt auch nochmal 400-500€ mehr, die man ggf in andere Tools stecken kann. Wenn du deine mal mitbringen kannst schaue ich mir die dennoch gerne mal an. - You are receiving this because you commented. Reply to this email directly or view it on Gi

**Comment by Pakue95** [comment]
Jap, bin da

**Comment by Pakue95** [comment]
Wir haben uns am Freitag die Kappex von Rolf angeschaut. Sehr cooles Gerät mit vielen nice-to-have Funktionen. Danke fürs Vorbeibringen!

Dennoch haben wir uns jetzt für die Bosch entschieden, weil die größeren Schnittmaße und der deutlich günstigere Preis sich für unseren Einsatzzweck als Kappsägenstation besser eignen.

Martin und ich waren gestern beim Bauhaus und haben die Bosch bestellt und sollte nächste Woche dann aufschlagen. Bis dahin können wir uns ans Comissioning machen - hierzu bald ein ein neues Issue.
