### ISSUE TITLE
Laser-Abluftfilter bauen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#179]
Ohne Filter sollte **noch nichts**, außer vielleicht mal Papier oder leimfreies Holz während Tests im Beisein eines Geschäftsführers, im Laser bearbeitet werden.

*(aus #166:)*

*Zur Abluftfilterung könnten wir anstelle [dieses Filterschranks](https://hpclaser.co.uk/p/bofa-ad500-laser-fume-filter/) von HPC, den wir uns nicht unbedingt leisten können, über einen Eigenbau nachdenken. Die Absaugung ist schon im Lasercutter integriert, wir bräuchten also nur eine abgedichtete Box mit Filtermedien wie sie das [Fablab Neuenstadt gebaut zu haben scheint](https://www.fablabs.io/machines/sabko-6040). Die sollten wir dann einfach mal nach Erfahrungen und Bauplänen fragen!*

Ich kann mindestens das Holz beisteuern! Erstmal rumfragen finde ich immer noch sehr sinnvoll, es gibt auch bestimmt noch weitere Eigenbauten in der Community :-)

Wie "smart" wir das Ding machen wollen (Durchflussmessung o.ä.?) ist erstmal eine Zeitfrage, spätestens zum Tor-4-Kurs im Mai muss der Laser laufen -> #174

**Comment by LukasFreeze** [comment]
Hab mal eine Mail nach Neuenstadt geschickt :-)

**Comment by LukasFreeze** [comment]
Natürlich haben manche Leute ihre Eigenbau-Luftfilter auch schon online dokumentiert, ich starte hier mal eine Liste (editiert gerne diesen Kommentar für mehr Details oder weitere Funde!)

- https://laser-engravers.de/forum/thread/5723-absaugung-eigenbau/
- https://m.heise.de/make/artikel/Rauchreinigungsanlage-fuer-Lasercutter-4110578.html?seite=all
- https://wiki.shackspace.de/infrastruktur/fablab/lasercutter/abluft
- https://wiki.fablab.fau.de/technik/lasercutter#baustelleluftfilter-selber-bauen

**Comment by LukasFreeze** [comment]
Da der Bot gerade tot ist - kleines Update ;-)

Hab meine Recherchen im letzten Post nochmal etwas erweitert und durchkommentiert!

**Comment by Johannes09** [comment]
So ungefähr würde ich die Abaugung bauen. 
Bauteit >2wochen 
Kosten >250€
Grobe Skizze: 
![2020_02_28_050921](https://user-images.githubusercontent.com/22060480/75564790-120c5080-5a4d-11ea-96b1-b552d6c64715.png)

**Comment by LukasFreeze** [comment]
Huch, warum zwei Filtersätze? Das erschwert doch eher die Wartung, oder übersehe ich den entscheidenden Vorteil?

Ich habe bisher so etwas im Kopf, Maße und damit Kosten kann ich ohne die mitgelieferte Absaugung gesehen/vermessen zu haben aber noch nicht abschätzen:

![IMG_20200229_102259](https://user-images.githubusercontent.com/19755883/75606746-3b31ed00-5af0-11ea-9695-c1428f64efdf.jpg)

Woraus setzen sich denn deine 250 € zusammen?

**Comment by LukasFreeze** [comment]
noch kurz ein paar Erkenntnisse von gestern:
- der Lüfter zieht ganz gut, allerdings erst wenn er Widerstand hat - "Standby-Modus" kann leicht für schlechte Saugleistung gehalten werden
   - leider wissen wir nicht, *wie viel* Saugleistung er hat
- @Johannes09 hat davon abgeraten den Lüfter um 90° gekippt einzubauen, was einen schlankeren Filterturm wie in meiner Skizze ermöglichen würde - um die Lager zu schonen würde das Gerät also seitlich rausstehen (auch nicht weiter schlimm)
- ich hätte Holz für ein Gehäuse von 44x45.5x98 cm oder 39x41x125 cm, genaue Maße würden sich aus den Dimensionen der gewählten Filter herleiten

**Comment by LukasFreeze** [comment]
Ach ja, hier kaufen die Neuenstädter ein: https://htm-filtershop.de/

"Grobfilter" in meiner Zeichnung würde hier wohl einem Taschenfilter entsprechen :-)

Langsam hätten wir dann alles beisammen, um eine Einkaufsliste zusammenzustellen, oder? Falls jemand Zeit hat, zueinanderpassende Teile zu recherchieren, immer her damit!

**Comment by NitramLegov** [comment]
Aus gegebenem Anlass treffen wir uns morgen, 22.03.2020 um 15 Uhr im whereby. Falls jemand dazustoßen möchte: Der Link steht in der Telegram Gruppe.

**Comment by Pakue95** [comment]
Hier mal ein paar Vorschläge für ein Filtersetup:
 * Als Grobfilter einen F9
  * [592x592x48mm F9 Filter für 60€](https://htm-filtershop.de/epages/htm-shop.sf/de_DE/?ObjectPath=/Shops/htm-shop/Products/PF-12-1004/SubProducts/PF-12-1004-438)
* HEPA H13
  * [ 610 x 610 x 292mm HEPA H13 Filter für 170€](https://www.as-luftfilter.de/Schwebstofffilter-E10-H14/HEPA-Filter--Schwebstofffilter-H13/MDF-Rahmen/Rahmentiefe-292mm/product-1168.html)
* Aktivkohlefilter als Granulat
  * [25kg á 93€ bei 600x600mm Wanne sind das ca. 15cm tief](https://www.luftundklima24.de/Aktivkohle-25-kg-Pellets-Geruchsfilterung)

 Ich persönlich finde einen H13 Filter zu viel, da das die Klasse von Filtern in Kernkraftwerken ist.

**Comment by LukasFreeze** [comment]
H13 ist das mindeste, was in sämtlichen kommerziellen Absaugungen stecken
müsste, darunter heißt es nämlich noch nicht HEPA:
https://de.m.wikipedia.org/wiki/Schwebstofffilter#Effizienz_und_Standardisierung

Ich denke wir brauchen mindestens E12, aber lieber H13 da das schon seinen
Grund haben wird wenn es überall genutzt wird.

**Comment by Pakue95** [comment]
Die ABL Reihe von Cameo hat aber auch kein HEPA Filter.

**Comment by LukasFreeze** [comment]
Hmm, die kannte ich nicht (habe mich hier auf vacuair UML oder die von
unserem Händler empfohlene BOFA-Systeme bezogen). Es sieht aber so aus als
hätten die "ABL"-Geräte überhaupt keine ernstzunehmenden Filter, auch keine
Aktivkohle: https://www.cameolaser.de/laser/absauganlagen/vacuair-abl-1500/

Da steht zwar "nachrüstbar", aber in den Recherchen weiter oben (glaube
Fablab FAU) wurde davor gewarnt dass ohne anständigen Feinfilter schnell
"die Aktivkohle verstopft" (also wohl deren Packung aus Vlies o.ä.)

Einfach ungeklärte Abluft nach draußen zu blasen halte ich in unserer Lage
für sehr problematisch, dafür braucht man schon einen nicht mit anderen
Parteien geteilten Hof und lieber auch noch einen Schornstein, und *gut*
ist es selbst dann nicht :-P

**Comment by NitramLegov** [comment]
[Das hier](https://www.emw.de/de/filter-campus/filterklassen.html) Fand ich noch eine ganz gute Übersicht über die verschiedenen Filterklassen und Anwendungsgebiete. Weiß jemand, ob es Regularien in diesem Bereich gibt?

**Comment by Pakue95** [comment]
Hier noch eine Studie bzw. eine [Zusammenfassung](https://www.komnet.nrw.de/_sitetools/dialog/4842) zu Schadestoffemission von CO2-Lasecuttern:

* Hauptstoffe, die bei PMMA entstehen sind:
    * Methylmethacrylat (MMA) 
    * Formaldehyd
    * Acetaldehyd,
    * Aceton, 
    * Benzol 
    * Butadien
    * Hexanal
    * Methylethylketon (MEK)
    * Phenol und Toluol

**Comment by Pakue95** [comment]
Ich habe mal ein Design mit den vorgeschlagenen Filtern angefangen. Befindet sich momentan in unserem Fusion360 Team.

**Comment by NitramLegov** [comment]
Wer Zugriff auf das Fusion Team möchte meldet sich bitte bei Johannes, Patrick, Lukas oder mir.

Wer das Design ohne Zugriff anschauen möchte kann diesen Link benutzen:
https://a360.co/2Wzd9VH

**Comment by LukasFreeze** [comment]
Zur besseren Abdichtung und erleichtertem (sprich geraderem) Zusammenbau
könnten wir über Falze an den Kanten der Platten nachdenken:
https://de.m.wikipedia.org/wiki/Falz_(Verbindungstechnik)#Verwendung_au%C3%9Ferhalb_der_Verbindungstechnik

Das wäre mit einer Oberfräse recht schnell gemacht, müsste aber im Design
schon bedacht werden damit die Box nicht plötzlich kleiner wird ;-)

**Comment by Pakue95** [comment]
Im Zusammenhang zu #194 haben wir mal die Fertigstellung des Lasers priorisiert, dazu ist natürlich auch eine funktionierende Absaugung erforderlich. 

Die letzten Tage habe ich mal dazu genutzt das [Fusion Design](https://a360.co/2UWUuBS) umzusetzen. Der momentane Stand seit gestern ist, dass der Kasten fertig ist, das Behältnis für die Aktivkohle (ohne Gitter) gebaut ist, Ein-/Auslasssanschlüsse angebracht sind und der erste Abschnitt für den F9 Filter in-place ist.

Noch zu tun ist:
* Verstärkungswinkel einbauen (drucken gerade bei mir)
* Aktivkohle Box ein Gitter verpassen und ein Stück Stoff verpassen, damit die Kohlepellets nicht durchfallen können
* Dichtungen anbringen
* ggf. alle Fugen abdichten wenn wir vorhaben einen positiven Druck am Einlass zu haben.
* Halterung für die AK-Filterbox bauen
* Klemmvorrichtung für den F9 Filter planen und umsetzen

Benötigte Materialen:
* 15mm Dichtungsbank
* Feines Gitter für die AK
* Rollen für die Absaugung (sonst iwie blöd zu transportieren) 

Hier noch ein paar Bilder für die visuelle Stimulation: 

![IMG_3549](https://user-images.githubusercontent.com/19751734/79006501-99270b00-7b59-11ea-80d3-3376685b0d3a.jpeg)
![IMG_3552](https://user-images.githubusercontent.com/19751734/79006511-9debbf00-7b59-11ea-8b6f-0ab1437ca79c.jpeg)
![IMG_3557](https://user-images.githubusercontent.com/19751734/79006525-a3490980-7b59-11ea-860e-4f38010af6bc.jpeg)
![IMG_3561](https://user-images.githubusercontent.com/19751734/79006543-ae9c3500-7b59-11ea-9d13-346ea1d6145b.jpeg)
![IMG_3563](https://user-images.githubusercontent.com/19751734/79006549-b065f880-7b59-11ea-974a-86a727544529.jpeg)

**Comment by Pakue95** [comment]
**Update:**

Martin und ich haben über Ostern die Abluft fertig gebaut und mit F9 Filter, sowie 25kg Aktivkohlepellets bestückt. Der gelbe Lüfter is momentan nur oben auf den Anschluss aufgelegt, muss also bis zur finalen Freigabe noch fixiert werde. 

Im Rahmen von #194 haben wir die Abluft mit Lasern der PET Folie für die Gesichtsschilder getestet. Das PET hat ziemliche Rauchentwicklung von daher ist es ein guter "worst-case" Test für die Filteranlage. Vom Volumenfluss ist der gelbe Lüfter mehr als ausreichend um den Innenraum des Lasers gut/schnell vom Rauch zu evakuieren. Zusammen mit dem Lüfter, der mit dem Laser geliefert wurde, ist die Absaugung natürlich noch besser, jedoch kann ich mir vorstellen, dass der Innendruck damit über dem Umgebungsluftdruck sein könnte und damit ungefilterte Luft, durch Undichtigkeiten in der Filterbox, in den E-Room gelangen kann. Zudem ist ein zu hoher Luftstrom auch eher kontraproduktiv um alle Gerüche/Aerosole mit der Aktivkohle herauszufiltern.

Was uns zum nächsten Punkt führt: Die Geruchsfilterung ist noch nicht 100%ig. Als wir das PET geschnitten haben ist doch noch einiges an Geruch nach außen getreten und man hat es deutlich im E-Room gerochen. Wenn die Abluft nach außen geleitet wird ist das natürlich nicht mehr bemerkbar, jedoch sollten wir das noch fixen bis der Laser freigegeben werden kann.

Meine Vermutung, warum die Aktivkohle noch nicht wie erwartet filtert, ist, dass die Luft nicht lange genug durch die Pellets wandert um genug Aerosol abzugeben. Das könnte man durch 3 Dinge verbessern:
* **mehr Aktivkohle**
    Momentan haben wir nur 25kg von max. 50kg AK in der Box, was so ca. 15-20cm Luftweg ist. Nochmal 25kg Pellets drauf zu packen würde den Weg verdoppeln und das Filterergebnis bestimmt verbessern. Nachteil: Nochmal 100€ AK und viel Gewicht in der AK-Box (Macht die Box dann sehr Kopflastig und unpraktischer neu zu befüllen).
* **geringere Luftstrom**
    Würde die Zeit in der Luft in der Aktivkohle ist verlängern um ein besseren Austausch zu ermöglichen. Wäre ich persönlich dagegen, da das auch die Absaugung am Laser verschlechtert.
* **AK-Box etwas verändern**
    Durch Trennwände in der Box mit der Aktivkohle kann man den Weg, den die Luft durch die Pellets nehmen muss, vergrößern und damit die Filterleistung verbessern. Das wäre persönlich mein Favorit. Ich würde die Tage das Fusion Projekt mit möglichen Änderungen an der AK-Box updaten. 

Hier noch ein paar optische Updates:

![IMG_3566](https://user-images.githubusercontent.com/19751734/79414912-38119400-7fac-11ea-962d-858f19909f58.jpeg)
![IMG_3570](https://user-images.githubusercontent.com/19751734/79414940-4790dd00-7fac-11ea-83dd-794890dbed30.jpeg)

**Comment by LukasFreeze** [comment]
Ich wäre auch dafür, den Luftweg durch die vorhandene Aktivkohle irgendwie
zu verlängern.

Gab es ein Problem mit dem mitgelieferten, bzw. habt ihr den auch mal
ausprobiert? Dieser gelbe ist ja ganz anders gebaut, sicher dass er weniger
Leistung hat als der mitgelieferte?

Mich wundert aber gerade generell die Position: nachdem ich meine Skizze
hier gepostet hatte hieß es doch, dass ein in die Box blasender Lüfter
effizienter als ein saugender sein müsste? @Johannes09 meinte außerdem,
dass es für die Lager schlecht sein könnte wenn der (mitgelieferte) Lüfter
gekippt wird, ist das beim gelben nicht so?

Wenn Ein- und Auslassöffnung der Box gleich groß sind und die Plattenstöße
mit Silikon o.ä. abgedichtet sind - sieht auf dem Foto ja so aus - kann ich
mir schon gut vorstellen dass das dicht bleibt, wenn der Lüfter reinpustet
statt saugt :-)

**Comment by LukasFreeze** [comment]
Update von @Pakue95 : der mitgelieferte Lüfter ist mit verbesserter Filtereinheit zu schwach, der gelbe hat glücklicherweise mehr Leistung und wird jetzt (mit einem Schlauch und Nachstromöffnung) angebracht.

**Comment by Titan-OX** [comment]
@Johannes09 und ich haben Rohre und ein Fliegengitter im Bauhaus besorgt und verlegt. wir haben oben in die Plexiglasscheibe ein Loch mit dem Fein gemacht und das Gitter mit Fugensilikon eingesetzt. Da das Gitter so nah unterm Dach ist und es so Lamellen hat wird es wahrscheinlich nicht rein regnen. 

![image](https://user-images.githubusercontent.com/22505956/83976697-dd395080-a8fb-11ea-97ac-507dd8a09983.png)

**Comment by NitramLegov** [comment]
@Johannes09 hat heute den Schlauchadapter für den gelben Ventilator designed, gedruckt und angebaut.

Beim ausprobieren ist uns aufgefallen, dass der Auslass nach draußen (aus dem Fenster, siehe Bild von @Titan-OX ) noch nicht 100% dicht ist. Da müssen wir nochmal ran.

**Comment by LukasFreeze** [comment]
Wo ist denn die undichte Stelle - muss man da nochmal von außen an das Gitter? Dann müsste man nämlich mit den Rollos an diesem Fenster warten bis die Abluft fertig ist

**Comment by LukasFreeze** [comment]
Mit der Korrektur in #217 müsste das hier dann auch erledigt sein :-)
