### ISSUE TITLE
P5 - Err: MINTEMP BED

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#180]
P5 schmeißt aktuell den folgenden Fehler:
![IMG_20200209_182025_771](https://user-images.githubusercontent.com/7809163/74109886-d1c15d00-4b87-11ea-8994-9e64788c4636.jpg)
Der Fehler ist hier ganz gut beschrieben: https://help.prusa3d.com/article/am4dykf2rw-mintemp

Ich denke wir sollten den Fühler checken und falls er wirklich kaputt ist austauschen.

Es kann auch sein, dass einfach der Raum zu kalt ist. Allerdings sollte das in diesem Fall eigentlich auch für alle anderen Drucker gelten

**Comment by Narquadah** [comment]
Bett Thermister ist defekt und ein neuer muss bestellt werden. @Pakue95 bestellt einen.

**Comment by NitramLegov** [comment]
Ich glaube Erik braucht auch einen :)
________________________________

**Comment by ErikSchatz** [comment]
JA Bitte!!!-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 12.02.20, 21:43 schrieb NitramLegov <notifications@github.com>:

  Ich glaube Erik braucht auch einen :)
   ________________________________

**Comment by Pakue95** [comment]
Ich werde nächste Woche einen neuen Sensor bei Prusa bestellen. 

@ErikSchatz: Über den Space kann ich dir leider keine privaten Ersatzteile bestellen, den musst du selbst ordern.

**Comment by Pakue95** [comment]
Die Sensoren sind angekommen und sind oben im 3D-Druck Regal deponiert.

**Comment by Pakue95** [comment]
Habe heute den neuen Sensor eingebaut und der Drucker funktioniert wieder. Sind dann noch 2 weitere Sensoren übrig.
