### ISSUE TITLE
P3 - gestörtes Druckverhalten

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#181]
P3 hatte heute Probleme beim Drucken, die sich in einem Versatz auf der XY Ebene bemerkbar gemacht haben:
![IMG_20200209_181945_623](https://user-images.githubusercontent.com/7809163/74109965-6deb6400-4b88-11ea-88ae-de7ec88d44d4.jpg)

Der Druck sollte laut @ErikSchatz eigentlich eine ganz normale Box werden, die nicht diesen Versatz aufweist.
Wie man auf dem Bild sehen kann gibt es ungefähr in der Mitte des Drucks eine kleine angeschmorte Stelle. @Johannes09 hat die Vermutung geäusert, dass es von Filamentresten kommt, die am Extruder kleben und runtertropfen, sobald dieser heiß wird. Daher schlägt er vor, erstmal den Extruder zu reinigen und zu schauen, ob das das Problem löst.

**Comment by Narquadah** [comment]
Habe mal neu mal kalibriert und die fehlende Schraube am Bett ersetzt. Einen Test Druck müsste man noch machen.

**Comment by Johannes09** [comment]
Ich habe die Düse heute auseinander genommen gereinigt und z kalibriert.
![20200215_180237](https://user-images.githubusercontent.com/22060480/74593722-9fec4280-502e-11ea-8673-ddb034eeae99.jpg)
![20200215_175401](https://user-images.githubusercontent.com/22060480/74593724-a4b0f680-502e-11ea-96a7-b041e51597d1.jpg)
Es muss nur noch ein Testdruck gemacht werden.

**Comment by NitramLegov** [comment]
Der Testdruck hat stattgefunden und war erfolgreich.
Wer sich selbst überzeugen möchte möge sich den neuen Knauf der Lagertür anschauen :)
