### ISSUE TITLE
Neuer Küchenbereich

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#182]
Im neuen Space haben wir deutlich mehr Platz für unsere Küche als bisher. Daher können wir speziell die Arbeitsfläche deutlich ausbauen. Aus diesem Grund stehen im Gemeinschaftsraum hinter den Spinden zwei neue Arbeitsplatten die darauf warten, aufgebaut zu werden.

Folgendes ist (aktuell) die grobe Idee:
1. Der Kühlschrank soll neben den Metallträger an der Tür zum Lager
2. Direkt an den Kühlschrank schließt die erste Arbeitsplatte an. Diese Platte beinhaltet unter den Hängeschränken die Spüle.
3. Am Ende der ersten Platte schließt im 90° Winkel die zweite Platte an, die dann an der Außenwand entlang geht. Unter dieser Platte werden die Getränke gelagert (jeweils 2 Kästen pro Getränkesorte)

Eckpaten für Abstimmungsbedarf sind Johannes und Kim (daher hier auch assigned)

**Comment by lmnl99** [comment]
Hallo ich würde es machen mit der Küche bräuchte aber noch jemanden der mit hilft, da ich mich nicht so gut auskenne. Ich bin Schlüssel Mitglied wenn sich also ein normales Mitglied zum helfen entschließt, könnten wir dies auch an einem Wochenende erledigen.

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by NitramLegov** [comment]
@lmnl99 oh, sorry! Ich sehe jetzt erst, dass du hier Hilfe angeboten hattest. Mega cool, danke dir!

In der Zwischenzeit hat die Küche Fortschritte gemacht und steht soweit :) Der Kühlschrank läuft auch wieder. Was noch gemacht werden muss ist die Spüle anzuschließen (nach #167 ), die Getränkekästen einzuräumen und ggf. die Arbeitsplatte an der Wand nach draußen zu verlängern (damit die bis zum Audioregal geht 😍)

**Comment by NitramLegov** [comment]
Denke hier kann man auch zumachen. Was wir in der Vergangenheit hatten funktioniert wieder - und alle Verbesserungen können wir im Rahmen anderer Issues angehen
