### ISSUE TITLE
nächste "Tor 4"-Förderrunde - Bewerbung bis 15. Mai!

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#184]
Wir könnten in die nächste Runde gehen! Wie ihr mittlerweile wohl alle mitbekommen habt waren wir letztes Jahr mit unserer Bewerbung auf die BASF-Kulturförderung erfolgreich (#111 ) und bereiten gerade Details zur Austragung unserer davon unterstütztem Kurse vor (#172, #173, #174, #175 ).

Jetzt gibt es die nächste Ausschreibung für Projekte im 2. Halbjahr 2021 mit der Fragestellung "Müssen wir denn noch reden?": https://www.basf.com/global/de/who-we-are/organization/locations/europe/german-sites/ludwigshafen/gesellschaftliches-engagement/woran-wir-arbeiten/arts-and-culture/Tor4/muessen-reden.html

Fällt euch dazu etwas "Maker-mäßiges" ein? Oder habt ihr einfach Lust, beim Ausarbeiten des Antrags mitzumischen? Dann meldet euch bitte! :-)

**Comment by NitramLegov** [comment]
Ich denke aus "Müssen wir denn noch reden?" lassen sich sicherlich Maker-spezifische Ideen entwickeln, die der Fragestellung auf den Grund gehen und sich kritisch mit dem Einfluss moderner Technologien auf unser Kommunikationsverhalten beschäftigen.

Als offensichtliches Beispiel fallen mir hier erst einmal Sprachassistenten ein, mit denen sich einige täglich unterhalten. Hier kann man Möglichkeiten aufzeigen und einen eigenen Assistenten bauen, aber auch kritische Fragestellungen wie z.B. den Datenschutz beleuchten.

Damit ist auch generell die Brücke zur KI nicht weit - zur kritischen/künstlerischen Auseinandersetzung mit dem Thema könnten wir ggf. einen Filmeabend veranstalten, in dem wir Filme zeigen, die sich kritisch mit dem Thema auseinandersetzen (Ex Machina o.Ä.)
Wenn wir dazu die Gedanken der Teilnehmer auf einem Whiteboard oder ähnlichem sammeln kommt bestimmt auch wieder etwas gutes für eine Abschlussveranstaltung zusammen.

In einem ganz anderen Feld können wir uns bewegen, wenn wir Workshops oder ähnliches anbieten, die demonstrieren, dass es auch beim Machen auch vernünftige Kommunikation ankommt. Ein Workshop, in dem man zu Anfang gemeinsam planen muss, um am Ende ein gutes Ergebnis erzielen zu können. Gerne auch mit spielchen, die die Bedingungen etwas erschweren (Plant mal, ohne ein Wort zu sagen oder Ähnliches).


Wer hilft bei der Vorbereitung und Antragstellung?

**Comment by LukasFreeze** [comment]
Langsam heißt es "jetzt oder nie" - wollen wir uns mal im [whereby](https://kumbier.whereby.com/comakingspace) treffen, um zu schauen ob und wie wir uns bewerben?

Ich würde einfach mal Mittwochabend (19:00?) vorschlagen, aber sagt bitte Bescheid wenn ihr da nicht könnt und gerne dabei wärt - dann finden wir sicher noch einen besseren Termin!

**Comment by LukasFreeze** [comment]
Dieses Mal scheint sich wohl kein Team für eine Bewerbung zu finden, schade aber auch kein Weltuntergang.
