### ISSUE TITLE
Laser - PC einrichten

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#185]
Wie in #166 beschrieben haben wir einen neuen Lasercutter. Dieser Lasercutter kommt mit seiner eigenen Software, die wir in irgendeiner Form lauffähig bekommen müssen.

Die Software, die wir da bekommen ist Lasercut 5.3 

Ich schlage vor, dass der Lasercutter einen dedizierten PC bekommt. Dieser sollte meiner Meinung nach mit Windows laufen, um Kompatibilitätsprobleme mit der Software möglichst auszuschließen. Falls die Software unter Windows 10 läuft am liebsten mit Windows 10. Alternativ auch gerne mit Windows 7, dann kriegt der Rechner aber keinen Netzwerkzugang.

Hardware seitig haben wir noch was verfügbar. Wer sich um das Issue kümmern möchte kann gerne einen von uns ansprechen.

**Comment by LukasFreeze** [comment]
Die Installationsdateien für Lasercut 5.3 müssten auf dem orangen "HPC"-Stick im eRoom liegen, auf der Wiki-Seite "Laser Cutter" sind schon ein paar Fablabs mit Software-Doku verlinkt und wir sollten natürlich eine [eigene Seite anlegen](https://wiki.comakingspace.de/index.php?title=Lasercut_5.3&action=edit&redlink=1) ;-)

Die Vollversion der Software wird wohl nur mit einem "soft dog" Dongle laufen, dieser kleine weiße USB-Stick liegt momentan im Büro. Damit er nicht verloren gehen kann sollten wir in irgendwie an diesen PC ketten!

**Comment by NitramLegov** [comment]
Good news: Auch wenn die Software selbst spannend ist läuft sie unter Windows 10.

Einen dedizierten PC halte ich dennoch für sinnvoll. An diesen Sollten wir dann wie von Lukas beschrieben den Dongle ketten!

**Comment by NitramLegov** [comment]
Ich habe mich gerade mal drangesetzt und meine Erfahrungen die ich in den letzten Tagen gewinnen konnte im Wiki dokumentiert. Bilder folgen noch.
Die Seite sollte jemandem der weiß, wie man mit einem Laser umgeht hoffentlich einen guten Einstieg bieten.

Alles in allem muss ich sagen, dass die Software besser ist als gedacht, wenn man sich mal dran gewöhnt hat. Allerdings sehe ich Risiken bei Leuten, die lange nichts mit dem Laser gemacht haben und dann wieder einsteigen wollen. Diese müssen sich ja immer wieder neu "dran gewöhnen". Intuitiv finde ich die Software nämlich nicht.

**Comment by NitramLegov** [comment]
Laser PC steht im E-Room und ist fertig eingerichtet
