### ISSUE TITLE
Türschließer

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#186]
Die meisten (alle?) unserer Innentüren brauchen noch Türschließer, am dringendsten die zur Werkstatt.

Bei den Außentüren sehe ich noch die Gefahr, dass sie mit zu schwachen Schließern nur angelehnt bleiben und dann leichter übersehen werden als eine klar offen stehende Tür, aber hinten ist schon ein alter Schließer halbwegs montiert den wir zumindest ausprobieren könnten.

Für die Innentüren müssen wir jedenfalls etwas kaufen - wir haben bei mir auf der Arbeit gute Erfahrungen mit dem **Burgwächter TS 503 S SB** gemacht, bei dem man (wie vermutlich bei der ganzen Modellreihe) über zwei Schrauben die Schließgeschwindigkeit/-kraft für den weiten Weg von "ganz auf" bis "fast zu" und das letzte bisschen zum Zuklappen einzeln einstellen kann.

![IMG_20200219_104031_344](https://user-images.githubusercontent.com/19755883/74821557-1a091980-5304-11ea-8e49-2dd037cc6564.jpg)

**Comment by NitramLegov** [comment]
Im Regal hinter den Spinden liegt noch ein Türschließer den wir nutzen können. Wenn der für uns funktioniert müssen wir schonmal einen weniger kaufen. Gegebenenfalls kann der ja für die Tür zum Lager oder zum E-Room genutzt werden.

**Comment by LukasFreeze** [comment]
Das ist so ein unschön einstellbarer und ggf ganz schön "aggressiver"
Türschließer wenn ich mich nicht irre, würde ich wenn wir die Wahl haben
lieber nicht an eine leichte Innentür bauen. Aber die Eingangstür braucht
ja auch noch einen, sobald das Schloss leichter einschnappt (#188),
vielleicht eignet er sich dafür?

**Comment by LukasFreeze** [comment]
Der Eingangstür-Schließer hat das Zeitliche gesegnet, war wohl doch zu alt (und auch leider nicht zweistufig einstellbar)....

@Pakue95 hat günstige Schließer bei Pollin gefunden, die wir ausprobieren könnten:
- [hydraulisch 65 kg, 90° Haltefunktion](https://www.pollin.de/p/tuerschliesser-hydraulisch-65-kg-mit-900-haltefunktion-490378) - 1x für die Eingangstür
- [hydraulisch 45 kg, 90° Haltefunktion](https://www.pollin.de/p/tuerschliesser-hydraulisch-45-kg-mit-900-haltefunktion-490377) - 1-2x zum Testen für Innentüren: müsste sicher für "Fertig-Türen" reichen, Schallschutztüren evtl zu schwer?

**Comment by LukasFreeze** [comment]
Ich habe noch eine "Türfeder" im Lager entdeckt, vielleicht taugt die was für eine der Innentüren? Vermutlich kann sie nur drücken und nicht ziehen, deshalb für außen nicht geeignet...
Sie liegt jetzt jedenfalls mit dem restlichen Zeug der Türen-"Baustelle" auf dem Schränkchen neben der Eingangstür!

([so eine](https://static.opo.de/Gruppe66/66.072.01-04_2013120229_x.jpg))

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by LukasFreeze** [comment]
Großzügig gerechnet (Pollin-Links weiter oben): 5 Türschließer á 20 € ->
Bedarf 100 € :-)

**Comment by NitramLegov** [comment]
Nachdem in der betterplace funding Ecke nichts mehr passiert ist habe ich Türschließer gekauft und an allen Innentüren installiert. Türen die weiter als 90° geöffnet sind bleiben geöffnet. Alles darunter wird geschlossen.

Bei den Außentüren wäre mir ähnlich wie Lukas das Risiko zu groß, dass sie nicht ganz zufallen und dann angelehnt bleiben.
