### ISSUE TITLE
laser cutter commissioning

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#187]
@Pakue95 and I unpacked the laser cutter last night to finally check whether it survived the delivery, so far everything looks okay :-)

Next, we need to move it to its spot in the eRoom (in two parts - managers know how), make sense of all the extra parts and assemble them, and go through our usual "commissioning" checklist on the [wiki page](https://wiki.comakingspace.de/Laser_Cutter)!

A printed manual and a USB stick with software and documentation (already backed up in the office) are in the eRoom for anyone interested. The most important points could be added to the wiki right away, but of course please don't just copy & paste the foreign text.

All work on the machine itself needs to be coordinated with a manager (the case openings are locked anyway), so this issue could help schedule meetings to make progress here :-)

Most questions and suggestions are also better posted here than in the wiki, don't be shy!

Also see #185 & #179 !

**Comment by NitramLegov** [comment]
Quick update: The laser has been moved to its spot in the E-Room.

**Comment by LukasFreeze** [comment]
today we set the machine up far enough to start aligning the mirrors, but unfortunately we could not get the laser tube to "fire". None of the troubleshooting steps from the manual brought a solution, so I just contacted support...will keep you posted :-(

**Comment by LukasFreeze** [comment]
The problem was that the coolant water was flowing in the wrong direction ("outlet" of the chiller has to go into "inlet" of the laser cutter and vice versa). So the machine does work and we can keep commissioning it once the shutdown is over!

**Comment by NitramLegov** [comment]
@Pakue95 invested quite some time to get #179 done.
Yesterday we were able to bring it to a state that we were able to operate the laser and perform test cuts.

During this, we of course had to install and use the LaserCut Software. The Software is kind of....interesting...and will need some detailed description in the Wiki. I think it will really be best to have a dedicated PC for this (#185 ).

**Comment by NitramLegov** [comment]
The laser PC got the softdog dongle and a wifi dongle installed today. So the laser can be used by people that already have got the new introduction.
