### ISSUE TITLE
Eingangstür verbessern

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#188]
Man muss die Eingangstür leider noch ganz schön stark zuschlagen/-ziehen, was nicht gerade gut für sämtliche Teile des Schlosses ist. Meistens kann man bei den guten Einsteckschlössern die Falle etwas weiter zurückstellen sodass nur der schräge Teil über den Rahmen rutschen muss, wenn das hier geht ist es vielleicht schon die Lösung!

Außerdem hat @Pakue95 einen Regenschutz für den elektronischen Knauf vorgeschlagen, damit wir lange Spaß damit haben :-P

Fehlt da nicht noch die komische Türschwelle? Die ist schon in #177 als Wärmelücke dabei!

**Comment by LukasFreeze** [comment]
@Pakue95 hat einen Regenschutz gebaut, heute haben wir die klemmende Falle dann auf die genau "passend" angeschrägte Rahmenpartie zurückgeführt den er jetzt rundgeschliffen hat. Trotzdem bitte weiter beobachten!

Ich hab jetzt den Türschließer installiert und es scheint alles zu funktionieren!

**Comment by LukasFreeze** [comment]
Leider dehnt sich die Tür in der Sonne so stark aus, dass wir noch mehrmals nachschleifen mussten. Jetzt passt zwar die Tür (bei allen bisher erlebten Temperaturen) in den Rahmen, allerdings klemmt die Falle doch wieder gerne im Rahmen fest. Bei Öffnungsversuchen mit klemmender Tür hat sich außerdem der Wechselstift (Vierkant in der Klinke) verdreht.

TO DO: 
* Rahmen/"Schließblech" oben noch weiter ausfräsen (links, also Außenseite) und bei > 25 °C testen
* Wechselstift ersetzen, am besten durch einen massiven der sich nicht wieder verdrehen kann (aktuell ist er ca. 10 cm tief geschlitzt)

**Comment by Titan-OX** [comment]
Did you have to redo it after I had ground it down?

**Comment by LukasFreeze** [comment]
No, the door/frame gap looks fine for now - but the part of the lock that
goes into it still gets jammed so you can hardly move the handle.

**Comment by LukasFreeze** [comment]
Das "Schließblech" ist jetzt recht sauber ausgefräst und ich denke auch weit genug, bitte bei Gelegenheit trotzdem noch nach starker Sonneneinwirkung testen :-)

**Comment by LukasFreeze** [comment]
Heute in den hohen 20ern klemmte die Tür wieder, es liegt am Schließblech....da muss also "Richtung außen" dringend nochmal was weggenommen werden!

Wenn jemand Zeit hätte, aber nicht ganz versteht was ich meine, einfach Bescheid sagen :-)

Wir haben leider beide nur kurz nach was geschaut und konnten heute nicht zur Verbesserung beitragen, aber @Narquadah war auch da und hat vorgeschlagen, ein Schild an die Tür zu hängen bis es wieder richtig geht. Etwas in Richtung "keine Gewalt am Knauf anwenden, sondern Tür beim Drehen zudrücken falls es klemmt" könnte hilfreich sein!

**Comment by LukasFreeze** [comment]
Hat nochmal jemand an einem heißen Tag Gelegenheit gehabt, die Tür in der Mittagszeit zu testen?

Abends funktionierte sie jetzt immer so gut (mit leichtem Andrücken), dass ich glaube, dass das Problem mit einem Türschließer ohne weiteres Fräsen zu lösen sein sollte :-)

**Comment by NitramLegov** [comment]
Ich glaube @Pakue95 hat hier vor kurzem etwas gemacht.

Ist das damit gefixt? :)

**Comment by Pakue95** [comment]
Momentan ja, kann sich im Sommer aber ggf. ändern. Denke mittelfristig sollte man den Spalt-Vierkant an der Klinke ersetzen, da der nicht so formstabil ist.
