### ISSUE TITLE
neue T-Shirts

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#189]
Heyho, ich habe mich nochmal mit einem Design beschäftigt, das in seinen Grundzügen noch aus der Gründungsphase und der Suche nach einem Logo stammt, um damit T-Shirts zu bedrucken :-)

Wer hätte Interesse so etwas zu tragen (oder kann noch Verbesserungsvorschläge bieten)?

![grafik](https://user-images.githubusercontent.com/19755883/75114896-63d26680-565a-11ea-9599-9691a8ac1148.png)

Bei der Farbe könnte ich mir auch etwas rötliches oder grünliches gut vorstellen (-> ["Burgundy" oder "Bottle Green"?](https://www.cantana.com/bio-und-fair/sonderangebote/50-bio-t-shirts-inkl-1-farbigem-druck/)), schwarze Shirts habe ich persönlich genug und da gibt es ja auch schon @Pakue95 s Design, das wir bei Interesse nochmal neu auflegen könnten!

Ob wir das nachher als private Sammelbestellung machen oder als Werbemittel über den Space kaufen müssten wir noch klären. Ich möchte jedenfalls gerne [fair gehandelte Bio-Baumwolle](https://www.cotton.de/fair-bio/) was immer noch sehr günstig zu bekommen ist, zum Beispiel:
* [Cantana.com Sonderangebot 50 Stück](https://www.cantana.com/bio-und-fair/sonderangebote/50-bio-t-shirts-inkl-1-farbigem-druck/) (5,50 € pro Stück - allerdings Druck nur vorne)
* [Cantana.com regulär](https://www.cantana.com/bio-und-fair/t-shirts/bc-inspire-t-men-tm042/) (Angebot für einfarbigen Druck vorne und hinten angefordert)
* [cotton.de](https://www.cotton.de/fair-bio/bc-inspire/inspire-basic-men/) (je nach Bestellmenge, z.B. 5,84 € pro Stück in Farbe mit einfarbigem Druck vorne - hinten müsste angefragt werden)

Wie ihr seht habe ich jetzt hier Männershirts gelistet, wenn sich genug Interessentinnen für einen anderen Schnitt finden wäre das natürlich auch sehr cool! Aber ansonsten können die Frauen ja eher so ein Männershirt "falsch" anziehen als andersrum, oder? ;-P

**Comment by NitramLegov** [comment]
Finde ich gut. Die Grafik gefällt mir ziemlich gut, Das "MACH doch was du willst" ist jetzt nicht mein Fall, da würde ich persönlich eher nochmal unser Logo hinpacken.

Bezüglich deiner Auswahl an Shops: Wo haben wir denn die letzten T-Shirts bestellt? Bei denen fand ich um ehrlich zu sein den Schnitt nicht gut, da sie recht kurz und damit nicht lang genug waren (YMMV). Daher würde ich dort nicht noch einmal bestellen wollen (oder einen anderen Schnitt auswählen).

**Comment by LukasFreeze** [comment]
> Das "MACH doch was du willst" ist jetzt nicht mein Fall, da würde ich persönlich eher nochmal unser Logo hinpacken

Mein Fall ist es offensichtlich schon, alternativ hatte ich da aber auch mal an "Freiraum zum Selbermachen", den Leitsatz des Verbunds offener Werkstätten gedacht :-)
Das Logo finde ich nicht so geeignet, weil ich mit dem Design neugierig machen und Leute ansprechen möchte, die uns noch nicht kennen - weiter unten und ggf hinten ist der Name/das Logo ja dann immer noch gut erkennbar, aber ich halte es nicht für die beste "Eröffnung"

Ich würde auch auf jeden Fall woanders bestellen als letztes Mal (das war glaub ich Flyeralarm?) weil es die von dir beschriebenen Probleme mit dem Schnitt gab und es halt auch einfach billigste Qualität war. Die jetzt verlinkten Shops habe ich zwar noch nicht ausprobieren können, aber es ist eben zumindest bio & fair.

**Comment by NitramLegov** [comment]
"Freiraum zum Selbermachen" finde ich besser als "MACH doch was du willst". Aber das ist ja subjektiv, vielleicht haben andere ja auch noch eine Meinung :)

Ansonsten bin ich stark dafür, ein vorne und hinten bedrucktes T-Shirt zu bestellen. Hinten das Logo und die Website finde ich auch gut. Sollen wir da noch die Werkstattadresse draufschreiben?

**Comment by emka** [comment]
"Freiraum zum Selbermachen" gefällt mir auch besser. Die Adresse würde ich weglassen und ein T-Shirt mit besserem Schnitt fände ich einen Aufpreis wert.

**Comment by LukasFreeze** [comment]
Ich hab das geklärt, wir dürften den Spruch vom VoW verwenden:

![grafik](https://user-images.githubusercontent.com/19755883/75884557-56209c00-5e25-11ea-99b0-5f3f6463ec29.png)

Die Werkstattadresse würde ich hinten auch eher weglassen, die bringt einem ja ohne Aufsichtszeiten eh wenig und beides bekommt man über die Website :-)  Aber vielleicht kommen ja noch mehr Meinungen, ich verlinke dieses Issue mal vom nächsten Plenum!

**Comment by Cujoontour** [comment]
Finde ich gut. Der „Freiraum“ gefällt mir besser. Würde ich kaufen !

**Comment by Cujoontour** [comment]
Ich würde zwei Stück bestellen. In der Version Freiraum - Größe M. Besten Dank ;-)

**Comment by LukasFreeze** [comment]
![IMG_20201015_204614](https://user-images.githubusercontent.com/19755883/96173780-aa960900-0f28-11eb-8026-7aa770620225.jpg)

Die erste Auflage 😁 - gibt's weltexklusiv für Helfer bei #172, #174 und #175 !

**Comment by LukasFreeze** [comment]
wir nehmen ab sofort auf der Website verbindliche Vorbestellungen für T-Shirts entgegen :tada:  @Cujoontour deine zwei Shirts können auch verschiedene Farben sein!

  https://comakingspace.org/shop.html

 Natürlich kann man sich auch weiterhin durch Mitarbeit bei den Tor-4-Workshops ein Helfershirt verdienen, aber so ein einzelnes Shirt muss ja auch mal in die Wäsche ;-)

**Comment by NitramLegov** [comment]
Ich mache hier mal zu. Shirts sind da, wurden auch teilweise schon verkauft und ich glaube die Helfershirts sind auch verteilt :)

Falls es hier doch noch was zu tun gibt gerne wieder aufmachen :)
