### ISSUE TITLE
Stabiles Regal unter der Decke

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#19]
In der Holzwerkstatt ist viel Platz unter der Decke, wo man in einer Art Regal Material lagern könnte. Es muss allerdings auch sehr zuverlässig stabil sein.

**Comment by LukasFreeze** [comment]
Micha hat eine Idee, wie man da mit Stahlteilen was bauen könnte - sind jetzt auf dem Weg zum Baumarkt!

Einschätzung der Wandstärke: 24 cm

**Comment by LukasFreeze** [comment]
Es sind jetzt 8 Stahlstangen mit 12 mm in der Wand, besonders belastbar ist das ganze allerdings wahrscheinlich noch nicht - wir hatten keinen längeren Bohrer...

- 20 cm sollten in der Wand stecken (10er-Bohrer + hämmern, mit 12er zu locker!)
- die Stangen auf Augenhöhe brauchen noch Schutz - @JohannesGruhler druckt was

**Comment by Pakue95** [comment]
Kann ein 10er Bohrer mitbringen der lang genug sein sollte.

**Comment by LukasFreeze** [comment]
Die Wand war 18 cm dick, Stäbe sind jetzt 16 cm tief drin - danke an alle, die geholfen haben!
