### ISSUE TITLE
Neue Kappsäge: Bosch GCM 12 GDL - Commissioning

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#191]
Die neue Kappsäge muss wie jedes andere Gerät auch unsere Commissioning Schritte durchlaufen. Der Forstschritt wird im wiki dokumentiert und kann hier diskutiert werden
https://wiki.comakingspace.de/index.php?title=Chop_Saw

**Comment by Pakue95** [comment]
Die Kappsäge kann nun verwendet werden! Schaut euch am besten die Wikiseite oder die Anleitung vor dem ersten Benutzen an, wenn ihr schon eine Einweisung für die Kappsäge habt. Ich gebe auch gerne eine kurze "Auffrischung" falls Bedarf besteht.
