### ISSUE TITLE
Makita 3612BR (router) commissioning

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#192]
We got a powerful router that could be installed in the router table! The commissioning steps are tracked in the wiki: https://wiki.comakingspace.de/Routers#Makita_3612BR

The issue tracker is better for discussions, though - I'll start with missing parts:  We should order collet sleeves *(Spannhülsen)* or even proper sized collets *(Spannzangen)* for 6 and **8 mm** router bits.

From what I found so far, the original Makita part numbers for collet sleeves are:
- 6 mm - 763801-4
- 8 mm - 763804-8   ([makita.ae](http://www.makita.ae/accessories/routing_planing/router_trimmer_accessories.html))

- [x] find a store that sells these (or equivalent) parts
- [x] buy the best option - if we can find collets, that would be better than collet sleeves

**Comment by LukasFreeze** [comment]
I found the collet sleeves on Amazon.de:
- [6 mm collet sleeve (13 €)](https://www.amazon.de/Makita-763801-4-Spannhuelse-6mm/dp/B00AEVU2TY/)
- [8 mm collet sleeve (10,39 €)](https://www.amazon.de/Makita-weniger-Oberfr%C3%A4se-Modelle-RP2300FCX/dp/B0193EWLSC/)



but actual collets?!
- original part number of collet nut: 763629-0 ([ereplacementparts.com](https://www.ereplacementparts.com/makita-3612br-router-parts-c-97_122_24243.html?osCsid=l16elg91j7cgn253anm2jlp621))
- there is a [Trend collet at Sautershop](https://www.sautershop.de/spannzange-1/2-12-7mm-t-06748?c=13145) that is supposed to be compatible (but much too large), maybe that is worth checking out - are smaller Trend collets compatible as well?

**Comment by LukasFreeze** [comment]
Has anyone else found collets for this router? Otherwise I'd say we should soon order the collet sleeves I linked in the previous post, that way we can continue commissioning soon and still have time to get the originally planned Triton router in case anything goes wrong with this one.

**Comment by LukasFreeze** [comment]
@Pakue95 könntest du die Hülsen dann bitte bei Gelegenheit bestellen?

**Comment by Pakue95** [comment]
Ist bestellt.

**Comment by LukasFreeze** [comment]
Die 8-mm-Spannhülse habe ich kurz getestet, funktioniert super: man kann sie nicht zu weit reinstecken (bzw im Frästisch "fallen lassen"), und auch bei gelöster Spannzange sitzt sie fest genug um nicht rauszufallen 👍 Fräsergebnis war auch gut, die Maschine ist allerdings ganz schön laut...

Zum Anziehen braucht man einen 24er Schraubenschlüssel, momentan haben wir einen für die Drechselbank und könnten bei erfolgreicher Tischmontage noch über einen eigenen (abgewinkelten?) für den Frästisch nachdenken.

**Comment by LukasFreeze** [comment]
Dank hervorragender Laser-Schablone von @Pakue95 konnte ich gestern die Montageplatte für den Frästisch bohren und die Maschine montieren, läuft super :-)

Der Frästisch ist untenrum jetzt auch etwas schallgedämpft, hoffentlich bringt's was: ich hatte da noch etwas Akustikschaum-ähnliches Verpackungsmaterial rumliegen, seitlich ist es nur magnetisch befestigt und hinten mit Schrauben und einer provisorischen Zwinge, damit die Platte bei Bedarf auch als Anschluss für einen Staubsaugerschlauch herhalten kann.

Einen 24er Schlüssel habe ich auch noch gefunden, wenn die Wiki-Seite noch ein, zwei Fotos zur Doku hat können wir das "commissioning" dann beenden :-D
