### ISSUE TITLE
Anschaffung: Staubabsauggerät(e)

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#193]
Mit der Anschaffung der Abrichte sollten wir unsere Staubabsaugung in der Holzwerkstatt ausbauen. Wir haben mittlerweile mehrere Geräte die eine, mehr oder minder feste, Absaugung zur Verwendung brauchen und die BAMATO AB-550, die wir als Dauerleihgabe haben, reicht hierfür nicht mehr aus.

Martin und ich waren heute bei einer Hausmesse von Felder Group in Bruchsal und haben uns unter anderem mal die Staubabsauglösungen von denen angeschaut. Dabei hat uns die AF14 ganz gut gefallen, da die recht solide aussah, gute Unterdruck und Volumenwerte hat, sowie einen optionalen M-Klasse Staubfilter hat. Preislich liegt der bei 450€ und der M-Filter bei 339€ (ohne MwSt) ([s. Felderkatalog](http://fms.felder-group.com/Aktionen/FJA/2020/Gewerbe/FE_FJA_2020_Gewerbe_DE-neu/50/#zoom=z)).

Günstigere Alternativen kann man schon für weitaus weniger Geld haben, wie z.B. die [scheppach Hd12](https://www.ebay.de/p/1520555484), oder die BAMATO AB-550, für knapp über 100€. Ich persönlich würde da eine etwas leistungstärkere Absaugung als Neuanschaffung bevorzugen; auch im Hinblick der Langlebigkeit.

Eine mittlere Klasse wäre die [Holzmann ABS1500FF](https://www.maschinenhandel-gronau.de/holzbearbeitung/absaugung/16512/holzmann-dust-collector-abs1500ff) für 300€ mit ca. halber Saug- und Volumenleistung.

Falls jemand weiteren Input hat immer her damit.

**Comment by LukasFreeze** [comment]
Ich finde eine Absaugung mit echtem Staubfilter auf jeden Fall gut für Tischkreissäge und Bandsäge (und was noch so kommen mag), das sollten wir also gerne zur Voraussetzung bei einer Neuanschaffung machen - damit fliegen Scheppach und Bamato für mich schonmal raus, von der Qualität des Motors wahrscheinlich ganz zu schweigen.

An der Abrichte sollte weniger feiner Staub anfallen, daher könnte die Bamato-Anlage in Zukunft dort angeschlossen werden (Luftstrom reicht völlig aus)!

Also zu den übrigen Vorschlägen:

Bei **Felder** schreckt mich der Preis ehrlich gesagt immer noch ab, auch wenn wir natürlich Qualität kaufen sollten und glücklicherweise ein paar in dieser Richtung gebundene Mittel übrig haben ist das echt ein Wort! Und was mir fehlt, vor allem für die (vermutliche) Hauptnutzung mit der Tischkreissäge, ist ein automatischer Start mit dem Bearbeitungsgerät. Die zusätzlich erhältliche [Anlaufautomatik-Kiste von Felder](https://de.feldershop.com/Absaugen/Absauggeraete-Steuerung/Anlaufautomatik.html) ist durch Tischkreissäge und Bandsäge nicht triggerbar, da die nur 230 V brauchen...

**vielleicht findet da jemand ein alternatives Bauteil?** soweit ichs verstehe sollte zB diese hier funktionieren:
- [2x Master 230 & 400 V, 2x Slave 230 & 400 V](https://www.amazon.de/dp/B01B4F8X3A)

Der Preis bliebe also mein einziges Argument gegen Felder, aber wie du schon sagst ist die **Holzmann**-Maschine viel schwächer :-/  Dass viel Leistung gut wäre sehe ich wie du, das erlaubt uns hoffentlich mittelfristig den Anschluss an ein Rohrsystem...

Ich habe noch eine [**Jet**-Anlage](https://professional-tools.de/maschinen/absaugen-filtern/jet-dc-1100ck-t-absauganlage-400v) inkl Filter für ca 600 € ohne MwSt gefunden, allerdings auch die ohne Anlaufautomatik und mit deutlich weniger Leistung.

Aber was wäre denn hiermit: [**Bernardo** DC 350 F](https://professional-tools.de/maschinen/absaugen-filtern/bernardo-absauggeraetes-dc-350-cf)? Die hat einen höheren Volumenstrom, aber etwas schwächeren Unterdruck als die Felder AF14 (was ist wichtiger??) und kostet inkl. Filter ohne MwSt unter 450 €.

**Comment by Pakue95** [comment]
Wenn die Anlaufautomatik als Master nur CE Anschlüsse hat kann man auch einen CE-Schuka Adapter verwenden. Ich denke nicht dass die Trigger auf allen 3 Phasen Strom brauchen um auszulösen. Die Einheit, die du verlinkt hast sollte funktionieren. Hier eine gleiche von Holzmann: 

https://www.maschinenhandel-gronau.de/holzbearbeitung/absaugung/11/holzmann-compact-distribution-box-ala1

Bei der Kreissäge würde ich annehmen, dass der Unterdruck wichtiger ist, da wir am Ende eine starke Verjüngung zur Säge hin haben, die den Volumenstrom sowieso limitiert. 

Über ein Rohrsystem haben wir uns auch bei Felder unterhalten, aber bei den Strecken in der Werkstatt (10-15m Kreissäge-CNC) braucht man schon nochmal eine deutlich größere Absaugung um die 20m/s laut BGV einzuhalten. Wenn die Luftgeschwindigkeit deutlich darunter liegt läuft man Gefahr, dass sich der Staub im Rohr absetzt. Da reden wir dann eher in der Größenordnung von einer RL 160 bzw RL 200, was dann doch nochmal eine ganz andere Investition ist...

**Comment by LukasFreeze** [comment]
Ich würde sagen das hier kann zu: die eigentliche Anschaffung ist erledigt, "commissioning" geht [im Wiki](https://wiki.comakingspace.de/Dust_Extractors#Felder_AF_14) weiter und die Infos bezüglich Rohrsystem packe ich nochmal in #77 :-)
