### ISSUE TITLE
PPE Drucken

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#194]
Hallo zusammen,

aus verschiedenen Richtungen erreichen uns aktuell Anfragen, ob wir Möglichkeiten haben, Schutzausrüstung zu drucken.

Dazu haben wir Maker aus Heidelberg zusammengetragen, die Zuhause einen oder mehrere 3D Drucker stehen haben und bereit sind zu helfen. Koordiniert wird das Ganze in einer WhatsApp Gruppe und einem Google Sheet.

**Aktueller Druck**
Aktuell drucken wir folgende Datei:

https://www.prusaprinters.org/prints/25857-prusa-protective-face-shield-rc3
( covid19_headband_rc3.stl )

***Archive***
*MediFrames*
[medi-frames-v5.zip](https://github.com/comakingspace/do-something/files/4381184/medi-frames-v5.zip)
Gute Ergebniss bekommen wir mit PLA, 10% Infill, ca. 1mm (0.9mm) Wandstärker und einer extrusion von 50mm/min. Damit kommen wir auf ca. 30min vom Slicer geschätzte Druckzeit

Auf einen Prusa bekommen wir 2 Einheiten des Objekts. Mit Schichthöhe 0,35mm kommen 2 Stück auf eine Druckzeit von ca. 1h

*Große Klemme*
[Grose Klemme du_nn.zip](https://github.com/comakingspace/do-something/files/4393076/Grose.Klemme.du_nn.zip)
> Es muss realtiv stabil gedruckt werden da es vielmaliges aus und einklemmen von Kabeln standhalten muss.
> Ganz gute Ergebnisse erziehlen wir mit:
> Layer Height 0.2, Wandstärke 1mm, Infill 20%, Printspeed 70mm/s auf nem Ultimaker 3
Ziel: 120 Stück

*Kleine Klemme*
[kleine Klemme.zip](https://github.com/comakingspace/do-something/files/4388802/kleine.Klemme.zip)

> Es muss realtiv stabil gedruckt werden da es vielmaliges aus und einklemmen von Kabeln standhalten muss.
> Ganz gute Ergebnisse erziehlen wir mit:
> Layer Height 0.2, Wandstärke 1mm, Infill 20%, Printspeed 70mm/s auf nem Ultimaker 3

[Absaughalter.zip](https://github.com/comakingspace/do-something/files/4405597/Absaughalter.zip)

*Absaughalter*
> Das Modell sollte realtiv stabil gedruckt werden.
> Ganz gute Ergebnisse erziehlen wir mit:
> Layer Height 0.2, Wandstärke 1mm, Infill 20%, Printspeed 70mm/s auf nem Ultimaker 3

**Comment by dazim** [comment]
1x Ender-3 (1.0 mm nozzle),  23,5x23,5, Druckt=Ja

**Comment by oriri** [comment]
kann morgen Vormittag ab ca. 10:00 auf 3 CR10V2 drucken. leider nur 0.4mm Düsen. mit 100mm/s und 0.3mm Schichtdicke und 20% Infill komme ich auf 30min Druckzeit

**Comment by S-Kallenberger** [comment]
1x Ender-3, 23,5x23,5, Druckt=Ja

**Comment by NitramLegov** [comment]
Achtung, Update: Es gibt jetzt schon ein neues Design. Bitte die V5 drucken, die oben angehängt ist :)

**Comment by JonasEuchnner** [comment]
1x CR-10, 30x30, ab heute abend

**Comment by ragflyer** [comment]
2x, Eigenbau 21x21, heute 18:00, kann sie in CoMS einwerfen falls das hilft

**Comment by NitramLegov** [comment]
@ragflyer Danke! Kommst du aus dem Stadtgebiet Heidelberg? Ich würde dann morgen Abend rumfahren (so ab 18/19 Uhr denke ich) und die Sachen einsammeln. Dafür bräuchte ich nur eine Adresse, zu der ich dann eben kommen soll.

**Comment by EricMb96** [comment]
1x Anycubic i3 Mega S; Druckt = Ja

**Comment by dazim** [comment]
In Vertretung:

Timo, Anet A2 plus, druckt=ja

**Comment by JCS22** [comment]
2x CR10S, Druck=ja, 16 fertig

**Comment by VenaHarambeMagma** [comment]
1x Prusa Mk3s, ab jetzt. wird noch kleine Klemme.zip gedruckt?

**Comment by Pakue95** [comment]
Momentan Die Große Klemme (Siehe ganz oben).

**Comment by Pakue95** [comment]
Schilde uÄ. sind mittlerweile wieder ohne Lieferengpässe zu bekommen. 

Nochmal vielen Dank an alle Leute die bei der Aktion so tatkräftig mitgeholfen haben!
