### ISSUE TITLE
Online-Workshops/Webinare entwickeln

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#195]
Solange der aktuelle Shutdown anhält können wir uns vielleicht per Videokonferenz zu angesagten Themen austauschen oder sogar richtige Vorträge ausarbeiten! Großer Vorteil wäre bei denen, dass man sie auch nach Wiedereröffnung als Seminar im Gemeinschaftsraum wiederholen könnte :-)

Als Anregung für Themen und zur Übersicht der möglichen Tutoren haben wir ja schon immer die ["Seminar Ideas" im Wiki](https://wiki.comakingspace.de/Seminar_Ideas), vielleicht findet da jemand etwas passendes für sich? Meldet euch einfach wenn ihr Ahnung von irgendwas habt und wir finden bestimmt einen guten Termin!

Außerdem hab ich Anfang der Woche in der [Telegram-Gruppe](https://wiki.comakingspace.de/Telegram_Group) eine kleine Umfrage laufen lassen und es kam dieses Ranking der gewünschten Themen raus (ca. 20 Teilnehmer): 
- 3D-Design/-Druck (10 Stimmen)
- Elektronik (7)
- Gärtnern (7)
- Kochen/Backen (6)
- Programmieren (6)
- 2D-Design/Zeichnen (5)
- Metall-Theorie (4)
- Nähen/Häkeln/Stricken (4)
- Wiki (2)
- Holz-Theorie (2)

Daraufhin gab es auch schon kurze Meldungen von möglichen Tutoren! Konkretere Details willkommen ;-)
- Kochen: @FHuchinson , Ciara (vegan), @LarsKumbier 
- Gärtnern: Dirk (Mischkultur, biologische Schädlingsbekämpfung)
- 3D: @LarsKumbier (Blender), @reogaro (OpenSCAD)
- 2D: @LarsKumbier (Gimp, Inkscape)
- Holz: @LarsKumbier 
- Programmieren: @LarsKumbier , @kenomaerz (Python)
- Git/Github: @kenomaerz

**Comment by Titan-OX** [comment]
I'm planing on hosting a blender beginners webinar for 3d printing. I wanted to cover things you can't model easily in Fusion. I would like to have a trial with 1 student (no prior experience) first to have a time estimate, make sure streaming works and get feedback.

**Comment by NitramLegov** [comment]
I would offer myself as a test student :)

**Comment by LukasFreeze** [comment]
Morgen Abend (Donnerstag) geht es mit Dirks Gärtner-Session los! 20 Uhr im [bewährten "whereby"-Raum](https://kumbier.whereby.com/comakingspace) :-)

**Comment by LukasFreeze** [comment]
Das Thema "3D" war ja laut Umfrage am beliebtesten, vielleicht könnten wir kommende Woche dazu etwas veranstalten? 

@Titan-OX Wie steht es um das Blender-Intro? @LarsKumbier hatte sich ja auch dafür angeboten, habt ihr beiden euch schonmal ausgetauscht? :-)

Außer Blender hatte @reogaro noch OpenSCAD vorgeschlagen, das wäre auch sicher interessant! Bist du da schon startklar oder müsstest du noch was vorbereiten?

Als "Notlösung" könnte ich eine Session mit Tinkercad anbieten, für blutige Anfänger und Kinder könnte das ein netter Einstieg vor den richtigen Tools sein...und ich mach ehrlich gesagt immer noch recht viel damit, wenn es schnell gehen soll ;-)

SketchUp könnte ich auch mal zeigen, besteht daran Interesse?

**Comment by Titan-OX** [comment]
Ja ich bin dabei was zusammen zu stellen. Ich wollte das vorher noch mal mit @NitramLegov testen um feedback zubekommen und die streaming technik auf die probe zu stellen.

**Comment by Titan-OX** [comment]
Blender seminar war erfolgreich und alle Teilnehmer könnten eine 3d druckbare  Tasse modellieren ich kann im Sommer wahrscheinlich noch Mal ein Seminar geben. **Whereby Tipp**: ich hatte im Probe Lauf mit @NitramLegov kein Mauszeiger in der Übertragung. Die "Lösung" war von Firefox auf Chrome umzusteigen.

**Comment by NitramLegov** [comment]
Inzwischen haben Stattgefunden:
- Gärtnern (Fokus Mischkultur) von Dirk
- Blender (Fokus auf dem Design einer 3D druckbaren Tasse) von Luzian
- KI in der Medizin von Keno
Das finde ich eine ordentliche Ausbeute. Luzian hat sogar schon das nächste Blender Seminar angekündigt :)


@LukasFreeze Hatte mich angesprochen, ob ich noch ein Development Seminar zum Thema Bot-Entwicklung machen könnte. Ich würde mich hierbei auf eine Extract - Load - Transform Strecke von Twitter auf Slack oder ähnlichem fokussieren und schaue mal, was ich in den nächsten Wochen hinbekomme :)

**Comment by NitramLegov** [comment]
Ich glaube wir können uns wieder auf physische Workshops konzentrieren :-)
