### ISSUE TITLE
Metal Lathe Electricity

### ISSUE THREAD

**Issue by Titan-OX** [comakingspace/do-something#196]
The big metal lathe isn't connected to an outlet since we moved to the new space. It's motor runs on 3 phase ac and it is my understanding that the peek current draw during startup would overwhelm the fuse. Therefore the outlet it was hooked up to in the old space hat some kind of current limitation feature. Before we can use the lathe again we have to
- bolt it down 
- get 3 phase ac to it (nearest outlet is next to the sink)
- install some kind of protection circuit (VFD would also allow speed control)

**Comment by Titan-OX** [comment]
Update: I've decided to move the lathe to the left next to the fire hose where currently the metal storage is located. This move was decided because it increases the distance to the angle grinders and decreases the distance to the 3 phase outlet to an extent where we can use the old rubber cable of the lathe.

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by Johannes09** [comment]
Elektrisch fehlt nur noch ein Motorschutzschalter mit Gehäuse 1-1,6A
z.B. [amazon](https://www.amazon.de/Motorschutzschalter-1-1-Geh%C3%A4use-M25-Kabelverschraubung/dp/B0849VH7LR/ref=mp_s_a_1_8?dchild=1&keywords=motorschutzschalter+mit+geh%C3%A4use&qid=1619162982&sprefix=motorschutzschalzer+mit+ge&sr=8-8) 34,50

**Comment by LukasFreeze** [comment]
Den spende ich! Ist bestellt :-)

Leo hat übrigens Bier-Belohnung für eine Einweisung ausgesetzt wenn die
Maschine dann wieder läuft :-D

**Comment by Titan-OX** [comment]
Ich wollte ja noch Tutor dafür werden.

**Comment by NitramLegov** [comment]
Das ist ja geil. Ich wollte gerade auf Bestellen drücken da hab ich die Mail von Lukas gesehen 😅 Danke Lukas!

@Titan-OX Lass uns mal gemeinsam im Whereby "hirnen", wie wir das hinbekommen. Aktuell dürfen sich ja nur zwei Haushalte treffen, das macht unser klassisches Modell "Geschäftsführer + neuer Tutor + Mitglied" für neue Tutorenschaften natürlich unmöglich. Aber vielleicht finden wir ja gemeinsam eine Lösung, die auch in Corona-Zeiten tragfähig ist!

**Comment by LukasFreeze** [comment]
@NitramLegov kannst du selbst denn schon drehen? Du könntest ja Geschäftsführer und Lehrling in Personalunion sein :-P

**Comment by Johannes09** [comment]
Ich habe die Drehmaschine angeschlossen. 
Aber bevor wir die jetzt freigeben, ist es sinnvoll noch ein paar Dinge zu machen die jeder machen kann der die Freigabe vorantreiben möchte. 
Drehbank reinigen
- Gehäuse
- Zahnräder der Zugspindel entfetten und neu fetten
- Laufflächen reinigen und neu schmieren 
- …
Standort festlegen und im Boden verschrauben
Drehbankspezifisches Werkzeug zur Drehbank legen
…

@Titan-OX 
@reogaro

**Comment by reogaro** [comment]
Gestern haben @Johannes09 und ich unter mehr oder weniger fleißiger Aufsicht von @Titan-OX die Maschine gereinigt und geölt. Es war keine Grundreinigung aber die Oberflächen kann man jetzt wieder anfassen und die Zahnräder haben keinen pechschwarzen Film mehr. Die Laufflächen haben auch neue Schmiere.
Es fehlt noch die Verschraubung. Die Drehmaschine ist auf zwei Balken aufgebockt und ich sehe keinen Grund sie nicht im namen der Transportfreundlichkeit auf diesen zu verschrauben, dann könnte man sie einfach mit der Ameise verschieben.

Außerdem zu tun, aber nicht für die Inbetriebsnahme nötig:
- Das scheinbar fehlende 21er Zahnrad finden oder ersetzen
- Die extra Zahnräder säubern (Ultraschallreiniger wäre hierfür perfekt!)
- Das Werkzeug sortieren und organisiertere Lagermöglichkeiten schaffen

**Comment by Fragegeist** [comment]
> 
> 
> Gestern haben @Johannes09 und ich unter mehr oder weniger fleißiger Aufsicht von @Titan-OX die Maschine gereinigt und geölt. Es war keine Grundreinigung aber die Oberflächen kann man jetzt wieder anfassen und die Zahnräder haben keinen pechschwarzen Film mehr. Die Laufflächen haben auch neue Schmiere.
> Es fehlt noch die Verschraubung. Die Drehmaschine ist auf zwei Balken aufgebockt und ich sehe keinen Grund sie nicht im namen der Transportfreundlichkeit auf diesen zu verschrauben, dann könnte man sie einfach mit der Ameise verschieben.
> 
> Außerdem zu tun, aber nicht für die Inbetriebsnahme nötig:
> 
>     * Das scheinbar fehlende 21er Zahnrad finden oder ersetzen
> 
>     *** Die extra Zahnräder säubern (Ultraschallreiniger wäre hierfür perfekt!)**
> 
>     * Das Werkzeug sortieren und organisiertere Lagermöglichkeiten schaffen


Moin,
ich habe ein 10L Ultraschallbad daheim - passen die zu reinigenden Zahnräder da wohl rein? Wenn ja, könnte ich das übernehmen bzw. das US-Bad auch sonst flexibel zur MakingHour mal mitnehmen.

**Comment by reogaro** [comment]
> ich habe ein 10L Ultraschallbad daheim - passen die zu reinigenden Zahnräder da wohl rein? Wenn ja, könnte ich das übernehmen bzw. das US-Bad auch sonst flexibel zur MakingHour mal mitnehmen.

Wunderbar. 10L sind locker genug. Ich würde vorlschlagen das ich am kommenden Do-Something Samstag eine "Zu Waschen"-Kiste zum mitnehmen zusammenstelle da die Zahnräder sicher deutlich einfacher zu Transportieren sind als so ein klobiger 10L Oschi.

Oder gibt es vielleicht generell noch mehr Werkzeuge und Teile die vom Anschleppen eines Ultraschallreinigers profitieren würden? @LukasFreeze du weißt das warscheinlich am besten?

**Comment by Titan-OX** [comment]
Soweit ich das sehe ist die Drehbank soweit wieder einsatzbereit. Ich werde sie bei Gelegenheit mit @Pakue95 noch einmal durchgehen und dann sollte sie endlich wieder freigegeben werden

**Comment by Pakue95** [comment]
@Titan-OX und ich sind die Drehbank am WE durchgegangen und sieht soweit gut aus. Die Stromversorgung muss man momentan via einem CE Verlängerungskabel (das von der Abrichte) lösen, bis wir neue Leitungen in der Werkstatt gelegt haben. Bitte nach Verwendung wieder wegräumen, da das Kabel sonst ungünstig vor dem Waschbecken liegt.
