### ISSUE TITLE
Fusion 360 - Clean up Project and link wiki

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#197]
Since we have quite a few Fusion 360 Designs which we use around the space, there is a new fusion 360 Team and Project for us:
https://mygmx17088.autodesk360.com/g/all_projects/active (this should link to the team. Please let me know if it does not)
https://mygmx17088.autodesk360.com/g/projects/20200315274960626/data/dXJuOmFkc2sud2lwcHJvZDpmcy5mb2xkZXI6Y28uMWg0aF81NGpUNHVjdWdWZFV6WThHdw (this should link to the project. Please let me know if it does not)

Since the structure in there grew historically and has been migrated from two different projects, we need to clean this up a bit:
- [x] Properly fit all files in the correct folder. Create a new one if there is no fit

After this, we should make sure that our wiki links to the files so that they can be found by others easily as well:
* Find the files to be linked from the wiki
* Find the correct wiki page
* Create public link to the file
* Link file

**Comment by Johannes09** [comment]
Gute Idee! Ich finde es gut, dass du dich darum kümmerst.

**Comment by NitramLegov** [comment]
I have deleted the file since apparently nobody knew what it was
