### ISSUE TITLE
"Heißmetall"-Ecke

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#199]
Es gab nach dem Umzug immer mal wieder Ideen, wie wir Schweißecke & Co. hier in der Halle aufbauen könnten - bündeln wir das doch alles mal hier :-)

* (mindestens) Simon und Helmuth haben Hilfe angeboten, um in Zukunft schweißen zu können
* Andi E. würde gerne eine Esse haben
* @lmnl99 und @Chris0812 sind eure Schmelzöfen noch aktuell?
 
Mein Vorschlag wäre ein Bereich für das alles - gemeinsame Voraussetzung ist nämlich eine Abluft! Wir haben einen ausreichend starken Lüfter vom Laser übrig (#179), daran hätte ich eine Art Abzugshaube mit Aktivkohlematte als erste Stufe angeschlossen. @Pakue95 hat vorgeschlagen, darauf folgend noch eine längere Rohrstrecke zur Kondensation von Metalldämpfen folgen zu lassen bevor der Rest dann raus geht.

Wie wäre es mit dem Bereich direkt links vom Hinterausgang, wo jetzt auch schon die Schweißausrüstung steht? Die Fenster direkt oberhalb des Tores müssten sich anpassen lassen falls wir die Abluft nicht direkt durch das große Fenster legen können.

**Comment by Titan-OX** [comment]
Links neben dem Tor sind auch die einzigen Fenster die nicht aus Glas sind.

**Comment by Titan-OX** [comment]
Wichtig wäre dass alle Schläuche hitzebeständig sind den anders als der Laser werden heiße Metall Funken eingesaugt. Ein Ofenrohr würde den thermischen Anforderungen gerecht werden jedoch sind diese nicht flexibel. Wie zuversichtlich seid ihr was die laser Abluft angeht?

**Comment by LukasFreeze** [comment]
> Wie zuversichtlich seid ihr was die laser Abluft angeht?

Was meinst du damit - ob der übrig gebliebene Motor genug Luft zieht und
die Wärme aushält? Wenn der Motor erst gegen Ende der Rohrstrecke verbaut
ist mache ich mir da keine großen Sorgen :-)

Auch beim Rohr könnten wir vielleicht nach einem Meter hitzebeständigem
Rohr auf etwas flexibleres wechseln, was meint ihr? Selbst wenn wirklich
Funken hochgezogen werden, glühen die ja immer sehr schnell aus.

**Comment by LukasFreeze** [comment]
@Pakue95 und ich haben uns die Ecke letzte Woche nochmal genauer angeschaut und ein ungefähres Konzept aufgestellt :-)

![IMG_20200811_132921_727](https://user-images.githubusercontent.com/19755883/89934727-52354900-dc11-11ea-9b8e-dda23ee9659b.jpg)

Hübsch, nicht wahr?

Diese Schritte wären zu erledigen, bevor wir überhaupt eine Durchführung der Abluft ins Fenster schneiden (rot):
* Absaugelemente "Rüssel" und "Haube" bauen (grün), zum Beispiel aus dem bereitliegenden Trockenbauprofil mit praktischer Gitterstruktur und irgendwelchen Blechen. Falls dafür die grünen Bleche im Fundus interessant wären, könnte ich nochmal mehr besorgen!
* Montage und Anschluss des Lüfters (weiß) - wir denken dass schon HT-Rohre ausreichen würden, wenn jemand flexibles Material für solche Anwendungen kennt wäre das aber sicher interessant!
* Montage der Abzugshaube über die Wand, NICHT direkt an die Scheibe (braun) - könnten zB zwei Holzbalken werden, die dann aber hinter einem Blech verschwinden sollten

Zögert nicht mit Nachfragen, ansonsten frohes Schaffen falls sich schon jemand damit beschäftigen kann!

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by Titan-OX** [comment]
Wäre es schlau eine Dunstabzugshaube einfach zu kaufen? Aus der laserabluft kann man noch ein Rüssel machen

https://www.ebay-kleinanzeigen.de/s-anzeige/dunstabzugshaube/1811347825-86-8256

**Comment by LukasFreeze** [comment]
Oh ja, das würde es sicher wesentlich vereinfachen 😅

Ich bin dafür und gebe gerne auch Geld dazu!

**Comment by produkt-manager** [comment]
Je nach Schweißverfahren handelt es sich um Gefahrstoffe. Professionelle Anlagen sind so aufgebaut https://www.kemper.eu/de/wissenswertes/schweissrauch-vorschriften-und-gesetze/massnahmen-zur-schweissraucherfassung. Vorschriften: https://www.arbeitssicherheit.de/schriften/dokument/0%3A3554989%2C5.html.

**Comment by LukasFreeze** [comment]
Genau, deshalb konnten wir das Schweißen seit unserem Umzug leider noch
nicht wieder ermöglichen - das alte Gebäude hatte einen Hinterhof, wo wir
eine oben offene Kabine aufgestellt haben, und jetzt würden wir mit Punkt-
und Flächenabsaugung (mit Ableitung nach draußen!) die nächstbessere Lösung
aufbauen :-)

**Comment by produkt-manager** [comment]
... die Grafiken und deren ganzer Text zeigen dann, welche Volumenströme für die einzelnen Schweißverfahren und wo mindestens nötig sind. Siehe hier https://www.kemper.eu/de/wissenswertes/absauggeraet-ueberblick-einsatzbereiche

**Comment by Titan-OX** [comment]
Ich würde die Kabine oben gerne geschlossen haben sodass die Abluft keine Luft von der Seite zieht

**Comment by Titan-OX** [comment]
https://www.ebay-kleinanzeigen.de/s-anzeige/abzugshaube/1802020617-86-8136

https://www.ebay-kleinanzeigen.de/s-anzeige/abzugshaube-whirlpool-haube-1-woche-benutzt/1585341374-86-5191
Meinungen?

**Comment by LukasFreeze** [comment]
Ich wär für sowas wie die erste, schön viel Fläche - muss halt nur jemand
abholen können 🙈

**Comment by Titan-OX** [comment]
ich könnte mich opfern. oder wir fragen jonah oder leo

**Comment by Fragegeist** [comment]
Moin,
ich schalte mich mal in die Diskussion hier ein. Ich bin noch sehr frisch bei euch dabei bzw. komme jetzt erst dazu, aber haber selber großes Interesse an der Schweißecke - ergo mag ich gerne auch mithelfen, falls gewünscht.
Da ich in Wiesloch arbeite ist die Kleinanzeigen Variante 1 für mich gut erreichbar. Ich könnte die Haube die Tage duchaus abholen, wenn es ein Konsens-Ja für die geben sollte. 
LG
Alex

**Comment by Fragegeist** [comment]
Guten Morgen.
Die Haube aus Kleinanzeigen Link 1 ist geklärt und wir nächste Woche Dienstag abgeholt. Bringe sie dann nächsten Mittwoch in den Space.

**Comment by Titan-OX** [comment]
Hat alles geklappt?

**Comment by Fragegeist** [comment]
"noch" nicht. Verkäufer stand im Stau. Hole die Haube morgen Nachmittag dann aber sicher ab und komme direkt zum Space damit. Bin eh ab 17 Uhr bei Lukas zur weiteren Einweisung und danach noch zur Hour da ;)

**Comment by Titan-OX** [comment]
![IMG_20210724_005952.jpg](https://user-images.githubusercontent.com/22505956/126850812-21447412-3312-4eb7-8f98-472217a32946.jpg)

Die Halterung ist da aber die Abluft ist noch nicht festgeschraubt. 

Was noch gemacht werden muss:
- [ ]  Abluft befestigen
- [ ]  Laser Abluft montieren (Push or pull?)
- [ ]  "Rüssel verlegen"
- [ ]  Fliegengitter für draußen kaufen
- [ ]  2 Löcher in die Scheiben schneiden
- [ ]  Venting/plumbing
- [ ]  Strom für Abluft und Schweißgerät
- [ ]  Abnehmen lassen

**Comment by LukasFreeze** [comment]
Fliegengitter kann ich mitbringen und dazulegen, wenn ich damit zu langsam bin kann man ja immer noch was kaufen ;-)

**Comment by Titan-OX** [comment]
![IMG_20210814_212759.jpg](https://user-images.githubusercontent.com/22505956/129459475-01293cea-43cb-4773-9d73-a2a8d0502d48.jpg)

Die Anzugshaube ist festgeschraubt und wirkt sehr stabilisierend.

**Comment by Titan-OX** [comment]
Was noch gemacht werden muss:
- [x]  Abluft befestigen
- [ ]  Laser Abluft und Brett fixieren
- [ ]  mehr Alurohr kaufen [ebay](https://www.ebay.de/itm/332242666885?_trkparms) in 150mm
- [ ]  "Rüssel verlegen"
- [ ]  2 Löcher in die Scheiben schneiden, so hoch wie möglich
- [ ]  Rohre nach zu den Löchern legen
- [ ]  Strom für Abluft und Schweißgerät
- [ ]  Wiki updaten ([intro](https://wiki.comakingspace.de/Arc_Welding_Introduction), Welding [Enclosure](https://wiki.comakingspace.de/Welding_Enclosure) & [Category:Welding](https://wiki.comakingspace.de/Category:Welding#Setup)
- [ ]  Abnehmen lassen

**Comment by Titan-OX** [comment]
Ich hab gestern noch Mal gemessen wie viel Rohr wir noch brauchen. 
Der Rüssel Bracht min 1.8m und die Rohre zum Fenster jeweils ca 2m. Wir haben von der laserabluft noch ein 2m Schlauch den ich für die Dunstabzugshaube nehmen würde da dort weniger Funken durch fliegen.
Heißt 3m Alu Schlauch reichen nicht aber 5m sollte hinkommen.
[5m von Amazon](https://www.amazon.de/Intelmann-Alu-Flexrohr-150mm-L%C3%A4nge/dp/B010BEVJUO)

**Comment by NitramLegov** [comment]
Ich habe den Schlauch bei Amazon bestellt und frech beschlossen, dass ich ihn zu Lukas schicken lasse.

**Comment by Titan-OX** [comment]
Der Schlauch ist im space angekommen und Nana und ich haben Vorbereitungen getroffen das Loch im Fenster zu schneiden. Voraussichtlich machen wir Freitag weiter

**Comment by Titan-OX** [comment]
Danke an Luca und @reogaro für die Hilfe beim Bohren am Samstag ![IMG_20210918_133825.jpg](https://user-images.githubusercontent.com/22505956/134306274-011dc9d8-e711-4868-8c0a-e9ef399c1ca5.jpg)

Wir haben die Maske auch gleich festgeschraubt und die Schläuche durchgesteckt. Der schwarze Schlauch für die Dunstabzugshaube ist etwas kurz und muss eventuell noch mit einem Stück Rohr verlängert werden. ![IMG_20210918_143922.jpg](https://user-images.githubusercontent.com/22505956/134307210-31ad507c-ab22-4cc3-8d16-1389cb04a391.jpg)
![IMG_20210918_144100.jpg](https://user-images.githubusercontent.com/22505956/134307266-032b8c4a-6137-48d3-b679-6ea720135592.jpg)
Ein Fliegengitter wäre eventuell auch noch gut zu haben.

Wie gut die Schläuche halten wenn die Motoren vibrieren ist noch nicht sicher. Wir sollten sie am besten noch richtig festmachen

**Comment by LukasFreeze** [comment]
Huch, ich dachte der schwarze Schlauch wird der "Saugrüssel" für unten? Die
Aludinger halten ja mechanisch nicht sehr viel aus und dürften schnell
Löcher bekommen wenn sie bewegt werden, oder wie ist da der Plan?

Die Schläuche außen richtig festzumachen wäre auf jeden Fall wichtig, da
ärgern wir uns nur später drüber wenn sie sich im Zweifel mitten im Projekt
lösen...

**Comment by Titan-OX** [comment]
Ich wollte was Funkenfestes als Rüssel haben. Und der Alu Schlauch bleibt auch besser in Position.

**Comment by Blacksheep70** [comment]
Wir sollten uns mal dringend zusammen setzen. Die Keramikwolle würde ich stiften, das macht den Ofen leichter. Ich denke dieser müsste eh mobil konstruiert werden damit er leichter zu handeln und zu parken ist. Schreib mich einfach mal über Telegram an und wir können zusammen was machen. Samstag wäre ich auch im Space und hätte ab 12 Zeit.

**Comment by FHuchinson** [comment]
Ich hab halt keinen Schlüssel für den Space und müsste daher jemandem Beiwohnen. Aber klar Telegram wär mir auch lieber.

**Comment by Titan-OX** [comment]
BTW wenn ich das issue abgeschlossen hab widme ich mich wieder Einweisungen

**Comment by LukasFreeze** [comment]
Hier ist wieder was passiert seit dem letzten "do-something day" :-)

Sven und @Johannes09 haben sich bohr-lose Befestigungsmöglichkeiten an den Stahlträgern überlegt, wir haben den offenen Träger unkompliziert mit OSB verkleidet und @Titan-OX hat gestern probeweise einen Teil des Vorhangs aufgehangen - sieht gut aus, ich Depp hab nur kein Foto gemacht!

Für das letzte Stück fehlten noch ein paar Seilklemmen und zusätzliche Ösen wären auf ganzer Länge gut. Dazu idealerweise noch Magnete zum Wandanschluss und etwas Überlappung zwischen den einzelnen Vorhängen und das ganze ist schön blickdicht :-)

**Comment by Titan-OX** [comment]
![IMG_20220223_203156.jpg](https://user-images.githubusercontent.com/22505956/155598389-d73fdb89-fbd2-40f0-ae9f-812be5a5b8dd.jpg)

Gut das ich ein Bild hab

**Comment by NitramLegov** [comment]
Ich habe @Titan-OX Magnete versprochen, die sich für die Befestigung des Vorhangs eignen könnten. Die bringe ich bei einem meiner nächsten Besuche mit.

**Comment by SebMakesThings** [comment]
Braucht ihr noch Ösen und falls ja welcher Durchmesser würde ausreichen? Glaube ich hab noch ein Sortiment 11mm Einschlagösen.

**Comment by LukasFreeze** [comment]
Ja, die Ösen wären super! Und die Magnete bestimmt auch :-D

**Comment by Titan-OX** [comment]
![IMG_20220319_190422.jpg](https://user-images.githubusercontent.com/22505956/159135494-c55930aa-ceea-488c-a602-5c5067a24e42.jpg)
Vorhang funktioniert

**Comment by Titan-OX** [comment]
https://www.pollin.de/p/v-tac-led-flutlichtstrahler-vt-4051-5959-eek-f-50-w-4250-lm-4000-k-535002
so ein licht brauchen wir für die ecke noch. Das könnte auch an anderen stellen im Space praktisch sein (z.B. drehbank)

**Comment by NitramLegov** [comment]
Ich glaube in meinem Fach auf der kommibench liegen noch so Strahler wie der bei der cnc fräse.

Kannst du gerne haben

**Comment by NitramLegov** [comment]
Kann man denn den Vorhang schnell auf und abbauen? Da der direkt an der Tür ist finde ich das wichtig, um ordentlich rein und rausfahren zu können.

**Comment by Titan-OX** [comment]
halbwegs schnell und ohne Werkzeug

**Comment by NitramLegov** [comment]
Sehr cool! Wie ist das gedacht? Ich würde vorschlagen, dass der Vorhang nach dem Schweißen immer abgebaut wird und eben aufgebaut wird, wenn jemand schweißen möchte.

Wenn wir das so machen sollten wir das noch in die Introduction aufnehmen :)

**Comment by Titan-OX** [comment]
so war das nicht gedacht. Ist dann immer ein act das ding aufzubauen. der vorhang ist nicht 90° zur wand sondern weniger man sollte also mit dem auto noch gut reinkommen

**Comment by NitramLegov** [comment]
Ah, okay. Ich dachte wenn das halbwegs schnell und ohne Werkzeug geht ist das nicht so ein großer act, das auf- und abzubauen.

Dann müssen wir uns das vor Ort mal anschauen und am besten die Meinung der Leute mit einem Fahrzeug einholen :-) wenn die sagen es passt so wäre das fein für mich. Ansonsten müssen wir da halt nochmal nachdenken, wie wir damit umgehen

**Comment by LukasFreeze** [comment]
Ich bin mir auch ziemlich sicher dass das passt, es ragt ja auch nicht in
die Tür rein und müsste auch mit Stangen statt Drahtseilen leicht
trapezförmig verschiebbar sein.

Wenn ich es richtig erkenne sollten wir aber die linke Stange nochmal um ca
30 cm kürzen, da sollte keine Lücke zwischen Vorhang und Wand sein!

Saucool dass ihr die Aufhängung fertig gekriegt habt 😍

**Comment by Titan-OX** [comment]
Ich konnte den roten Vorhang komplett schließen aber es noch Mal zu kürzen halte ich für sinnvoll sowie es anders befestigen

**Comment by NitramLegov** [comment]
Wir haben am Wochenende mit den Fahrzeugleuten gesprochen. Die haben bestätigt, dass es fein ist, wie der Vorhang gerade steht.

Insofern keine Objections von mir an der Stelle :)

**Comment by Fragegeist** [comment]
Moin, 
Haben wir im Space 3-adriges Stromkabel zum Basteln einer Zuleitung.
Ich habe 2*30w LED Strahler besorgt mit denen ich Freitag gerne eine Beleuchtung für die Brennecke basteln möchte.

**Comment by Blacksheep70** [comment]
> Moin, Haben wir im Space 3-adriges Stromkabel zum Basteln einer Zuleitung. Ich habe 2*30w LED Strahler besorgt mit denen ich Freitag gerne eine Beleuchtung für die Brennecke basteln möchte.

Ich müsste noch was übrig haben. Ich komme heute in den Space und lege, was ich gefunden habe, auf die kleine (rote) Fräse. Kannst Dir dann davon nehmen was Du brauchts.

**Comment by Titan-OX** [comment]
Wir haben inzwischen @NitramLegov ´s LED Strahler gefunden aber die sind nicht ganz so toll wie die von dir @Fragegeist. @Johannes09 wird die anschließen wenn er die Steckdosen für die ecke montiert. mit 60W LED sind Automatik Helme gar nicht mal mehr so wichtig XD

**Comment by Titan-OX** [comment]
![IMG_20220406_200441.jpg](https://user-images.githubusercontent.com/22505956/162039691-61be7cd7-5514-4f8e-8e2f-9236aa8447b9.jpg)
Thanks to @NitramLegov for the lamps and thanks to @Johannes09 for the wiring

**Comment by NitramLegov** [comment]
Nice! Was fehlt da jetzt noch? Ist das fertig für die Abnahme?

**Comment by Titan-OX** [comment]
Steckdosen für die Schweißgeräte wären noch geil. Und etwas aufräumen ist auch nicht verkehrt

**Comment by NitramLegov** [comment]
Hier gibt es Neuigkeiten:
Für den neuen Filter des Laser-Cutters wird die bisher in der Schweißecke eingebaute Abluft wieder beim Laser benötigt und ist daher wieder abgebaut.

Als Test haben wir außerdem gestern den schwarzen Schlauch von der Schweißecke abgebaut, weil der neue Laser-File auch einen 150er Schlauch braucht (und der Schlauch da ja initial auch her kommt).
Der Test mit dem Schlauch war nicht erfolgreich. Den Schlauch werden wir daher wieder in der Schweißecke anbringen.

Sobald der neue Filter an den Laser Cutter angeschlossen ist kann die bisherige Laser-Abluft (die gelbe) in der Schweißecke genutzt werden :-)

**Comment by NitramLegov** [comment]
@Pakue95 hat heute gemeldet, dass die Schweißecke doch den van Leuten im Weg steht und daher nochmal 30-50cm versetzt werden muss:
https://coms-hd.slack.com/archives/G010WPMQNBS/p1655482631108199

Ich plädiere nach wie vor für eine Lösung, die leicht und schnell auf und abbaubar ist. Die sollte dann immer nach dem schweißen abgebaut werden :)

**Comment by LukasFreeze** [comment]
Wir haben am Freitag eine Idee getestet, mit der die Vorhänge leicht zu ändern sind aber standardmäßig stehen bleiben können - es geht ja um Arbeitsschutz, wenn es Hürden beim Aufbau gibt wird schnell gepfuscht...

Die Stange auf der rechten Seite (beim Tor) muss durch ein Drahtseil ersetzt werden und der dazugehörige Betoneimer bekommt Rollen. Damit kann jederzeit ohne Kraftaufwand aus dem Quadrat ein Dreieck gemacht werden, aber wir haben nicht das Problem mit dem Durchhängen das wir Drahtseil ringsrum mal hatten. @Titan-OX hatte auch noch die Idee, ein zusätzliches Drahtseil schräg von oben zu spannen, was das Durchhängen nochmal verringert ohne beim "Abbau" im Weg zu sein :-)

**Comment by o-liver** [comment]
Das hier würde ich gerne auf die Agenda für den Do-Something-Day tun. Jetzt kann ich aber nicht alle Kommentare hier lesen. Könnte jemand für uns dieses Thema zusammenfassen und eine ToDo Liste schreiben von dem was noch zu tun ist? Danke!

**Comment by LukasFreeze** [comment]
@o-liver ja, das wäre definitiv ein cooles Projekt für Samstag! Und du hast leider recht, dass man aus diesem Issue aktuell nicht ganz schlau wird: es gab nämlich eine unverhoffte Spende und die ganze Ecke ist jetzt von Messewänden umgeben :-)

Ich versuche mal zusammenzufassen, was meines Wissens noch zu tun ist:
![20230509_231452](https://github.com/comakingspace/do-something/assets/19755883/e89315c0-42c2-42f7-b511-e045b205a739)

- [ ] Stellwände links und rechts an der Wand verankern (orange) - passende Brettchen für je zwei Schrauben liegen schon in den Rahmen
  - [ ] rechts oben muss außerdem noch ein heraussägendes Stück Holz aubgesägt werden, damit das Panel eingesetzt werden kann
- [ ] Vorhang verschiebbar machen (rot) - vielleicht findet sich passendes Schienenmaterial im Fundus?
- [ ] Fliesentischplatte reinbringen auf Tischgestell montieren (lila)
- [ ] Absaugung fertigmachen™ (grün) - da weiß Marcel K mehr und will soweit ich weiß auch kommen
- [ ] "Werkzeugwand" (Sperrholzplatte) an die freie Wand (blau) schrauben, lehnte neulich irgendwo außen

Gerne ergänzen falls hier noch was fehlt :-)

**Comment by o-liver** [comment]
> rechts oben muss außerdem noch ein heraussägendes Stück Holz aubgesägt werden, damit das Panel eingesetzt werden kann

Wäre es nicht besser wir bewegen die Wände 10 cm nach rechts, dann müssen wir da nichts absägen? Wer hat denn diese platte für die absauge zugeschnitten? Vielleicht hat sich die Person dabei etwas gedacht. 
![20230513_113637.jpg](https://github.com/comakingspace/do-something/assets/29037234/01737e42-3a1d-4e98-81cf-08d7efcfe13b)

**Comment by o-liver** [comment]
Wir sägen es ab.

**Comment by Pakue95** [comment]
@NitramLegov und ich sind gerade nochmal durchgegangen und haben folgende Punkte festgestellt, die noch umgesetzt werden müssen.

1. Die Absaugung an der gelben Lüftung braucht noch einen Einlass um direkt am Tisch absaugen zu können. Momentan ist das Lüftungsventil einfach direkt an der gelben Lüftung angeschlossen, was nicht so mega sinnvoll ist.
2. Die Küchenabzugshaube und die Beleuchtung ist nicht angeschlossen bzw. abgeschnitten.
3. Die linke Seite der Messewand müsste noch in der Wand verankert werden. Siehe rechte Seite.
4. Zubehör wie Schweißhelm, Lederschürze und Handschuhe sollten noch einen festen Platz haben, an dem sie aufgehängt werden.

![IMG_6766](https://github.com/comakingspace/do-something/assets/19751734/717dd170-d1a9-419a-a6f1-a00c7c902d7f)
![IMG_6767](https://github.com/comakingspace/do-something/assets/19751734/65154867-6099-47ce-8d81-ec8dab7d3d0f)
![IMG_6768](https://github.com/comakingspace/do-something/assets/19751734/d1db241e-8980-4974-aef9-e577c528055d)
![IMG_6769](https://github.com/comakingspace/do-something/assets/19751734/2d3441b4-d5e4-4256-86dc-6bb348622e20)
![IMG_6770](https://github.com/comakingspace/do-something/assets/19751734/e2bafa58-5181-41e4-af29-0f973ff8f131)

**Comment by LukasFreeze** [comment]
![20230928_012612](https://github.com/comakingspace/do-something/assets/19755883/84fb6b59-fdb6-44bc-a432-4f36ba346a15)

Fertig!! Danke an Mamad und @Johannes09 für die Hilfe heute Abend 😎
