### ISSUE TITLE
Lautsprecher ansteuern

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#2]
So ähnlich wie die Uhren (#1) gibt es auch Lautsprecher in fast jedem Raum, die bestimmt irgendwo zusammenlaufen und kontrolliert werden könnten!

Wenn wir das schaffen können wir viele tolle Sachen machen, z.B.
* Türklingel in den Werkstätten hörbar machen
* Musik hören
* irgendwelchen Quatsch.

Hat jemand Ideen, wie wir am besten anfangen? Als allererstes mal den Kabeln folgen nehme ich an? ;-)

**Comment by LukasFreeze** [comment]
Es gibt eine Verteilerdose, auf der "Lautsprecher" steht:

![inkedimg_20171118_023521_li](https://user-images.githubusercontent.com/19755883/32983099-ce4e3374-cc8f-11e7-86ee-7577dec66c53.jpg)

Bevor wir daran rumspielen sollte allerdings ein Elektriker drüberschauen (wie bei #1)

**Comment by Henrik99** [comment]
Ich hab mal einen der Lautsprecher von der Wand abgehängt. So wir ich das verstehe bekommt der Lautsprecher ein 100V Audio Signal welches Dan von dem Transformator auf die Spannung für dem Lautsprecher runter gewandelt wird. (wahrscheinlich damit über die langen Strecken im Haus nicht so hohe Verluste entstehen) falls einer sich mit audio auskennt kann es sich gern dem Projekt widmen. Bei der Dose ist es das selbe wie bei dem Uhren und es sind alle 3 Leitungen parallel geschaltet. Auch hier müsste jemand die Leitungsfühung heraus finden. Dem Lautsprecher hab sich auf dem E-Bench gelassen.
![img_20171122_205718](https://user-images.githubusercontent.com/33910698/33147620-bbc5857c-cfc8-11e7-9c06-2b42921c5bdc.jpg)

**Comment by Henrik99** [comment]
Hab noch etwas Recherche betrieben um diese Lautsprecher mit 100V zu betreiben braucht man einen ELA Verstärker. Hier wird [http://www.hifi-forum.de/viewthread-42-40.html](url) das ganze Vehrfahen recht gut beschreiben. Wir können den Lautsprecher natürlich auch direkt mit einem normalen Verstärker  betreiben und einfach den Transformator überspringen. Die Frage ist Dan auch noch wie gut die laut die Lautsprecher sind, wahrscheinlich nicht allzu besonders. (evtl neue Boxen bauen?). Es wäre auch ne gute Idee wenn man die Klingel noch irgendwie mit dem Lautsprecher Koppelt damit man die auch überall hören kann. Falls ihr noch Ideen habt meldet euch.

**Comment by NitramLegov** [comment]
Wir haben die Lautsprecher heute mal direkt an einen Pi mit Suptronics X400 HAT gehängt ( http://www.suptronics.com/xseries/x400.html )
Das klang gut. Ohne die 100V Regelung im Lautsprecher wird es entsprechend lauter...

**Comment by NitramLegov** [comment]
Nur um das hier auch dokumentiert zu haben:
https://wiki.comaking.space/Project:Enhanced_Door_Bell

Die Türklingel liefert 9V Wechselspannung. Die soll mit einem Arduino abgegriffen werden und entsprechend soll über ein Audio Shield Ton auf den Lautsprechern wiedergegeben werden.
Zusätzlich soll es ein Soundboard geben

**Comment by LukasFreeze** [comment]
Ich würde sagen ihr habt es schon echt gut zum Laufen gebracht und alle weiteren Updates landen eh direkt auf der [Wiki-Projektseite](https://wiki.comakingspace.de/Project:Enhanced_Door_Bell), also mach ich hier mal zu :-)
