### ISSUE TITLE
Pegboard in CNC-Raum

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#20]
Im CNC-Raum fliegt viel Kleinkram rum, den man super an einem Pegboard befestigen könnte.

**Comment by LukasFreeze** [comment]
das Pegboard kam mir noch sehr elastisch vor als ich es neulich kurz gesehen habe, spricht was dagegen noch zwei Schrauben (mit Abstandshalter) weiter unten in die Wand zu jagen?

**Comment by emka** [comment]
Das könnte man noch machen, bisher habe ich nur die vorhandenen Löcher in der Wand genutzt. An den unteren Ecken kleben sogar schon die passenden Abstandshalter mit doppelseitigem Klebeband, die kann man abziehen und direkt verwenden.

**Comment by NitramLegov** [comment]
Done
