### ISSUE TITLE
P1 Broken Heatbed

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#200]
P1's heatbed is currently not functional. @Johannes09 had a look at it and found that the connector for the headbed on the mainboard has partially molten. 

Next step would be to order and replace the connector and the corresponding header on the PCB.
Here are the relevant parts:
* Molex 395300002 (Connector)
* Molex 395311004 (Socket)

**Comment by lmnl99** [comment]
Ich Leg morgen zwei Molex Stecker zum Drucker. Socket hab ich leider keinen.

**Comment by Pakue95** [comment]
@Johannes09 und ich haben nochmal über die Reparatur gesprochen und sind zum Entschluss gekommen, dass es besser wäre die Kabel zu ersetzen und mit einem Flachstecker zum trennen direkt ans Board zu löten. Die Stecker sind alle nicht das Wahre wenn die konstant bewegt werden. 

Als Kabel soll ein zwei-adriges 1.5mm^2 110 Ölflex dienen. Teile sind bestellt.

**Comment by Johannes09** [comment]
Ich habe das Kabel ersetzt und den Drucker Kalibriert (Z-Achse , first layer call)
