### ISSUE TITLE
Workbee CNC aufbauen 

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#201]
Nach dem Umzug muss unsere Workbee CNC Fräse wieder flott gemacht werden. Damit habe ich heute angefangen. Folgende Aufgaben sind noch zu erledigen:

- [x] an ihren Platz stellen
- [x] die Tische auf gummimatten stellen
- [x] einen Fuß neu drucken und anbringen
- [x] die fräse auf gummimatten stellen 
- [x] mit der Wasserwaage ausrichten
- [x] den zweiten Notaus am richtigen Ort anbringen
- [x] den zweiten Notaus anschließen (@Johannes09)
- [x] sicherstellen, dass die Spindel senkrecht eingebaut ist
- [x] eine Steckdose für den pi schaffen (@NitramLegov bringt eine steckerleiste mit)
- [x] Aufhängung für das spindelkabel und den absaugschlauch schaffen
- [x] alles anschließen
- [x] von der spoilerplate 1mm abnehmen

**Comment by NitramLegov** [comment]
Die cnc fräse wurde heute plan gefräst.

Damit kann die fräse meiner Meinung nach freigegeben werden.

**Comment by LukasFreeze** [comment]
Bitte beobachten, wenn das weiter auftritt sollten wir ein neues Issue öffnen:

Ich wollte heute etwas fräsen und hatte mehrfach das Problem, dass plötzlich keine Bewegungen mehr möglich waren. In der CNCjs-Konsole wurden noch fleißig Kommandos geschickt, die aber scheinbar nicht bis in die Steuerelektronik vorgedrungen sind :-(
Fehlermeldungen gab es nicht, erst beim Versuch eines reconnects wurde klar dass die Verbindung unterbrochen war - reconnect in CNCjs brachte kein Feedback der Maschine mehr (üblicherweise alle möglichen aktuellen Werte) und eine Aktualisierung im Browser führte zu "Verbindung zum Server wurde unterbrochen".

Nur ein richtiger Restart von Panel und Fräse haben geholfen, und ich bilde mir ein dass die Verwendung des Panels besonders häufig zu diesem Fehler geführt hat - der einzige letztlich erfolgreiche Job wurde allein über das Browser-Interface vorbereitet 🤔

**Comment by Johannes09** [comment]
Ich habe jetzt noch den zweiten Not-aus angeschlossen
