### ISSUE TITLE
Festool-Staubsaugeradapter Zyklonabscheider CNC Fräse

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#202]
Der Zyklonabscheider der Cnc fräse sollte einen Adapter für die festool staubsauger bekommen

**Comment by Titan-OX** [comment]
Abmaße hast du nicht?

**Comment by NitramLegov** [comment]
Ne, sorry. Gemessen habe ich nicht, aber wir haben ja einen messschieber :)
Willst du das übernehmen?

**Comment by LukasFreeze** [comment]
Habt ihr schon hier reingeschaut? https://github.com/comakingspace/CommonFiles/tree/master/3DPrintingFiles/WorkbeeCNC

Es gibt einen zwei Jahre alten "Festool Adapter" für irgendwas, falls der am falschen Teil sitzt könnte man sonst den aktuellen "Cyclone Adapter" modifizieren :-)

**Comment by NitramLegov** [comment]
@Johannes09 @Pakue95 und ich haben uns gestern hierüber unterhalten und sind zu dem Schluss gekommen, dass der Staubsauger der bei der CNC Ecke steht aktuell ausreicht und wir nicht wirklich wollen, dass jemand mit einem langen Fräsjob einen der Festool Sauger "blockiert" :)

Darum mache ich hier zu
