### ISSUE TITLE
Laser cutter focusing laser is out of calibration

### ISSUE THREAD

**Issue by kenomaerz** [comakingspace/do-something#203]
Yesterday, @Pakue95, @NitramLegov and I found, that the laser cutter focusing help is not calibrated correctly. To achieve best focus, you need to aim the calibration help ~5mm to the right of the actual laser beam, which is not quite optimal.

We probably need to contact the manufacturers for a fix.

**Comment by LukasFreeze** [comment]
How exactly is the focusing supposed to work for this machine? Is it not
possible to adjust the calibration help?

**Comment by NitramLegov** [comment]
@Johannes09 and me took a look at the calibration help (laser pointer) and adjusted it a bit. We'll need to check whether it was enough or not.

**Comment by LukasFreeze** [comment]
> We'll need to check whether it was enough or not.

Did that work?

**Comment by kenomaerz** [comment]
I have been using Patrick's calibration helper and have been getting good results. I'll close this for now.
