### ISSUE TITLE
CNC Router Control Panel

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#204]
The Control panel of our CNC Router is broken.

It looks like the PCB got in touch with some kind of fluid. Therefore, a new PCB needs to be soldered:

- [x] Find the needed parts in the space (@Pakue95 can indicate which parts are needed)
- [x] Solder PCB

Ideally, we should also use this issue and make a new proper housing for the raspberry pi and the control panel.

**Comment by NitramLegov** [comment]
The Raspberry Pi itself is still up and running, so CNCjs can be used. This issue might though explain the recent issues with it

**Comment by LukasFreeze** [comment]
Good find!

While it is of course unfortunate to be broken in the first place, it does
explain everything I reported the other week and should be an easier fix
than troubleshooting some inconsistent connectivity issues :-)

Did you do the first tests cuts with CNCjs only, or did the panel still
work properly then? No liquids were involved in my short routing attempt
for sure, maybe it happened during the move?

**Comment by NitramLegov** [comment]
Both Johannes and me did a first test with CNCjs only without the panel attached. For us, it worked fine.

The secret of the liquid was revealed as well in the meantime. Apparently, the control panel has been attached to the housing using wood glue. Surprisingly, the electronics did not like this.

**Comment by NitramLegov** [comment]
Patrick soldered the new pcb today and I lasered a nice top for it.

@Narquadah is it possible we do not have support for the on/off button yet?  We should add that and the support for the rotary switch as the next step.

In parallel, I could work on designingthe rest of the housing

**Comment by NitramLegov** [comment]
The Control panel was installed in a housing and generally works.

There is a bug that the X+, Y+ and Z+ Buttons do not work when it is installed in the housing, which is kind of odd. 

We need to debug this :-)

**Comment by NitramLegov** [comment]
Closed with #307
