### ISSUE TITLE
Umzugsspuren in der Werkhalle aufräumen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#205]
Wir sollten dringend "klar Schiff" machen - mit Blick auf die kommenden Veranstaltungen und unsere Besucher, die Lust auf eine Mitgliedschaft bekommen sollen, aber auch weil eine unaufgeräumte Werkstatt leider zu noch mehr Durcheinander einlädt...

- [x] Was zum Beispiel seit dem Umzug kaum verändert wurde ist der **"unklar wohin"-Tisch in der Nähe der Metallecke** wo erstmal alles gelandet ist was keinen Platz und zT auch keinen offenkundigen Nutzen hatte. Hier sollten möglichst Leute mit verschiedenen "Fachgebieten" drüber schauen, was sie zuordnen können und vor der Entsorgung retten möchten!

- [x] Außerdem liegen die **Holzreste** ziemlich unpraktisch in der Gegend rum, Bohli hatte uns dafür eine rollbare Kiste gestiftet die wir als nutzbares Lager ausbauen könnten. Abgesehen von der Platzverschwendung und geringen Nutzbarkeit ist der aktuelle Haufen auch eine Stolpergefahr!

- [x] ein Tisch ist noch voll mit **Schrauben**, Muttern, Nägeln und Scheiben, die entweder einfach noch nicht weggeräumt sind oder komplett vermischt wurden - komplett sauberes Sortieren ist hier wahrscheinlich utopisch, aber um weggeräumt zu werden braucht es zumindest einen Ansatz von Ordnung :-P
Um sich hier einzubringen muss man sich noch gar nicht auskennen.

Diese Liste kann wie immer gerne ergänzt werden!

Wenn das gröbste weggeschafft ist können wir dann direkt zum Herausputzen der einzelnen Ecken übergehen und neue PR-Fotos machen :-) -> #118

**Comment by LukasFreeze** [comment]
Thanks Karel for spending over an hour with the unassorted screw table! As far as I know, wood screws are sorted according to their heads/drives now and we were able to put a few metric screws/washers into the proper cabinet :-)

For the scrap wood, I'm thinking about dividing the blue wagon in the middle - big pieces in one half, smaller ones in the other? The smaller half could be covered with a lid so it doesn't invite people to throw in the *really* small bits: 
![IMG_20200715_215917](https://user-images.githubusercontent.com/19755883/87593134-46766580-c6eb-11ea-90b8-3d13264ab8a5.jpg)

**Comment by LukasFreeze** [comment]
Wir waren gestern zu viert am Werk, um einige Altlasten loszuwerden - @Johannes09 und @Pakue95 haben besonders im Elektronikbereich ordentlich aufgeräumt und @NitramLegov und ich haben zwei Transporterladungen Schrott zum Recyclinghof gebracht :-)

**Comment by LukasFreeze** [comment]
Morgen kommt wieder einiges an Müll weg wenn der Lala-Van alles mitkriegt :-)

Damit besonders der Holzabfall nicht immer so ein Akt ist (zwei Abende umräumen in kleinere Kartons) habe ich die übergroße Abfallkiste jetzt endlich mal gekürzt: im Test mit Johannes war sie jetzt bei maximaler Füllug mit zwei Personen zu heben.
![IMG_20210528_233106](https://user-images.githubusercontent.com/19755883/120045506-76331100-c010-11eb-93e9-0a0a0e5da84c.jpg)

Was das mit diesem Issue zu tun hat: die hier erwähnte blaue Kiste wurde schon langsam als Ausweich-Müll genutzt, das sollte natürlich absolut nicht sein (noch viel größer...) und deshalb ist sie jetzt erstmal neben den Fahrzeugplätzen "versteckt" bis Zeit für den Ausbau als Restebox ist.

**Comment by LukasFreeze** [comment]
kleines Update vorm nächsten "do-something day" kommenden Samstag: die blaue Kiste ist dank des neuen Plattenlagers nicht mehr nötig und kann wohl auseinander genommen werden, wenn niemand noch eine tolle Idee dafür hat.

Wie wäre es bei den rumliegenden Werkzeugen/Teilen mit einer Sortierung in drei Kategorien?
- nützlich, nur noch ohne Platz (am besten wird hier gar nicht groß gesammelt, sondern sinnvolle Plätze gesucht) - Steven hat letzte Woche zB auch wieder zahlreiche Bohrer wegsortiert :-)
- nützlich zum Vorrichtungsbau (sowas wie halbe Schraubzwingen oder was da sonst so rumfährt?)
- Entsorgung (könnte für interessierte Mitglieder noch 1-2 Wochen stehen bleiben, was dann nicht mitgenommen wurde kommt ganz weg)

**Comment by NitramLegov** [comment]
![DSC_1563](https://user-images.githubusercontent.com/7809163/162640723-2cfd561c-76c6-4692-beef-ba4d732c6fcb.JPG)
Der Tisch bei der metallecke ist fast komplett aufgeräumt. Einige Schrauben räumen wir die Tage noch weg.
Außerdem sind einige Sachen erstmal "nur" in die Metallwerkstatt gewandert. Dort wird mehr Ordnung geschaffen, sobald ein paar der neuen Boxen fertig sind, die @Pakue95 aktuell baut :-)

**Comment by NitramLegov** [comment]
Die Schrauben sind einsortiert / in den Tisch bei der Schraubecke geräumt und der Tisch bei der Metallecke ist frei. Damit wäre dieses issue für mich abgeschlossen :-)
