### ISSUE TITLE
P3 Kabelführung neu machen

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#206]
Die Kabelführung/Zugentlastung bei P3 auf der X Achse ist nicht richtig montiert und muss neu gemacht werden um Kabelbruch zu vermeiden.

**Comment by ErikSchatz** [comment]
Die Zugentlastung ist gemacht, 

aber die Druckqualität ist bescheiden!
(neigt zum Stringing, unregelmäßige Schichten (bei 4mm Zylinder))

**Comment by reogaro** [comment]
Ich habe weder Stringing noch unregelmäßige Schichten reproduzieren können. P3 hat 2 Testdrucke problemlos abgeschlossen.
