### ISSUE TITLE
Streaming-Lösung für die "Tor 4"-Diskussionsabende

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#207]
Unser Konzept der Tor-4-Themenblöcke sah ursprünglich vor, am Samstag nach dem wesentlichen Teil des anmeldepflichtigen Kurses noch eine öffentlichere Diskussionsrunde im Gemeinschaftsraum zu veranstalten.

Mit Abstandsregel kommen wir dann allerdings höchstens auf 20-30 Besucher, da wäre es cool wenn man sich auch virtuell dazuschalten könnte!

Der whereby-Kanal würde bis zu 50 Leute zulassen, wie stabil dann alles noch ist wissen wir halt leider nicht im Voraus. Aber wir könnten trotzdem einen Testdurchgang machen, zum Beispiel im Rahmen eines Plenums?

Ich fänd außerdem schön, nicht nur die Präsentationen via "Bildschirm teilen" zu zeigen, sondern auch ein Video aus Besucherperspektive - wir wollen schließlich zumindest ein bisschen von der Stimmung im Space einfangen! Dieses Video könnte dann von einem "Regisseur" im Raum gemanagt werden und zB bei Anschauungsobjekten und Zwischenfragen statt der gerade laufenden Bildschirmpräsentation gezeigt werden.
@Pakue95 hatte dazu schon technische Ideen, die er am besten selbst erläutert ;-)

Konkret sollten wir hier...
- [ ] überlegen was wir genau tun
- [ ] Testlauf mit möglichst vielen Mitgliedern abhalten
- [ ] dokumentieren wie es geht, damit während einer Veranstaltung möglichst wenig Expertise nötig ist und nötigenfalls kurzfrist eingesprungen werden kann

Siehe auch #172 #173 #174 und #175 :-)

**Comment by NitramLegov** [comment]
Wenn ich das richtig im Kopf habe hat das Setup letztes mal ganz gut geklappt, oder?

Damit könnten wir hier zumachen, was meint ihr?

**Comment by LukasFreeze** [comment]
Nee, da gab es leider ziemliche Probleme, wir hatten eine Stunde lang mit
Leistung & Netzwerkstabilität zu kämpfen während schon die ersten externen
Beiträge anfingen 🙈

Außerdem waren glaube ich noch mehrere Komponenten geliehen (weiß @Pakue95
sicher besser als ich), wir sollten schon gucken ob wir mit vertretbaren
Kosten etwas stabileres für die weiteren beiden Abende hinkriegen

**Comment by Pakue95** [comment]
Muss ich Lukas zustimmen. Das Audioequipment war überwiegend von @Narquadah geliehen, wobei die wireless Mikros nicht wirklich funktioniert hatten, als es darauf ankam und wir sind dann auf XLR umgestiegen. Ich hätte die Hoffnung das von Rode da etwas besser abschneidet; Sind aber auch 200 Euro... 

Video war eigentlich ganz ok, ist nur etwas lästig alle 60-90min den Akku zu wechseln. Ggf. auch mit nem [Raspi](https://www.jeffgeerling.com/blog/2020/raspberry-pi-makes-great-usb-webcam-100) zu lösen. 

Whereby hat bei 5-6 Leuten mit Webcam an auch nicht so mega viel Spaß gemacht, aber da gibt es recht wenig, was man dagegen tun kann.

**Comment by LukasFreeze** [comment]
auch diese Fragestellung wird jetzt wieder relevant :-P

@Pakue95 und @NitramLegov ihr hattet beide Ideen für Verbesserungen bei den nächsten beiden Events, richtig? Wie bald könnten wir einen Link festlegen, damit der schon an die Interessenten verteilt werden kann wenn sie auf unsere Einträge auf div. Kanälen stoßen?

Bisher steht auf eventbrite, meetup und unserer Website jeweils "Details folgen".

**Comment by Pakue95** [comment]
Audio sollte diesmal besser klappen, da ich ein anderes Interface habe, was bisher sehr gut funktioniert hat. Als Mikro würde ich wieder @Narquadah Handmikro nehmen und das den Sprechern in die Hand drücken. Das Wireless Shure Mikro im Space hat leider garnicht gut funktioniert da irgendwas gestört hat. 10m XLR Kabel habe ich da. 

Wenn wir noch Raumaudio wollen muss man noch ein Mikro dafür besorgen.

Wenn wir wieder Whereby benutzen wollen muss man den Zuschauern die Video/Audio Rechte nehmen, sonst schmiert das sicherlich wieder ab bei 6-7 Webcam Streams. Müsste @NitramLegov wissen, ob das geht.

**Comment by LukasFreeze** [comment]
Ich hab mit Martin geschrieben: "Whereby passt" 👍 

es wird dann jeweils hier stattfinden, habe die diversen Eventseiten schon angepasst: whereby.com/comakingspace

**Comment by NitramLegov** [comment]
Der Workshop hat erfolgreich stattgefunden :)
