### ISSUE TITLE
Scheppach Standbohrmaschine Tiefenstop defekt

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#208]
Der Tiefenstop der Scheppach Standbohrmschine ist defekt. Das Kunststoffteil, welches über dem Futter montiert ist, hat zwei Risse und ist deshalb nicht mehr fest mit der Maschine verbunden.

Zur Reparatur muss das Futter abmontiert werden und das Teil ersetzt werden. Ein 3D gedrucktes Ersatzteil sollte machbar sein.

![IMG_3869](https://user-images.githubusercontent.com/19751734/93015490-392a0a00-f5ba-11ea-8de8-9d79b77bd47e.jpeg)
![IMG_3868](https://user-images.githubusercontent.com/19751734/93015492-3c24fa80-f5ba-11ea-8340-508222dc0991.jpeg)
![IMG_3870](https://user-images.githubusercontent.com/19751734/93015494-3e875480-f5ba-11ea-880c-255854e1c469.jpeg)

**Comment by Pakue95** [comment]
Und ist gefixed:

![IMG_3902](https://user-images.githubusercontent.com/19751734/93938946-57b2a280-fd2a-11ea-9582-11b283285a1a.jpeg)

**Comment by LukasFreeze** [comment]
Cool! :-D

Ich hoffe natürlich dass es lange hält, aber wollen wir das Design vorsichtshalber trotzdem in [CommonFiles](https://github.com/comakingspace/CommonFiles/tree/master/3DPrintingFiles) ablegen?

**Comment by Pakue95** [comment]
Ja, auf thingiverse ist es schon: https://www.thingiverse.com/thing:4604161

**Comment by drei85** [comment]
> Ich hoffe natürlich dass es lange hält, [...]

Leider nein. Ich weiß nicht ob es schon gerstern Abend passiert ist oder ich heute den Tiefenstop abgerissen habe.

![IMG_20201008_123208_HDR](https://user-images.githubusercontent.com/48619066/95490550-a69e4000-0998-11eb-962b-8541f4cd95c8.jpg)


Ich würde das `Teil` auch nochmal drucken, allerdings habe ich das noch nie gemacht und auch keine Berechtiung für diesen Teil des Spaces.

Was kann ich machen? / Wie kann ich behilflich sein bei der Reperatur?

**Comment by Pakue95** [comment]
Ich druck die linke Hälfte nochmal stärker. Sollte morgen Abend fertig sein.

**Comment by Pakue95** [comment]
Teil ist ausgetauscht.
