### ISSUE TITLE
Ankündigungen/Werbung: Tor-4-Kurse "Präzisionstechnik trifft Kunst" (Laser-Linoldruck)

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#209]
In etwas über einem Monat geht es endlich weiter und wir veranstalten die ersten Kurse unseres von der BASF-Kulturförderung "Tor 4" geförderten Projektes!

Hier soll es ums Abarbeiten der Werbung für die Laser-Kurse gehen, inhaltliches dazu findet ihr in #174 :-)

**Titel**: You can make it! Präzisionstechnik trifft Kunst

**Leiter & Helfer**: @kenomaerz , ...??

**Daten & Zeiten**: 28.8.2021 (13-19 Uhr)

**Teilnehmer**: je 10 Tickets (via Eventbrite)

**Zielgruppe**: Anfänger - keinerlei Vorkenntnisse nötig!

**Materialkostenbeitrag**: 10 € pP

**Beschreibung**: *fehlt noch! Vorschläge willkommen :-)*

**Fotos**: *fehlen noch! Vorschläge willkommen :-)*

## Advertisement ToDo:

* to be done by a [manager](https://wiki.comakingspace.de/Management):
  * [x] Eventbrite pages [Okt20](https://www.eventbrite.de/e/120420530047) // [Aug21](https://www.eventbrite.de/e/you-can-make-it-prazisionstechnik-trifft-kunst-tickets-165678333355)
  * [x] Google-Kalender
  * [x] [Meetup](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/)
  * [x] [Facebook](https://www.facebook.com/comakingspace/)
  * [ ] [Instagram](https://www.instagram.com/comakingspace/)
  * [ ] [Twitter](https://www.twitter.com/comakingspace/)
  * [x] *if there's time:* announce in the next newsletter (@LukasFreeze)
  * [ ] *if there's time:* [Rhein-Neckar-Zeitung](https://www.rnz.de/kontakt/redaktionen.html)

* help welcome:
  * [x] event wiki page ([Category:Seminars](https://wiki.comakingspace.de/Category:Seminars))
    * https://wiki.comakingspace.de/Linoprint_with_Laser_Engraving_Workshop
  * [ ] announce via Members mailing list
  * [ ] [Telegram Group](https://wiki.comakingspace.de/Telegram_Group)
  * [ ] "Maker Community HD" WhatsApp Group
  * [x] [Heidelberg.de Veranstaltungskalender](https://www.heidelberg.de/hd,Lde/HD/Erleben/veranstaltungskalender.html)
  * [x] [Make: calendar](https://www.heise.de/make/kalender/new_event/)
  * [ ] *if there's time:* Poster (to be hung up by the city)

PS: mein Denglisch liegt hauptsächlich an der verwendeten Vorlage, die Veranstaltungen finden auf deutsch statt!

**Comment by LukasFreeze** [comment]
Wir brauchen hier noch bessere Fotos, bisher habe ich nur schnell was aus einem slack-Update von Keno zusammengepfuscht - oder ist uns das gut genug? 😆  Einfach hier reinposten bitte!

![img_20200819_215812LASER](https://user-images.githubusercontent.com/19755883/93993132-a8f47d80-fd8e-11ea-8b08-9cb15e45b869.jpg)

**Comment by LukasFreeze** [comment]
die folgenden Termine sind auf unbestimmte Zeit verschoben, daher wird hier erstmal pausiert - bitte wieder aufmachen, wenn wir wissen wie es weitergeht!

**Comment by LukasFreeze** [comment]
Wir müssen hier dringend wieder loslegen, als möglichen Termin haben wir auf slack den 28. und 29.8. ins Auge gefasst.

@kenomaerz ist leider verhindert, würde aber jemanden einlernen - wer hätte Zeit und Lust, den Workshop und Diskussionsabend auszurichten? Das dürfen natürlich sehr gerne mehrere Leute sein! Die Uhrzeiten könnten wir dann gemeinsam aushecken, möglich wäre zB ein zweigeteilter Workshop Sa/So tagsüber mit Diskussionsabend am Samstag (wie #172), aber vielleicht kann man den Workshop auch an einem einzigen Tag schaffen und dann sogar zwei volle Termine anbieten? Oder natürlich notfalls nur einen Tag, wenn niemand so viel Zeit haben sollte.

Mit diesem Event "verdienen" wir uns den Laser, also bitte meldet euch wenn ihr auch nur ein paar Stunden mithelfen könntet! Die Details besprechen wir dann am besten mit allen Freiwilligen, habe gerade nicht annähernd genug Zeit um hier alles aufzuschreiben ;-)

**Comment by ozel** [comment]
ich wäre wie gesagt dabei, allerdings nicht alleine. Kenne den space generell noch zu wenig und hatte auch noch keine Einführung zum Laser. Inkscape Kentnisse sind vorhanden.

Ich habe prinzipiell an beiden Tagen Zeit, wenn Workshop und Diskussion zusammen an einem Tag gehen fände ich das gut. Wenn ich #174 richtig verstanden habe, ist der Zusammenbau einer 3D-Druck Presse nicht Teil vom Workshop.  D.h. ein halber Tag sollte ausreichen für den Workshop, oder?

**Comment by ErikSchatz** [comment]
Da könnte ich auch unterstützen,

 

da ich in der letzten Augustwoche vom Urlaub zurück bin

 

und sowiso mal etwas mit dem Lasercutter machen wollte.

 

VG, Erik

 
 

Gesendet: Dienstag, 20. Juli 2021 um 14:35 Uhr
Von: "Lukas" ***@***.***>
An: "comakingspace/do-something" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: Re: [comakingspace/do-something] Ankündigungen/Werbung: Tor-4-Kurse "Präzisionstechnik trifft Kunst" (Laser-Linoldruck) (#209)


 

Wir müssen hier dringend wieder loslegen, als möglichen Termin haben wir auf slack den 28. und 29.8. ins Auge gefasst.

@kenomaerz ist leider verhindert, würde aber jemanden einlernen - wer hätte Zeit und Lust, den Workshop und Diskussionsabend auszurichten? Das dürfen natürlich sehr gerne mehrere Leute sein! Die Uhrzeiten könnten wir dann gemeinsam aushecken, möglich wäre zB ein zweigeteilter Workshop Sa/So tagsüber mit Diskussionsabend am Samstag (wie #172), aber vielleicht kann man den Workshop auch an einem einzigen Tag schaffen und dann sogar zwei volle Termine anbieten? Oder natürlich notfalls nur einen Tag, wenn niemand so viel Zeit haben sollte.

Mit diesem Event "verdienen" wir uns den Laser, also bitte meldet euch wenn ihr auch nur ein paar Stunden mithelfen könntet! Die Details besprechen wir dann am besten mit allen Freiwilligen, habe gerade nicht annähernd genug Zeit um hier alles aufzuschreiben ;-)

**Comment by LukasFreeze** [comment]
Hey ihr beiden, sehr cool 😍 

Ich hab gestern mit @NitramLegov telefoniert, der sich als Laser- und Space-"Profi" als Organisator anbieten würde und sich dann wohl melden wird sobald konkrete Vorbereitungen/Testläufe anstehen :-)

Mit etwas Glück könmen wir @kenomaerz sogar ganz in Ruhe lassen, denn er hatte den praktischen Teil schon wunderbar ins Wiki gestellt: https://wiki.comakingspace.de/Linoprint_with_Laser_Engraving_Workshop

Akut stehen jetzt Plakate an, die @Pakue95 gestalten würde wenn man ihm sagt was drauf soll. Ich hab bisher nur "irgendwas mit Laser oder 3D-Drucker" gesagt, hat jemand konkretere Ideen? 😅 

Außerdem brauchen wir Vorträge fürs Abendprogramm, gerne mit Ideen wen man dafür anfragen könnte oder welche Mitglieder coole Projekte vorstellen würden. Mir sind heute morgen "KI-Kunst" (deep dreaming und so, da haben wir evtl einen Kontakt) und das Open Press Project eingefallen (sollte ursprünglich auch im Workshop vorkommen), weitere Vorschläge unglaublich willkommen ;-)

PS: Ich erstelle für die ganzen Fakten auch gleich eine Wiki-Seite, damit es übersichtlicher wird als mit den ganzen einzelnen Issues: https://wiki.comakingspace.de/You_can_make_it

**Comment by LukasFreeze** [comment]
@ozel @ErikSchatz habt ihr Präferenzen, was die Uhrzeit angeht?

wenn wir uns auf den Samstag konzentrieren gibt es zwei Optionen, die die Leute hoffentlich mitmachen:
- Workshop 10-16 Uhr, Diskussionsabend 16-20 Uhr
- Workshop 13-19 Uhr, Diskussionsabend 19-21:30 Uhr + open end ("bis 23 Uhr" dürfte vor allem abschrecken, daher erstmal kürzer?)

**Comment by ozel** [comment]
Die spätere Kombo passt gut finde ich, ich könnte aber auch früher. Vllt. muss man die Dauer der Diskussion garnicht so genau angeben. Hängt stark von den Teilnehmern ab, oder?

**Comment by ErikSchatz** [comment]
... das 2. würde auch mir eher passen!

 

VG, Erik

 
 

Gesendet: Dienstag, 27. Juli 2021 um 14:01 Uhr
Von: "Lukas" ***@***.***>
An: "comakingspace/do-something" ***@***.***>
Cc: "ErikSchatz" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [comakingspace/do-something] Ankündigungen/Werbung: Tor-4-Kurse "Präzisionstechnik trifft Kunst" (Laser-Linoldruck) (#209)


 

@ozel @ErikSchatz habt ihr Präferenzen, was die Uhrzeit angeht?

wenn wir uns auf den Samstag konzentrieren gibt es zwei Optionen, die die Leute hoffentlich mitmachen:


	Workshop 10-16 Uhr, Diskussionsabend 16-20 Uhr
	Workshop 13-19 Uhr, Diskussionsabend 19-21:30 Uhr + open end ("bis 23 Uhr" dürfte vor allem abschrecken, daher erstmal kürzer?)

**Comment by Pakue95** [comment]
Hier mal ein WIP vom Poster...
![PrecisionMeetsArtPoster](https://user-images.githubusercontent.com/19751734/127807562-9c0db712-75f9-43f0-9b4c-cebb599ab165.jpg)

**Comment by LukasFreeze** [comment]
Sorry, hab den Posterentwurf gar nicht mehr kommentiert - sehr sehr cool!

Meetup-Seiten sind jetzt auch angelegt, wir haben heute grünes Licht für digitale Werbung bekommen :-) https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/events/

**Comment by Pakue95** [comment]
Beim Text bin ich mir noch nicht sicher. Ggf. kann @kenomaerz da noch mal ein Auge drauf werfen?
Sonst würde ich die dieses Wochenende gerne bestellen.
![Artboard1@0 25x](https://user-images.githubusercontent.com/19751734/128587779-d645552e-544b-4f64-9357-f107d8dd9d4d.jpg)

**Comment by NitramLegov** [comment]
Der Workshop hat erfolgreich stattgefunden :)
