### ISSUE TITLE
Besserer Freifunk-Router

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#21]
Unser Freifunk-Router ist unterdimensioniert und hängt sich gelegentlich auf.

- [x] Herausfinden, welches Modell für Freifunk Rhein-Neckar geeignet und leistungsfähig genug für viele Leute ist
- [x] Modell besorgen/spenden
- [x] Firmware flashen (@emka kann helfen)

**Comment by emka** [comment]
Die Firmware gibt es [für den WNR2200](https://fw.ffrn.de/?q=Netgear%E2%81%A3%20WNR2200%E2%81%A3%20alle%E2%81%A3%20Erstinstallation).

**Comment by NitramLegov** [comment]
Also, den WNR2200 habe ich geflasht, bring ich am Mittwoch mit, dann können wir den entsprechend fertig aufsetzen und ausprobieren.
Zusätzlich dazu würd ich gerne folgendes machen:

- [ ] Wiki Seite erstellen, die das Netzwerk (bzw. die Netzwerke) im Comakingspace dokumentiert
- [ ] Ein "Internes" WLAN aufsetzen

Für das interne WLAN schwebt mir vor, dass dort entsprechend die Mitglieder des Space Zugriff bekommen. Nach außen kann es ja per NAT ins Freifunk-Netz gehen. Vorteil wäre, dass man dann entsprechend interne services anbieten kann. Mir schwebt da die Musikbox, der Drucker, ein NAS sowie ggf. ein MQTT-Broker (z.B. für das soundboard, etc) vor.
Das Interne Netz würde ich über einen extra Router lösen wollen - man kann sicherlich in Irgendeiner Form die Netzwerkkonfiguration des Freifunk Routers umbiegen, das muss man dann aber ggf. nach jedem Update nochmal machen...

**Comment by NitramLegov** [comment]
@SystemOverlord Ich habe heute mal den Pi angeschlossen. Mit dem pi konnte ich zwar kommunizieren, der hatte aber kein Internet.

Wir sollten uns mal hinsetzen und die Konfiguration des Internen WLAN nochmal ordentlich testen und entsprechend im Wiki dokumentieren (kann man aus OpenWRT einfach config files rausziehen?)

**Comment by NitramLegov** [comment]
Ich mach hier mal zu ;)
Doku ist im Wiki ("Network"), das Netzwerk funktioniert.
