### ISSUE TITLE
Teilnahme/Förderung Code Week BW?

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#211]
Vom 10. bis 25. Oktober ist "Code Week Baden-Württemberg", gibt es jemanden der Ideen und vor allem Zeit für passende Workshops hätte? Wir könnten auch Fördermittel beantragen, wenn ein paar Bedingungen erfüllt werden!

Alle Infos gibt es hier: https://bw.codeweek.de/workshop-organisieren/

"Notfalls" könnten wir auch einfach unsere regulären Aufsichtszeiten anmelden, sofern die jeweiligen Leute nichts dagegen haben dass möglicherweise ein paar Neulinge im eRoom bespaßt werden wollen - @NitramLegov in der ersten Woche wärst du das, soll ich einen der Termine eintragen? Ich selbst stehe am 23. im Kalender und könnte es mir auch vorstellen, wenn sich noch jemand als Backup findet :-)

Auch der erste Termin "Präzisionstechnik mit Kunst" (#209 ) würde super ins Programm passen, oder @kenomaerz ?

Deadline zur Anmeldung ist der 10. Oktober, aber je früher wir gelistet sind desto mehr Leute werden natürlich auf uns aufmerksam :-)

**Comment by ErikSchatz** [comment]
Hallo Lukas,

 

ich habe etliche micro:bits,

 

die ich einsetzen kann,

und mit einer Online-Entwicklungsumgebung mit Blöcken,

java.script oder python programmiert werden können.

Und eine Erweiterung mit Elektronik ist herzlich willkommen!

(wg. Zuschuss!)

Kombis mit dem raspi sind auch möglich.

Außerdem habe ich in der Zeit auch noch Ferien.

 

Ich schaue das mir mal die Tage an, und würde am Fr. Abend reinkommen zum Planen.

 

Grüße, Erik

 
 

Gesendet: Dienstag, 29. September 2020 um 16:20 Uhr
Von: "Lukas" <notifications@github.com>
An: "comakingspace/do-something" <do-something@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [comakingspace/do-something] Teilnahme/Förderung Code Week BW? (#211)


 

Vom 10. bis 25. Oktober ist "Code Week Baden-Württemberg", gibt es jemanden der Ideen und vor allem Zeit für passende Workshops hätte? Wir könnten auch Fördermittel beantragen, wenn ein paar Bedingungen erfüllt werden!

Alle Infos gibt es hier: https://bw.codeweek.de/workshop-organisieren/

"Notfalls" könnten wir auch einfach unsere regulären Aufsichtszeiten anmelden, sofern die jeweiligen Leute nichts dagegen haben dass möglicherweise ein paar Neulinge im eRoom bespaßt werden wollen - @NitramLegov in der ersten Woche wärst du das, soll ich einen der Termine eintragen? Ich selbst stehe am 23. im Kalender und könnte es mir auch vorstellen, wenn sich noch jemand als Backup findet :-)

Auch der erste Termin "Präzisionstechnik mit Kunst" (#209 ) würde super ins Programm passen, oder @kenomaerz ?

Deadline zur Anmeldung ist der 10. Oktober, aber je früher wir gelistet sind desto mehr Leute werden natürlich auf uns aufmerksam :-)

**Comment by LukasFreeze** [comment]
Coole Sache, daraus können wir bestimmt etwas machen! Ich bin heute leider mal wieder nicht da, aber sag dann einfach welcher Tag/Uhrzeit es werden soll und ich kann mich um die Anmeldung kümmern :-)

**Comment by ErikSchatz** [comment]
Hallo Lukas,

 

3 Themen würde ich anbieten:

 

- Lichtorgel und mehr: Elektronik steuern mit dem BBC micro:bit Mikrocontroller (Eltern-Kind-Workshop: Alter 10 bis 14 Jahre, So 12.10.2020, 15 Uhr und 17 Uhr)

  (Beschreibung: Hallo Mädels und Jungs, wolltet ihr schon immer mal wissen was man mit Progrmmieren ganz real anfangen kann?

                         Ihr werdet eine einfache, graphische Block-Programmiersprache (easy wie Lego) lernen und zum Schluss damit LED´s zum Blinken bringen.

                         Bringt einfach einen Laptop, euere Eltern (1 Elternteil reicht) und Masken für jeden mit!

 

- Messen mit dem Raspberry Pi und dem BBC micro:bit Mikrocontroller (Erwachsenen, Datum&Zeit?, Geld beantragen)
 


 

- IoT mit LoRaWAN: mit der sense:box Messdaten online bringen (Erwachsenen, Datum&Zeit?, Geld beantragen)

 

Wie sieht es mit den Tor4-Workshops aus?

 

 

Viele Grüße,

Erik

 

 

 
 

Gesendet: Freitag, 02. Oktober 2020 um 14:14 Uhr
Von: "Lukas" <notifications@github.com>
An: "comakingspace/do-something" <do-something@noreply.github.com>
Cc: "ErikSchatz" <erik.schatz@web.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [comakingspace/do-something] Teilnahme/Förderung Code Week BW? (#211)


 

Coole Sache, daraus können wir bestimmt etwas machen! Ich bin heute leider mal wieder nicht da, aber sag dann einfach welcher Tag/Uhrzeit es werden soll und ich kann mich um die Anmeldung kümmern :-)

**Comment by LukasFreeze** [comment]
Der konkrete Workshop klingt doch schonmal super, ich hoffe nur wir kriegen
ihn noch schnell genug beworben...ich bereite mal was vor und
veröffentliche es, sobald noch zwei Unklarheiten beseitigt sind:
- Meinst du *Sonntag* den 11. oder Montag *den 12.*?
- sollen um 15 *und* 17 Uhr Leute kommen (zwei Durchgänge, je <2 h) oder
von 15 *bis* 17 Uhr?

Die anderen Ideen klingen auch interessant, werden aber wohl nicht mehr
vorm Anmeldeschluss am 10. festgemacht werden können, oder? Dann würde ich
neben deinem micro:bit-Workshop noch mind. eine der regulären Zeiten mit
anmelden, wo wir uns viel mit 3D-Druck beschäftigen :-)

Lass uns die weiteren Ideen für die nächste Gelegenheit im Kopf behalten!

**Comment by ErikSchatz** [comment]
Hallo Lukas,da habe ich mich vertan.Natürlich sollte es So 11.10. 15 - 17 Uhr heißen. Soll ich die Anmeldung im Namen des Space machen? Man kann die gleiche Veranstaltung auch mehrmals machen. Mal schauen wer da kommt. Schlüssel-Anhänger drucken zu den Öffnungszeiten Kann ich auch anbieten.VG, Erik-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 07.10.20, 23:54 schrieb Lukas <notifications@github.com>:

   Der konkrete Workshop klingt doch schonmal super, ich hoffe nur wir kriegen
   ihn noch schnell genug beworben...ich bereite mal was vor und
   veröffentliche es, sobald noch zwei Unklarheiten beseitigt sind:
   - Meinst du *Sonntag* den 11. oder Montag *den 12.*?
   - sollen um 15 *und* 17 Uhr Leute kommen (zwei Durchgänge, je <2 h) oder
   von 15 *bis* 17 Uhr?
   
   Die anderen Ideen klingen auch interessant, werden aber wohl nicht mehr
   vorm Anmeldeschluss am 10. festgemacht werden können, oder? Dann würde ich
   neben deinem micro:bit-Workshop noch mind. eine der regulären Zeiten mit
   anmelden, wo wir uns viel mit 3D-Druck beschäftigen :-)
   
   Lass uns die weiteren Ideen für die nächste Gelegenheit im Kopf behalten!

**Comment by LukasFreeze** [comment]
ich hab mir schon ein Profil angelegt, da ist die Eventanmeldung jetzt auch
schnell gemacht :-)  Ein Foto vom micro:bit in Aktion wäre aber noch super,
falls du etwas hast!

Hast du fürs Schlüsselanhänger drucken einen bestimmten Termin im Auge, an
dem du sicher kannst?

**Comment by LukasFreeze** [comment]
Der Sonntag ist jetzt schonmal sichtbar:
https://bw.codeweek.de/das-programm-2020/veranstaltung/2020-10-11-lichtorgel-und-mehr-elektronik-steuern-mit-dem-bbc-microbit-mikrocontroller
