### ISSUE TITLE
P4 hotend Assembly ist spröde

### ISSUE THREAD

**Issue by Narquadah** [comakingspace/do-something#215]
Das P4 hotend assembly hat einige Risse und muss ausgetauscht werden.

**Comment by BananaBirb** [comment]
hi, das neue Assembly-stück liegt daneben, können wir das schon umbauen?

**Comment by Pakue95** [comment]
Hotend Bauteil ist ausgetauscht und Drucker wurde neu kalibriert. 
Mittelfristig sollten alle Bauteile, die gedruckt sind, ausgetauscht werden.
