### ISSUE TITLE
Laser exhaust is leaking 

### ISSUE THREAD

**Issue by Titan-OX** [comakingspace/do-something#217]
During the linocut workshop the e-room smelled very bad. Keno and I noticed a lot of smoke coming from the port in the window.

**Comment by Pakue95** [comment]
Martin and I replaced the piece of piping, connecting to the outside vent, with a larger one (that actually fits...). It is glued in place with some acrylic. I'm not sure if it will hold as it is difficult to get a decent amount of acryl in that spot. If it gets loose we'd have to remove the outside vent to access the spot better.

The next few people to use the laser should check whether it seals properly. If it doesn't please reopen the issue.
