### ISSUE TITLE
P2 - clogged nozzle

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#219]
1) please describe the problem:
3D Printer P2 seems to have a clogged nozzle

**Comment by Johannes09** [comment]
P2 scheint zu funktionieren.
![grafik](https://user-images.githubusercontent.com/22060480/97983454-9fbaef80-1dd5-11eb-9559-14f5cfae2116.png)
Ich könnte mir vorstellen, dass das am Filament oder am USER lag.
- Filament Durchmesser zu groß
- falsche Temperatur eingestellt

**Comment by reogaro** [comment]
P2 didn't have any issues on saturday, successfully finished a 3-hour testprint. I'm closing this issue.
