### ISSUE TITLE
Fusion360 CAM postprocessing verbessern

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#22]
Fusion360 in der aktuellen Version erzeugt beim Postprocessing für grbl Befehle, die mit unserem Board "soft limit violation" erzeugen, z.B. ```G28 Z0```.

Ausserdem erzeugten auch schon die alten Versionen Werkzeugwechsel, z.B. ```T1 M6```, die einen "unsupported command" ergeben.

- [ ] Herausfinden wie man den Postprocessor konfiguriert
- [ ] Anpassen, um solche Befehle nicht zu erzeugen
- [ ] Im Wiki dokumentieren, wie man die Anpassungen bei sich macht

**Comment by NitramLegov** [comment]
Seid ihr sicher, dass das am Gcode liegt?
https://forums.autodesk.com/t5/fusion-360-computer-aided/g-code-for-simple-xyz-cnc-machine/td-p/7643016

Dieser Thread klingt nach einem ähnlichen Problem - und dort war es eher ein Problem mit den Settings an der Maschine, nicht mit dem Gcode.

**Comment by emka** [comment]
Das könnte helfen. Die limit switches sind bei [0, 0, 0], mit back off um 3mm, also [-3. -3. -3] (beides Maschinenkoordinaten). Wenn der tool change nach z=0 fahren will (anscheinend konfigurierbar), ist er schon über dem Limit von -3

**Comment by NitramLegov** [comment]
Habe heute übrigens bei folgender Zeile im Gcode eine "not supported" Meldung bekommen:
S16000 M3

Das ist mein kompletter code bis zu dem Punkt:
(Bohrfrasen2)
M9
T1 M6
S16000 M3
G54

Muss ich mir im Detail nochmal anschauen..

**Comment by LukasFreeze** [comment]
@NitramLegov bei dir ist "T1 M6" (tool change) drin, der laut dem OP Probleme macht.

Dieses issue wäre auch für die [kleine CNC-Fräse](https://wiki.comakingspace.de/CNC_Mill) interessant, die läuft auch mit grbl

**Comment by NitramLegov** [comment]
Fusion bietet inzwischen die Möglichkeit, ein sogenanntes machine setup zu erstellen und darin einige Einstellungen zu speichern.

Machine Setups kann man im CAM Modul verwalten:
![image](https://user-images.githubusercontent.com/7809163/85235654-1b179800-b417-11ea-9cc8-2ff8df4bf7b4.png)

@Johannes09 hat eine Datei angelegt, die man über Maschine importieren importieren kann:
![image](https://user-images.githubusercontent.com/7809163/85235678-53b77180-b417-11ea-9d8a-80481a4f454f.png)

Mein Vorschlag an dieser Stelle wäre, dass wir das Setup erstmal testen und die Datei auf Vollständigkeit prüfen. Wenn die Datei steht und auch die gewünschte Funktionalität bringt sollten wir das verpflichtend in die Einweisung mit aufnehmen.

**Comment by NitramLegov** [comment]
Das machine setup scheint zu funktionieren. Daher habe ich das in die Einweisung aufgenommen und mache hier zu
