### ISSUE TITLE
P3 - Thermal Runaway

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#220]
P3 threw a thermal runaway error two times in a row.

**Comment by Pakue95** [comment]
I tried printing with it just now and didn't receive any thermal runaway error. However it seems that the temperature is not quite right for the hotend. It's also assembled the wrong way around...

**Comment by reogaro** [comment]
I was unable to reproduce this error on saturday and couldn't find any issues with the hotend assembly. Can you try repeating the steps that lead to the thermal runaway @NitramLegov or did someone fix the Printer and forgot to close this issue?

**Comment by NitramLegov** [comment]
Since this issue is 8 months old and cannot be repeated, I think we can close this.

If the error occurs again, we can open a new issue :)
