### ISSUE TITLE
Klettbelag der Exzenterschleifer schützen/wiederherstellen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#221]
Ich habe diese Woche ein Video gefunden, wonach unter anderem der Einsatz von Schleifgittern zu einer erhöhten Temperatur der Kletthaken an Schleifmaschinen führen kann, sodass sie stumpf werden: https://www.youtube.com/watch?v=_11dTPMABvs

Ganz "passend" hat @LarsKumbier gestern Abend dann festgestellt, dass die Klettfläche am Bosch PEX 300 AE hinüber ist :-(

Vorschlag: wir kaufen "Protector-Pads" wie im Video empfohlen
* [125 mm](https://www.holz-metall.info/shop1/artikel13975.htm) für den Bosch-Schleifer - müsste wohl aufgeklebt werden, so kaputt wie der Teller schon ist
* [150 mm](https://www.holz-metall.info/shop1/artikel13974.htm) für den Festo-Schleifer - hoffentlich noch nutzbar wie vorgesehen, also mit seiner Schlaufen-Rückseite an die Haken des Tellers geklettet

Kosten wären 2x 5,95 € und 4,90 € Versand, ich würde behaupten das ist so sinnvoll dass wir auch direkt mehrere Pads besorgen könnten.

Assignees: @FHuchinson als Eckpate und @Pakue95 als Inventarmanager :-)

**Comment by NitramLegov** [comment]
Da hier etwas kaputt gegangen ist schlage ich vor, das auf die Liste der lost or broken things zu setzen, die entsprechend ja einer Priorisierung bedarf:
https://wiki.comaking.space/Lost_or_Broken

Die Liste ist aus Patricks regelmäßigen checks entstanden. Hier haben wir auch schon einen Punkt "Schleifecke: Schleifmaschinen brauchen alle neue Aufsätze"

Was meint ihr dazu?

**Comment by LukasFreeze** [comment]
Ich finde es schon sinnvoll, die Diskussion über nicht triviale Ersatzteile
hier zu führen - im Wiki geht das eher unter, wär ja cool wenn viele Leute
mitkriegen was *warum* kaputt geht und was dagegen getan wird.

Aber die Übersicht im Wiki ist natürlich wichtig, füge gleich einen Link
hinzu :-)

**Comment by kenomaerz** [comment]
Wurde als Bedarf bei betterplace hinzugefügt: https://www.betterplace.org/de/projects/80975-comakingspace-spenden-fuer-eine-offene-werkstatt

**Comment by SebMakesThings** [comment]
Bin zwar erst ganz neu dabei aber begeistert von eurem Konzept. Die Teller zu ersetzen ist echt sinnig, unterstütze als Einstand gerne die Anschaffung. Geld an Betterplace ist raus.

**Comment by Pakue95** [comment]
Mega! Schaue dann dass ich das Teil bestelle.

**Comment by Pakue95** [comment]
Beim Festool 150mm und bei der Bosch PSS 250 AE sind jetzt neue Schleifteller angebracht!

**Comment by Fragegeist** [comment]
Haben wir auch einen Haben wir auch einen Bosch 300AE? Mit runder Grundplatte?

**Comment by LukasFreeze** [comment]
Yup, hier: https://wiki.comakingspace.de/Eccentric_Sanders#Bosch_PEX_300_AE

@Pakue95 welchen Bosch-Fuß hattest du denn jetzt ersetzt: den rechteckigen (PSS 250 AE), wie du schreibst, oder? Angedacht war hier ja auch der runde (PEX 300 AE), da akuter Bedarf bestand...ich hätte eine Spende von Schwiegermutti die dafür direkt verwendet werden könnte ;-)

**Comment by Fragegeist** [comment]
Die Spende können wir dann anderweitig einsetzen. 
Ich habe dieses Teil:
https://smile.amazon.de/dp/B00BHBXW56/ref=cm_sw_r_cp_apa_glt_i_RQXB3NTH75ZS8BNSFNV1?_encoding=UTF8&psc=1
Auf Verdacht Mal bestellt gehabt weil günstig dran gekommen. Wäre damit dann die Reparatur des PEX 300 AE abzuschließen?

**Comment by SebMakesThings** [comment]
Hab heute mal die Ecke aufgeräumt, alles sortiert und Beispielscheiben zu dem jeweils passenden Lochbild an die Wand geklebt. 
@Pakue95 Falls noch im Budget wäre ein „immer drauf“ Protektorpad für den Festool spitze, es liegen jede Menge nicht passende 150er Scheiben rum, die da sonst sicher immer wieder mal verwendet werden. Hab die nicht passenden Scheiben jetzt erstmal alle gesammelt und im Holzregal unten verstaut.
![741528AD-0925-499E-80E2-209647EB3AEA](https://user-images.githubusercontent.com/87819637/127775337-8c33c049-3655-427d-9582-37a2c2dfcfa0.jpeg)

**Comment by Pakue95** [comment]
Mega! Danke fürs Aufräumen!

Meinst du als Protektorpad sowas in der [Art](https://www.amazon.de/Schutzauflage-Schleifteller-Polierteller-Stützteller-Klett-Schleifscheiben/dp/B00J279JRC)?

**Comment by Pakue95** [comment]
Der Schleifteller von @Fragegeist hat für die 300er Bosch genau gepasst und ist nun eingebaut. Danke an Alex für die Spende!

![IMG_4236](https://user-images.githubusercontent.com/19751734/128251688-753adf94-ab97-4d55-963e-0797aed5f745.jpeg)

**Comment by LukasFreeze** [comment]
der [eigentliche Vorschlag ](https://github.com/comakingspace/do-something/issues/221#issue-762454508) hier wurde noch nicht umgesetzt, wir haben jetzt "nur" neue Schleifteller (sehr geil!!) aber nicht die zwischen Schleifteller und Schleifmedium zu klettenden Protector-Pads, um die neuen Teller länger am Leben zu halten als die letzten - oder?

**Comment by Pakue95** [comment]
Nein, bisher wurde nur die Teller ausgetauscht. Der Punkt mit den Schleifgittern ist nicht wirklich schlüssig. Die typischen M480 Schleifgitter kann man eh nicht ohne "Adapterpad" benutzten

**Comment by LukasFreeze** [comment]
Ah, in dem Video zur Abnutzung scheinen es "beklettete" Gitter zu sein -
wir hätten sicher nur andere? Oder ist das Adapter-Pad das gleiche wie so
ein "Protektor-Pad"? Dann bräuchten wir die Dinger ja sowieso ;-)

Ich kann sie auch gerne spenden, wenn die vorgeschlagenen Pads das sind,
was wir brauchen - aber jetzt bin ich nicht mehr ganz so sicher

**Comment by NitramLegov** [comment]
Wir haben inzwischen komplett neue Schleifmaschinen.

Bezüglich Schleifgittern: Die sind cool, müssen allerdings wie hier beschrieben mit einem Adapterpad genutzt werden, das sich mit der Zeit auch auflöst und nachgekauft werden muss.

Wenn wir das wirklich tun wollen (und auch verpflichtend machen) müssten wir meiner Meinung nach diese Adapterpads und Schleifgitter vorrätig halten. Das sehe ich um ehrlich zu sein nicht als sinnvoll an.

Da hier auch seit einem Jahr nichts passiert ist mache ich mal zu :-)
