### ISSUE TITLE
Lasercutter fährt nach Homing an die immer gleiche Startposition

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#222]
Gestern Abend gab es folgendes Problem: wird der Lasercutter vor Beginn seines Jobs "gehomed", sprich es wird am Gerät oder in LaserCut 5.3 auf "Datum" gedrückt, fährt er wie erwartet nach hinten rechts an seine Endstops.

Danach fährt er allerdings, egal wohin man den Kopf zuvor manuell steuert, mit Beginn des Jobs zu einer Stelle am rechten Rand des Laserbetts und will von dort loslegen. Nach Neustart des Geräts ohne Homing kann man wie üblich von der Stelle anfangen, wo der Kopf sich beim Starten des Jobs befand - aber die Maschine ohne Homing zu betreiben ist nicht gerade schön...

Vor einer Woche ist das definitiv noch in Ordnung gewesen! Wenn wir wieder in die Werkstatt können sollten wir gucken ob es sich wieder erledigt hat, hier schonmal als Reminder...

**Comment by NitramLegov** [comment]
Wir hatten heute bei der Einführung das gleiche Problem. Ich habe nochmal die machine settings auf den laser geschrieben. Danach hatte sich das Problem zumindest für unseren Job heute erledigt.

@kenomaerz du hattest gestern auch gelasert, oder? Hattest du ein ähnliches problem?

Ich würde das issue mal offen lassen. Falls es nochmal auftritt schlage ich die folgenden Punkte vor:

- neusetzen des relativen Startpunktes in lasercut
- verschieben des Jobs auf dem worktable in lasercut
- neustarten von lasercut und Neuaufbau des jobs

Falls eines davon hilft haben wir zumindest einen workaround...eine wirkliche problemursache habe ich heute nämlich nicht gefunden.

**Comment by LukasFreeze** [comment]
Es gab wohl wieder Probleme, was aber funktioniert:

- Laser einschalten
- Homing
- dann erst die Auftragsdatei übertragen

@NitramLegov hofft, das Ganze irgendwann mit einem Auto-Homing beim Maschinenstart überflüssig zu machen.

**Comment by NitramLegov** [comment]
Ich habe auto homing angemacht :)

**Comment by NitramLegov** [comment]
Am Wochenende haben @Pakue95 und ich herausgefunden, wie man den Startpunkt des Lasers fixieren kann. Wenn das gemacht wurde fährt der Laser immer an diesen Punkt und startet den job von dort...und das auch nach einem Neustart....

Falls das passiert kann man das wie folgt fixen:

Der Laser muss im Zustand sein, in dem der aktuelle Job grau hinterlegt ist:
![image](https://user-images.githubusercontent.com/7809163/131665555-baccf1ba-e132-4a73-8cb6-f0f1aed52b12.png)

Hier klickt man nun auf die "Enter" Taste am Laser.

Darauf öffnet sich ein neues Menü, in dem man "Cancel..." auswählen muss.

Hat man das gemacht startet der Laser den Job wieder brav an der Stelle an der er aktuell steht.

**Comment by Pakue95** [comment]
Scheint ja jetzt gelöst zu sein, oder?

**Comment by NitramLegov** [comment]
Aktuell scheint es so, ja

Meiner Meinung nach fehlt hier allerdings noch Doku im Wiki. Stand nur bisher nicht ganz weit oben auf meiner ToDo Liste

**Comment by NitramLegov** [comment]
Ist dokumentiert
