### ISSUE TITLE
Collect activities for betterplace "Thank you" Mail 

### ISSUE THREAD

**Issue by kenomaerz** [comakingspace/do-something#225]
We should write a letter acknowledging the outstanding support we received trough betterplace.org. Please collect activities we should mention here

- Online Seminars (Introductions, Digital Seminars)
- Tor 4 (Please specify)
- Face shields (Please write 2-4 sentences @NitramLegov)
- Umbau (Please write 4-6 sentences @Pakue95 @LukasFreeze @Pakue95 )
- Electricity (Please write 2-4 sentences @Johannes09)
- What else? Please comment!

**Comment by LukasFreeze** [comment]
Hoffentlich noch rechtzeitig hab ich jetzt auch mal ein bisschen am Entwurf
geschrieben 🙈
Zu Tor 4 würde ich hier aber nichts sagen, das war ja eine unabhängige
Förderung und kein Kostenpunkt.
