### ISSUE TITLE
Dekupiersäge zerlegt...

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#227]
Leider ist schon zum wiederholten Mal die Spannschraube hinten an der [Dekupiersäge](https://wiki.comakingspace.de/Scroll_Saw) so weit herausgedreht worden, dass sie aus ihrer Mutter rutscht und die Maschine damit unbrauchbar ist. **Auf keinen Fall in diesem Zustand einschalten!**

Die Reparatur erfordert keine besonderen Fähigkeiten, aber etwas Zeit die ich gestern Abend, als ich den Schaden entdeckt habe, leider nicht hatte:
- Säge vom Tisch abschrauben
- vorsichtig umdrehen/so über eine Tischkante ragen lassen, dass man die Mutter sehen kann
- Schraube wieder "einfädeln"
- Sägeblatt einhängen, Schraube anziehen, Testschnitt machen

Wenn jemand eine Idee hat, wie dieses Problem in Zukunft verhindert werden könnte, immer her damit! Vielleicht passt eine Stoppmutter o.ä. ans Ende der Schraube? Könnte mir aber leider auch vorstellen, dass dann nicht mehr genug Einstellungsstrecke für den Sägeblattwechsel bleibt.

**Comment by HannaMuenne** [comment]
Hej Lukas, ich habe die Säge gestern Abend wieder zusammengebaut. Beim Sägeblattwechsel ist es mir aber tatsächlich auch gleich noch mal passiert und hab's erneut wieder zusammengebaut. Das Sägeblatt ist jetzt im entspannten Zustand noch eingehangen. Es scheint ein Problem zu geben, wenn man versucht das Sägeblatt zu entfernen. Bevor man dafür genug Spiel hat ist die Spannschraube schon rausgedreht, irgendwas passt da nicht, hab aber noch nicht rausgefunden woran es liegt. 
Der nächste kann es erstmal wieder nutzen - bis zum nächste Sägeblattwechsel.

**Comment by Pakue95** [comment]
Habe die Säge abgebaut und den Haltemechanismus kontrolliert. Der Keil, der auf der Gewindestange sitzt rutscht aus seiner Position raus, weil das Haltestück [28092-120](https://www.fluidonline.de/proxxon-28092-120-haltestueck-fuer-dekupiersaege-dsh_9427_17742) verbogen ist. Sieht man auch ganz gut auf der Skizze, dass das Teil normalerweise ein Z-Biegung mit 90° Winkeln haben sollte.

Ich habe es mal auf dem Schraubstock wieder hingebogen und jetzt scheint der Keil nicht mehr rausrutschen zu können. Mal schauen ob das wieder auftritt. Vermutlich ist das Haltestück mit der Zeit durch den Keil nach unten gehämmert worden. Vielleicht durch zu wenig Spannung auf dem Blatt?

![IMG_4148](https://user-images.githubusercontent.com/19751734/119254366-28ed1480-bbb6-11eb-98d8-6bb9f3136ea6.jpeg)
![IMG_4150](https://user-images.githubusercontent.com/19751734/119254370-2be80500-bbb6-11eb-8591-40c3ceb58c3e.jpeg)

**Comment by Pakue95** [comment]
FYI, der Puffer ([28092-203](https://www.fluidonline.de/proxxon-28092-203-puffer-fuer-dekupiersaege-dsh_9417_17732)), der unter der Spannung-Stellschraube sitzt ist auch schon etwas mitgenommen. Noch nichts tragisches, aber sollte man mal im Auge behalten, wenn der Arm anfängt unruhig zu laufen.
