### ISSUE TITLE
Einheitliche Werkzeugbilder für Wiki und Website

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#229]
Auf unserer neuen Website möchten wir gerne Übersichten über unsere Geräte veröffentlichen, die sich aus dem Wiki ergeben:
https://github.com/comakingspace/comakingspace.github.io/issues/8

Hier möchten wir vor allem Bilder der Maschinen zeigen, um neugierigen Menschen den Einstieg über die Webseite zu erleichtern :)

@kenomarz und ich haben daher am Wochenende angefangen, Bilder von unseren Maschinen und Werkzeugen zu machen. Ganz fertig geworden sind wir nicht. Wir wollen in den nächsten Wochen daran weiterarbeiten. Daher dient dieses Issue als "Schaffliste". (@kenomaerz hat die aktuellen Bilder und kann die Maschinen nach seiner ersten Durchsicht abhaken)

Wood Workshop
- [x] Bandsaws
- [x] Belt Sander (Currently Broken, so out of scope!)
- [x] Belt and disc sander
- [x] Biscuit Joiner
- [x] Chop Saw
- [x] Circular Saws
- [x] Corded Drills
- [x] Cordless Drills
- [x] Drill Presses
- [x] Drying Ovens
- [x] Dust Extractors
- [x] Eccentric Sanders
- [x] Flatiron
- [x] Hot Glue Gun
- [x] Impact Drills
- [x] Jigsaws
- [x] Jointer-Planer
- [x] Metabo BS 1638 W
- [x] Oscillating Tool
- [x] Router Table
- [x] Routers
- [x] Scroll Saw
- [x] Sheet Sanders
- [x] Shop Vacs
- [x] Table Saw
- [x] Wood Lathes

Metal Workshop
- [x] Bandsaws
- [x] Bench Grinders
- [x] CMI C-S-BS 250
- [x] Compressor
- [x] Disc Grinders
- [x] Heat Gun
- [x] Metal Lathes
- [x] Rotary Tool
- [x] Welding Transformer

CNC Corner

- [x] CNC Router
- [x] Shop Vacs (Pikachu is in an extrabox, Festool Vacs are fine)

Electronics Room

- [x] 3D Scanners
- [x] 3D Printer
- [x] Drying Ovens
- [x] Function Generator
- [x] Hot Air Soldering Station
- [x] Laser Cutter
- [x] Oscilloscope
- [x] Power Supplies
- [x] Soldering Irons
- [x] Water Chiller

**Comment by NitramLegov** [comment]
@Fragegeist Hättest du in der nächsten Zeit nochmal Zeit, die restlichen Geräte noch abzulichten? :-)

**Comment by Fragegeist** [comment]
Ich würde es Freitag versuchen wollen. 
Denke dass ich am Abend in den Space kommen könnte. Muss ich aber noch mit der Regierung abstimmen ;)

**Comment by NitramLegov** [comment]
Danke @Fragegeist für die verbleibenden Bilder 😍!
