### ISSUE TITLE
Bohr-/Schraubecke besser organisieren

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#23]
Die Ecke für die Bohrer und Schraubenzieher ist mittlerweile ziemlich chaotisch. 

- [ ] Organisation für Bohrer
   Wandhalterung oÄ.
- [x] Schraubenzieher organisieren

![img_1707](https://user-images.githubusercontent.com/19751734/40873638-861b46d6-6664-11e8-8d1a-10938f266da7.jpg)

**Comment by LukasFreeze** [comment]
Für die Schraubenzieher-Wandhalterung(en) schlage ich vor, zwei Leisten mit etwas Abstand voreinanderzuschrauben - so hätten wir deutlich weniger Arbeit und mehr Flexibilität als mit einzelnen Löchern oder Schlitzen in einem aufwändigeren Halter.

**Comment by NitramLegov** [comment]
Nur für die Doku:
Die Bohrmaschinen wurden von der Wand gehängt und hängen jetzt an der Seite der Werkbank. An der Stelle an der die Bohrmaschinen hingen, hängt jetzt ein Holzbrett mit einer Halterung für die Schraubenzieher.
Für die Bohrer kann man entweder Halterungen 3D-Drucken. Gestern gab es noch einen Vorschlag:
Im Rahmen der Aufräumaktion im electronics room ist ein Brett freigeworden. Da könnte man mit der CNC-Fräse entsprechende Aussparungen reinfräsen und das als Sideboard irgendwo in der Werkstatt aufhängen. Das Brett steht im electronics room hinten an der Wand.

**Comment by NitramLegov** [comment]
![dsc_0222](https://user-images.githubusercontent.com/7809163/42314169-bdc7cd08-8044-11e8-848e-b2b0042871e9.JPG)
Das ist das Brett...noch nicht gut, aber besser ;)

**Comment by LukasFreeze** [comment]
Unter dem Tisch gibt es jetzt Schubladenschränkchen, die wir mit mehrfachen oder nur sehr selten benutzten Bohrern etc füllen können. Bitte direkt beschriften!

Was die Wand angeht: @NitramLegov und ich haben vorhin noch ein bisschen überlegt, was wo hinpasst, und es wird wohl auf ein weiteres Brett (#30) links neben dem Kabelkanal hinauslaufen. Da wäre schön viel Platz für die Holz- und Metall-Sprialbohrer, und man kommt sehr gut dran. Für "Spezialwerkzeug" darf man sich ruhig mal etwas strecken, und wir würden Forstnerbohrer u.ä. auf dem Brett vom letzten Post unterbringen.

Da das graue Bitset nicht die allerbeste Qualität hat, ständig sehr durcheinander gebracht wurde und ich es zuhause und für Repair Cafés gebrauchen kann, habe ich außerdem ein kleineres Set von Makita gestiftet und dafür den Großteil des grauen wieder an mich genommen. Sagt Bescheid falls ihr jetzt irgendetwas vermissen solltet, ich bin mir aber ziemlich sicher dass 90 % der Bits aus dem alten Set eh viel zu speziell waren und außerdem gab es die wichtigen nur einmal oder mittlerweile gar nicht mehr (wie gesagt, nicht die beste Qualität...)

**Comment by NitramLegov** [comment]
Das von @LukasFreeze erwähnte Brett hängt inzwischen an der Wand (Danke an Erik, der hat geholfen)
![img-20180720-wa0020](https://user-images.githubusercontent.com/7809163/43136892-62ff88a6-8f4a-11e8-82ff-42d9dda5d97d.jpeg)

Die Bohrer sind sortiert und liegen auf dem Tisch. Für die Holz und Steinbohrer sollten wir eigene Halterungen herstellen (drucken? aus einem Holzblock ausschneiden?)
Für die Metallbohrer können wie die existierenden Halterungen aus dem blauen Kasten nutzen. Laut @Pakue95 war das eine Spende an den Space, wir können da also die Blindniete aufbohren und das entsprechend auseinanderbauen.

Wenn wir das aufhängen sollten wir darauf achten, dass die Bohrer schräg stehen, damit man sie auch gut rausnehmen kann.

**Comment by LukasFreeze** [comment]
Neulich wurden die ganzen Kleinteile vom rechten Teil des Tisches soweit ich weiß spontan in irgendeine Schublade geräumt, da sollten wir sie meiner Meinung nach aber nicht versauern lassen sondern noch einige an die Wand bringen (Stufenbohrer zum Beispiel) und den Rest wenigstens in *beschrifteten* Schubladen ordnen :-P

**Comment by NitramLegov** [comment]
Closed, since this task will most likely change when the space gets moved
