### ISSUE TITLE
Frästisch-Höhe nicht einstellbar

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#230]
["Vorarbeit" via slack]

Vor ein paar Wochen steckte die Fräse im Frästisch so fest, dass sie weder hoch noch runter ging. Markus schien sie zwischenzeitlich repariert zu haben, aber jetzt ist leider der Spannhebel abgefallen:
 @kenomaerz "Ich habs mir heute nochmal angeschaut. die Feder die den Festspannheben spannt ist raus - und ich krieg sie nicht wieder eingesetzt, bin aber auch nicht sicher, wie genau das ursprünglich war. Kann sein, dass das für jemanden der sic hauskennt 3 Handgriffe sind."

Die Teile sind auf den Tisch geklebt, falls jemand Zeit hat :-)

Als langfristige Lösung würde ich außerdem vorschlagen, die Federn aus den Säulen der Fräse zu entfernen (wenn möglich), sodass sie nur noch nach unten "fällt" statt dort durch zusätzlichen Druck verkantet zu werden. Genug Gewicht hat sie eh...

**Comment by LukasFreeze** [comment]
Ich war heute kurz da und hab's hoffentlich wieder hinbekommen :-)

Der Klemmhebel sitzt wieder wo er hingehört, ist allerdings schon etwas "ausgenudelt" (greift eigtl einen Außensechskant aber wird bald rund sein wenn er zu stark gedrückt wird).

Außerdem habe ich die beiden Federn aus den vertikalen Säulen genommen, @kenomaerz fand den ersten Fräsversuch gleich sehr viel angenehmer! Falls die Fräse doch einmal im Handbetrieb genutzt werden soll wäre es gut, die Federn wieder einzusetzen.

Sie liegen jetzt eingetütet im Unterschrank, soweit ich weiß :-)

**Comment by LukasFreeze** [comment]
![IMG_20210616_175233](https://user-images.githubusercontent.com/19755883/122269746-d7e2ee80-cedd-11eb-8a21-d64695b7e6a0.jpg)

Auch noch ein Foto, ging gerade nicht..

**Comment by kenomaerz** [comment]
Jo, ich hab die federn mit Malerkrepp zusammengeklebt und in die entsprechende Tüte gepackt. Fräse lass sich jetzt viel leichter einstellen. Gar kein Vergleich zu vorher.
