### ISSUE TITLE
table saw: angle locking lever detached

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#231]
Karel reported the table saw to be broken, I just had a very quick look and think it **should not be used** before this is fixed: the angle locking lever has come off and the saw could now change its angle mid-cut due to vibrations, possible resulting in dangerous kickback!

Hopefully there is a good picture in the manual [(PDF)](https://www.manualslib.com/manual/46190/Elektra-Beckum-Topline-Pk-255.html) , I could not find a threaded rod sticking out far enough to screw the lever on :-(
Pulling the angle adjustment knob lets the threaded rod disappear even further though, so maybe that can be reversed.

Photo of the current situation (compare to the [wiki image](https://wiki.comakingspace.de/File:Elektra_Beckum_PK_255.jpg), where the lever seems to be in the middle of the angle knob):
![IMG_20210526_172116](https://user-images.githubusercontent.com/19755883/119691348-cb252a80-be4a-11eb-8d17-17ec9eea6263.jpg)

**Comment by Pakue95** [comment]
The angle lock is connected through a threaded rod that goes all the way to the other side of the saw. If you loosen the handle too much the rod+nut can be pushed out of its socket. 

I may fix it in place with a bit of silicon in the future but it is now usable again. 

![image](https://user-images.githubusercontent.com/19751734/119767399-052c1600-beb7-11eb-9aa4-97ddff826099.jpeg)
