### ISSUE TITLE
linker Anschlag der Kappsäge verbogen und Lineal-Halter abgebrochen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#232]
An der Kappsäge ist ein Stück Aluguss mit der Schraube, die das linke Anschlaglineal hält, ausgebrochen.

Keine Ahnung wie das ohne exzessive Gewalt überhaupt passiert, aber na gut - normal sagen wir da "shit happens" und schauen gemeinsam, wie wir es fixen.

ABER: in diesem Fall wurde der Schaden offenbar bemerkt, nicht gemeldet und dann auch noch vertuscht (woanders wieder angeschraubt). Echt jetzt?! Das ist nicht nur potenziell saugefährlich, da das große Aluteil dann lose drauflag, sondern auch ein absolutes no-go beim Umgang mit geteilten Geräten!!

Wenn sich jetzt doch jemand "erinnert" aber nicht an den Pranger gestellt werden möchte, kann er sich auch gerne still und leise bei @Pakue95 melden oder den Anschlag direkt ersetzen...aber das ist einfach saumäßig schlecht gelaufen! Bitte lasst uns unsere Maschinen, erst recht die coolen neuen wie diese Kappsäge, lange erhalten und über Unfälle einfach rechtzeitig sprechen 😤

Vorne kaputt, hinten heile:
![IMG_20210527_230822](https://user-images.githubusercontent.com/19755883/119900145-63530a80-bf44-11eb-8a65-bce464e460a9.jpg)

**Comment by LukasFreeze** [comment]
cool. Der verbleibende Teil des Anschlags ist auch noch verbogen, das Ding muss also definitiv ausgetauscht werden.

**Comment by Pakue95** [comment]
Das ist ziemlich uncool...

Ist das nur das Teil 65, das ausgetauscht werden muss, oder auch 63? For reference: https://www.boschtoolservice.com/at/de/boschprof/spareparts/gcm-12-gdl-3601M23600

**Comment by Pakue95** [comment]
Ok, ich schau es mir morgen nochmal an und bestell dann das Ersatzteil. Voraussichtlich sind das kapp 40€.

**Comment by NitramLegov** [comment]
Ich würde hier wirklich hoffen, dass sich hier jemand verantwortlich fühlt. Shit happens, aber das hier klingt schon ziemlich krass. 

Im Budget ist sowas momentan eigentlich nicht, da wir immernoch mit den lockdown Auswirkungen zu kämpfen haben und noch nicht wieder wirtschaftlich sind :/

**Comment by kenomaerz** [comment]
Ich glaube, dass man das nochmal explizit rumschreiben sollte.

**Comment by Pakue95** [comment]
So, nach längeren Lieferzeiten ist der Anschlag jetzt ersetzt. FYI es mussten auch beide Teile - oben und unterer Anschlag - ausgetauscht werden, da beide verbogen waren.

Der Austausch hat jetzt in Summe ca 40€ gekostet.

![IMG_4253](https://user-images.githubusercontent.com/19751734/131581275-a5cb15be-d976-41e7-97d9-61d7c0dc3604.jpeg)
