### ISSUE TITLE
Tischkreissäge defekt (elektrischer Schaden)

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#234]
Die Tischkreissäge startet nicht mehr, es *dürfte* an diesem zerstörten Kondensator liege :

![IMG_20210630_193741_145](https://user-images.githubusercontent.com/19755883/124025565-e0b0e580-d9f0-11eb-972e-6e96963fd7cd.jpg)

@Johannes09 weiß am besten Bescheid, bis ein neuer Kondensator eingebaut werden konnte müssen wir jedenfalls leider ohne die Säge auskommen.

**Comment by LukasFreeze** [comment]
Sven hat direkt einen Ersatz bestellt 😍

**Comment by Johannes09** [comment]
Die Tischkreissäge funktioniert wieder und ist von @Pakue95 freigegeben.
