### ISSUE TITLE
CNC Router Staubabsaugung erneuern

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#235]
Der 3D-gedruckte Absaugschuh ist beim Fräsen abgefallen und hat dabei eine unschöne Begegnung mit dem Fräser gehabt. Markus hat schon einen neuen gedruckt, aber bei der Gelegenheit können wir den da das Setup etwas verbessern.

![IMG_4193](https://user-images.githubusercontent.com/19751734/125132925-56aa0080-e105-11eb-9bc8-ee21f27595c1.jpeg)

Die Idee ist es die neue Halterung an den Gewindelöchern der Spindelhalterung zu befestigen (Maße folgen) und wechselbare Borsten daran zu montieren. Die Borsten können ggf aus Folie oder Besenborsten gemacht werden.

**Comment by fisch3r** [comment]
Habe gemessen und und mal ein erstes 3D-Modell erstellt. Ich kann aber leider nicht in der Fusion Gruppe speichern. Fehlen mir da die Rechte oder liegt das an der Basic Lizenz?
Ich würde diese Woche mal einen erste Variante davon drucken und mich dann hier wieder melden.

**Comment by NitramLegov** [comment]
![image](https://user-images.githubusercontent.com/7809163/126041352-27ec2fe3-1056-492c-8a07-3894682599ec.png)
An den Berechtigungen für das Fusion Team sollte es nicht liegen. Eher an der Lizenz :(

**Comment by NitramLegov** [comment]
Ich habe gerade nachgeschaut - an den Berechtigungen im Fusion Team sollte es nicht liegen. Da hast du die gleichen wie alle anderen auch. Dann liegt es eher an der Lizenz :-/

**Comment by fisch3r** [comment]
Danke fürs Nachschauen. Schade aber kann man erstmal nix machen. 
Inzwischen habe ich die erste Version mal gedruckt und auch mal zum Test installiert (inzwischen wieder abgebaut). Die Bohrungen haben gut gepasst und der Schlauch saß danke Schelle auch sehr sicher. 
![IMG_6065](https://user-images.githubusercontent.com/584963/126062659-18de7a32-0cc4-4dfc-a55c-a54ef5cc1b96.jpg)

An der Unterseite habe ich drei Stellen für Magneten vorgesehen und die jetzt auch eingeklebt:

![IMG_6070](https://user-images.githubusercontent.com/584963/126062689-34d66119-4918-4a73-9a17-aee96025a63a.jpg)

Es fehlt jetzt natürlich noch der zweite Teil der unten mit Hilfe der Magneten befestigt wird und dementsprechend leicht abnehmbar ist. Aktuell bin ich mir noch nicht sicher wie der aussehen sollte. Mit @Pakue95  hatte ich diskutiert, dass man so eingeschnittene Folie nutzen könnte als Staubschutz. Ähnlich wie hier:

<img width="372" alt="dust_collector" src="https://user-images.githubusercontent.com/584963/126062898-e030c2c4-866e-4201-824c-aab5a6b92841.png">

**Comment by NitramLegov** [comment]
@fisch3r Kannst du die f3d Datei hier hochladen? :)

Oder mir in Slack schicken?

**Comment by fisch3r** [comment]
@NitramLegov  hier ist die Datei, habe sie aus Fusion exportiert, hoffe das Format passt. Falls nicht, kann dir auch gerne eine STL oder so geben
[cnc_dust_collector v7.f3d.zip](https://github.com/comakingspace/do-something/files/8163996/cnc_dust_collector.v7.f3d.zip)
.

**Comment by NitramLegov** [comment]
Danke @fisch3r !
Ich habe da mal reindesigned :)
<img width="676" alt="image" src="https://user-images.githubusercontent.com/7809163/156356989-8cd031d9-d5cc-4cec-9850-8db8b641f515.png">

Die Idee ist, über eine Verjüngung den Luftstrom zu intensivieren - mal sehen, wie gut das funktioniert. Zur not ist alles parametrisiert und kann nochmal geändert werden.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/7809163/156357088-0b0d0077-1ad8-44c7-9588-ea9b3c6cccb4.png">

Das Design kann in Fusion gefunden werden:
https://a360.co/3vy5iJE

**Comment by NitramLegov** [comment]
Internal Notes:
Maximale Höhe Dustshoe: 4,2 cm
Distanz Fräser - Z-Achse: 2,2 cm

**Comment by NitramLegov** [comment]
Dust shoes sind gedruckt (zwei verschiedene höhen) und mit Leder versehen, um die Seiten dicht zu machen.

Können ausprobiert werden. So lange mache ich hier mal zu
