### ISSUE TITLE
Printer SD card dodgy

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#237]
Karel informed me today that the SD card in the P4 printer is right dodgy, some of the printers could not recognize it or read the files on it properly.

**Comment by reogaro** [comment]
After testing 3 computers and 2 SD card readers I concluded the SD was broken. We'll need a replacement.

**Comment by reogaro** [comment]
All printers seem to have working SD cards now. If anything arises in the future, someone can open a new issue.
