### ISSUE TITLE
Kreissäge Spaltkeil zu hoch

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#239]
Der Spaltkeil der Kreissäge scheint etwas zu hoch eingestellt zu sein, sodass man keine "Kerbe" sägen kann. 

@LukasFreeze magst du da morgen auch einen Blick drauf werfen?

![image](https://user-images.githubusercontent.com/19751734/127222775-b0cff7f0-a785-4106-b9de-07fe8a35d6bb.jpeg)

**Comment by LukasFreeze** [comment]
Das könnte sein, der Abstand zwischen Zahnspitzen und Keil kommt mir auf
dem Bild auch etwas groß vor. Ich hab's mir für morgen aufgeschrieben!

PS: du meinst eine Nut ;-)

**Comment by LukasFreeze** [comment]
fixed - der Spaltkeil ist jetzt auch nur noch 6 mm von den Zähnen entfernt, was ein besserer Abstand ist als vorher
