### ISSUE TITLE
Der Holzabfall ist wieder voll!

### ISSUE THREAD

**Issue by Johannes09** [comakingspace/do-something#240]
Wir sollten mal wieder den Holz Müll zum Recyclinghofbringen.
Das wäre eine Aufgabe für zwei mit einem Transporter oder einem größeren Auto. 

- Größe der Holzmüllkiste 95x75cm 

- Recyclinghof Oftersheimer Weg 8, 69124 Heidelberg

- Einen Auswies mit Wohnort Heidelberg oder HD-Kennzeichen

- 4€ Holz abfall Gebühr (wird erstattet)

**Comment by LukasFreeze** [comment]
Die Gebühr fällt sogar gar nicht an, da zwei Punkte auf unseren Müll
zutreffen: unbehandeltes Holz (keine Imprägnierung für den Außenbereich)
und nicht gewerblich (ich sage immer "aus einer Hobbywerkstatt" und musste
noch nie zahlen) :-)

**Comment by Pakue95** [comment]
@Titan-OX und ich haben gestern den Holzmüll und die alten Leuchtstoffröhren weggebracht. Die 4€ Gebühr fiel trotzdem an.
