### ISSUE TITLE
PlatformIO Seminar am 25.09.

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#241]
Lasst uns die kommende Veranstaltung bewerben!

**Titel:** Einführung in PlatformIO

**Leiter & Helfer**: @Narquadah 

**Datum & Zeit:** 25.09.2021 14:00-18:00

**Teilnehmerzahl:** 10

**Zielgruppe:** ??

**Kosten:** Free

**Beschreibung:** https://wiki.comakingspace.de/PlatformIO_Seminar

**Fotos:** *fehlen noch! Vorschläge willkommen :-)*

## Werbung - ToDo:

* hier können alle helfen:
  * [ ] **Freunden und Bekannten davon erzählen!!**
  * [x] Wiki-Seite (https://wiki.comakingspace.de/PlatformIO_Seminar)
  * [ ] ["Makers"-Verteiler](https://wiki.comakingspace.de/Mailing_List)
  * [ ] [Telegram-Gruppe](https://wiki.comakingspace.de/Telegram_Group)
  * [x] "Maker Community HD" WhatsApp-Gruppe
  * [ ] [Heidelberg.de Veranstaltungskalender](https://www.heidelberg.de/hd,Lde/HD/Erleben/veranstaltungskalender.html)
  * [x] [Make:-Kalender](https://www.heise.de/make/kalender/new_event/)

* von der [Geschäftsführung](https://wiki.comakingspace.de/Management) oder anderen Ehrenamtlichen mit Zugang zu erledigen:
  * [x] Eventbrite-Seite
  * [x] Google-Kalender
  * [ ] [Meetup](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/)
  * [ ] [Facebook](https://www.facebook.com/comakingspace/)
  * [ ] [Instagram](https://www.instagram.com/comakingspace/)
  * [ ] [Twitter](https://www.twitter.com/comakingspace/)
  * [ ] LinkedIn
  * [ ] *bei genug Vorlaufzeit:* in nächstem Newsletter erwähnen (@LukasFreeze)
  * [ ] *bei genug Vorlaufzeit:* [Rhein-Neckar-Zeitung](https://www.rnz.de/kontakt/redaktionen.html)

**Comment by ErikSchatz** [comment]
Ich bin dabei!Danke für die Info!VGErik-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 06.09.21, 21:47 schrieb Martin ***@***.***>:

   
  Lasst uns die kommende Veranstaltung bewerben! 
  Titel: Einführung in PlatformIO 
  Leiter & Helfer: @Narquadah 
  Datum & Zeit: 25.09.2021 14:00-18:00 
  Teilnehmerzahl: 10 
  Zielgruppe: ?? 
  Kosten: Free 
  Beschreibung: https://wiki.comakingspace.de/PlatformIO_Seminar 
  Fotos: fehlen noch! Vorschläge willkommen :-) 
  Werbung - ToDo: 
   
    hier können alle helfen: 
     
      Freunden und Bekannten davon erzählen!! 
      Wiki-Seite (https://wiki.comakingspace.de/PlatformIO_Seminar) 
      "Makers"-Verteiler 
      Telegram-Gruppe 
      "Maker Community HD" WhatsApp-Gruppe 
      Heidelberg.de Veranstaltungskalender 
      Make:-Kalender 
      
    von der Geschäftsführung oder anderen Ehrenamtlichen mit Zugang zu erledigen: 
     
      Eventbrite-Seite 
      Google-Kalender 
      Meetup 
      Facebook 
      Instagram 
      Twitter 
      LinkedIn 
      bei genug Vorlaufzeit: in nächstem Newsletter erwähnen ***@***.***) 
      bei genug Vorlaufzeit: Rhein-Neckar-Zeitung

**Comment by NitramLegov** [comment]
@ErikSchatz Willst du als Teilnehmender mit dazu oder eher, um @Narquadah zu unterstützen? Nur damit Kim weiß, worauf er sich einstellen kann.

**Comment by ErikSchatz** [comment]
Kim hätte mich an der Backe,

du natürlich auch!

Aber sobald ich es kapiert habe kann ich natürlich auch anderen helfen.


VG

 

Gesendet: Dienstag, 07. September 2021 um 08:50 Uhr
Von: "Martin" ***@***.***>
An: "comakingspace/do-something" ***@***.***>
Cc: "ErikSchatz" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [comakingspace/do-something] PlatformIO Seminar am 25.09. (#241)


 

@ErikSchatz Willst du als Teilnehmender mit dazu oder eher, um @Narquadah zu unterstützen? Nur damit Kim weiß, worauf er sich einstellen kann.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NitramLegov** [comment]
Alles klar, also eher als Teilnehmer :)

Sobald ich die Eventbrite Seite geschaltet habe kannst du dich darüber anmelden. Das dient einfach dazu, die Anzahl der Teilnehmenden zu begrenzen.

**Comment by NitramLegov** [comment]
Ich habe die Eventbrite Seite erstellt:
https://www.eventbrite.de/e/microcontroller-programming-with-platformio-tickets-170726917807

@Narquadah  Die "Tickets" habe ich auf 6 Stück reduziert

**Comment by produkt-manager** [comment]
Interessant und lehrreich. Danke dafür. Die Plattform (die ich vorher nicht kannte) hat viel Potential.

**Comment by NitramLegov** [comment]
Seminar hat stattgefunden war wohl gut.
