### ISSUE TITLE
3D Printer P3 Knickschutz erneuern 

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#242]
Bei P3 fehlt das 2.85mm Filament, welches als Knickschutz für die X-Achse dient.

Braucht:
* Kabelbinder
* 2.85mm Filament (liegt noch welches unter den Druckern. @Johannes09 hat glaube ich auch noch welches aus ABS)

![image](https://user-images.githubusercontent.com/19751734/132451535-1ecb1e45-d053-4372-aec0-6a01d050e4a4.png)
Image credit @Titan-OX

**Comment by Johannes09** [comment]
![20210912_151648.jpg](https://user-images.githubusercontent.com/22060480/132993231-bdb1e89a-3a2a-4b9d-9f88-9a0a38c7a500.jpg)

**Comment by Johannes09** [comment]
Ich habe mal einen neuen knicksutz installiert
