### ISSUE TITLE
Project photo signs

### ISSUE THREAD

**Issue by LarsKumbier** [comakingspace/do-something#246]
On the last [Plenum](https://wiki.comakingspace.de/Plenum/Meeting_minutes/2021-10-06#Working_Group_Public_Relations:), we suggested to post more on our social media channels. To encourage members to take some pictures with their work, the idea of creating a few arrow signs with some funny comments came up - similar to the one from the RepairCafé:

![grafik](https://user-images.githubusercontent.com/647850/136351680-bff26411-605b-4a23-a9ce-edeefcf0d7ed.png)

The signs can be made from cardboard, out of wood or with the laser.

**Comment by NitramLegov** [comment]
Today I also made a laser engraved version of such a sign. I would say this should be enough for people to take pictures with :-)

<img width="619" alt="image" src="https://user-images.githubusercontent.com/7809163/197620016-f4c596b9-887e-4b17-9b15-1000c42fbbde.png">
