### ISSUE TITLE
Schleifmaschine(n) reparieren

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#25]
Es sind zwei Schleifmaschinen vorhanden, die allerdings aktuell noch nicht genutzt werden können.

Bei beiden ist jeweils der an/aus Schalter kaputt. Aktuell ist er überbrückt, muss aber ausgetauscht / ersetzt werden.

Bei einer der Schleifmaschinen hat außerdem der Geschwindigkeitsregler einen Wackelkontakt.
Die Maschinen liegen aktuell bei Lukas.

**Comment by LukasFreeze** [comment]
bei den beiden erwähnten Exzenterschleifern handelt es sich um einen Festo
RO 2 E und einen Festo RO 150 E - Informationen bitte [hier im Wiki](
https://wiki.comaking.space/Eccentric_Sanders) zusammentragen :-)

2018-06-07 23:52 GMT+02:00 NitramLegov <notifications@github.com>:

**Comment by LukasFreeze** [comment]
Ich arbeite heute von zuhause ein bisschen an der Doku, die Schleifer könnten auch schonmal von jemandem im Space (mit Hinweis auf dieses "Issue"!) auf das Reparatur-Regal in der Holzwerkstatt gebracht werden -> #38 

Hier das Handbuch für den RO 2 E: https://ns323666.ip-37-187-156.eu/manuals/Festo%20Orbital%20Sander/Festo%20RO%202%20E%20Orbital%20Sander.pdf

Für den RO 150 E konnte ich nichts finden, das Gerät sieht dem 2er aber sowas von ähnlich dass ich keine Probleme damit sehe, einfach für beide die gleiche Anleitung anzunehmen.

**Comment by NitramLegov** [comment]
Die Schleifmaschinen sind jetzt im Reparatur-Regal und haben jeweils einen Aufkleber mit "#25".

**Comment by LukasFreeze** [comment]
@lokowandg hat sich heute den etwas besseren Schleifer angesehen und den Kontakt, der normalerweise durch den Schiebeschalter unterbrochen wird, innen mit einem passenden Stückchen Sperrholz festgeklemmt.

Das ist schonmal besser als das alte Stück Holz außen am Schalter, aber das Gerät geht immer noch an sobald der Stecker in die Steckdose gesteckt wird - ich habe dafür einen Schnurschalter bestellt und werde ihn bei der nächsten Gelegenheit einbauen.

Der Wackelkontakt am Drehregler könnte sich durch eine generelle Entstaubung schon erledigt haben, sehen wir dann später ;-)

**Comment by LukasFreeze** [comment]
@Johannes09 hat den Schnurschalter gestern eingebaut, morgen Nacht werde ich ein paar Platten schleifen und wenn währenddessen kein Wackelkontakt mehr bemerkbar ist wäre der erste Schleifer fertig repariert :-)

Als nächstes dann so bald wie möglich 
- Einweisung schreiben (hab schon ein paar Notizen...)
- Staubsaugeradapter basteln (#24)

**Comment by LukasFreeze** [comment]
Der Schleifer hat sich gestern ganz vernünftig angestellt, da es noch keine Einweisung gibt habe ich ihn aber nochmal ins Büro gebracht.

**Comment by NitramLegov** [comment]
added the commissioning template to the wiki

**Comment by Pakue95** [comment]
Ich habe den RO 2 E heute auch nochmal getestet und keine Probleme festgestellt. Habe noch 1-2 Punkte zur Einweisung hinzugefügt und finde fände diese jetzt vollständig. Wenn es keine Einwende gibt werde ich sie heute Abend freigeben.

**Comment by Pakue95** [comment]
der RO 2 E ist jetzt offiziell benutzbar. Der Festo RO 150 E geht fürs erste wieder ins Lager. Wenn Interesse am Reparieren hat einfach melden bzw. ein neues Issue aufmachen.
