### ISSUE TITLE
Biscuit Jointer Commissioning

### ISSUE THREAD

**Issue by LarsKumbier** [comakingspace/do-something#250]
Our [Biscuit Jointer](https://wiki.comakingspace.de/Biscuit_Joiner) is just missing the documentation and a QR-Code to be commissioned. A non-manager could prepare everything, so that a manager could give their thumbs-up (after the also missing  security check)

**Comment by LukasFreeze** [comment]
The introduction is already done:
https://wiki.comakingspace.de/Biscuit_Joiner_Introduction

**Comment by Duehok** [comment]
I have added pictures to the wiki that can be used to explain the use of the joiner, which cannot really be guessed just from seeing the tool:

https://wiki.comakingspace.de/Biscuit_Joiner

They are full resolution. A smaller resolution can (and probably should) be used once the page is more filled.

**Comment by NitramLegov** [comment]
According to @LarsKumbier comment in the wiki, this was commissioned by Lukas?

Is the Tool now publicly available and "just" needs a QR Code?

**Comment by Pakue95** [comment]
QR Code is already done. I'd like to have just 1-2 more paragraphs in the Docu. Currently there is very little information for people who haven't seen a biscuit joiner yet.

**Comment by LukasFreeze** [comment]
Patrick has even printed the code I think, but his dust extraction comment
came after Lars and I tested the machine - @Pakue95 should we make this a
requirement or just "nice to have"?

I'll also add a bit more to the documentation shortly

**Comment by Pakue95** [comment]
Proper dust extraction should be a priority imo as it going along with the safety of the equipment. I might get to design a test piece today.

**Comment by Pakue95** [comment]
Dust extraction adapter is done
![IMG_4430](https://user-images.githubusercontent.com/19751734/140572318-4b0899fc-0494-48b8-86e3-a9b0f14e72ba.jpeg)
!
