### ISSUE TITLE
deutsche Bezeichnungen der Ausrüstung für Wiki & Website

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#252]
(könnte sehr gut mit #229 kombiniert werden, bekommt aber lieber mal eine eigene Liste)

Es wäre super, wenn wir die Ausrüstungs-Galerien im Wiki (siehe auch #161 ) und auf der Website bilingual gestalten könnten, also je nach Wunsch englisch oder deutsch beschriftet.

Die Infoboxen im Wiki enthalten ja schon "synonyms", die allerdings nicht einfach übernommen werden können:
- hier stehen gerne *mehrere* gebräuchliche Namen zu finden (alles, was man so findet)
- weitere englische Namen sind ebenso vertreten wie nicht ganz korrekte (in Anführungsstrichen)
- es sollte eine Übersetzung *pro Seite* gesetzt werden, nicht pro Box

Trotzdem muss man sich jetzt nicht super auskennen um hier zu helfen, denn die Liste der deutschen Namen beginnt üblicherweise mit der "richtigen" Bezeichnung und wird dann immer umgangssprachlicher :-)

Mein Vorschlag: **wir gehen die Ausrüstung durch und fügen der Hauptbox jeder Seite den Parameter "german" hinzu, mit der "richtigen"/besten Übersetzung als Wert** (Bsp Wiki-Seite "Compressor": `|german = Kompressor`

*Erläuterung für Fortgeschrittene*: Das fügt der Seite im Hintergrund die SMW-Property "Has German" hinzu. Die habe ich gerade angelegt und auch mit den ersten zwei Geräten der Metall-Maschinen-Galerie getestet: https://wiki.comakingspace.de/Metal_Workshop/Gallery#Maschinen_(DE)

In der Leseansicht sind "german" und "[[Has German::]]" unsichtbar, stört also überhaupt nicht :-)

**To Do:**
Wood Workshop
- [x] Belt Sander
- [x] Biscuit Joiner
- [x] Chop Saw
- [x] Circular Saws
- [x] Corded Drills
- [x] Cordless Drills
- [x] Drying Ovens
- [x] Dust Extractors
- [x] Eccentric Sanders
- [x] Flatiron
- [x] Hot Glue Gun
- [x] Impact Drills
- [x] Jigsaws
- [x] Jointer-Planer
- [x] Metabo BS 1638 W
- [x] Oscillating Tool
- [x] Reciprocating Saw
- [x] Router Table
- [x] Routers
- [x] Scroll Saw
- [x] Sheet Sanders
- [x] Shop Vacs
- [x] Table Saw
- [x] Wood Lathes

Metal Workshop
- [x] Bench Grinders
- [x] CMI C-S-BS 250 (als "Metall-Bandsäge")
- [x] Compressor
- [x] Disc Grinders
- [x] Heat Gun
- [x] Metal Lathes
- [x] Rotary Tool
- [x] Welding Transformer

CNC Corner

- [x] CNC Router
- ~~Shop Vacs~~

Electronics Room

- [x] 3D Printers (Prusa i3 MK2S)
- [x] 3D Scanners
- [x] Drying Ovens
- [x] Function Generator
- [x] Hot Air Soldering Station
- [x] Laser Cutter
- [x] Oscilloscope
- [x] Power Supplies
- [x] Soldering Irons
- [x] Water Chiller

Knifflige Fälle wird es sicher auch mal geben, gerne einfach überspringen und hier kommentieren :-)

**Comment by NitramLegov** [comment]
Ich würde dennoch vorschlagen, dass wir der deutschen Übersetzung ein eigenes Feld im InfoBoxTemplate spendieren. Das kann dann in der Ausgabe gerne in den Synonyms auftauchen und bei einer "extrabox" eben keine smw property setzen.

Der Grund dafür ist, dass ich es unseren Usern möglichst einfach machen möchte, diese Informationen einzutragen.

Nutzer, die den visual editor nutzen (der ja default ist) können somit einfach ein Feld ausfüllen und gut ist. Und die "power user", die mit source code editing arbeiten haben keine Nachteile.

Kann bei Gelegenheit daran arbeiten, das in das Template einzufügen.

**Comment by LukasFreeze** [comment]
Können wir auch gerne machen! Ich würde das in der Ausgabe dann aber lieber
ganz ausblenden als in die "Synonyms" zu mixen, das führt sonst nur zu
Dopplungen wenn man sich nicht groß damit beschäftigt

**Comment by NitramLegov** [comment]
Das klingt sinnvoll, lass uns das so ausprobieren :) 

Nur für die QR Codes überlege ich dann, ob ich das nicht sogar in die Überschrift packe. Da kam ja zum Beispiel auch das Feedback, dass wir die deutschen Begriffe mit hinhängen sollten.

Aber in den QR Codes ersetze ich die Überschrift eh. Das kann ich also im wikicrawler machen :)

Und wie ich die Website dann im Detail aufbaue weiß ich eh noch nicht 😅

**Comment by LukasFreeze** [comment]
Die Maschinen müssten fertig sein! Wenn doch noch einzelne fehlen bemerken wir das bestimmt beim Aufhübschen von Galerien (#161 ) :-)

Doch weiter geht's: da wären z. B. noch *ein paar* "kleine" Werkzeuge in der Holzwerkstatt...
- [ ] Bandsaw Blades
- [ ] Bandsaw Fence
- [ ] Bandsaw Sled
- [ ] Bench Hook
- [ ] Bevel Gauges
- [ ] Calipers
- [ ] Caulking Guns
- [ ] Centerline Gauge
- [ ] Chisels (Woodworking)
- [ ] Circular Saw Guide
- [ ] Clamps
- [ ] Corner Clamping Jigs
- [ ] Crosscut Saws
- [ ] Dowel Centers
- [ ] Fretsaws
- [ ] Hatchet
- [ ] Hole Saws
- [ ] Inclinometer
- [ ] Japanese Saws
- [ ] Knives
- [ ] Levels
- [ ] Mallets
- [ ] Miter Boxes
- [ ] Oscillating Tool
- [ ] Outfeed Roller
- [ ] Panel Carriers
- [ ] Personal Protection
- [ ] Planes
- [ ] Pliers
- [ ] Pruning Saw
- [ ] Punches
- [ ] Push Blocks
- [ ] Push Sticks
- [ ] Rasps
- [ ] Reciprocating Saw
- [ ] Saw Sets
- [ ] Scissors
- [ ] Spatulas
- [ ] Tape Measures
- [ ] Vises
- [ ] Wolverine Jig
- [ ] Woodturning Tools
- [ ] Wrenches
- [ ] Yardsticks

Wer diese Liste nicht so praktisch findet kann auch einfach in der Galerie unter https://wiki.comakingspace.de/Holzwerkstatt sehen, wo Name und/oder Bild noch nicht passen ;-)

**Comment by LukasFreeze** [comment]
Danke @NitramLegov für die Einpflegerei 😍  "pliers" und "wrenches" sind noch nicht abgehakt - warum? Wollen wir die auch noch splitten?

Im Gemeinschaftsraum sind auch noch ein paar Sachen ohne deutsche Namen, aber die Priorität ist da wohl erstmal der [(veraltete) Rest der Seite](https://wiki.comakingspace.de/Common_Room), bevor wir über eine Übersetzung nachdenken...

**Comment by NitramLegov** [comment]
Ja, die Pliers und Wrenches würde ich auch noch splitten wollen.

Ich habe uns auch mal DataCheck Seiten angelegt:
https://wiki.comakingspace.de/Category:Machines/DataCheck
https://wiki.comakingspace.de/Category:Tools/DataCheck

Da sehen wir auch, dass es noch Sachen gibt, die uns rausfallen, weil sie keine Locations haben, die wir abfragen

Zum Beispiel sind die Screwdriver Bits im "Drilling Table" und der Spin Dryer im "Precious Plastics Corner".

Da sollten wir uns noch überlegen, ob wir die Locations möglichst spezifisch haben wollen oder ob uns "Wood Workshop", "Metal Workshop", "Electronics Room" und "Common Room" (ggf. noch eine Location "Office" oder "Not Available" für kaputte Sachen?) ausreichen.

Je nachdem, wie wir das entscheiden sollten wir das dann aber auch konsequent durchziehen :)

Aktuell fehlen und so einige Sachen in unseren Übersichten

**Comment by NitramLegov** [comment]
Da ich aus Wiki Sicht eigentlich gut fände, die Locations möglichst spezifisch zu haben ("Drilling Table" hilft mir deutlich mehr als "Wood Workshop", wenn ich etwas suche) habe ich mal geschaut, ob es die Möglichkeit gibt, Properties quasi zu "vererben".

Es gibt da wohl ein bisschen was, aber wirklich cool ist das nicht:
https://www.semantic-mediawiki.org/wiki/Help:Inheritance_in_hierarchies

Eine alternative wäre, dass wir ein Set an validen Locations definieren. Dann könnten wir beim Wood Workshop sagen, dass die Seite eben mehrere Locations abfragen muss. Das ginge, wäre nur Aufwand, falls eine neue Location dazukommt...das wissen die "üblichen Verdächtigen" dann ja aber und wir könnten das auch auf der Seite der Location Property dokumentieren

Eine Herausforderung könnte noch sein, bei einem Umzug der Geräte/Tools das wiki aktuell zu halten 🙈

**Comment by NitramLegov** [comment]
Aaaah, super! Die Subqueries gefallen mir gut :-)

Ich schlage vor, diesen Teil des Issues (Datenstrukturen für Locations und zugehörige Maschinen & Tools) in ein eigenes Issue auszulagern und dieses hier wirklich auf die deutschen Bezeichnungen zu beschränken. Das mache ich bei Gelegenheit mal.

**Comment by NitramLegov** [comment]
Die deutschen Bezeichnungen der Tools habe ich angepasst soweit mir bekannt & relevant. Damit ist für mich dieses Issue abgearbeitet und kann geschlossen werden.

Für die Diskussion über die Locations habe ich #265 angelegt. Die Diskussion über die allgemeine Struktur der Werkzeugseiten können wir in #266 führen.

Falls die Default Bilder in den Gallerien stören schlage ich vor, ein _neues_ Issue aufzumachen, um die zu ersetzen. Eine Arbeitsliste kann über https://wiki.comakingspace.de/Special:WhatLinksHere/File:Tool-default.png oder über https://wiki.comakingspace.de/index.php?title=Special:Ask&q=%5B%5BCategory%3ATools%5D%5D+%5B%5BHas+image%3A%3AFile%3ATool-default.png%5D%5D generiert werden :-)
