### ISSUE TITLE
Belt and Disc Sander Comissioning

### ISSUE THREAD

**Issue by SebMakesThings** [comakingspace/do-something#253]
I've purchased a belt and disc sander for the space that now needs comissioning. I'll start the wiki pages now and of course would be super happy if someone of you would join to work on the wiki

https://wiki.comakingspace.de/Belt_and_Disc_Sander
https://wiki.comakingspace.de/Belt_and_Disc_Sander_Introduction

Be patient with me, that's my first Wiki Edit ;-)

**Comment by NitramLegov** [comment]
The introduction is final and the commissioning template was removed from the wiki page. Therefore, I am closing this issue.
