### ISSUE TITLE
Upcoming Wiki Changes

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#254]
I´ll make a few changes to our mediawiki soon:

- [x] - Extend session expire significantly (currently 1h)
- [x] - Allow uploading of larger files (up to 50MB?)
- [x] - Allow uploading of videos
- [x] - enable TimedMediaHandler Extension
- [ ] - Enable MediaViewer Extension
- [x] - Move to GHCR Container

Any more suggestions?

**Comment by NitramLegov** [comment]
I have checked the session expire. It´s currently 30 days.

We have had reports from users which indicated that they had been logged out while editing a page. We have to monitor this in the future and do further analysis regarding the root cause.

**Comment by NitramLegov** [comment]
I had the MultiMediaViewer Extension activated today. It is really nice, but using it unfortunately breaks the redirect functionality of galleries coming from semantic queries.

Therefore, I have disabled it again.

Most likely, I will enable Extension:BetaFeatures soon and make MediaViewer a Beta feature to be activated by each user.

**Comment by LukasFreeze** [comment]
Regarding the session timeout: are we sure people were actually logged out? I get this error a lot, note I am still logged in (menu at the top right) but the edit only goes through when I try a second time:
![IMG_20211107_194247_196](https://user-images.githubusercontent.com/19755883/140657689-7c99e312-6ea4-4b2c-8f47-101d3b33e9d4.jpg)

**Comment by LukasFreeze** [comment]
I just had a real logout issue after max. 9 minutes:
Created a member at 22:38, got a permission error at 22:47 when trying to create the next one.

Win 10, Firefox 94.0.2
