### ISSUE TITLE
expand woodturning tool holder

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#257]
I have a bunch of additional woodturning tools that a friend of the Space donated - however, they need a proper home before we can enjoy them!

My idea would be a holder that *could* have a place on the wall next to the existing one, but *should* be portable to be set up next to the red lathe when it is used on any bench. We could also make two holders, a fixed and a portable one!

![IMG_20211120_125024](https://user-images.githubusercontent.com/19755883/142738432-d0236d82-7ea7-482e-9604-e97376a40dcb.jpg)

**Comment by NitramLegov** [comment]
During #264 we identified a bunch of new Woodturning tools which first need to get sharpened (#280) and then need to be made available in the Woodturning tool holder.

I would also propose to label the tools in some way so that people know what they are :)

**Comment by Jrosy** [comment]
Sorted![IMG_20221111_215400.jpg](https://user-images.githubusercontent.com/104432223/201429228-0695c6c3-ddd4-4283-8c2a-9e0fa054a6a3.jpg)

**Comment by Jrosy** [comment]
Although we might need to glue on a couple of small blocks lower down for the few shorter tools (impossible to cover both short and long in one). I suggest we wait until we've labelled all tools and sort them on the holder to see where the short tools end up
