### ISSUE TITLE
Jigsaw exhaust adapter broken off

### ISSUE THREAD

**Issue by SebMakesThings** [comakingspace/do-something#258]
![image](https://user-images.githubusercontent.com/87819637/143680024-2ab6aba5-ed54-4afb-beae-967d044aac9e.jpg)

Happened today during my sawing, can print new one but need stl from creator.

**Comment by Pakue95** [comment]
If you give me the measurements, I can design one quickly.

**Comment by NitramLegov** [comment]
@Pakue95 I think there is something in Fusion already:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/7809163/143686274-90e0432d-6b06-4004-adbb-dbcc996ef31f.png">


@SebMakesThings I can invite you to our Fusion360 Team if you tell me in private, which E-Mail Adress to use :)

**Comment by LukasFreeze** [comment]
Ich hab das ursprüngliche Design von Malte wiedergefunden, stand im Wiki aber ist (noch?) nicht bei uns hochgeladen: https://www.thingiverse.com/thing:3408971

Könnten wir also nochmal probieren, falls nicht schon jemand eine neue Version konstruiert hat! Neulich war die Säge jedenfalls immer noch ohne Adapter unterwegs, bzw. hatte jemand den Adapter von der Dekupiersäge (falschrum) draufgesteckt was dementsprechend aber auch nicht zum Staubsauger gepasst hat...

**Comment by NitramLegov** [comment]
![DSC_1552](https://user-images.githubusercontent.com/7809163/156832893-f042fcba-c529-4ce2-8e00-6266ed61574f.JPG)
