### ISSUE TITLE
neues Blatt für die Tischkreissäge

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#260]
@Pakue95 hat neulich das Blatt unserer Tischkreissäge von dunklen Ablagerungen befreit, die den Sägespaß deutlich reduziert hatten, aber auf Dauer müssen wohl auch mal die Zähne geschärft werden. Damit das keine wochenlange Zwangspause für die ganze Maschine bedeutet, wäre ein Ersatzblatt super und ich sollte eins vorschlagen: von den "roten von Freud" hört man viel gutes und ich wäre für das hier! https://www.sautershop.de/kreissaegeblatt-hm-250-x-2.8/1.8-x-30-mm-z-60-fr-fr23w003t?c=16324

**Comment by Pakue95** [comment]
Ist bestellt

**Comment by LukasFreeze** [comment]
@Pakue95 hat das Blatt schon gewechselt und es tut seinen Job <3
