### ISSUE TITLE
Frästisch: Fehlende Reduzierhülse

### ISSUE THREAD

**Issue by drei85** [comakingspace/do-something#261]
An der Oberfräse, die im Frästisch eingebaut ist, fehlt die Reduzierhülse der Spannzange. Ich konnte sie rund um den Fräsertisch leider nicht finden.

Christoph 

![IMG_20220102_182751](https://user-images.githubusercontent.com/48619066/148039151-55a5c89a-66a3-4585-8f95-0a5a5f2f342f.jpg)

**Comment by Pakue95** [comment]
Sollte unten im Schrank in der Plastikbox mit den anderen Ersatzteilen sein.

**Comment by LukasFreeze** [comment]
Ist wieder da!
