### ISSUE TITLE
Delta 3D-Printer

### ISSUE THREAD

**Issue by MartinMeyerOnGithub** [comakingspace/do-something#262]

**Comment by NitramLegov** [comment]
What's the issue / plan here?

**Comment by MartinMeyerOnGithub** [comment]
Information-gathering of how a Delta 3dprinter can be configured.

**Comment by MartinMeyerOnGithub** [comment]
Marlin settings, things to be aware of ...

**Comment by NitramLegov** [comment]
Hmmm, okay. Is there any specific Space-Project attached? If so, I would propose to start finding a group to work together on the project. Best would be in slack :)

If this is just about information gathering, I would propose to ask around whether somebody has experience in this area (for example, there is #topic-3d-printing in slack, which might be a good starting point.

As for an issue, I would say let´s close this if there are no specific things to be done **for the space**

**Comment by NitramLegov** [comment]
As a starting point, please also see:
https://duet3d.dozuki.com/Wiki/Calibrating_a_delta_printer

**Comment by LukasFreeze** [comment]
As I understood, the idea was that Steven wanted to get involved with the
delta printers standing around in the eRoom and would ask for the current
status and collaborators since there was no issue or wiki page to be found
about it

**Comment by NitramLegov** [comment]
Aaaah, Thanks @LukasFreeze. That´s a different topic :)

For this, there is #proj-deltaprinter in Slack which I think is used for discussions around this. 

Of course, a wiki-page and an issue to bring these channels together absolutely makes sense

**Comment by NitramLegov** [comment]
Since this is a stale issue, without too much content in it, I´m gonna close this :)
