### ISSUE TITLE
Wiki admin list

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#263]
- [x] Update 
- [x] fix favicon
- [x] install Extension:RottenLinks

Anything else you would like? Mention it in the comments :-)

**Comment by LukasFreeze** [comment]
having thumbnail images for embedded STLs would be nice - is this an option for us? https://www.mediawiki.org/wiki/Extension:3D/en#Install_3d2png

**Comment by NitramLegov** [comment]
The wiki is already capable of handling stl and other 3D object files with the 3DAlloy extension: https://www.mediawiki.org/wiki/Extension:3DAlloy

When I took care of the 3D files, I picked this extension over the one you have mentioned for the following reasons:
- supports more file types
- adds a real 3D render which shows the object from all sides instead of just generating a thumbnail

You can see this in action on https://wiki.comakingspace.de/User:NitramLegov/Playground

I am not sure, how the two extensions would work together, so I prefer keeping 3DAlloy unless there are reasons against it :)

**Comment by LukasFreeze** [comment]
Ah, I thought we might be using the 3D extension already (also shows parts
from all sides when clicked) and just don't have the thumbnail rendering
part of it.

If thumbnails *should* work, then I guess there is a minimum size or they
can't be used in galleries? It looks nice on your playground, but I was
originally asking because I saw them not rendering on
https://wiki.comakingspace.de/Project:FlyerStand

**Comment by NitramLegov** [comment]
I guess 3DAlloy does not provide thumbnails in galleries

**Comment by LukasFreeze** [comment]
SMW gallery redirects don't work in mobile view (clicking a photo leads to the file page, not the machine/tool page) - maybe something that can be fixed within the mobile extension?

**Comment by NitramLegov** [comment]
I have worked on the Session issue today, but am not super sure whether what I did helped or not. Let´s keep an eye on it

**Comment by NitramLegov** [comment]
The issues with SMW gallery redirects on mobile pages has been resolved by disabling MobileFrontend and switching to a truly responsive Skin (Medik)

**Comment by NitramLegov** [comment]
https://wiki.comakingspace.de/Special:RottenLinks?showBad=1&limit=1000
