### ISSUE TITLE
Wiki: Werkzeug-Locations 

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#265]
Wie in #252 besprochen sollten wir uns überlegen, wie wir die Locations der Maschinen und Tools im Wiki aufbauen. 

Die Entscheidung, die wir hier treffen sollte ist, ob wir lieber "generische" Locations wie "Wood Workshop", "Metal Workshop" möchten oder lieber "spezifischere" Locations wie "Chop Saw Station", "Router Table", o.Ä. Lukas und ich habe in https://github.com/comakingspace/do-something/issues/252#issuecomment-1118692699 und https://github.com/comakingspace/do-something/issues/252#issuecomment-1119508226 bereits angerissen, dass wir beide dafür sind, die Locations möglichst spezifisch zu machen und eine "Hierarchie" aufzubauen, die angibt, dass die Chop Saw Station im Wood Workshop zu finden ist.

Für mich gibt es hier also zwei Sachen zu entscheiden:
- Wie bilden wir das technisch ab?
- Welche Locations haben wir?

### Technische Abbildung
Zur Abbildung in SMW hat Lukas in https://github.com/comakingspace/do-something/issues/252#issuecomment-1119508226 folgenden Vorschlag gemacht:

> Technisch würden uns denke ich "subqueries" weiterhelfen, gekoppelt mit
Kategorisierung der Locations:
[[Location::<q>[[Category:Woodworking]]</q>]] liefert alle Seiten, deren
Location in der Kategorie Woodworking ist. Schaut zum Testen mal mit
Special:Ask wie es geht, funktioniert seit heute morgen zB auch für alle
Sachen beim "Drilling Table" weil ich diese Seite als "Woodworking"
kategorisiert habe :-)
EDIT: Sammlung "Locations" im Wiki --> https://wiki.comakingspace.de/Locations 
EDIT 2: mein subquery-Vorschlag ist hoffentlich nicht ganz das, was [@NitramLegov](https://github.com/NitramLegov) da als wenig coolen Workaround gepostet hatte :-P Ich hatte es hier gefunden: https://www.semantic-mediawiki.org/wiki/Help:Subqueries_and_property_chains

Meine *Gedanken* dazu sind aktuell:
- Die Idee mit Subqueries finde ich richtig gut und glaube, dass das der richtige Weg ist!
- Ich bin noch nicht glücklich damit, Properties und Categories zu vermischen. Vielleicht finden wir hier eine andere Möglichkeit - ich kann da mal rumspielen und schauen, ob das auch anders geht
- Wenn wir die Locations ausbauen schlage ich vor, in der Property eine Liste von erlaubten Werten zu setzen (https://www.semantic-mediawiki.org/wiki/Help:Special_property_Allows_value)

### Liste der Locations
Um über die Locations zu entscheiden habe ich mal angefangen, eine Karte der Wertstatt zu malen (basierend auf unserem SweetHome3D Modell) und meine vorgeschlagenen Locations einzuzeichnen. Abgelegt habe ich das in https://github.com/comakingspace/CommonFiles/tree/master/CoMS%20Model und bearbeiten könnt ihr es mit diagrams.net (https://app.diagrams.net/#Hcomakingspace%2FCommonFiles%2Fmaster%2FCoMS%20Model%2FWiki_Locations.drawio).

Daraus ergibt sich folgender Vorschlag zur Diskussion. Grüne Bereiche sind für mich die übergeordneten Locations, Lila Bereiche die spezifischen.
<img width="609" alt="image" src="https://github.com/comakingspace/do-something/assets/7809163/3bb6149b-7fd0-4cc7-8c6a-3f9bbdcdde63">

**Comment by LukasFreeze** [comment]
Ich finde die skizzierte Struktur schon sehr gut, störe mich eigentlich nur an den ganzen "Corners" - das wären für mich "Areas", aber ist vielleicht auch nur Geschmackssache.

Mit einer Mischung von Properties und Categories sehe ich überhaupt kein praktisches Problem, aber das weißt du ja schon ;-)

**Comment by NitramLegov** [comment]
Cool, dann sind wir uns ja prinzipiell einig. Dazu, ob die "Corner" jetzt "Corner" oder "Area" heißen sollen habe ich keine starke Meinung. Daher habe ich die mal alle in "Area" umbenannt.

Dann kann ich mich bei Gelegenheit mal dran machen, das aufzubauen und umzusetzen :-)

**Comment by NitramLegov** [comment]
Ich habe mal als Unterseite meiner User-Page ein bisschen was zum testen aufgebaut und bin soweit zufrieden damit.

Effektiv bekommen die Location Seiten die Kategorie "Location" zugewiesen.
Die spezifischen Seiten (Also die "Areas") haben dann eine Property (habe die mal "Sits In" genannt, um nichts zu zerhageln), die auf die übergeordnete Location hinweist.

Und die Maschinen bekommen die gleiche Property zugewiesen, nur dass diese auf die Area hinweist.

Und falls wir eine Maschine dennoch mal direkt einem Workshop zuweisen funktioniert auch das :-)


Das heißt ich würde dann irgendwann loslegen und das umsetzen.

**Comment by NitramLegov** [comment]
Für die meisten Machines habe ich die Location auf eine spezifische Location gesetzt. Für mich ist alles außer "Common Room", "Electronics Room", "Metal Workshop" und "Wood Workshop" eine spezifische Location.

Offen sind:
- Common Room
- - [Laminator](https://wiki.comakingspace.de/Laminator)
- - [Panasonic PT-F300NTE](https://wiki.comakingspace.de/Panasonic_PT-F300NTE)
- Metal Workshop
- - [Bench Grinders](https://wiki.comakingspace.de/Bench_Grinders)
- - [Disc Grinders](https://wiki.comakingspace.de/Disc_Grinders)
- - [Dremel 4000](https://wiki.comakingspace.de/Dremel_4000)
- - [Myford ML7](https://wiki.comakingspace.de/Myford_ML7)
- Wood Workshop
- - [BAMATO AB-550](https://wiki.comakingspace.de/BAMATO_AB-550)
- - [Elektra Beckum PK 255](https://wiki.comakingspace.de/Elektra_Beckum_PK_255)
- - [Metabo BS 1638 W](https://wiki.comakingspace.de/Metabo_BS_1638_W)

Um Vorschläge für Location Namen bin ich dankbar (ich schätze wir werden hier neue Locations brauchen) :-)

**Comment by Pakue95** [comment]
Hier mal noch ein paar Änderungsvorschläge zur Locationbenennung nachdem ich angefangen hab die Locations auch in unserer Anlagenverwaltung einzutragen (aktueller Stand Wiki):

* Common Room
  * Community Wall
  * **Gaming & Chillout Zone -> Chillout Area (kürzer und benutzt den "Area" Suffix wie auch die anderen Locations)**
  * Kitchen
  * Lockers
  * Office Supply Shelf
  * Personal Protection Shelf
  * Seminar Area
  * Sewing Area
* Electronics Room
  * 3D Printing Area
  * **Electronics Workbenches -> Electronics Area (wäre konsistenter)**
  * Laser Area
* Metal Workshop
  * (+) Metal Lathe (Area)
  * Grinding Table
  * **Metal Workbench -> Handheld Metal Tool Area**
  * **Metallwerkstatt -> ist das nicht redundant?**
  * Welding Area
* Network
* Office
  * **Lukas/Bench -> Lukas Workbench (Konsistenz)**
  * Patricks Workbench
  * (+)**Martins Workbench**
  * (+)**Johannes Workbench**
  * (+)**Office Storage**
* Storage Hallway
  * CoMS Storage
* Vehicle Workspaces
* Wood Workshop
  * CNC Area
  * Clamp Cart
  * Drilling Table
  * Gluing Area
  * **Handheld Wood Tool Wall** -> siehe Roubo Workbench
  * **Holzwerkstatt -> Nicht auch redundant?**
  * Measuring Shelf
  * Precious Plastic Area
  * Public Storage
  * **Roubo Workbench -> mit "Handheld Wood Tool Wall" zu "Handheld Wood Tool Area" vereinigen?**
  * Router Table
  * Sanding Area
  * Saw Station
  * Tool Carousel
  * Wood Storage
  * Woodturning Area

**Comment by NitramLegov** [comment]
Hier noch meine Gedanken dazu:
- Bei den deutschen Übersetzungen (Holzwerkstatt, Metallwerkstatt) sind einfach nur die Übersetzungsseiten der entsprechenden Location zugeordnet, damit sie in der Liste nicht eigenständig auftauchen (Die Liste generiert sich aus der Category "Facilities"). Würde das jetzt nicht als riesen Problem sehen :)
- Deine Umbenennungen gehe ich prinzipiell mit, bis auf die folgenden Kommentare:
- - **Electronics Area**: Ja, wäre logischer. Brauchen wir einen neuen Namen für den E-Room? Der hat ja inzwischen Elektronik, Lasern, Drucken und Airbrush drin...irgendwie ruft das danach, dass "Electronics Room" nicht mehr passend ist 🙈
- - **Metal Workbench**: Ich glaube hier wurde nach dem Aufbau des Messestandes und der Schweißecke nie wirklich das Wiki aktualisiert. Ich könnte mir vorstellen, dass es sinnvoll wäre, zwischen Hot Metal Area und Handheld Metal Tool Area zu unterscheiden. Die Handheld Metal Tool Area würde dann halt auch den Compressor beinhalten. Oder sollen wir sie Cold Metal Area nennen? 🤔 Das wäre dann aber Konsistent zur Holzwerkstatt.

**Comment by LukasFreeze** [comment]
Falls wir den eRoom umbenennen wollen, wäre vielleicht "FabLab" eine
Option? So heißt im RZL der Bereich mit Laser & Co, wenn ich mich richtig
erinnere.

Ansonsten fiele mir noch "Tech Area" ein... Nur mal so als Gedanken in die
Runde :-)

**Comment by Pakue95** [comment]
Find FabLab hat ja schon durch die gleichnamigen Spaces eine eigene Konnotation. Dann eher "Digital Fabrication Area".

**Comment by LukasFreeze** [comment]
Das ist zu lang, um sich wirklich durchzusetzen finde ich 😅

Also ich hab auch nichts dagegen, den alten Namen zu behalten (oder von mir
aus "Raum" in "Bereich" umzuwandeln)

**Comment by Pakue95** [comment]
Realistisch werden wir von E-Room/Electronics Room eh nicht weg kommen. Und bis auf die Airbrush sind die Geräte schon noch im Bereich der Elektronik einzuordnen.

**Comment by NitramLegov** [comment]
@Pakue95 ich habe deine Änderungen im Wiki eingepflegt mit folgenden Anpassungen meinerseits:
- Aus Gründen der Konsistenz habe ich "Patricks Workbench" in User:Pakue/Bench verschoben 

Mir fehlt noch eine Entscheidung, wie wir das mit dem Metallzeug machen. Sprich: Wie nennen wir den Teil im Messestand und wie nennen wir den Teil außerhalb?

Patrick hat für den Messestand "Welding Area" vorgeschlagen. Hat jemand Präferenzen für den Rest?

**Comment by LukasFreeze** [comment]
Alternativ Hotbox 🤪

**Comment by NitramLegov** [comment]
Habe das umgesetzt.

Wir haben noch ein paar Geräte, die im "Wood Workshop" oder "Metal Workshop" direkt sind:
**Wood**:
[Elektra Beckum PK 255](https://wiki.comakingspace.de/Elektra_Beckum_PK_255)
[Hammer A3-31](https://wiki.comakingspace.de/Hammer_A3-31)
[Metabo BS 1638 W](https://wiki.comakingspace.de/Metabo_BS_1638_W)
[Altendorf F 45](https://wiki.comakingspace.de/Altendorf_F_45) (to be fair, die hat im wiki eine leere location)

**Metal**:
[Dremel 4000](https://wiki.comakingspace.de/Dremel_4000)

Habt ihr Meinungen, was gute spezifischere Locations wären? Oder ist das bei diesen Geräten in Ordnung?

**Comment by NitramLegov** [comment]
Ich glaube hier können wir zumachen. Die Locations kommen inzwischen aus SnipeIT. Änderungen können wir dort pflegen, falls notwendig :)
