### ISSUE TITLE
Wiki: Struktur der Werkzeugseiten

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#266]
Im Nachgang an #252 sollten wir uns zusätzlich zu den Locations, die wir im Wiki pflegen wollen (#265) auch um die Struktur unserer Werkzeug & Maschinenseiten kümmern.

Aktuell ist es so, dass wir Seiten haben, die mehrere Maschinen zusammenfassen und den Namen eines "Maschinentyps" haben (Beispiel: https://wiki.comakingspace.de/Cordless_Drills), eine Seite haben wir, die mehrere Maschinen zusammenfasst und den Namen von einer davon trägt (https://wiki.comakingspace.de/Prusa_i3_MK2S) und wieder andere Seiten sind Maschinenspezifisch und es gibt eine extra Seite, die dann den Maschinentyp erklärt (Beispiel: https://wiki.comakingspace.de/Bandsaws mit den spezifischen Seiten https://wiki.comakingspace.de/Metabo_BS_1638_W und https://wiki.comakingspace.de/CMI_C-S-BS_250).

Somit haben wir aktuell 3 verschiedene Logiken, wie wir Maschinenseiten im Wiki pflegen. Ich denke hier sollten wir uns für die Zukunft auf eine Logik einigen und diese dann konsequent durchziehen.

Mein Vorschlag ist hier, die Logik der Bandsägen [Edit: Doku [hier](https://wiki.comakingspace.de/Project:Navigation_Galleries#Outsourcing_Parts_of_a_Page)] auf _alle_ Maschinen und Tools auszuweiten. Das bedeutet:
- Alle verfügbaren Maschinen bekommen eine spezifische Seite, auf der nur Infos zu dieser speziellen Maschine zu finden sind.
- Für jeden Maschinentyp gibt es eine übergeordnete Seite, die allgemeine Infos zu dieser Art von Maschine gibt
- Das gilt auch für Maschinentypen, von denen wir nur eine Maschine haben (zum Beispiel also auch für die Dekupiersäge)

Vorteile sehe ich dadurch folgende:
- Wir haben eine konsistente Logik im Wiki und vermeiden Wildwuchs
- @Pakue95 hatte mal vorgeschlagen, die Asset-IDs aus unserer Internen Anlagenverwaltung mit im Wiki aufzunehmen. Mit der oben beschriebenen Logik könnten wir das tun. Das hätte den Vorteil, dass wir perspektivisch eine Synchronisierung unserer internen Anlagenverwaltung und dem Wiki schaffen könnten (Beispielsweise in Hinblick auf die Location und den Status der Maschine)

Was denkt ihr?

**Comment by LukasFreeze** [comment]
Sorry, wollte hier eigentlich schon länger antworten 🙈

Ich stimme auf jeden Fall zu dass dein Vorschlag die logischste Lösung ist. Das für sämtliche Seiten umzusetzen ist aber eine ganz schöne Aufgabe, da muss ich persönlich ganz ehrlich sagen dass Zeit & Motivation momentan nur für die Seiten mit mehreren Maschinen reichen (was sich direkt positiv in den Ausrüstungs-Galerien bemerkbar macht)...

**Comment by NitramLegov** [comment]
Dann sind wir uns ja einig, was die Struktur angeht :-) Dass es eine ziemliche Arbeit ist, das für alles umzusetzen sehe ich genauso wie du. Aber wenn wir uns prinzipiell einig sind kann man (tendenziell ich, wenn ich mal wieder einfach stupide vor mich hinarbeiten will) das ja nach und nach angehen. Das ist ja nichts, was morgen fertig sein muss.

Wir können dann ja auch anfangen, bei neuen Seiten / Seiten, die wir gerade eh anfassen (aktuell CNC Mill & Wood Lathes) direkt darauf zu achten, die neue Struktur zu nutzen

Bezüglich einer Reihenfolge zur Umsetzung schlage ich folgendes vor:
- Maschinenseiten mit mehreren Maschinen
- Toolseiten mit mehreren Tools
- restliche Maschinen
- restliche Tools

**Comment by NitramLegov** [comment]
Bei den Tools kommt es finde ich sehr darauf an. Nimm zum Beispiel "Breadboards": da gibt es keine riesen Unterschiede, das würde für mich so passen.

Nimm dann aber "Bevel Gauge": da haben wir allgemeine Informationen und eine infobox, die dann eine spezifische bevel gauge beschreibt. Das wäre für mich ein Fall, den wir trennen sollten.
Zusätzlich (und nicht auf der seite) gibt es noch die seite "Goniometer", die man integrieren könnte (das ist aber kein muss)

Also ich glaube bei den Tools müssen wir mit Sinn und Verstand draufschauen. Im Zweifel tendiere ich zumindest da immer zu einer konsistent durchgezogenen Logik, sofern das keine Nachteile mit sich bringt.

**Comment by LukasFreeze** [comment]
Wenn wir "Goniometer" integrieren finde ich das schon wieder sinnvoll, dann
ist "Bevel Gauges" ein gutes Beispiel, aber die allermeisten Seiten dürften
schon spezifisch genug sein - wird sich ja dann zeigen, was nach Aufteilen
der Seiten mit mehreren Tools übrig bleibt :-)

**Comment by LukasFreeze** [comment]
Ich poste hier nochmal die nötigen Bearbeitungen für Blöde (☝️)

**Einzelseiten:**
- Titel = Name der Maschine
- beginnen mit einer gleichlautenden h2-Überschrift (`== $Titel ==`) direkt vor der Infobox
- *kein* `<br clear=all>` am Ende - macht manchmal Probleme und ist nicht nötig

**"Sammelseiten":**
- bekommen an der passenden Stelle diesen Block eingefügt:
```
<br clear=all>
{{#ask:
 [[Machinetype::$type]]
 |order=descending
 |format=embedded
 |embedonly=yes
}}
<br clear=all>
```

Gerne ergänzen, wenn ich etwas vergessen habe 😅 Die Leerzeile am Anfang der Einzelseiten, von denen ich in #161 noch berichtet hatte, sind scheinbar doch nicht nötig.

**Comment by LukasFreeze** [comment]
Hmm...zu früh gefreut, was die Leerzeilen am Anfang der Unterseiten angeht :-(

Zumindest funktioniert es bei den Bandsägen nicht anders, warum es bei den Brandkolben geklappt verstehe wer will. Oder findest du noch einen Unterschied zwischen https://wiki.comakingspace.de/Ideal_ESH (zweites Gerät bei "Pyrography Burners", lässt sich problemlos einbinden) und https://wiki.comakingspace.de/CMI_C-S-BS_250 (zweites Gerät bei "Bandsaws", verliert wieder wie früher die Formatierung seiner Überschrift? Die eigentlichen Queries auf beiden Über-Seiten habe ich angeglichen... 🤔

(Den Bug würde ich zur Fehlersuche nochmal kurz drin lassen aber wohl morgen irgendwann wieder die Leerzeilen einfügen 😕)

**Comment by NitramLegov** [comment]
Eine weitere Frage auf die ich gestoßen bin und die wir klären sollten ist die Kategorisierung der zusammenfassenden Seiten (wie zum Beispiel "Bandsaws").

Die werden aktuell teilweise (wenn sie eine zusätzliche InfoBox beinhalten) als "Machines" kategorisiert.

Damit haben wir einzelne Maschinen und Maschinentypen in der gleichen Kategorie. Das macht eine ordentliche Auswertung der Daten schwierig und ich denke wir sollte da klar trennen zwischen Seiten für Maschinen und Seiten für Maschinentypen.

Das würde dann aber bedeuten, dass Seiten wie "Bandsaws" nicht mehr in die Kategorie "Machines" gehören.

Um das für Leser möglichst wenig verwirrend zu gestalten schlage ich vor, auf der Seite Category:Machines  eine Tabelle/Liste der MachineTypes (ggf. mit zugehörigen Maschinen) einzufügen.

**Comment by LukasFreeze** [comment]
Hmm, das hatte ich auch nicht bedacht, aber ich sehe ein gravierenderes Problem als eine unsaubere Datenstruktur: der Nutzen einer Liste mit den einzelnen neuen Maschinenseiten geht für normale Leser gegen Null und wir wollen ja auch gar nicht, dass zu den "Unterseiten" navigiert wird. Da fehlen dann die allgemeinen Informationen, Projektideen etc die die "Maschinentyp"-Seiten insgesamt wertvoll machen. Dass die SMW-Galerien zum Teil auf die Unterseiten verweisen ist aus dem gleichen Grund problematisch, aber mal Thema für ein eigenes Issue...

Wenn es künftig eine Kategorie "MachineTypes" geben soll, sollte sie imho die alte Kategorie "Machines" ersetzen, denn die ist relativ häufig verlinkt und für Leser relevant. Eine neue Maschinenliste nach Marken/Modellnummern (Unterseiten halt) kann dagegen versteckter bleiben, da sie nur für Wiki-Spezis interessant ist ;-)

Die Kategorisierung der zwei unterschiedlichen Arten von Maschinenseiten müssten wir ja größtenteils über die InfoBoxen hinbekommen (type definiert ja/nein), aber wenn wir uns einen nervigen Umzug der Links von "Machines" auf "MachineTypes" und einen wenig intuitiven Namen für die eigentlich intuitivere Seite ersparen wollen, würde ich noch einen Vorschlag in den Raum werfen: wollen wir nicht lieber eine neue Kategorie für die "Unterseiten" einführen, zB Category:SpecificMachines?

Eine weitere Option wäre eine reine SMW-Übersicht der spezifischen Maschinen, dann würden einfach alle InfoBoxen in denen ein "MachineType" definiert ist zu gar keiner Kategorisierung mehr führen.

**Comment by NitramLegov** [comment]
Zu den SMW Galerien, die auf die Unterseiten verweisen: Das löst sich, sobald die MachineTypes ordentlich gepflegt sind. Dann stelle ich nämlich im smw-query das redirecttarget von "-" auf "MachineType" um und die Galerien verweisen auf die Übersichtsseiten, wo sie ja auch hin sollen. Zum ausprobieren habe ich das vor einer Weile unter https://wiki.comakingspace.de/Project:Navigation_Galleries/Sandbox umgesetzt.  Hier linkt die Bandsäge schon auf die richtige Seite (Bandsaws). Dafür linkt der Frästisch auf "Tool mount" und die Shop Vacs nur auf das Bild. Aktuell funktioniert das also noch nicht, weil wir eine inkonsistente das noch nicht, weil unsere Datenhaltung da noch sehr unsauber ist.

Einen Umzug von "Machines" zu "MachineTypes" würde ich recht entspannt sehen. Über die ReplaceText Funktionalität kann ich das recht fix umsetzen. Da muss jetzt niemand manuell das komplette Wiki durchgehen oder ähnliches.

Wenn wir anhand des vorhandenseins des "MachineTypes" entscheiden wollen, wie eine Seite Kategorisiert wird sehe ich zwei Probleme: Zum einen ist es nicht wirklich intuitiv, wenn ein Parameter versteckt ein anderes Verhalten triggert. Zum anderen müssen wir aber auch da aufräumen. Die Bench Grinders sind zum Beispiel ein "Power sharpening tool", die

**Comment by NitramLegov** [comment]
Das Thema mit den redirects der Galerien löst sich mit diesem Issue :)
Wenn wir nämlich konsistent die MachineTypes gepflegt haben stelle ich das redirecttaget auf MachineType um und die Galerien verweisen auf die Übersichtsseite. Aktuell geht das noch nicht, da wir hier keine konsistente Datenhaltung haben.

Um das zu testen habe ich das vor einer Weile schonmal in der [Sandbox](https://wiki.comakingspace.de/Project:Navigation_Galleries/Sandbox) umgesetzt. Da sieht man schön, dass es bei den Bandsaws (die schon entsprechend der neuen Logik gepflegt sind) funktioniert, aber die Corded Drills einen MachineType "Drills" haben (der sogar auf eine Category verweist). Der Router Table hat einen nicht existierenden MachineType ("Tool mount") und die Shop Vacs haben gar keinen. Darum kann ich das erst umstellen, nachdem dieses Issue hier abgeschlossen ist.

Bezüglich einer möglichen Umstellung von Machines auf eine andere Kategorie: Die Verlinkungen auf die Category:Machines zu ändern wäre kein größeres Problem. Das kann ich mit ReplaceText ganz gut machen, dafür muss also niemand das ganze Wiki durchsuchen ;) Ich finde die Unterscheidung "SpecificMachine" und "Machine" deutlich weniger intuitiv als die Unterscheidung "MachineType" und "Machine" (eine SpecificMachine ist ja eigentlich immer auch eine Machine...). Allerdings sehe ich auch, dass die Suche nach "Machines" natürlich intuitiver ist als die nach "MachineTypes". Um ehrlich zu sein sehe ich hier das Grundproblem an der verwirrenden MainPage, die eine solche Suche notwendig macht. Dafür brauchen wir aber mal mehr Zeit.

Um hier aus der Not eine Tugend zu machen schlage ich vor, der Category:Machines Seite eine [Tabelle](https://wiki.comakingspace.de/index.php?title=Special:Ask&limit=500&offset=0&q=%5B%5BMachineType%3A%3A%2B%5D%5D&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fsearchlabel%3D...-20further-20results%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FMachineType%0A%3F%3DMachine%0A%3FLocation%0A&sort=MachineType&order=asc%2Casc&eq=yes#search)  hinzuzufügen, die oberhalb der ganzen spezifischen Maschinen steht. 
Das kann man natürlich auch noch anders formatieren ([Liste](https://wiki.comakingspace.de/index.php?title=Special:Ask&q=%5B%5BMachineType%3A%3A%2B%5D%5D&p=format%3Dul%2Flink%3Dall%2Fheaders%3Dhide%2Fsearchlabel%3D...-20further-20results%2Fpropsep%3D%2C-20%2Fvaluesep%3D%2C-20%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FMachineType%0A%3F%3D-%0A&sort=MachineType&order=asc&eq=no&offset=0&limit=500), [Baumstruktur](https://wiki.comakingspace.de/index.php?title=Special:Ask&q=%5B%5BMachineType%3A%3A%2B%5D%5D&p=format%3Dtree%2Flink%3Dall%2Fheaders%3Dhide%2Fsearchlabel%3D...-20further-20results%2Fpropsep%3D%2C-20%2Fvaluesep%3D%2C-20%2Fclass%3Dsortable-20wikitable-20smwtable%2Fsep%3D%2C-20%2Fparent%3DMachineType%2Fstart-20level%3D1&po=%3FMachineType%0A%3F%3D-%0A&sort=MachineType&order=asc&eq=no&offset=0&limit=500), [Ähnlich der Category Übersicht](https://wiki.comakingspace.de/index.php?title=Special:Ask&q=%5B%5BMachineType%3A%3A%2B%5D%5D&p=format%3Dcategory%2Flink%3Dall%2Fheaders%3Dhide%2Fsearchlabel%3D...-20further-20results%2Fcolumns%3D3&po=%3FMachineType%0A%3F%3D-%0A&sort=MachineType&order=asc&eq=no&offset=0&limit=500))

Bezüglich der Unterscheidung anhand der Pflege des MachineTypes in der Infobox habe ich folgende Gedanken:
- Für mich wäre es unintuitiv, wenn ein Feld im Hintergrund ein Verhalten triggert, das aus der Beschreibung des Feldes nicht ersichtlich ist (das setzen einer komplett unrelated Kategorie). 
- Als Voraussetzung müssen wir dann natürlich die MachineTypes aufräumen. Die RouterTable Seite dürfte dann zum Beispiel nicht auf "Tool mount" verweisen. Das müssen wir dann in diesem Issue mitmachen :)

Eine direkt bessere Lösung habe ich noch nicht. Alles was mir einfällt (neues Template, zusätzlicher Parameter) ist auch nur semigeil...

**Comment by LukasFreeze** [comment]
Wir dürfen halt aus dem Wiki keinen Datenspielplatz machen und dadurch die Nutzbarkeit verschlechtern, darum wollte ich meine Bedenken hier frühzeitig anmelden.

Was die Suche nach "Machines" mit der Startseite zu tun hat leuchtet mir allerdings nicht ein - wenn ich Maschinen sehen möchte, egal auf welcher Seite ich aktuell bin, gebe ich das eben so in die Suche ein und käme nicht auf "MachineTypes" (bei Links genauso)...

Bei den Galerien habe ich was durcheinandergebracht, dass die nach entsprechender Änderung auf die Types verweisen könnten ist klar :-) aber schau dir das Ganze mal mobil an, das ist richtiger Mist...Verlinkung aufs Foto statt auf irgendeine Inhaltsseite!

**Comment by NitramLegov** [comment]
Bezüglich der Galerien habe ich den DefaultSkin auf Medik umgestellt und MobileFrontend endlich deaktiviert. Das hat das Problem gelöst ;)

Was mir aufgefallen ist ist, dass in der mobilen Ansicht jetzt alle Teile der Seite per default ausgeklappt sind. Das finde ich noch ungeschickt, glaube aber wir können damit erstmal leben. Ein fix scheint da schon in Planung zu sein :)

**Comment by NitramLegov** [comment]
Naja, von "Datenspielplatz" sind wir noch sehr weit entfernt :-D Aktuell führen wir ja noch nur eine gewisse Grundstuktur ein, um die wichtigen Sachen zumindest mal auswerten zu können. Dadurch kann dann wenigstens mal auffallen, wo Informationen fehlen oder veraltet sind. Im nächsten Schritt kommt dann irgendwann eine (semi-) automatisierte Datenpflege.

Bezüglich der Nutzbarkeit: Wir erhöhen ja gerade die Nutzbarkeit. Vor allem für neue Leser oder unregelmäßige Nutzer erhöht eine klare Struktur die Nutzbarkeit. Außerdem schaffen wir uns die Möglichkeit, auf den Seiten ordentliche Übersichten einzufügen. Denk nur mal an die Category:Introductions oder eben die jetzt möglichen Werkzeug Gallerien. Das erhöht meiner Meinung nach deutlich die Nutzbarkeit und ist für uns (nach dem Einmalaufwand) vergleichsweise Aufwandsarm.

**Comment by NitramLegov** [comment]
Ich *glaube* ich bin durch damit, die Machines auf eigene Seiten auszulagern. Daher habe ich in der MachineInfoBox die Has caption property auf den Parameter MachineType gesetzt.

Außerdem habe ich auf den Workshop Seiten das redirect target auf den MachineType gesetzt. Das sollte diese Gallerien nützlicher machen für die meisten Besucher :-)

Was mir noch aufgefallen ist:
- Vom Laminator fehlt noch ein Name
- Vom Hot Plate Stirrer fehlt noch ein Name
- Wir haben eine extra Seite "Lathes", die in der Category:Machines drin ist, da aber manuell reingesetzt wird (ohne Infobox).
- Bei den Maschinentypen haben ein paar eine Infobox, andere nicht. Hier sollten wir uns überlegen, ob das für uns OK ist.
- Bei den Maschinentypen sollten wir uns außerdem überlegen, welche Semantic Properties wir hier erwarten.

Ich habe jetzt mal folgenden Seiten eine "extrabox" gegeben:
- Maschinentypen (also den Seiten, in die wir andere integrieren) - sofern sie eine zusätzliche Infobox haben (das haben nicht alle)
- Maschinen, die einem Mitglied gehören (zum Beispiel [Lukas/Ultrasonic Cleaner](https://wiki.comakingspace.de/User:Lukas/Ultrasonic_Cleaner))

Die "extrabox" setzt in der MachineInfoBox jetzt eine Property "Has extrabox" auf yes. Dadurch sind diese Seiten identifizierbar.


Schaut gerne mal drüber, ob euch noch etwas fehlt / ich etwas vergessen habe.

**Comment by NitramLegov** [comment]
Mit dem neuen Aufbau konnten wir den Maschinen (soweit vorhanden) auch eine assetid zuweisen, die den Link zu unserer internen Anlagenverwaltung (SnipeIT) herstellt. Perspektivisch ist angedacht, den Status unserer Maschinen (Nutzbar, in Commissioning, Kaputt, Gone, etc.) und auch die Location automatisiert aus der offiziellen Liste in SnipeIT zu füttern und so sicherzustellen, dass das wiki immer aktuell ist.

Warum ich das hier erwähne:
Wir haben einige Geräte doppelt, die jetzt erstmal keine assetid bekommen haben. Spontan fallen mir ein:
- Staubsauger
- Akkuschrauber
- 3D Drucker

In der Anlagenverwaltung sind die natürlich doppelt gepflegt und haben auch eigene Anlagennummern.

Wenn wir die Vorteile oben nutzen wollen würde das bedeuten, dass wir auch die Maschinenseiten im Wiki doppeln müssen. Das hätte den Vorteil, dass wir upgrades (magnetisches Druckbett oder Ähnliches) tatsächlich auf den Seiten der einzelnen Maschinen vermerken können. Es hätte allerdings den Nachteil, dass die Maschinen auf den Übersichtsseiten mehrfach vorkommen (Was ich gar nicht sooo schlimm finde, wenn wir damit einfach zeigen, dass wir die Maschine mehrfach haben).

Welche Meinungen habt ihr dazu?

**Comment by Pakue95** [comment]
Finde die Lösung mit doppelnder Wiki-Seite auch nicht schlimm. Momentan sind mehrere Exemplare nur im Text vermerkt, was nicht so leicht erkennbar ist wie mehrere Maschinen auf der Übersichtsseite.

Wie würdest du das *Naming Scheme* handhaben? Durchnummerieren wie die 3D Drucker (P1, P2, [...]); Eigennamen wie bei manchen Geräten in SnipeIT (vielleicht nicht so aussagekräftig?)

**Comment by NitramLegov** [comment]
Beim Naming Scheme ist mein Vorschlag, pragmatisch vorzugehen und einfach in Klammern ein (#Nummer) zu setzen
Allgemeine Doku zum Gerät dann quasi immer bei #1

Also hätten wir:
Festool CTM26 E AC (#1)
Festool CTM26 E AC (#2)
Makita DDF484 (#1)
Makita DDF484 (#2)
Makita DDF483 (#1)
Makita DDF483 (#2)
Prusa i3 MK2S (#1)
Prusa i3 MK2S (#2)
Prusa i3 MK2S (#3)
Prusa i3 MK2S (#4)
Prusa i3 MK2S (#5)
Prusa i3 MK2S Multi Material

Also kein #6 bei den Druckern, weil P6 ja ein anderer Drucker ist.

**Comment by NitramLegov** [comment]
Ist erledigt

**Comment by LukasFreeze** [comment]
Was ist hier noch zu tun? Auf der Seite "Category:Machines" habe ich gerade die vorgeschlagene Tabelle eingesetzt, weil die mangelnde Übersicht für mich das einzige verbleibende Problem darstellte.

Die letzten offenen Fragen meine ich in [diesem Kommentar](https://github.com/comakingspace/do-something/issues/266#issuecomment-1289711996) gefunden zu haben:
>- Bei den Maschinentypen haben ein paar eine Infobox, andere nicht. Hier sollten wir uns überlegen, ob das für uns OK ist.

Für mich okay, eine Seite ohne echte Unterseiten braucht imho nicht mehrere Boxen

>- Bei den Maschinentypen sollten wir uns außerdem überlegen, welche Semantic Properties wir hier erwarten.

Verstehe ich ehrlich gesagt nicht (mehr) 😅  - braucht es dazu dieses Issue noch? Oder wird das konkret, wenn jemand Auswertungs-Ideen hat?

**Comment by NitramLegov** [comment]
Ich glaube hier sind wir fertig :)
