### ISSUE TITLE
New CNC Portal Mill commissioning

### ISSUE THREAD

**Issue by SebMakesThings** [comakingspace/do-something#267]
We have a new small CNC machine. It is a DIY machine and the previous owner used it successfully to machine aluminum parts for other CNCs. It is functioning but needs a few updates to fulfill the safety and easy-of-use requirements of the space. Target of this issue is to track the different steps needed to turn this from a private machine into a well-documented and commissioned one. Helpers are welcome, please contact me. 

Some machine specs: 80kg, stainless steel portal, 300x360 work area, 800w HF ER11 spindle, ball screw drives, controller unitSMC5-5-N-N (Mach3), stepper drivers 3x Leadshine DM556.

**Getting started**

- [x] Manager to assign a desk
- [x] Build back wall and basic enclosure for mounting electronics and protection
- [x] "Cut air" tests, Fusion post set-up, soft-limit set-up
- [x] Get pdf manuals of controller and drivers
- [x] Find a name. Ideas welcome 

**Mandatory safety features** 

- [x] Install Main Switch and Emergency Stop

**Required for usability**

- [x] ER11 collets
- [x] Homing switches purchase (provided by Martin)
- [x] Homing switches installation and set-up
- [x] Extend cables between drivers and controller
- [x] Install LED Worklights
- [x] Design Clamping and spoil board solution (decision to start with simple machine vise, lower profile one needed)
- [x] Fine-tune perpendicularity of spindle with dial gauge
- [x] Documentation of all working settings

**Required for longevity**

- Cover bearings and spindles against wood dust (bellows)

    - [x] Build box with max free height on all sides around workplate for Y-Axis dust protection
    - [ ] Find u-shape bellow for x-Axis rails and spindle protection (optional)

**Commissioning**

- [x] Wiki Machine Page
- [x] Wiki Instruction Page
- [x] Final inspection / approval

**Prio 2**
- [ ] Replace wooden dust protection box with transparent one
- [x] Vacuum solution for wood machining
- [ ] Lubrication solution (cylinder available)

![IMG_3362](https://user-images.githubusercontent.com/87819637/172129253-9bdefe45-11d7-4f77-9aae-774749f63ace.jpg)

**Comment by NitramLegov** [comment]
Endstops have been provided to @Johannes09

**Comment by SebMakesThings** [comment]
Major milestone achieved yesterday!
@Johannes09  finished the electronics, emergency stop and main switch is installed. We also lengthened the cables to the controller.
Luca designed and printed end-stop extensions for the x-axis and we mounted and connected the Z-Axis homing switch.
Homing is now working and soft-limits are set and effective.
Thanks also to @Pakue95  for printing a collet organizer.

First test milling in softwood successful

Polypropylen  sheets are ordered to build a box around the workplate as a first step for dust/chip protection of the linear rails on Y-Axis.

**Comment by SebMakesThings** [comment]
Update: 
- LED lights (3 strips in 45 degree angle behind woods trip on top front of box
- Wooden U-shaped rails built for dust protection of Y linear rails. Works well. 
![IMG_3488](https://user-images.githubusercontent.com/87819637/173250672-8c92d1d4-b864-40ca-bfaa-3f1d7a5e0f06.jpg)
![IMG_3489](https://user-images.githubusercontent.com/87819637/173250707-864d3662-30e8-444d-abf1-90d3085d3f43.jpg)

**Comment by produkt-manager** [comment]
Schön heller Raum. Dieser Typ Dustcover sieht auch ganz funktionell aus. https://www.pinterest.de/pin/yaxis-dust-covers-for-shapeoko-3--155303887526013297/

**Comment by Titan-OX** [comment]
wir haben aber eine mit Kugelumlaufspindel und das Design ist für die mit Zahnriemen wie an der großen [WorkBee](https://wiki.comakingspace.de/CNC_Router#WorkBee). Und für die Führungsschienen wäre es am besten wenn erst gar kein Dreck hin kommt und nicht nur weg gebürstet wird

**Comment by SebMakesThings** [comment]
Update: 
- Measured perpendicularity of Spindle Z movement - values are ok to start but could be optimized (0,03mm per 10mm tilted)
- Vacuum adapter purchased and installed (see picture), to be used for wood milling. Luca volunteered to design and print a festool adapter. Zyklone solution should not be needed to start (small workpieces) 
- Polycarbonate sheets for dust protection fences arrived in the mail

![IMG_3559](https://user-images.githubusercontent.com/87819637/174340913-1e73d0ef-ae11-4b37-a01f-3140c596b15a.jpg)

**Comment by Titan-OX** [comment]
Would you add it to https://wiki.comakingspace.de/CNC_Router
Or create "CNC mill"?

**Comment by Titan-OX** [comment]
[Machine tools guide rail way cover bellows protection, 310 mm x 80 mm x 450 mm](https://www.aliexpress.com/item/4000712208858.html )
this one seams to be about the right size. Aliexpress sellers also offer customized bellows. The third option is to make them ourselves.

**Comment by NitramLegov** [comment]
Regarding the Wiki, please see the difference between a Router and a Mill explained here:
https://www.shopsabre.com/the-differences-between-a-cnc-router-and-a-cnc-mill/

> CNC Router:
> It is typically mounted on a stationary table with a larger workspace, featuring a spindle that moves along three axes – X, Y, and Z.
> 
> CNC Mill:
> Instead of using a stationary table, many CNC mills move in an X-Y configuration, with the spindle moving on a linear axis above the workpiece.

@LukasFreeze If we apply this differentiation, my understanding would be that this tool is a CNC Router and not a Mill - correct?

**Comment by SebMakesThings** [comment]
Latest Updates:
- Luca printed a festoon adapter for the vacuum shoe and it works great, nearly no wood dust escapes. 
- Luzian and I did a step-by-step documentation for the controller. Pictures and Powerpoint with some visuals on pictures plus text as prep for the wiki pages are stored on the next cloud in documents folder. @NitramLegov please advise if there is a better location
- @NitramLegov @LukasFreeze Regarding the "Mill or Router" discussion: If we go by material differentiation, I'd like to categorize this as a mill as it is designed to mill aluminium and harder wood. Advantage of this is also a clearer separation in the wiki from the "soft stuff only" inc router as some of the safety instructions, restrictions on materials, etc, will be different. Most common name for these kind of machines when purchased from a professional vendor are "CNC Portal Mill".

**Comment by Titan-OX** [comment]
Should we show the setup of the work-zeros in separate captioned pics or the gallery. Currently we have both because I could not decide. 
What about a complementary video showing the process?

**Comment by LukasFreeze** [comment]
Sorry for the late reply - I'm with Sebastian on the naming question as it will make sense to have a different introduction for router vs mill and the current separation by motor/material type also seems to me to be the more common one.

We once had the type of "mill" in the definition @NitramLegov posted and just called it "milling table" (DE Kreuztisch).

So my choice would be simply "CNC mill", but  "CNC portal mill" would also be okay if we need to make it super clear for some reason :-)

**Comment by NitramLegov** [comment]
That just means that we would need to move the "Eleks mill" to the cnc router page and move the Kress cnc away from the cnc router page.

Makes sense for me, since the Eleks mill shares the workflow and introduction with the workbee.

**Comment by SebMakesThings** [comment]
Update: 

- Wiki Page & Wiki Introduction page V1.0 done. Corrections, further ideas, etc. welcome. Please focus on initial minimum requirement for commissioning. 
- Axis alignment done, good enough for now

Next Step: Test-introduction with manager

**Comment by NitramLegov** [comment]
I took a first glance at the introduction and have the following comments / suggestions:

- The Introduction links to "[CNC router workholding](https://wiki.comakingspace.de/CNC_Router_Workholding)" in the safety measures. This page is focussed on our CNC Router and does not contain information regarding the CNC Mill. This should be changed so that we can explain our members how to properly secure the workpiece on the new machine.
- Should we add a section about cooling your workpiece and bit with some liquid when milling metal?
- Regarding the hot chips flying: Is it recommended to wear long clothes (e.g. not just t-shirts) to prevent injuries from hot chips flying around?
- The demonstration should include starting and executing the job
- I have rephrased the safety measures in the SHOULD/MUST/MUST NOT style we´re trying to use for new / updated introductions. Please check if this is appropriate.

**Comment by Di3mex** [comment]
> * The Introduction links to "[CNC router workholding](https://wiki.comakingspace.de/CNC_Router_Workholding)" in the safety measures. This page is focussed on our CNC Router and does not contain information regarding the CNC Mill. This should be changed so that we can explain our members how to properly secure the workpiece on the new machine.

Same principles apply. I would classify this machine as a CNC router that is rigid enough for aluminium, not a CNC mill.

> * Should we add a section about cooling your workpiece and bit with some liquid when milling metal?

Coolant is not required for aluminium if your cutting parameters are right.

> * Regarding the hot chips flying: Is it recommended to wear long clothes (e.g. not just t-shirts) to prevent injuries from hot chips flying around?

I have only ever seen big mills throwing big hot chips around. These smaller machines don't really toss chips around and a dust shoe is recommended either ways.

**Comment by SebMakesThings** [comment]
Thanks for all your comments. I'm excited to get this running. To wrap up:

1) Naming of the wiki section / machine: The decision for "CNC Mill" is a controversial one without a black&white answer. It is at least common on vendor pages like Sorotec for this type of "cnc portal mill" machine. But the real reason behind the decision taken was to separate it clearly in the wiki from the workbee "cnc router" due to practical issues, e.g. that many of the statements on the CNC router page apply to wood only and that we'll have a separate introduction. I think this is a good working compromise that serves the purpose. 

2) Workholding: Yes, the principles are the same. The way the instructions are written however we'll have to update and provide at least some concrete guidance / best practice how to use a t-slot table, etc.

3) Coolant: I fully agree with the statement above: When using proper settings and the right end mills, no coolant is needed for aluminium. A few parts to get started to build a "minimal amount lubrication system" are available if somebody at some point feels like it. I'd say let's not promote it for now to reduce the mess it makes. 

4) Hot chips: Probably no need to promote special clothing. 

5) Milling Metal and Dust Shoe: I vote against that as the current dust shoe connects directly to the festool shop vac and the aluminum chips tend to clog the hose. Also not sure about the mix of hot(ish) metal chips and wood dust. Probably fine but I'd say let's keep our general line to always say "no vacuum for metal work". 

Remaining steps before test-introduction, as far as I see:

- [ ] write guidance on workpiece holding on t-slot table
- [ ] add steps to start and execute job in introduction wiki page

**Comment by NitramLegov** [comment]
@SebMakesThings If I got the conversation right, only Aluminium is allowed to be used without coolant. Does this mean that we should only allow aluminium to be milled (apart of wood and plastics of course) until a lubrication system is on place?

If so, that is fine with me, but we should then make this clear on the machine page and in the introduction.

**Comment by Titan-OX** [comment]
Brass should also be easy to mill.

**Comment by SebMakesThings** [comment]
Update 
- Demo introduction done yesterday evening to Patrick, green light from his side
- @LukasFreeze @NitramLegov Please check and give your ok for the introduction to finish commissioning

**Comment by Di3mex** [comment]
@SebMakesThings Great progress! So glad to see this is going somewhere.

Regarding materials - I would like to make a suggestion. 

There would be a benefit in making it a rule to only use this mill for metals - Aluminium and brass. Steel has to be tested. The rigidity may be the limiting factor. If one sprays some WD40 on it from time to time during cutting it might work. I don't really see any point in using this mill for wood and polymers. 

I would highly recommend buying a separate vacuum. It can be a really cheap Einhell vacuum (43€ on Amazon). 3D print or buy a Cyclone separator and only use this vacuuming system for metal. Even if the vacuum is not permanently attached to a dust shoe it will be very beneficial for cleanup. A CNC machine inside a box will get covered in chips and a vacuum is the most efficient way of cleaning it up and really the only way to get the chips in the back and the corners of the enclosure. If the machine is only for metals, we also don't have to be worried about igniting wood dust inside the vacuum, because there won't be any.

Polymers are the worst without a dust shoe. They literally can stick to the machine.

![PXL_20211118_102741973 MP_2](https://user-images.githubusercontent.com/966375/197060018-6d2dd5e4-81c6-4569-8f3c-197070114862.jpg)

**Comment by Titan-OX** [comment]
Cutting hard wood is one of the main things I wanted to use the mill for

**Comment by SebMakesThings** [comment]
The main reason I bought this is to work on small but high precision hardwood projects. So yes, wood is not only allowed for this machine but also highly recommended, can‘t wait so see what Titan-OX comes up with! The dust shoe we have installed works extremely well.

**Comment by NitramLegov** [comment]
I am just a test comment :)

**Comment by Di3mex** [comment]
@SebMakesThings Thanks for clearing this up. I was under the impression that the other CNC was able to machine "wood", meaning all types of wood well.

I am looking forward to using this machine for the first time :-).

Maybe the vacuums are fine with aluminium. From my experience what really clogs a vacuum fast are the long and curly chips you get from the drill press. A CNC makes smaller chips, so as long as you don't overload the vacuum with piles of aluminium it should be fine.

![PXL_20221021_095901166](https://user-images.githubusercontent.com/966375/197169545-60d9496f-b12a-4443-ba91-c5f6e7272003.jpg)

This is the cyclone separator I am using on my CNC. You attach a vacuum on one side and the CNC on the other. This might be a worthy addition when machining metal, as all of the chips would land in the separator and not the vacuum. This also allows to attach a shorter hose between the CNC and the separator. So if there is a clog it won't be in the 3 Meter hose of the Festool vacuum, but the shorter hose. Also one could use a hose with a bigger diameter, or a smooth inside to prevent clogs. 

If you guys are interested, I can offer to build/donate a separator.

**Comment by SebMakesThings** [comment]
@Di3mex Great Info, such a separator could be a great addition to avoid clogging of the festools and to avoid frequent bag replacement.

@LukasFreeze @NitramLegov  I think your green light on the introduction is now the last step needed to start using it and to allow me to give some introductions as a tutor. Please let me know if you think anything is missing, as far as I can tell we finished the open mandatory points.

**Comment by NitramLegov** [comment]
We have started our internal approval of the new introduction :-) Since we are talking about something safety related, all of us are reviewing these things thoroughly, which might take some time :)

So this is on our list to get done rather sooner than later, but these reviews might take a bit time :)

**Comment by LukasFreeze** [comment]
I was the last one to find the time for this today, the past weeks were just too stressful...delayed, but never forgotten!
Since I also didn't trip over any obvious problems, the review was quick after all and we should be good to go for a test intro :-) any small holes that are discovered there (workflows are always good for surprises) are best filled on the go and should not block the "commissioning"
