### ISSUE TITLE
Wiki: erleichterte Verlinkung der User-Seiten

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#268]
Alle Mitglieder bekommen von uns einen Wiki-Account unter "User:<Name>", aber zum leserlichen Verlinken muss man sich immer die Mühe machen und einen alternativen Text hinzufügen: [[User:Name|Name]]. Am Anfang ist das sicher für einige schwer zu verstehen und später ist es immer noch nervig. Aktive User richten sich daher oft einen "redirect" ein, sodass auch einfach nur der Name verlinkt werden kann aber die richtige Seite angesteuert wird.

Ich habe jetzt überlegt, das künftig standardmäßig beim Anlegen neuer Mitglieder zu machen, weil das so gut wie keine zusätzliche Zeit kostet wenn ich eh dabei bin und hoffentlich eine weitere kleine Hürde abbaut :-)

Für die bestehenden *aktiven* User, die a) schon Inhalt auf ihrer Seite haben oder b) vor < 3 Monaten beigetreten sind könnten wir es bei Gelegenheit nachholen. Das können als kleine Fingerübung auch alle selbst ausprobieren!

Hier könnt ihr euch ein Beispiel ansehen: https://wiki.comakingspace.de/index.php?title=Lukas&redirect=no - es sind auch beliebige andere Namen (Klarnamen, Abkürzungen?) möglich, solange noch niemand anderes sie als Nutzernamen hat.

- [ ] [User:Airlag](https://wiki.comakingspace.de/User:Airlag)
- [ ]     [User:AlexBaumgart](https://wiki.comakingspace.de/User:AlexBaumgart)
- [ ]     [User:Andreas](https://wiki.comakingspace.de/User:Andreas)
- [ ]     [User:Ankri](https://wiki.comakingspace.de/User:Ankri)
- [ ]     [User:Armin](https://wiki.comakingspace.de/User:Armin)
- [ ]     [User:BenKenobi](https://wiki.comakingspace.de/User:BenKenobi)
- [ ]     [User:Björn](https://wiki.comakingspace.de/User:Bj%C3%B6rn)
- [ ]     [User:Blacksheep](https://wiki.comakingspace.de/User:Blacksheep)
- [ ]     [User:Canastaking](https://wiki.comakingspace.de/User:Canastaking)
- [ ]     [User:Christoph](https://wiki.comakingspace.de/User:Christoph)
- [ ]     [User:Ciaran](https://wiki.comakingspace.de/User:Ciaran)
- [ ]     [User:Cujoontour](https://wiki.comakingspace.de/User:Cujoontour)
- [ ]     [User:DANIEL BULTRINI](https://wiki.comakingspace.de/User:DANIEL_BULTRINI)
- [ ]     [User:Diemex](https://wiki.comakingspace.de/User:Diemex)
- [ ]     [User:Ed Green](https://wiki.comakingspace.de/User:Ed_Green)
- [ ]     [User:ErikSchatz](https://wiki.comakingspace.de/User:ErikSchatz)
- [ ]     [User:F.Huchinson](https://wiki.comakingspace.de/User:F.Huchinson)
- [ ]     [User:Haluwate](https://wiki.comakingspace.de/User:Haluwate)
- [ ]     [User:Hanna](https://wiki.comakingspace.de/User:Hanna)
- [ ]     [User:Heidleberg trashure](https://wiki.comakingspace.de/User:Heidleberg_trashure)
- [ ]     [User:Herdis](https://wiki.comakingspace.de/User:Herdis)
- [ ]     [User:Ignaz](https://wiki.comakingspace.de/User:Ignaz)
- [x]     [User:Johannes](https://wiki.comakingspace.de/User:Johannes)
- [ ]     [User:Jonah](https://wiki.comakingspace.de/User:Jonah)
- [ ]     [User:JuliaWe](https://wiki.comakingspace.de/User:JuliaWe)
- [ ]     [User:Kalunho](https://wiki.comakingspace.de/User:Kalunho)
- [x]     [User:Keno](https://wiki.comakingspace.de/User:Keno)
- [ ]     [User:Khaos8rood](https://wiki.comakingspace.de/User:Khaos8rood)
- [ ]     [User:LaVo](https://wiki.comakingspace.de/User:LaVo)
- [ ]     [User:Lars](https://wiki.comakingspace.de/User:Lars)
- [ ]     [User:Leo](https://wiki.comakingspace.de/User:Leo)
- [ ]     [User:Lexboreas](https://wiki.comakingspace.de/User:Lexboreas)
- [ ]     [User:Lmnl99](https://wiki.comakingspace.de/User:Lmnl99)
- [ ]     [User:LokowandtG](https://wiki.comakingspace.de/User:LokowandtG)
- [ ]     [User:Lucas](https://wiki.comakingspace.de/User:Lucas)
- [x]     [User:Lukas](https://wiki.comakingspace.de/User:Lukas)
- [x]    [User:Luzian](https://wiki.comakingspace.de/User:Luzian)
- [ ]     [User:MaKu](https://wiki.comakingspace.de/User:MaKu)
- [ ]     [User:Mfisch3r](https://wiki.comakingspace.de/User:Mfisch3r)
- [x]     [User:Mitja](https://wiki.comakingspace.de/User:Mitja)
- [x]     [User:Narquadah](https://wiki.comakingspace.de/User:Narquadah)
- [x]     [User:NitramLegov](https://wiki.comakingspace.de/User:NitramLegov) *(als "Martin")*
- [ ]     [User:Olli.Klos](https://wiki.comakingspace.de/User:Olli.Klos)
- [ ]     [User:Ozel](https://wiki.comakingspace.de/User:Ozel)
- [x]     [User:Pakue](https://wiki.comakingspace.de/User:Pakue)
- [ ]     [User:Paul](https://wiki.comakingspace.de/User:Paul)
- [ ]     [User:PloenK](https://wiki.comakingspace.de/User:PloenK)
- [ ]     [User:Reinhard](https://wiki.comakingspace.de/User:Reinhard)
- [ ]     [User:Ronanb](https://wiki.comakingspace.de/User:Ronanb)
- [ ]     [User:Rudy](https://wiki.comakingspace.de/User:Rudy)
- [ ]     [User:Sebastian](https://wiki.comakingspace.de/User:Sebastian)
- [ ]     [User:St3ffi](https://wiki.comakingspace.de/User:St3ffi)
- [ ]     [User:Stefanr](https://wiki.comakingspace.de/User:Stefanr)
- [ ]     [User:SvenG](https://wiki.comakingspace.de/User:SvenG)
- [ ]     [User:Utis](https://wiki.comakingspace.de/User:Utis)
- [ ]     [User:Vera](https://wiki.comakingspace.de/User:Vera)

Findet ihr euch in dieser Liste nicht wieder, dann legt doch mal eure Nutzerseite an ;-) Eine tolle Möglichkeit, euch und eure Projekte vorzustellen!

**Comment by NitramLegov** [comment]
Finde das Thema nicht wirklich wichtig, aber wenn wir das angehen gibt es denke ich bessere Wege als das manuell zu tun.

Ich kann hier gerne einen kleinen bot schreiben, der die redirects anlegt. Gerne auch mit automatischer Anlage der User aus webling heraus.

Alternativ kann ich auch eine Erweiterung aktivieren, die beim ersten login des users die zugehörige User page anlegt. Und dann einen bot, der wöchentlich checkt, ob redirects existieren und die ggf. anlegt.
Das wäre in meinen Augen sinnvoller als eine manuelle Lösung.

**Comment by LukasFreeze** [comment]
Automatisch klingt sehr gut, übersteigt nur meine Erfahrungen :-)

Zu "Userpage anlegen": was sollte der Bot denn da draufschreiben? Das
greift ja dann schon inhaltlich in die privaten Seiten ein, was ich eigtl
nicht vorgehabt hätte. Aber vielleicht könnte ein Bot immer wieder checken,
ob es Redirects für alle User unter "User Pages" gibt? Die hätten per
Definition alle ihre Seite angelegt.

**Comment by NitramLegov** [comment]
Content seitig kann die Seite ja leer bleiben.

Ich finde die Idee ganz gut, eine Erweiterung die userpage beim login anlegen zu lassen und dann periodisch zu checken, ob es für die Page einen redirect gibt.

Aber wenn ich dich richtig verstanden hatte wolltest du doch auch beim User anlegen die Seite anlegen. Oder hättest du einen redirect auf eine nichtexistierende Seite angelegt?

**Comment by LukasFreeze** [comment]
Ich hätte quasi broken redirects erzeugt, aber nachdem ich das so
aufgeschrieben hatte kam es mir nicht mehr so schlau vor 😅

Würde dann eher vorschlagen wir lassen das mit dem frühzeitigen Anlegen,
aber für den Bestand wärs cool!

**Comment by NitramLegov** [comment]
Ich habe die Extension CreateUserPage (https://www.mediawiki.org/wiki/Extension:Create_User_Page) modifiziert, sodass sie automatisch einen redirect anlegt, falls der noch nicht existiert. Meinen Code habe ich auch schon vorgeschlagen, um ihn in die offizielle Extension aufzunehmen: https://phabricator.wikimedia.org/T313132 

Die Extension macht jetzt *beim login* folgendes:
- Check, ob die User-Page existiert
- Falls nein: User-Page anlegen mit content {{User}} (Siehe https://wiki.comakingspace.de/Template:User)
- Check, ob eine Seite mit dem Nutzernamen im Main-Namespace existiert
- Falls nein: Anlegen der Seite als redirect auf die User-Page

Damit sollte das issue für neue Mitglieder gelöst sein. Ob ich einen Bot schreibe, der das auch noch für die existierenden Seiten macht muss ich mal sehen :-)

**Comment by NitramLegov** [comment]
Redirects für existierende User-Seiten sind angelegt
