### ISSUE TITLE
Wandhalter für die Handschleifgeräte

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#269]
Auf dem "Schleiftisch" liegt immer nur alles planlos herum (@SebMakesThings hatte zwar einmal einen ehrenhaften Versuch gestartet, jedem Gerät eine "Zone" zuzuweisen, aber das war leider nur von kurzer Dauer) und geschliffen wird sowieso, wo mehr Platz ist. Außerdem wird die Drechselecke durch die neue Maschine (#264) bald etwas breiter.

Wir könnten also einige Probleme auf einen Schlag lösen, indem wir jedem Handschleifgerät ohne Koffer eine Box an der Wand bauen und dafür die Tischfläche im Schleifbereich abschaffen oder auf das nötigste (was wäre das?) reduzieren :-)

Bedingungen, die mir für die Wandboxen vorschweben:
- Platz für das Gerät und das Kabel in einer intuitiven Position
- sichtbarer Platz für den Gerätezettel mit QR-Code
- sichtbarer Platz für ein Beispiel-Schleifmittel
- ggf. Extrafach für Zubehör oder ausgedrucktes Handbuch

Fällt euch noch etwas ein? :-)

**Comment by LukasFreeze** [comment]
Ich übertrage hier mal ein bisschen von slack - Idee: nicht nur Beispiel-Schleifmittel, sondern echte Lagerfächer direkt bei den Geräten!

[Steffi] Auch wenn man Gefahr läuft, dass wieder Chaos ausbricht ggfs pro Schleifgerät ein Fach für passende Schleifpapiere. Ein gesammeltes Regal bringt auf jeden Fall Chaos. Vielleicht funktioniert es, wenn jedes Gerät sein eigenes Schleifpapierfach bekommt

[Ich] die Idee ist gut, vielleicht [montieren wir] Geräte mit gleichem Schleifmittel übereinander und [darunter] einmal pro "Stapel" ein Schleifpapier-Fach? Sonst gibt es manche an zwei Orten, das ist auch wieder schwer im Blick zu behalten 🤔

**Comment by NitramLegov** [comment]
Hier noch ein Update:
Durch den neuen [Deltaschleifer ](https://wiki.comakingspace.de/Festool_DTS_400_REQ) und den neuen Exzenterschleifer (Bosch Professional Exzenterschleifer GEX 40-150) haben wir nun die Situation, dass wir die Schleifpapiere gut trennen können.

Beide Exzenterschleifer nutzen nun 150mm Schleifpapiere, alles andere hat also in der Schleifecke nichts verloren.

Der Deltaschleifer ist in der Form der Schleifpapiere auch sehr eindeutig. Auch hier haben unpassende (zum Beispiel rein Dreieckige) Papiere in der Schleifecke nichts verloren.

Und Rechteckige Schleifpapiere für den Schwingschleifer sind ebenfalls klar erkennbar.

Eine Ausnahme ist das Oscillating Tool, das ja allerdings wo anders lagert und auch nicht mit einem Schleifgerät verwechselt werden sollte.

Außerdem druckt Patrick gerade Aufnahmen für Schleifpapier die in die neuen Holzkisten passen :)

**Comment by NitramLegov** [comment]
Die Handschleifgeräte haben inzwischen Wandhalter. Eine mögliche Ordnung für Schleifmittel sollte (falls notwendig) in einem separaten Issue besprochen werden
