### ISSUE TITLE
QR-Code and wiki-link for each tool

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#27]
In order to promote our wiki structure and to ease up the information gathering, I think it would be great if each tool (esp. the ones needing an introduction) would get a QR-Code linking to the correspondent wiki page. Of course, the plain link text should also be provided.
Maybe it makes sense to also print the tool info box?

- [x] Generate template
- [x] Identify relevant tools
- [x] Print QR-codes and put them on the tools.

**Comment by LukasFreeze** [comment]
+1 for the QR codes :-)

I would not write down the entire link for everything though, space will soon become an issue in case of small tools hanging next to each other. But every label around the page should lead to the relevant wiki page (or redirect to that page) if typed into the wiki search - I hope that is the case so far but please note whatever is unclear!

We've also been thinking about printing InfoBox-like labels but currently they change so often that it might only make sense for a few tools. How about starting with table saw, drill press and compressor to test it out?

**Comment by NitramLegov** [comment]
In general, adding the following to our templates:
|-
| QR Code: 
| [http://chart.apis.google.com/chart?chs=200x200&cht=qr&chl={{fullurl:{{FULLPAGENAME}}}} QRCode]
|-

Would create a link to the google API which generates a QR Code for the corresponding site.
You could enable loading external images for this domain following this guide:
https://www.mediawiki.org/wiki/Manual:Linked_images#External_image_syntax

An alternative approach would be to use the QRLite extension for mediawiki:
https://www.mediawiki.org/wiki/Extension:QRLite

These are just a few thoughts. I´m still hoping to be able to generate this in a semi-automatic way.

**Comment by NitramLegov** [comment]
I started putting together a quick and dirty generator for this:
https://github.com/comakingspace/CommonFiles/tree/master/Printouts/QRCodes
Basically the python file scans the category you are telling it for all pages - in these pages it takes the first infobox it finds, parses it, replaces the picture with a QR-Code and stores that as a html file.

Again: it is quick and dirty (and lot´s of hardcoded stuff), but it works.
Example files from categories Machines and Hardware are added as well, feel free to check them.

Please let me know about the things you dislike so far. I will then try to improve the script.

**Comment by NitramLegov** [comment]
The script got updated with the following:
1. options to parse a specific info box category
2. option to parse a specific page (in case you need to reprint a single page)
3. a small infotext "For further information please scan the QR-Code or check our" below the QR-Code

Printed QR-Codes can be found on the table in the common room. They should be reviewed, laminated and then attached to the different tools.

In case of any improvement suggestion, please let me know.

**Comment by NitramLegov** [comment]
Ich mach hier mal zu...
