### ISSUE TITLE
Plunge saw riving knife is loose

### ISSUE THREAD

**Issue by kenomaerz** [comakingspace/do-something#270]
The riving knife of our Festool plunge saw is loose to a dangerous degree. I cannot seem to fasten it any further, so this does probably require repair. When used, the knife can make contact with the saw blade (yay, sparks!)- so we might need to check the blade as well. The saw is in the manager's office for now, since it's a security risk to use it as is.

**Comment by Pakue95** [comment]
The saw blade was not properly aligned axially either by coming loose over time or by being assembled wrong. The riving knife was also at the wrong position.

Riving knife was readjusted by @LukasFreeze and I reassembled the saw blade which seemed to fix the issue.

We'll check back in 4 weeks to make sure it hasn't moved again.
