### ISSUE TITLE
Tag der offenen Tür zum fünfjährigen Jubiläum

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#271]
Kaum zu glauben, aber der Space erreicht diesen Herbst schon das Vorschulalter ;-)

Zu diesem Anlass möchten wir gerne wieder einen Tag der offenen Tür / "Open Day" veranstalten wie zuletzt vor unserem Umzug (2-jähriges Bestehen 2019 --> [Wiki-Seite mit kleiner Übersicht](https://wiki.comakingspace.de/Tag_der_offenen_T%C3%BCr)).

Hat jemand Ideen für ein **einfaches Projekt, das Gäste unter Aufsicht ausprobieren könnten** (und Lust, das zu organisieren)? Wir hatten zum Beispiel schon kleine Löt-Bausätze oder Herbstlaub aus Sperrholz an der Dekupiersäge, es darf aber definitiv auch etwas ganz anderes sein! Vielleicht auch essbare Kreationen...? Außerdem wäre es richtig cool, wenn viele Mitglieder **ein paar Projekte (fertig oder in Entstehung!) mitbringen** und wir wieder ein bisschen "Maker Faire" spielen können ;-)

**Bitte meldet euch, wenn ihr auf irgendeine Weise mitwirken möchtet!**

Das Ganze war die letzten Male nicht nur Werbung für den Space, sondern es war auch immer cool zu sehen was die anderen Mitglieder so treiben und auch mal Leute kennen zu lernen, denen man digital schon häufiger "begegnet" ist aber im Space andere Lieblingszeiten hat.
Trotzdem sollten wir die Veranstaltung natürlich gründlich bewerben (s. auch #topic-pr auf slack) - hier die grundlegenden Infos, die sich nach und nach füllen werden:

**Titel:** Tag der offenen Tür - 5 Jahre CoMakingSpace!

**Leiter & Helfer:** 
- @Pakue95 
- @NitramLegov 
- @LukasFreeze 
- @lmnl99 (3D-Druck)
- @SebMakesThings (Laser)
- ...tragt euch einfach ein oder meldet euch!

**Datum & Zeit:** Samstag, 24.09.2022 / 10-18 Uhr (danach gemeinsames Grillen für Mitglieder?)

**Teilnehmerzahl:** was immer Corona erlaubt

**Zielgruppe:** Interessierte Leute aus der Region oder anderen Spaces

**Kosten:** gratis

**Beschreibung/Programm:** Wir feiern unser fünfjähriges Bestehen mit einem Tag der offenen Tür, schaut doch auch mal vorbei!
Wir möchten euch die Werkstatt und Projekte unserer Mitglieder zeigen und haben uns auch ein paar familienfreundliche Laser-, 3D-Druck-, Elektronik- und Upcycling-Workshops ausgedacht, bei denen ihr euch ausprobieren könnt.

Der Eintritt ist natürlich frei und wir freuen uns auf viele neugierige Gäste!

*[EN] The CoMakingSpace is celebrating its five-year anniversary with an open day, come along and visit us for a bit!
We'd like to show you the workshops and some of our members' projects and we also came up with some family friendly laser cutting, 3D printing, electronics and upcycling courses.*

*The event is free to attend, of course, and we are looking forward to meeting many curious guests!*

**Fotos:** *fehlen noch! Vorschläge willkommen :-)*

## Werbung - ToDo:

* hier können alle helfen:
  * [ ] **Freunden und Bekannten davon erzählen!!**
  * [x] Wiki-Seite ([Tag der offenen Tür](https://wiki.comakingspace.de/Tag_der_offenen_T%C3%BCr))
  * [x] ["Makers"-Verteiler](https://wiki.comakingspace.de/Mailing_List)
  * [x] [Telegram-Gruppe](https://wiki.comakingspace.de/Telegram_Group)
  * [x] "Maker Community HD" WhatsApp-Gruppe
  * [x] [Heidelberg.de Veranstaltungskalender](https://www.heidelberg.de/hd,Lde/HD/Erleben/veranstaltungskalender.html)
  * [x] [Make:-Kalender](https://www.heise.de/make/kalender/new_event/)
  * [x] *bei genug Vorlaufzeit:* Poster (für die ["Kultursäulen" der Stadt](https://www.heidelberg.de/hd,Lde/HD/Rathaus/Kultursaeulen+_+kostenloses+Plakatieren.html)) --> Entwürfe s. Slack (#topic-pr), müssten bis 9.9. gedruckt gefaltet/abgegeben werden!

* von der [Geschäftsführung](https://wiki.comakingspace.de/Management) oder anderen Ehrenamtlichen mit Zugang zu erledigen:
  * [ ] Eventbrite-Seite(?)
  * [x] Google-Kalender
  * [ ] nebenan.de
  * [x] [Meetup](https://www.meetup.com/de-DE/heidelberg-makers-meetup/events/288240637/)
  * [x] [Facebook](https://www.facebook.com/events/1152092845516872) - bitte fleißig teilen!
  * [x] [Instagram](https://www.instagram.com/comakingspace/)
  * [x] [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6973293936748457984/)
  * [x] [Twitter](https://www.twitter.com/comakingspace/)
  * [x] *bei genug Vorlaufzeit:* in nächstem Newsletter erwähnen (@LukasFreeze)
  * [x] *bei genug Vorlaufzeit:* [Rhein-Neckar-Zeitung](https://www.rnz.de/kontakt/redaktionen.html)

**Comment by NitramLegov** [comment]
Steffi hat angeboten, an dem Tag den Van zu zeigen

**Comment by LukasFreeze** [comment]
Wie beim Plenum besprochen kümmere ich mich um die Einladung der Presse und würde (ggf mit etwas anderem Text) auch noch weiter streuen:

- RNZ
- HD24
- Mannheimer Morgen?
- Heise (Make:)
- Gemeinderat
  - Fraktionsgeschäftsstellen: https://ww1.heidelberg.de/buergerinfo/kp0040.asp?__kgrnr=369&
- Ökostadt
- Transition Town
- RZL
- Makerspace RN
- Fablabs Bruchsal & KA
- DAI(?)
- Dezernat16
- WerkStattSchule
- DieWerkstatt eV
- Nachbarschaft
-- Jacke wie Hose
-- Nachbarn in "unserer" Halle -> oder reichen dafür Poster?
- Bauhaus/Hornbach?

Fällt noch jemandem was ein, gerne direkt mit Kontakt?

**Comment by LukasFreeze** [comment]
Events auf Meetup und [Facebook](https://www.facebook.com/events/1152092845516872) sind online, letzteres bitte fleißig teilen wenn ihr dort aktiv seid! 😁

**Comment by NitramLegov** [comment]
@LukasFreeze hast du es schon geschafft, Zeitungen anzuschreiben? Ich denke das sollten wir spätestens diese Woche machen. Schaffst du das? Ansonsten kann ich auch einen Teil übernehmen / unterstützen. Du musst mir nur sagen, was ich tun soll :-)

**Comment by LukasFreeze** [comment]
Hatte ich mir auch für diese Woche vorgenommen und schaffe das :+1:

Die Stadt- und Make-Veranstaltungskalender und nebenan.de wären aber gut unabhängig davon zu erledigen wenn du magst!

**Comment by LukasFreeze** [comment]
Presse und Politik sind eingeladen, der Rest folgt vermutlich am Abend - mal schauen wer tatsächlich kommt! 🤞

Unabhängig davon sollten wir dieses Mal auch unbedingt wieder ordentlich Fotos machen! 2019 gab es ja letztlich gar nichts... @Fragegeist @produkt-manager seid ihr am Start und könntet eure Kameras mitbringen? Und Schnappschüsse von coolen Momenten können natürlich alle machen 😊

**Comment by LukasFreeze** [comment]
Kontakt zum Kulturfenster habe ich dann mal selbst rausgesucht, ist ja zum Glück kein Geheimnis. Andere "Non-Profits in our domain" standen denke ich schon großteils auf der Liste hier, aber sagt Bescheid wenn noch jemandem was fehlt!

Regenbogen2 hab ich einer spontanen Eingebung folgend auch einfach mal angeschrieben, ist ja quasi unser Haussender 😁

**Comment by LukasFreeze** [comment]
Morgen ist ja das exakte Jubiläum unseres Einzugs im ersten Gebäude, das würde ich als Aufhänger für den Newsletter nutzen. Schaffen wir morgen auch Twitter und Instagram? Letzteres könnte ich übernehmen, aber auch Twitter bin ich nicht zuhause ;-)

**Comment by NitramLegov** [comment]
Sowohl Twitter als auch Instagram können wir heute vorbereiten und dann einfach nach Zeitplan posten lassen :)

**Comment by LukasFreeze** [comment]
Nachdem gestern offenbar doch niemand Zeit hatte sind die Posts jetzt für morgen nachmittag (15 Uhr) geplant, Entwürfe liegen in Canva falls bis dahin noch jemand dran will

**Comment by NitramLegov** [comment]
Der Tag war ein voller Erfolg und auch unsere PR Aktivitäten scheinen gut gezogen zu haben ☺️

Damit kann das issue heir glaube ich zugemacht werden

**Comment by LukasFreeze** [comment]
Genau, nix mehr zu tun, aber für das nächste Mal lasse ich noch ein paar Erfahrungen hier:
- auf die gezielten Einladungen kam fast nie eine Antwort, es ist also schwer einzuschätzen wie viele tatsächlich beachtet wurden
- von der Presse war niemand da soweit ich mitbekommen habe, aber die RNZ hatte am Mittwoch einen kleinen Hinweis auf uns veröffentlicht
- es dürften gut und gerne 100 Besucher gewesen sein, einige mit Kindern und sogar eine Schülergruppe (zum Glück mit Vorwarnung 😉)
- es waren um die 15 Mitglieder im "Einsatz", die neben den Stationen oft 3-4 Führungen gleichzeitig betreut haben 💪
- @produkt-manager hat eine Zeit lang Fotos gemacht, auf die wir noch gespannt sein dürfen

Falls noch jemand Erwähnungen außerhalb der RNZ gesehen (oder im Radio gehört hat) wäre das sehr interessant!

**Comment by produkt-manager** [comment]
Die Fotos hochgeladen in einen neuen Ordner unter PR. Dort wo auch die anderen Fotos liegen

**Comment by ErikSchatz** [comment]
Hallo Lukas,

 

ich könnte im e-Room wieder sowas löten lassen wie 2019,

 

und nebenbei eine micro:bit-Lichtorgel programmieren lassen,

 

jemand anderes kann ja in Tinkercad wieder mal Gäste ihren

 

Namen mit dem Space-Logo zusammenfügen und drucken lassen.

 

Viele Grüße,

Erik

 
 

Gesendet: Donnerstag, 04. August 2022 um 20:43 Uhr
Von: "Lukas" ***@***.***>
An: "comakingspace/do-something" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [comakingspace/do-something] Tag der offenen Tür zum fünfjährigen Jubiläum (Issue #271)


 

Kaum zu glauben, aber der Space erreicht diesen Herbst schon das Vorschulalter ;-)

Zu diesem Anlass möchten wir gerne wieder einen Tag der offenen Tür / "Open Day" veranstalten wie zuletzt vor unserem Umzug (2-jähriges Bestehen 2019 --> Wiki-Seite mit kleiner Übersicht).

Hat jemand Ideen für ein einfaches Projekt, das Gäste unter Aufsicht ausprobieren könnten (und Lust, das zu organisieren)? Wir hatten zum Beispiel schon kleine Löt-Bausätze oder Herbstlaub aus Sperrholz an der Dekupiersäge, es darf aber definitiv auch etwas ganz anderes sein! Vielleicht auch essbare Kreationen...? Außerdem wäre es richtig cool, wenn viele Mitglieder ein paar Projekte (fertig oder in Entstehung!) mitbringen und wir wieder ein bisschen "Maker Faire" spielen können ;-)

Bitte meldet euch, wenn ihr auf irgendeine Weise mitwirken möchtet!

Das Ganze war die letzten Male nicht nur Werbung für den Space, sondern es war auch immer cool zu sehen was die anderen Mitglieder so treiben und auch mal Leute kennen zu lernen, denen man digital schon häufiger "begegnet" ist aber im Space andere Lieblingszeiten hat.
Trotzdem sollten wir die Veranstaltung natürlich gründlich bewerben (s. auch #topic-pr auf slack) - hier die grundlegenden Infos, die sich nach und nach füllen werden:

Titel: ???

Leiter & Helfer:


	@Pakue95
	@NitramLegov
	@LukasFreeze (machbarer Umfang TBD)
	...tragt euch einfach ein oder meldet euch!


Datum & Zeit: Samstag, 24.09.2022 / wie wäre es mit 10-18 Uhr, danach gemeinsames Grillen?

Teilnehmerzahl: was immer Corona erlaubt

Zielgruppe: Interessierte Leute aus der Region oder anderen Spaces

Kosten: gratis

Beschreibung/Programm: fehlt noch! Vorschläge willkommen :-)

Fotos: fehlen noch! Vorschläge willkommen :-)

Werbung - ToDo:


	
	hier können alle helfen:

	
		Freunden und Bekannten davon erzählen!!
		Wiki-Seite (Tag der offenen Tür)
		"Makers"-Verteiler
		Telegram-Gruppe
		"Maker Community HD" WhatsApp-Gruppe
		Heidelberg.de Veranstaltungskalender
		Make:-Kalender
		bei genug Vorlaufzeit: Poster (für die "Kultursäulen" der Stadt)
	
	
	
	von der Geschäftsführung oder anderen Ehrenamtlichen mit Zugang zu erledigen:

	
		Eventbrite-Seite(?)
		Google-Kalender
		nebenan.de
		Meetup
		Facebook
		Instagram
		Twitter
		bei genug Vorlaufzeit: in nächstem Newsletter erwähnen ***@***.***)
		bei genug Vorlaufzeit: Rhein-Neckar-Zeitung
