### ISSUE TITLE
Winkelanschlag des stationary sanders defekt

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#272]
Siehe Bilder 
![IMG_20220819_201452](https://user-images.githubusercontent.com/7809163/185681955-1435440e-1b53-422b-9af7-2dcaef0a61fa.jpg)
![IMG_20220819_201437](https://user-images.githubusercontent.com/7809163/185681961-53dca7d3-ef39-46e0-91fd-8b5fba54ae13.jpg)

**Comment by Fragegeist** [comment]
Ich habe Mittwochabend am Bandschleifen noch entgradet und den Winkel dazu abgenommen. Zu diesem Zeitpunkt erschien mit die Führung nicht lose. Ich kann mich täuschen, aber den Bildern navh würde ich vermuten, dass die Führung sehr lose ist. Deshalb müsste das Problem innerhalb der letzten 48h womöglich aufgetaucht sein.
Es fehlt die Fixierschraube jetzt oder worin liegt der defekt?

**Comment by LukasFreeze** [comment]
Ich musste vorhin eine Kleinigkeit schleifen und habe den Anschlag mit einer eingeklebten Schraube repariert (vorher vermutlich ein Plastikpin?). Die sollte eigentlich keinen großen Kräften ausgesetzt sein, aber wenn es nochmal kaputtgeht sollten wir eine passende längere Schraube besorgen und oben verkontern :-)
![20220904_151444](https://user-images.githubusercontent.com/19755883/188319146-7c284fa5-2bc9-4bd8-b9b8-393900fc02f4.jpg)
