### ISSUE TITLE
Rad-/Fußweg von der Straßenbahn (Ochsenkopf) zum Space ist auf Google Maps fehlerhaft

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#273]
Beim letzten Repair Café haben wir von externen Besuchern gehört, dass Google die Unterführung bei der Straßenbahnhaltestelle Ochsenkopf als "nicht zugänglich" führt und man auf einen mindestens doppelt so weiten Umweg geschickt wird ([Link](https://www.google.de/maps/dir/Ochsenkopf,+69123+Heidelberg/CoMakingSpace+(Makerspace+Heidelberg),+Siemensstra%C3%9Fe,+Heidelberg/@49.4109073,8.6470156,15z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x4797c6d612c4edd9:0x148021ae09eec847!2m2!1d8.6528614!2d49.4094463!1m5!1m1!1s0x4797c0d94355f4d7:0x889694d430da6feb!2m2!1d8.6466019!2d49.4082244!3e1)). Bis zum Tag der offenen Tür (#271) sollten wir das korrigieren, wenn irgendwie möglich!

Ich habe schon einmal direkt nach der Veranstaltung "Feedback" zu der vorgeschlagenen Route gegeben, leider hat sich seitdem jedoch nichts getan. Vielleicht, wenn es mehrere Leute tun? Oder hat jemand eine bessere Idee?

![grafik](https://user-images.githubusercontent.com/19755883/186881653-31fab742-5196-419b-9445-4c64afe8b2e4.png)

OpenStreetMap hatte ein ähnliches Problem, das konnte ich damals aber (natürlich) ohne Probleme fixen...

**Comment by Titan-OX** [comment]
Eventuell hilft es sich mit GPS navigieren zu lassen aber die richtige Strecke zu laufen und mit dem Rad zu fahren

**Comment by LukasFreeze** [comment]
Habs jetzt nochmal mit der Maps-App versucht, da ist das "contributing" etwas anders als im Browser https://support.google.com/maps/answer/10271004
🤞

**Comment by Titan-OX** [comment]
Geteilte Route
Von Am Bahnbetriebswerk nach Gesetzte Markierung über Ochsenkopfweg

6 min (500 m)


1. Auf Am Bahnbetriebswerk nach Nordosten
2. Links abbiegen
3. Leicht links abbiegen auf Gutachweg
4. Rechts abbiegen auf Wieblinger Weg
5. Rechts abbiegen auf Ochsenkopfweg
6. Ankunft an Zielort: Ochsenkopfweg 18
Diese Route findest du unter https://maps.app.goo.gl/4abk6CuT75YPWHzW8

Also ein Fußgänger wird richtig geleitet aber mit dem Rad schickt es einen über den Umweg

**Comment by NitramLegov** [comment]
![Screenshot_20220829-181653](https://user-images.githubusercontent.com/7809163/187247145-73a2b744-13e5-472c-8e1c-0790a2e8337d.png)

**Comment by LukasFreeze** [comment]
@Titan-OX sobald Start- und Zielpunkt außerhalb der fehlerhaften Straße liegen klappt nichts mehr, egal ob Rad oder zu Fuß :-(

Hoffen wir mal, dass unsere neuen Edits durchgehen...

**Comment by NitramLegov** [comment]
![Screenshot_20220912-020030](https://user-images.githubusercontent.com/7809163/189554647-df1f253d-cc74-465d-9680-163473b75c39.png)

**Comment by LukasFreeze** [comment]
Ich habe gerade auch nochmal sämtliche fälschlich als "restricted use" markierten Streckenabschnitte mit der Feedback-Funktion im Browser gemeldet. Das war zwar auch schon der ursprüngliche Ansatz im Frühling, aber vielleicht guckt ja jetzt jemand anderes drüber...

Hier an der Ecke vom Ochsenkopf gibt es jedenfalls auch eine gute Stelle um am Tag der offenen Tür einen Wegweiser aufzustellen, falls sie stur bleiben :-/

**Comment by NitramLegov** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/7809163/193623374-65ab6281-0aae-4c2f-9a30-f747ea283389.png">
Inzwischen wird der richtige Weg zumindest als Option in Google Maps angezeigt. Also kennt Google jetzt zumindest die Straßen. Ich habe auch nochmal alle Straßen gekennzeichnet, die fehlerhaft als eingeschränkt markiert sind.

**Comment by walzph** [comment]
<img width="1287" alt="image" src="https://github.com/comakingspace/do-something/assets/17416426/c92bbdd6-d600-454c-8bc6-6731e17b3cf8">
<br>
Update: Jetzt wird nur noch der "richtige" Weg durch die Unterführung angezeigt. Ich markiere den Issue daher mal als closed.
