### ISSUE TITLE
Wiki: Anpassungen des neuen Skins

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#275]
Wer heute ins Wiki schaut, dürfte eine andere Optik bemerken - @NitramLegov hat mit einer Änderung des Skins einige Probleme des vorher verwendeten "Mobile Frontend" in der mobilen Version beseitigen können :heart:

- SMW-Galerien (#161) verlinken auch mobil wieder die spezifizierten "redirect"-Seiten, nicht nur ihr Foto
- Recent Changes und "Diff"-Ansicht funktionieren auf mobilen Geräten in vollem Umfang
- die Sidebar wird als "Menü" komplett angezeigt
- ...

Bei so einer großen Umstellung gibt es allerdings natürlich auch unerwünschte Nebeneffekte, die wir hier sammeln können. Mir sind bisher diese Probleme und Problemchen aufgefallen, wenn noch jemand etwas findet bitte melden :-)

- [x] **"edit" und "edit source" neben Zwischenüberschriften werden mobil nicht mehr angezeigt.** Das ist ein großes Problem vor dem Hintergrund der neuen Maschinenseiten-Struktur (#266), da viele Unterbereiche nur eingebunden werden und über ein "edit" der gesamten Seite nicht zu bearbeiten sind. So sollte es aussehen:
 ![grafik](https://user-images.githubusercontent.com/19755883/188097752-19b2bd30-518d-4f24-aa45-1cfc06d3933b.png)

- [x] **die Inhaltsverzeichnisse werden am Desktop ungünstig positioniert und können Überschriften verdecken.**
  - Ein Problem scheint die Rechtsbündigkeit zu sein (früher linksbündig, dadurch war rechts genug Platz für InfoBoxen)
 ![grafik](https://user-images.githubusercontent.com/19755883/188098950-6c8635e9-8a0e-4e7b-8f97-b5a71bb517d5.png)

  - Beispiel für verdeckte Überschrift und sehr eng zusammengeschobenen Text (am rechten Seitenrand bleibt aber viel leerer Raum, kann der genutzt werden? Das Menü geht ja bis ganz rüber:
![grafik](https://user-images.githubusercontent.com/19755883/188098882-e7fcc00d-005e-464c-88a6-4d3f873b6f61.png)

- [ ] die Standardaktionen "Edit", "Edit source" und "Watch" sind jetzt sowohl mobil als auch am Desktop hinter einem Dropdown versteckt. Das finde ich schade, vielleicht können die wieder prominenter werden?
![grafik](https://user-images.githubusercontent.com/19755883/188097041-b112b558-458c-409f-a515-18c5dae35a7f.png)

- [x] die "Tools", die früher gut sichtbar in der Sidebar waren, sind jetzt oberhalb der Seiten. Für viele davon ist das sinnvoll, aber "Upload File" und "Special Pages" hängen ja nicht von der aktuell besuchten Seite ab und würden wieder gut (ggf. zusätzlich) in die Sidebar passen
![grafik](https://user-images.githubusercontent.com/19755883/188097387-36ad6f30-e94a-4ab4-bb6b-7754a346085d.png)

Dass die Texte mobil jetzt nicht mehr "eingeklappt" daherkommen finde ich persönlich voll in Ordnung, früher sahen manche Seiten (ohne Intro/InfoBox vor der ersten Überschrift) dadurch komplett leer aus. Zur einfachen Navigation gibt es dafür jetzt wieder die gewohnten Inhaltsverzeichnisse :-)

**Comment by LukasFreeze** [comment]
assigned @NitramLegov to do his magic 😁

**Comment by NitramLegov** [comment]
Edit und Edit Source werden mobil wieder angezeigt

Ich denke am Inhaltsverzeichnis kann ich auch was machen.

Allerdings fürchte ich, dass wir mit dem allgemeinen "Actions" Menü erstmal leben müssen

**Comment by NitramLegov** [comment]
Bezüglich der extra edit buttons gibt es ein Issue im Skin, das allerdings geschlossen ist. Das Verhalten des Skins wird wohl nicht geändert:
https://bitbucket.org/wikiskripta/medik/issues/19/how-to-add-a-seperate-button-for-edit

Damit habe ich gefixt was ich fixen konnte :)

Dass die Überschriften im Default mobil ausgeklappt sind finde ich noch sehr unschön. Damit muss man Mobil teilweise ewig scrollen, das ist nicht das Verhalten, was ich als User mobil erwarten würde. Es gibt aber schon ein Issue dafür, mal sehen, ob der Skin Autor das fixt:
https://bitbucket.org/wikiskripta/medik/issues/25/collapsible-headers
