### ISSUE TITLE
Anschlag der Abrichte nicht mehr auf 90° einstellbar

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#277]
Der Abrichten-Anschlag ließ sich heute leider nicht auf 90° einstellen, auch wenn die Stellschrauben (zum Begrenzen des max. Winkels bei 90°) komplett zurückgezogen waren.

Wenn ich nichts übersehen habe, sollten ein paar Unterlegscheiben zwischen Anschlag und Aufhängung helfen...

Außerdem ist ein Messfehler nicht ausgeschlossen: zwei Aluwinkel zeigten den gleichen Schiefstand, aber die massiven Schlosserwinkel waren nicht zu finden?!

**Comment by Pakue95** [comment]
Hab den Anschlag heute nochmal neu eingestellt. Die beiden Stellschrauben waren am Limit und konnten den Anschlag nicht weiter nach vorne neigen. Ich musste dafür dann die zwei Schrauben, mit denen der Anschlag am Kopf der Abrichte befestigt ist, lösen und etwas geneigt festmachen. 

Bei der Gelegenheit habe ich auch den optimalen niedrigen Anschlag entfernt und an die Wand bei den Leitern gehängt. Mir ist bisher noch nicht untergekommen, dass der genutzt wird und er macht das Neigen des Anschlags etwas schwieriger. Wenn er benötigt wird kann man ihn bei Bedarf wieder dranmachen. Bitte melden, falls der doch häufiger genutzt wird, dann mach ich ihn wieder permanent dran.

PS: Um den Anschlag noch genauer zu justieren braucht man besseres Messequipment, wobei die Aluextrusion vom Anschlag jetzt auch kein metrologisches Meisterwerk ist daher wahrscheinlich vergebene Liebesmühe.

![IMG_5732](https://user-images.githubusercontent.com/19751734/189497561-9dfaa0fe-1bbd-4976-8499-9998a5110d8b.jpeg)
![IMG_5733](https://user-images.githubusercontent.com/19751734/189497569-17a4a92d-8231-413e-b5a1-be3f7027431b.jpeg)
![IMG_5734](https://user-images.githubusercontent.com/19751734/189497570-556645b8-66de-4b52-a422-1bcd3f897e5d.jpeg)
![IMG_5735](https://user-images.githubusercontent.com/19751734/189497572-36effe61-4894-48d7-b55e-4b95424c5d3b.jpeg)
![IMG_5736](https://user-images.githubusercontent.com/19751734/189497575-bf5703d0-ce8d-4d21-b4ec-c03d0b88ffd0.jpeg)
