### ISSUE TITLE
notwendige Verbesserungen der Tischkreissäge

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#279]
Ich habe heute Mittag eine Einweisung gegeben und uns sind mehre Punkte aufgefallen, für die in dem Moment leider keine Zeit war aber die ziemlich sicher korrigierbar sind.

Ich versuche mal nach Sicherheitsrelevanz zu sortieren:
- [x] Parallelanschlag ist schräg 
  - zum Glück wird die Öffnung hinten weiter und nicht enger, aber es müsste sich an der Aufhängung ganz begradigen lassen (die Aluprofile sind nicht verzogen, sondern nicht ganz rechtwinklig an dem Teil mit der Feststellschraube befestigt)
- [x] Höhenverstellung ist extrem schwergängig
  - @Pakue95 kann man da was ölen oder die Spannung auf der Stange, die dahintersteckt, reduzieren?
- [x] Schiebeschlitten ist fast durchgesägt
  - hinten sollte dringend ein höheres Brett angeleimt werden. Abgesehen davon ist die Schnittfuge im Schlitten leider schon extrem breit geworden, den haben wohl Leute mit geneigtem Sägeblatt benutzt 😕
- [ ] Hebelzwingen und Gehrungsanschlag passen nur (noch?) sehr schwer in die Nut im Schiebetisch
  - die Zwingen hatte ich extra dafür runtergeschliffen, vielleicht doch nicht weit genug? Da es aber ziemlich sicher früher ging und auch der Anschlag betroffen ist müssen wir vielleicht nur einmal kräftig die Nut ausbürsten

**Comment by Titan-OX** [comment]
Von den zwingen gibt es mehrere und nicht alle passen. Vielleicht hat jemand die vertauscht

**Comment by LukasFreeze** [comment]
Nee nee, das waren schon die richtigen ;-)

Hatte die selbst mal passend gemacht

**Comment by Pakue95** [comment]
Parallelanschlag ist jetzt wieder parallel(-er) und die Spindelmutter an der Höhenverstellung ist nachgeschmiert und läuft jetzt besser. 

![image](https://user-images.githubusercontent.com/19751734/190697610-6bdc88e4-5a49-48bd-80a2-b46c8a850459.jpeg)

**Comment by LukasFreeze** [comment]
Ich habe eine der Hebelzwingen nochmal nachgeschliffen, jetzt passt wieder alles :-)

Das "Klemmen" des Gehrungsanschlags am Schiebetisch kann man auch als Feature sehen: öffnet man beide Klemmhebel, kann man den wackligen Anschlag in die Nut einführen und erst dann wieder im richtigen Winkel festziehen. Dadurch hat man leicht einen Griff am Schiebetisch, den man sonst erst durch umständliches Entfernen des Unterlegstücks und "Durchschrauben" des vorderen Klemmhebels bis an den Nutgrund hätte. Vor der Benutzung aber auf jeden Fall nochmal gut prüfen, dass wirklich alles fest genug angezogen ist!

Dem Schiebeschlitten hatte @Pakue95 schon wieder ein Brett angeleimt und damit gerettet. Wenn jemand wieder ganz akkurat damit arbeiten möchte sollte ein neues Brettchen über der Schnittfuge eingesetzt (z.B. in eine gefräste Vertiefung) und neu eingesägt werden, aber da sehe ich persönlich gerade nicht den Bedarf. Sonst kann man hier gerne wieder aufmachen :-)
