### ISSUE TITLE
Laptop Tisch cnc raum

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#28]
Im cnc Raum fehlt eine Möglichkeit, den Laptop beim gcode Senden abzustellen.

**Comment by emka** [comment]
Ich dachte an eine ausziehbare Platte, entweder mit Schubladenführung oder einfach zwei Holzblöcke mit Führungs-Nut seitlich. Die Details würde ich der Person überlassen, die das machen will.

**Comment by NitramLegov** [comment]
Habe einen alten computertisch mit Rollen und ausziehbarer Platte bekommen. Schauts euch mal an, das issue kann man dann denk ich zumachen :)
