### ISSUE TITLE
OSAMD-Workshop Oct. 2022

### ISSUE THREAD

**Issue by PaulGoldschmidt** [comakingspace/do-something#281]
**Name**:
OSAMD: Selber ein Luftqualitätsmessgerät bauen

**Presenter & helpers**:
Paul (organizer)

**Date & time**:
Saturday, 29.10.2022: 10.00 o'clock till 13.30

**Description**: *(can be used for advertising the seminar)*
Wir bauen zusammen die OSAMD-Messstation, ein quelloffenes Luftqualitätsmessgerät für Innenräume. Die Teilnahme ist vollständig gratis. Es wird darum gebeten, einen eigenen Laptop mitzubringen.

**Rooms**: *(e.g. Common room, wood workshop etc.)*
Common Room

**Tools & materials**: 
Soldering Iron

## Advertisement ToDo:

* to be done by a [manager](https://wiki.comakingspace.de/Management):
  * ~~Eventbrite page (if there are tickets)~~
  * [x] calendar entry
  * [ ] [Meetup](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/)
  * [ ] [Facebook](https://www.facebook.com/comakingspace/)
  * [ ] [Instagram](https://www.instagram.com/comakingspace/)
  * [ ] [Twitter](https://www.twitter.com/comakingspace/)
  * [x] *if there's time:* announce in the next newsletter (@LukasFreeze)
  * [x] *if there's time:* [Rhein-Neckar-Zeitung](https://www.rnz.de/kontakt/redaktionen.html)

* help welcome:
  * [ ] event wiki page ([Category:Seminars](https://wiki.comakingspace.de/Category:Seminars)
  * [ ] announce via Members mailing list
  * [Telegram Group](https://wiki.comakingspace.de/Telegram_Group)
  * "Maker Community HD" WhatsApp Group
  * [https://www.heidelberg.de/hd,Lde/HD/Erleben/veranstaltungskalender.html Heidelberg.de Veranstaltungskalender]
  * [https://www.heise.de/make/kalender/new_event/ Make: calendar]
  * ~~*if there's time:* Poster (to be hung up by the city)~~

## General considerations 
- what's the name/idea/purpose of the event?
- (if at the Space) is there permission from the [management](https://wiki.comakingspace.de/Management)?
- is there a fixed date and time yet?
- is there a registration deadline (if yes, please include a link to the form)?
- how many people are needed to organize it on the day of the event?
- are there any concrete tasks to be done in advance?
- what part of the work would you take over?

*to make sure your idea is visible, you should also share this "issue" via the [Mailing List](https://wiki.comakingspace.de/Mailing_List) and ask for help there!*

**Comment by LukasFreeze** [comment]
Für einiges reicht die Zeit jetzt natürlich nicht mehr, aber ich stelle es gerne noch bei Meetup rein :-)

Sollten alle TN Deutsch sprechen oder ist auch Englisch okay?

**Comment by PaulGoldschmidt** [comment]
Englisch passt auch, wenn man nicht komplett bei 0 anfängt oder wir genug helfer haben, die ggf. auch 1:1 betreuuen können. Danke!

**Comment by LukasFreeze** [comment]
Hmm, 1:1? Wie viele Helfer gibt es denn bisher?

**Comment by LukasFreeze** [comment]
@PaulGoldschmidt bevor wir hier zumachen: Sollten wir nächstes Mal (mit mehr Vorlauf 😉) etwas anders machen?
wie viele Leute kamen denn letztendlich und hat alles gut geklappt? 🙂
