### ISSUE TITLE
CNC Router Y-Axis behaving unexpected

### ISSUE THREAD

**Issue by PaulGoldschmidt** [comakingspace/do-something#283]
The CNC Router ([Ooznest WorkBee CNC](https://wiki.comakingspace.de/CNC_Router#WorkBee)) seems to have a problem with the Y-Axis movement: It looses steps & rattles while moving, homing fails currently aswell. It failed (loosing steps) while milling a gcode which has worked about ten times before, so the issue is likely not linked to the specific g-code. I checked the wiring and restarted everything, which did not resolve the issue. My guess is that something with the stepper motor driver (or the motor itself) isn't right, CNCjs doesn't throw out an specific error.
Anybody know what I could try debugging this issue further?

**Comment by PaulGoldschmidt** [comment]
Update:
The Y-Axis had a small pice of wood on the left linear rail hindering the y-axis from moving effectivly - now the router does successfully home itself, but three issues remain:
1) the y-axis movement is slow and still rattles; checked both motors, confirmed they are working. Maybe an issue with the drivers or perhaps something software-related?
The second issue is almost confirmed a software problem:
2) cncjs (or the firmeware itself) doesn't remember (?) the machine limits and softlocks when trying to move further than 150mm on the y-axis.
3) The scaling of movement on the x-axis is wrong - when instructing the x-axis to move 10 mm, it moves around 93 mm, when instructed to move 100 mm, it moves 930 mm.

Would it be possible that all three issuess are completly software-related? Is there maybe some machine profile which is needed? As @NitramLegov forked CNCjs, do you have an idea what could be happening here? (cc: @Johannes09)

**Comment by Pakue95** [comment]
The rattling might be due to the X axis not being aligned to the Y axis. Make sure both sides are equal-distant to the hardstops.

**Comment by PaulGoldschmidt** [comment]
Sadly, realining the X axis does not seem to help - I took a look at the issue w/ @NitramLegov and we determined that the most likely issue seems to be that the stepper motor drivers are damaged.
I will look into reordering the stepper motor drivers (see issue #104, DRV8825PWP) - but because I won't be in Heidelberg till mid-march or mid-april, I can't garantee an early fix in the next weeks from my side. If somebody wants to reorder them instead, please let me know, we can surely arrange something with the costs. Nevertheless I would defenetly need assistance in swapping those driver ICs.

**Comment by PaulGoldschmidt** [comment]
Alright, back in Heidelberg - if there are till this point no updates, I would now order some new drivers and hope that they are the issue. Anyone willing to help with this issue? As stated, my experience with the backbone of this machine is close to zero.

**Comment by Pakue95** [comment]
The issue was due to wrong grbl settings being loaded. When the setting from the [GitHub repo](https://github.com/comakingspace/cnc-panel) are entered it works fine. 

The odd thing is that they should be set to those values every restart. In case the get changed again we need to investigate further. Maybe by reinstalling the CNCJs Pi.
