### ISSUE TITLE
Metall Mill 

### ISSUE THREAD

**Issue by Titan-OX** [comakingspace/do-something#285]
We have this metal mill that we need to document and make available. Lino is currently working on getting it running again.

![IMG_20230201_234935.jpg](https://user-images.githubusercontent.com/22505956/216615420-5f9138fe-c9f0-40f0-b7fb-41a5163cc3d0.jpg)

**Comment by LukasFreeze** [comment]
Gibt es diese Fräse gar nicht mehr? Am üblichen Platz habe ich sie heute nicht gesehen 🤔

**Comment by Pakue95** [comment]
Ne, die ist weg. Nachdem über ein Jahr keinen Fortschritt mehr gemacht wurde (und auch nicht in Aussicht stand), habe ich Luzian gebeten die wieder mitzunehmen.
