### ISSUE TITLE
improve spray table wheels

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#287]
The spray table should be rolled in and out of the building with ease. Some small wheels were attached in a first attempt, but don't do the trick :-(

We could either attach bigger/better wheels on each leg (would need a brake, too!) or go with a wheelbarrel-like design using a single large wheel:

![20230302_014206](https://user-images.githubusercontent.com/19755883/222716024-ecbac3a9-b4cc-4497-a784-f9b98e2514bf.jpg)
(handles are optional, I hope the idea becomes clear 😆)

**Comment by Titan-OX** [comment]
I'd do to medium wheels. Around ø120mm.

Also the locking mechanism for the flaps is weak. So maybe a hinge at the top as well with a removable pin (on a string or semi captive) would do the trick

**Comment by Johannes09** [comment]
![20230303_202002](https://user-images.githubusercontent.com/22060480/222808181-291da35d-985a-4067-9dd7-a002092bfe42.jpg)
Ich habe den Tisch neue Räder verpasst.
Zum bewegen muss der Tisch auf der einen Seite hochgehoben werden.
