### ISSUE TITLE
verschwundene Klemmschraube an der Dekupiersäge

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#289]
Die Dekupiersäge kann gerade keine geklemmten Blätter (ohne Pins) aufnehmen, da die untere Klemmschraube fehlt:

![20230309_004057](https://user-images.githubusercontent.com/19755883/224007705-795a16ab-9fc3-442c-be29-85c273d6e8c7.jpg)

Vermutlich war sie nach der letzten Benutzung lose, hat sich losvibriert und wurde dann direkt abgesaugt :-P
Ein Ersatz sollte aber nicht kompliziert sein, wenn man die passende Größe findet (siehe fast identische Klemme am oberen Arm) und die Schraube aus der richtigen Richtung einbaut (ein Loch hat Gewinde, das andere nicht)

PS: auch an der Absaugung fehlte eine Schraube, dadurch war die Säge recht laut - das ist mir allerdings früher aufgefallen und ist schon behoben :-)

**Comment by LukasFreeze** [comment]
Yup, Hanna und ich hatten die im Czernyring auch schonmal in der Hand...

**Comment by NitramLegov** [comment]
@Pakue95 is this issue still relevant? 🙈

**Comment by LukasFreeze** [comment]
Ja, die Schraube fehlt immer noch

**Comment by LukasFreeze** [comment]
Eine M4x16 mm hat hat gepasst. Mal schauen wie lange sie diesmal durchhält 😜
