### ISSUE TITLE
Telegram-Bot wiederbeleben

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#294]
Wir hatten früher™ automatische Infos auf Telegram über Kalendereinträge und Fortschritte hier im issue tracker, das war ziemlich cool! Leider funktioniert dieser Bot seit ein paar Monaten nicht mehr, wer könnte sich das mal anschauen? 

Es scheint am Pi im Gemeinschaftsraum (beim Router zu liegen, @NitramLegov hat dazu vor einer Weile auf Telegram geschrieben:
>Habe heute mal auf den pi draufgeschaut, auf dem der bot läuft.
Der ist langsam ohne ausgelastet zu sein, schmeißt seltsame Fehlermeldungen und funktioniert ganz generell nur zögerlich.
>
>Ich vermute, dass da langsam die SD Karte nicht mehr will...
>
>Eine neue SD Karte auszusetzen sollte aber kein riesen Ding sein:
>- Die relevanten Daten (inklusive Install Skript) liegen auf GitHub: https://github.com/comakingspace/CommonRoomPiSettings
>- Die wöchentlichen Updates hier im Chat laufen über Cron. Die Einstellungen dazu kann ich zur verfügung stellen :)

**Comment by Titan-OX** [comment]
Ein WebCal link über den man immer die aktuellen Termine in sein eigenen Kalender synchronisieren kann wäre auch toll zu haben. Ich glaube das geht sogar mit dem Nextcloud Kalender könnte dann aber eventuell zu viele zugriffe auf den heztner server sein.

**Comment by LukasFreeze** [comment]
Oh, ich dachte das würde auf der Website angezeigt, aber war wohl nur bei der alten so 😅

Das hier ist der Link: https://calendar.google.com/calendar/ical/4hbi6bp3lol50h2m422ljg81t0%40group.calendar.google.com/public/basic.ics

@NitramLegov spricht was dagegen, dass ich den auch (wieder) unter "kalender" auf der Website platziere?

**Comment by walzph** [comment]
Hab den _CoMakingController_ Pi nun wieder neu aufgesetzt und direkt an die Fritz!Box gehängt. Danach alle bisherigen Dateien unter `/home/pi` rüber gezogen und das `Install.sh` Script ausgeführt.

Folgende Issues gibt es noch:
1. Das install script benutzt an einigen Stellen `pip3`, den alias gibt es beim aktuellen Raspbian nicht mehr. 
2. Nach manuellem `pip install -r requirements.txt` kann die cryptography library nicht gebuilded und installiert werden. Hab ich nun über `apt install python3-cryptograpy` installiert.
3. Das `telegram` Modul ist nicht in der requirements.txt, deshalb ImportError. Manuell installiert, neuer Error `telegram.ext`
4. Stattdessen über apt `python-telegram-bot` installiert, jetzt neuer ImportError: cannot import name 'run_async' from 'telegram.ext'

Fazit: @NitramLegov kannst du nochmal über die dependencies schauen und am besten alle dann auch auf minor/patch versions pinnen, damit das bei einem re-install weniger Probleme gibt?

**Comment by LukasFreeze** [comment]
Er ist wieder k.o. :-(

Kann das etwas mit dem Stromausfall vom letzten WE zu tun haben?

**Comment by NitramLegov** [comment]
Die Kalendereinträge werden inzwischen auf anderem Weg gepostet. Falls wir irgendwann die anderen Funktionen haben wollen schlage ich vor, das ggf. via. homeassistant zu implementieren.

Zumindest ich werde den bot in nächster Zeit nicht warten😅
