### ISSUE TITLE
3. OSAMD-Workshop (Bau einer Luftqualitätsmessstation)

### ISSUE THREAD

**Issue by PaulGoldschmidt** [comakingspace/do-something#299]
Ein letztes mal soll am 13. Juli 2023 im CoMakingSpace ein Workshop zum geleiteten Selbstbau des OSAMD-Projektes stattfinden. Dieser wird um 15:30 Uhr starten und bis etwa 18:00 Uhr gehen.
Der Workshop ist primär für 13 bis 25-Jährige gedacht (aus Projektfördergründen musste dieser Altersraum gewählt werden, aus Erfahrung kommen aber Jugendliche ab 17 Jahren zu den Workshops), wenn ihr älter seid, ist eine Teilnahme prinzipiell aber auch möglich. Die Anmeldung erfolgt bis zum 11. Juli unter [https://osamd.de/2023](https://osamd.de/2023).
Es wäre gut, drei bis vier weitere Helfende Hände dabei zu haben, diese erhalten auch eine Aufwandsentschädigung in der Höhe von 15 Euro pro Stunde.
Da dies der letzte Workshop der Reihe ist, wollen wir am Ende auf ein Getränk anstoßen, für Snacks ist gesorgt. Wenn ihr gerne helfen würdt, meldet euch bitte auch bis 11. Juli unter [paul@osamd.de](mailto:paul@osamd.de).

Ich freue mich auf das Event!

**Comment by Pakue95** [comment]
Ist der Workshop gut gelaufen?

**Comment by PaulGoldschmidt** [comment]
Lief sehr gut, waren knapp 15 Teilnehmer:innen! Schließe das Issue weil Workshop fertig.
