### ISSUE TITLE
mount more boards to the workshop walls

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#30]
We should reduce our pile of scrap wood and also need more places to hang tools so the tables/workbenches stay free.

Let's cover more walls with wood! The boards we hung so far are 20 mm thick which turned out to be a nice thickness for screwing for screwing on accessories like tool holders.

I especially think it's important to get some holders for measuring tools in place, some of them are too delicate to be shoved around on a shelf all the time.

- [ ] board(s) for marking & measuring equipment (currently on the ladder shelf)
- [x] board(s) to make room for bit & screwdriver storage (#23) 
- [ ] board(s) for wood lathe accessories
- [ ] board(s) for table saw accessories
- where else?

**Comment by LukasFreeze** [comment]
I started with some medium boards around the marking & measuring corner last night, feel free to add some more screws or more sophisticated holders to them!

**Comment by NitramLegov** [comment]
Johannes and me put quite some boards on the walls today ;)
