### ISSUE TITLE
Third (and last) WordClock Workshop

### ISSUE THREAD

**Issue by PaulGoldschmidt** [comakingspace/do-something#301]
- Six years ago, I did the first WordClock Workshop at the old Makerspace in the DAI Basement. Three years later, I did the same workshop again. Now another three years later, I plan to do one last Workshop to build the basement (_no frontplate will be provided due to the copyright held by Biegert & Funk Product GmbH & Co KG_) of the WordClock with up to twelve people.
- Management (@LukasFreeze | @Pakue95 | @NitramLegov) still needs to consent to the workshop.
- Time for the Workshop needs to be coordinated, the timeframe is one full day on a weekend in Q1/2024 (around 8 hrs) for the complete build.
- registration deadline will be shared on a later date
- No additional staff needed for organisation
- I pre-cut all the wood and have full-size PCBs premade to make the assembly easier

**Comment by LukasFreeze** [comment]
Da es nur wenige Interessenten gibt, wird der Workshop wohl im kleinen Kreis außerhalb des Space stattfinden.

@PaulGoldschmidt falls sich doch nochmal was ändert, einfach nochmal aufmachen :-)
