### ISSUE TITLE
Tiefenanschlag Scheppach DP 16SL ersetzen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#302]
Unsere kleine Säulenbohrmaschine ist bis auf weiteres nicht nutzbar:

![20231028_031141](https://github.com/comakingspace/do-something/assets/19755883/6c3ae8cb-beaa-4b40-aff5-c1228fdd9ee5)

Wer kann den Tiefenanschlag neu drucken und montieren? Wer auch immer das Ding dermaßen zerstört hat darf sich auch gerne mit einer Entschuldigung melden 😠

**Comment by LukasFreeze** [comment]
Ich glaube das hier ist das Design zum Nachdrucken: https://github.com/comakingspace/CommonFiles/blob/master/3DPrintingFiles/Drill%20Press%20Depthstop.step

**Comment by Pakue95** [comment]
3D Files sind im "Parts" Repo: https://github.com/comakingspace/Parts/tree/main/Scheppach_DP%2016_SL_Ständerbohrmaschine

Hab ein neues gedruckt und brings am Fr. mit.

**Comment by Johannes09** [comment]
ist gefixt
![photo_2023-11-01_22-49-32](https://github.com/comakingspace/do-something/assets/22060480/4ad70280-23f9-4235-a60f-ed3ae0e2fb3a)

**Comment by LukasFreeze** [comment]
Nachdem das Teil mehrfach neu gedruckt und immer wieder abgerissen wurde, hat diese Bohrmaschine nun eben keinen Anschlag mehr...
