### ISSUE TITLE
Workbee CNC: Wrong settings

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#303]
Today we had an issue with the CNC Router. Apparently, homing was disabled.

When checking the settings, I realized they have been changed (or reset to default?) again. I checked why the CNC Panel did not automatically set our desired settings and found that the service for the panel had an error:
![image](https://github.com/comakingspace/do-something/assets/7809163/caaf28ab-7c5a-4d71-935b-9920ae36c93e)

Restarting the service and reconnecting the cnc router helped.

Can somebody with more JavaScript knowledge look into this? @Narquadah Would this be something for you?

**Comment by Blacksheep70** [comment]
I can add that homing worked for me later that day. However, if appers to me that the machine settings are not correct. After unlocking and homing the command

`G1 X500 X500 F1600 `

lead to a soft limit alarm. The command

`G1 X200 Y200 F1600 `

worked fine.

As Workbee has a working area of 1250x1250 it's clear to me that somehow the machine settings are somehow lost / reset to defaults.

**Comment by NitramLegov** [comment]
Closed with #307
