### ISSUE TITLE
Lasercutter-Arbeitsfläche ist nicht parallel zur Optik

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#308]
[Jakob Sc in der Telegram-Gruppe:]

Der Lasercutter ist in der hinteren rechten Ecke ca 3mm höher als in den anderen drei Ecken. Vielleicht könnte man das mal nachjustieren? Ich helfe gerne mit, falls Hilfe benötigt wird.

**Comment by Pakue95** [comment]
Sollte nun wieder besser eingestellt sein.

| | | |
|--------|--------|--------|
| 2.63 | 2.59 | 3.00 |
| 2.68 | 2.57 | 2.80 |
| 2.78 | 2.65 | 2.54 |
