### ISSUE TITLE
Prusa MK2 MM - Erfahrungen sammeln & dokumentieren

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#31]
Zur 3D Drucker Farm ist ein Prusa MK2 mit Multi Material Aufsatz hinzugekommen. Der funktioniert wohl auch, man muss aber erste Erfahrungen sammeln, das Handling dokumentieren und einen Platz für den Drucker finden.

Das Issue mache ich einfach mal als zentralen Anlaufpunkt auf.
Falls es die Zeit erlaubt, werden Ciaran und ich uns am 20.06 morgens mal dransetzen.
Von prusa gibt es entsprechende Tutorials.
Für eigene Konstruktionen (mit export des STL files aus Fusion):
https://manual.prusa3d.com/Guide/Export+model+from+Fusion+360/378?lang=en
https://manual.prusa3d.com/Guide/Gcode+preparation+for+Multi+Material+v2.0/424?lang=en

Für vorhandene STL Dateien:
https://manual.prusa3d.com/Guide/Splitting+STL+using+MeshMixer/403?lang=en
https://manual.prusa3d.com/Guide/Splitting+STL+with+single+compact+part/380?lang=en

Most likely, documentation can be done here:
https://wiki.comakingspace.de/3D_Printer_Farm
Once the slicing documentation is done. the MM upgrade can be documented here:
https://wiki.comakingspace.de/Prusa_i3_MK2S

**Comment by NitramLegov** [comment]
https://www.prusaprinters.org/printing-soluble-interface-supports-prusa-i3-mk2-multi-material/

**Comment by NitramLegov** [comment]
Documentation is done. @Pakue95 , @emka  or @LukasFreeze  can you review it and close the issue if you are fine with it?
Let me know in case you´re missing something or are not happy with something.
I will open another issue for finding a proper location for the printer.

**Comment by LukasFreeze** [comment]
Nice, thanks for starting the documentation! More details will hopefully be added over time as people use the printer more :-)
