### ISSUE TITLE
Wiki-Suche auf "Project"-Namespace erweitern

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#313]
Man kann sich für das eigene Nutzerprofil einspeichern, in welchen Namespaces gesucht werden soll, wenn man etwas in der Suchleiste eingibt - inklusive Suchvorschlägen 🤯

![Screenshot_20240518_234546_Firefox](https://github.com/comakingspace/do-something/assets/19755883/50442122-da20-4e35-8644-fb3ba254c4c3)

Ich finde das für den "Project"-Namespace dermaßen sinnvoll, dass ich vorschlage es zum Standard zu machen: 

```
you just add this to your "LocalSettings.php" file, e. g. for the project namespace:

$wgNamespacesToBeSearchedDefault[NS_PROJECT] = true;
```
--> [Doku](https://m.mediawiki.org/wiki/Manual:$wgNamespacesToBeSearchedDefault)

**Comment by NitramLegov** [comment]
Done. I also added the namespaces "Category" and "Material"
