### ISSUE TITLE
MK3 shows thermal runaway error 

### ISSUE THREAD

**Issue by thomas-rekers** [comakingspace/do-something#314]
The MK3 shows thermal runaway error. Seconds before the error occurred, the extruder was smoking. Filament unloading did not work afterwards because it did not reach the necessary temperature. I did not know how to remove the printed filament from the bed. The display, printed filament and print settings can be seen here:
![printer_display](https://github.com/comakingspace/do-something/assets/31842080/ac9341a2-de22-475f-b36a-ac0ec6a91e33)
![printer_bed](https://github.com/comakingspace/do-something/assets/31842080/79bf6da5-c8d4-427b-b980-c722eb09ea46)
![print_settings](https://github.com/comakingspace/do-something/assets/31842080/5bd5aef3-0543-4eb4-b7da-2cccba43753b)

**Comment by dmaennle** [comment]
My MK3S had this issue when the temperature probe was malfunctioning. Changing the probe fixed the issue.

**Comment by LukasFreeze** [comment]
@lmnl99 kannst du bitte noch einmal kurz schreiben, was du hier schon versucht hattest?

**Comment by NitramLegov** [comment]
@Johannes09 was this fixed?

**Comment by Pakue95** [comment]
@Johannes09 swapped the board and the printer is available again. Seemed to be an issue with the PTC reading circuit on the main board.
