### ISSUE TITLE
Seminar: Einführung in die Slicer, Orca und Prusa Slicer 

### ISSUE THREAD

**Issue by lmnl99** [comakingspace/do-something#315]
Lasst uns die kommende Veranstaltung bewerben!

**Titel:** Einführung in die Slicer, Orca und Prusa Slicer 

**Leiter & Helfer**:  Luca (lmnl99)

**Datum & Zeit:**  Samstag der 13.07.24 14-17Uhr

**Teilnehmerzahl:** 10

**Zielgruppe:** An alle Mitglieder des Space die die Slicer besser verstehen möchten. 

**Kosten:** 0€

**Beschreibung:**  Erklärung und Erweiterung in die Fähigkeiten zur Benutzung der Slicer. Damit man besser druck Ergebnisse erzielen kann. 

**Fotos:** *fehlen noch! Vorschläge willkommen :-)*

## Werbung - ToDo:

* hier können alle helfen:
  * [x] Wiki-Seite ([Category:Seminars](https://wiki.comakingspace.de/Category:Seminars))
  * [x] [Slack](https://wiki.comakingspace.de/Slack)
  * [x] [Telegram-Gruppe](https://wiki.comakingspace.de/Telegram_Group)
  * [ ] "Maker Community HD" WhatsApp-Gruppe
 

* von der [Geschäftsführung](https://wiki.comakingspace.de/Management) oder anderen Ehrenamtlichen mit Zugang zu erledigen:
  * [x] Anmeldelink: [Nextcloud-Umfrage](https://cloud.comaking.space/apps/polls/s/YyEO35pZ)
  * [x] Google-Kalender

**Comment by LukasFreeze** [comment]
Ich habe eine einfache Wiki-Seite angelegt, kann gerne ergänzt werden :-)
https://wiki.comakingspace.de/Einf%C3%BChrung_ins_Slicen_f%C3%BCr_den_3D-Druck

Die Anmeldung würde ich statt Eventbrite über Nextcloud machen, das lief
beim Fusion-Seminar super. Note to self: Issue-Vorlage aktualisieren!

**Comment by LukasFreeze** [comment]
Anmeldelink: https://cloud.comaking.space/apps/polls/s/YyEO35pZ

Ab jetzt kann die Wiki-Seite gerne geteilt werden!

**Comment by lmnl99** [comment]
Beim Seminar waren leider nur 2 Leute Anwesend. Es kahm aber aber sehr gut an. Ich würde im laufe dieses Jahres nochmal ein Seminar anbieten.
