### ISSUE TITLE
Scroll Saw/Dekupiersäge is broken

### ISSUE THREAD

**Issue by reogaro** [comakingspace/do-something#316]
**Proxxon DSH won't turn on anymore.**

- Install Blade
- Plug in
- Turn on
- Nothing happens

Neither speed 1 or 2 work.
I ran it through the vacuum before, turned it off, and it didn't turn on again.
I suspect a switch or wiring issue but so far have not investigated further.

I'm currently working on the CNC mill don't want to get sidetracked by another machine. Can someone take a look at this?

**Comment by LukasFreeze** [comment]
Last week it also happened and miraculously worked again when I looked at it later (see note in the wiki) - could it be dirt in the switch?

**Comment by Pakue95** [comment]
The mains switch is broken and a replacement part is ordered. 
I guess that it'll be fixed in a week.

**Comment by Pakue95** [comment]
Switch has been replaced.
