### ISSUE TITLE
Bambu Lab P1S: Überhitzung des Bauraums

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#317]
Wir haben am Samstag wieder eine besonders fiese Verstopfung in einem der Bambu Lab P1S gelöst und es gibt wohl ein bekanntes Problem: der geschlossene Bauraum kann bei vielen Filamenten zu Verstopfungen führen ( s. Bambu Lab wiki](https://wiki.bambulab.com/en/general/filament-guide-material-table#build-plate-settings)). 

Lösungsvorschläge:
- [x] Erklärung im Wiki
- [x] Hinweis an oder in der Nähe der Drucker
- [ ] Lagermöglichkeit für die oberen Scheiben, die man wohl nur für "heiß gedruckte" Materialien wie ABS oder ASA verwenden sollte

**Comment by Pakue95** [comment]
Ich würde stark davon abraten die obere Glasplatte abzunehmen, da wir ziemlich viel Staub und Schmutz in der Luft haben, der den Lagern auf Dauer nicht gut tut. 

Lasst lieber den Hinweis auf die Tür beschränken, wenn die Raumtemperatur >30°C hat.

**Comment by LukasFreeze** [comment]
Stimmt, an Staub hatte ich nicht gedacht...mir kam der Deckel eleganter vor, weil man an offen stehenden Türen hängen bleiben könnte

**Comment by LukasFreeze** [comment]
![20240725_002225](https://github.com/user-attachments/assets/f71bddb3-ede0-42c9-bfae-7aab8aebadb3)
