### ISSUE TITLE
Fusion 360 Seminar für Einsteiger/Anfänger

### ISSUE THREAD

**Issue by lmnl99** [comakingspace/do-something#318]
Lasst uns die kommende Veranstaltung bewerben!

**Titel:** Fusion 360 Seminar für Einsteiger/Anfänger 

**Leiter & Helfer**:  Luca (lmnl99)

**Datum & Zeit:**  Samstag der 17.08.24 14-17Uhr

**Teilnehmerzahl:** 15

**Zielgruppe:** An alle Mitglieder und Externen die gerne die Grundfunktion von Fusion 360 (CAD Programm) kennen Lernen möchten. 

**Kosten:** 0€

**Beschreibung:**  Erklärung in das CAD Programm Fusion 360. In diesem Seminar geht es um das erstellen einer Skizze und einfacher Geometrien.  Das Seminar wird auf Deutsch gehalten.

**Fotos:** *fehlen noch! Vorschläge willkommen :-)*

## Werbung - ToDo:

* hier können alle helfen:
  * [x] Wiki-Seite ([Category:Seminars](https://wiki.comakingspace.de/Category:Seminars)) --> bereits existierende anpassen: https://wiki.comakingspace.de/Autodesk_Fusion_Seminar
  * [x] [Slack](https://wiki.comakingspace.de/Slack)
  * [x] [Telegram-Gruppe](https://wiki.comakingspace.de/Telegram_Group)
  * [x] "Maker Community HD" WhatsApp-Gruppe
 

* von der [Geschäftsführung](https://wiki.comakingspace.de/Management) oder anderen Ehrenamtlichen mit Zugang zu erledigen:
  * [x] Anmeldelink: [Nextcloud-Umfrage](https://cloud.comaking.space/apps/polls/s/xvWjbKkE)
  * [x] Google-Kalender
  * [x] Meetup
  * [x] Facebook-Event
  * [ ] Post auf Facebook/Instagram
  * [ ] weitere Kanäle?

**Comment by LukasFreeze** [comment]
Anmeldelink: https://cloud.comaking.space/apps/polls/s/xvWjbKkE

**Comment by LukasFreeze** [comment]
Facebook: https://www.facebook.com/events/1180594413261412/

Bitte fleißig teilen, wenn ihr dort aktiv seid!

**Comment by LukasFreeze** [comment]
es haben 4 Leute teilgenommen wenn ich mich nicht irre; @lmnl99 möchte als nächstes noch einmal das gleiche Thema außerhalb der Urlaubszeit wiederholen und dann ein Fortgeschrittenen-Seminar mit Bezug zum CAM (für CNC-Fräsen) anbieten
