### ISSUE TITLE
"neue" Laser-Absaugung

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#319]
Wir haben eine professionelle Absaugung dazubekommen, die einen besseren Volumenstrom als unsere bisherige Absaugung haben dürfte. Zum Einbau sind noch ein paar Schritte notwendig:

- [x] Dichtung am oberen Filtereinsatz erneuern (@lmnl99 )
- [x] Adapterbox für unseren Schlauch am Laser bauen (bisher @Johannes09 @LukasFreeze @lmnl99 )
- [x] Adapter für den Schlauch Auslass drucken (Freiwillige vor!)
- [x] Fernbedienung reparieren/ersetzen
- [ ] Geräteseite im Wiki

**Comment by LukasFreeze** [comment]
@Johannes09 cool dass das Ding schon läuft, wie du auf slack geschrieben hast 😍

Was muss man zum Gerät wissen? Hat die Fernbedienung einfach neue Batterien gebraucht oder wurde sie irgendwie ersetzt?

**Comment by Johannes09** [comment]
nichts 😉.
Es gibt keine änderrung am Arbeitsablauf.

**Comment by LukasFreeze** [comment]
https://wiki.comakingspace.de/Laser_Exhaust_System
