### ISSUE TITLE
Elektronik-Spende wegsortieren

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#326]
![20241114_014150](https://github.com/user-attachments/assets/c8f87d24-fa89-469d-9337-c95b236de5a2)
Wir haben einen Keller voll Elektronik "geerbt" - danke nochmal @lmnl99 und @Erik1000 fürs Abholen!

Der große Tisch im Gemeinschaftsraum ist nach dem ersten Sichten nun nicht mehr komplett belegt - manches taugt wohl nur noch zur Entsorgung (Ikea-Tasche beim Holzabfall), einiges konnte auch schon einsortiert werden.

Für den Rest braucht es vor allem nochmal Leute, die mehr Ahnung haben als ich - zB habe ich schonmal alle ICs die mir über den Weg liefen auf einen Stapel gepackt, weiß aber nicht ob das Müll ist (zu spezifisch?) oder für uns verwendbar.

**Comment by LukasFreeze** [comment]
(Vorher:)
![20241113_183309](https://github.com/user-attachments/assets/e0e0c3f7-634e-4b8b-b385-cdd837c49650)

**Comment by Johannes09** [comment]
Ich habe den Tisch freigeräumt und die brauchbaren Sachen in den E-Room gelegt.

**Comment by Erik1000** [comment]
Die ältere Dame kam heute nochmals vorbei und hat zwei neue Taschen mitgebracht. Außerdem sucht sie eine rechteckige Radioantenne, die wohl bei den Sachen der ersten Spende dabei gewesen sein soll (ich hatte sie nicht wahrgenommen)

**Comment by Erik1000** [comment]
![image](https://github.com/user-attachments/assets/82711532-28d2-4f63-a5cb-7c662b851158)

**Comment by Johannes09** [comment]
Ich habe keine Radioantenne gesehen.

**Comment by Erik1000** [comment]
Ist alles weggeräumt
