### ISSUE TITLE
Einhell Herkules HMB 4000 – Bandsägeblatt defekt  

### ISSUE THREAD

**Issue by Johannes09** [comakingspace/do-something#329]
Problem:  
Das Bandsägeblatt der horizontalen Bandsäge **Einhell Herkules HMB 4000** ist defekt und muss ersetzt werden, um den Betrieb der Maschine wiederherzustellen.  

To-Do-Liste:  
- [x] Analyse @Pakue95 
    - Herausfinden, welches Ersatzteil genau benötigt wird.  
- [x] Beschaffung @Johannes09 
- [x] Wareneingang  @Johannes09 
   - Lieferung überprüfen und in den Space legen.  
- [x] 4. Reparatur 
- [x] 5. Testen
- [x] 6. Dokumentation und Freigabe @Johannes09 
    - Reparatur in **SnipeIT** dokumentieren.  
    - issue schließen

**Comment by Johannes09** [comment]
Das Sägeblatt kommt wahrscheinlich am 6. Dezember an.

**Comment by Pakue95** [comment]
Sägeblatt ist ausgetauscht und funktioniert. 
@Johannes09 schließ das issue gerne wenn du mit der Doku durch bist.
