### ISSUE TITLE
Network settings

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#33]
We got a new raspberry pi for the music station, which needs to be reflected in the DHCP Settings of the Router.
In Addition, the Laser printer is now part of the network again and should also get a static IP.

**Comment by emka** [comment]
Olaf should still be able to access the settings. Otherwise I can figure out how to do it as well.
Could you post the relevant MAC addresses and desired IP address here?

**Comment by NitramLegov** [comment]
Olaf adjusted the settings today. The documentation is updated accordingly.
