### ISSUE TITLE
Beginner sewing workshop Kirschkernkissen

### ISSUE THREAD

**Issue by Titan-OX** [comakingspace/do-something#332]
**Name**:Kirschkernkissen nähen workshop

**Presenter & helpers**:Luzian

**Date & time**:14.12 or 15.12 time: tbd

**Description**: *Want to learn the basics of sewing and get microwave heatable hot pillow? Or do you just need a last minute Xmas gift? This will be basic and easy workshop suitable for beginners*

**Rooms**: *Common room*

**Tools**: Sewing machines. We have 2 working machines in the space. I can lend my overlock machine (already in the space) and Keno has volunteered his machine. 

**Materials to buy**: 
I have all necessary materials at home and could bring them as a backup in case the delivery does not arrive on time.
- [x] https://www.amazon.de/Konen-Overlockgarn-Wei%C3%9F-Lialina%C2%AE-Meter/dp/B00J7MK9HG 12€ (for the overlock machine but can be used on other machines as well)
- [x] https://www.amazon.de/10kg-lose-gereinigte-Kirschkerne-Kirschkernkissen/dp/B08298D68P 25€/10kg
- [x] https://www.amazon.de/Dinkelkerne-5-kg/dp/B009MMRQJK/262-9540447-2578345 (optional) 14€/5kg
- [x] https://www.amazon.de/aufodara-Baumwollstoff-Stoffpaket-vielf%C3%A4ltige-Baumwolltuch/dp/B08FDFWRW3/262-9540447-2578345 11€
- [x] https://www.amazon.de/aufodara-Baumwollstoff-Stoffpaket-vielf%C3%A4ltige-Baumwolltuch/dp/B08FDF8R5R/262-9540447-2578345 11€

## Advertisement ToDo:

* to be done by a [manager](https://wiki.comakingspace.de/Management):
  * [ ] Eventbrite page (if there are tickets) // Nextcloud "signup" poll (if there are no tickets)
  * [ ] calendar entry
  * [ ] [Meetup](https://www.meetup.com/de-DE/Heidelberg-Makers-Meetup/)
  * [ ] [Facebook](https://www.facebook.com/comakingspace/)
  * [ ] [Instagram](https://www.instagram.com/comakingspace/)
  * [ ] [Twitter](https://www.twitter.com/comakingspace/)
  * [ ] *if there's time:* announce in the next newsletter (@LukasFreeze)
  * [ ] *if there's time:* [Rhein-Neckar-Zeitung](https://www.rnz.de/kontakt/redaktionen.html)

* help welcome:
  * [ ] event wiki page ([Category:Seminars](https://wiki.comakingspace.de/Category:Seminars))
  * [ ] announce via [slack](https://wiki.comakingspace.de/Slack)
  * [ ] announce in the [Telegram Group](https://wiki.comakingspace.de/Telegram_Group)
  * [ ] announce in "Maker Community HD" WhatsApp Group
  * [ ] add to [https://www.heidelberg.de/hd,Lde/HD/Erleben/veranstaltungskalender.html Heidelberg.de Veranstaltungskalender]
  * [ ] add to [https://www.heise.de/make/kalender/new_event/ Make: calendar]
  * [ ] *if there's time:* Poster (to be hung up by the city)

## General considerations 
- what's the name/idea/purpose of the event?
- (if at the Space) is there permission from the [management](https://wiki.comakingspace.de/Management)?
- is there a fixed date and time yet?
- is there a registration deadline (if yes, please include a link to the form)?
- how many people are needed to organize it on the day of the event?
- are there any concrete tasks to be done in advance?
- what part of the work would you take over?

*to make sure your idea is visible, you should also share this "issue" via slack and/or Telegram and ask for help there!*
![2024-11-22-17-20-16-914.jpg](https://github.com/user-attachments/assets/90d884dd-ee09-4ed9-9ba5-abb9441c7db6)

**Comment by NitramLegov** [comment]
**What a great idea!** I love seeing how workshops in the Makerspace are gaining momentum—it’s exciting to see such creative energy!

At the same time, I think next Saturday might be a bit short notice to ensure the workshop is a smooth and enjoyable experience for everyone. Here are a few thoughts and considerations:

- **The cold temperatures in December:** The space can be quite chilly, and sewing is an activity that’s much more comfortable in a warmer environment.
- **Equipment readiness:** We currently have only one commissioned sewing machine. If we want to include the Brother machine from the office, we’d need to commission it first. I believe @Johannes09 is still waiting for some details, like the serial number, to document it in the asset management system.
- **Advance notice for participants:** Many people appreciate more time to plan ahead for workshops. A lead time of at least a month would help us attract more participants and potential helpers.
- **Limited management capacity:** While we’re always eager to support workshops, organizing one with such short notice can be challenging for everyone involved.

Regarding the workshop itself, I’m really looking forward to seeing it come together! To help with the planning, here are a couple of questions and ideas:

- Could you expand the workshop description a bit? This guide might help: [Event Description Guide](https://wiki.comakingspace.de/Event_Ideas#Short_Overview_(1%E2%80%932_Paragraphs)).
- What’s the maximum number of participants you’d like to accommodate?

**Here’s my proposal:** Let’s plan this workshop for late Q1 or early Q2 2025. This would give us:

- More time to prepare everything, making the planning process smoother and more enjoyable.
- The chance to explore options for additional sewing machines, which could make this workshop a regular feature at the Makerspace!

I’m really excited about the idea of a sewing workshop and want to help make it a success. With a bit more time and preparation, I’m sure it will be a fantastic experience for everyone! 😊

**Comment by Titan-OX** [comment]
**Description updated:** Want to learn the basics of machine sewing and get microwave heatable hot pillow (Kirschkernkissen? Or do you just need a last minute Xmas gift? This will be basic and easy workshop suitable for beginners. Choose one or more provided colorful fabrics or bring your own. 

Whats included:
-an assortment of colorful cotton fabrics
-cherry seeds for at least one big pillow
-thread

What you will learn:
-how a sewing machine works
-how to load the thread and how to operate it
-how to create neat seams

Fee: 5€ per person (should recoup the cost of the consumed materials but not the full amount ordered.)

**Comment by Titan-OX** [comment]
I can host 5 people alone and offer one workshop from 10-12 and a second one from 12:30-14:30
I know it's cold in the space but we are still open for making hours and I would like to advertise it as a Xmas workshop. This would not be a long workshop as the process is quite simple. With a hot drink to keep your hands warm it should be reasonably comfortable. Sewing in the cold is about as bad as typing, it is not brain surgery or watchmaking.

**Comment by Johannes09** [comment]
Nächstes Wochenende ist leider etwas knapp. Ich brauche eigentlich zwei Wochen Vorlauf für Bestellungen. Ich kann dir aber anbieten, das Zeug direkt zu dir zu schicken. Dann ist es gleich bei dir. 

Die zweite Nähmaschine, die der Space hat, kann leider noch nicht benutzt werden, da sie noch nicht in Betrieb genommen wurde und ich vor dem Termin nicht mehr im Space sein werde. Wir hätten das gestern machen können, aber dafür hätte ich etwas mehr Zuarbeit gebraucht.

**Comment by Titan-OX** [comment]
![Drawn picture of a sewing machine with light brown seeds and small colorful pillows next to it  Xmas colors](https://github.com/user-attachments/assets/0b0a3ad5-6521-4a2c-8305-33f3220651d1)

15.12.24 10:00-12:00 & 13:00-15:00 up to 5 people per slot.

How much do we charge is up to the managers.

**Comment by NitramLegov** [comment]
Thank you! With the updated information I was able to add the Seminar to our calendar! You can find it on Sunday:
![image](https://github.com/user-attachments/assets/add3dd79-f380-4494-803f-e59e1441b3af)

To describe the calendar entry, I have used the description you have provided with an information on how to sign up and participate: 

> Want to learn the basics of machine sewing and get microwave heatable cherry-pit-pillow (german = Kirschkernkissen)? 
> 
> Or do you just need a self-made last minute Xmas gift? This will be a basic and easy workshop suitable for beginners. Choose one or more colorful fabrics provided by us or bring your own.
> 
> What´s included:
> - an assortment of colorful cotton fabrics
> - cherry seeds for at least one big pillow
> - thread
> - different sewing machine types (though you can't take them home)
> 
> What you will learn:
> - how a sewing machine works
> - how to load the thread and how to operate it
> - how to create neat seams
> 
> 
> 
> Please note that this workshop is targeted at members and seats are limited. If you want to participate, let Luzian know on our internal communication platforms.


@Titan-OX Unfortunately, the workshop is planned with very little preparation time. Since management capacity is limited at the moment, we will not be able to provide you with a Ticket Shop via pretix or a signup form via Nextcloud. 
Therefore, possible participants are asked to contact you on the known communication channels and we have indicated that the workshop is members-only :)

Please let me know if you would like to add more specific means of contacting you.

As per the costs: The workshop will be free of charge :)

**Comment by Titan-OX** [comment]
The language around it being members only is very soft. Does this mean that members can invite others? Like book a spot for a friend or family member? Currently no one booked so I don't think it will take slots from members

**Comment by NitramLegov** [comment]
The language around members only was chosen to avoid extra effort for sign-up or advertisment :)

If somebody brings a friend or family member or you have somebody in mind who is not a member - feel free to let them join. However, please note they would not be able to maintain the list in the wiki. And since the wiki is public, you should not put their names in there due for data protection reasons.

**Comment by Titan-OX** [comment]
The seminar was a success. We had 5 students and made just shy of 10 pillows while learning how to operate and troubleshoot a sewing machine.
