### ISSUE TITLE
Oberfräse verfügbar machen

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#35]
Die zweite Oberfräse ist inzwischen dokumentiert und kann in den Woodworking workshop. Steht aktuell bei Lukas auf der Werkbank

**Comment by LukasFreeze** [comment]
fast - nicht auf meiner Werkbank, sondern auf der mit den "unfertigen"
Geräten (CoMaking-Raum rechts hinten) :-)

**Comment by NitramLegov** [comment]
Done
