### ISSUE TITLE
Bosch-Stichsäge

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#36]
Ich habe seit ein paar Wochen eine Stichsäge, die ich gerne in der Holzwerkstatt verfügbar machen würde, aber bisher kam ich noch nicht dazu.

To do:
- [x] Infobox mit Bild und Bedienungsanleitung zur Wiki-Seite [Jigsaws](https://wiki.comakingspace.de/Jigsaws) hinzufügen
- [x] Sicherheitscheck (keine lockeren Kabel etc.) durch @beanobeano, @emka, @Pakue95 oder mich
- [x] Funktionstest (ggf. Bemerkungen im Wiki) durch irgendwen mit Stichsägeneinweisung

**Comment by NitramLegov** [comment]
Added the commissioning template to the wiki page

**Comment by NitramLegov** [comment]
Die ist doch inzwischen fertig commissioned, oder? Kann man hier zumachen?

**Comment by LukasFreeze** [comment]
stimmt, im Wiki & vor Ort erledigt aber hier vergessen! :+1:
