### ISSUE TITLE
Handheld router Ferm FBF-1050E is faulty and broken

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#37]
It needs to be repaired. We put it back on the defect tools workbench

**Comment by LukasFreeze** [comment]
Any idea what is broken? Did it stop turning, or does something mechanical
not work anymore?

**Comment by NitramLegov** [comment]
Sorry, I just opened the issue real quick earlier to have it documented and then we moved on with other things ;) A piece of the router mechanically broke apart. It is needed in order to properly tighten the bit.
I found a drawing of the different parts of our router here:
https://der-rasenmaeher.de/bilder/ferm/20050FBF-1050EPRM1006.pdf
The broken piece is number 53.

The original part does not look like a high quality part to be honest. My proposal would therefore be to try to make our own replacement (maybe out of aluminium, which most likely is of better quality than the stuff ferm used...

**Comment by LukasFreeze** [comment]
No worries, I just wanted to make sure it's not forgotten in case we can't
get to it soon :-)

In order to generally improve the tool repair progress I think we should
move all tools that have an issue assigned to a clear and accessible spot.
I was thinking about the "ladder shelf" in the woodshop that is half empty
now that some measuring tools are on the walls (#30)

**Comment by NitramLegov** [comment]
Opened issue #38 for this 😅

**Comment by drei85** [comment]
Einer der Kabelbinder ist gebrochen, sodass ein Plastikteil der Spindelverriegelung gebrochen ist. Ich habe versucht das Plastikteil zu kleben und das Metallgehäuse wieder mit Kabelbinder zusammen zu halten. Das geklebte Plastikteil habe an die Maschine geklebt und an den Platz für defekte Werkzeuge gestellt.

Auf dem Heimweg kam mit die Idee, ob es eventuell möglich ist das defekte Metallgehäuse und den Mechanismus der Spindelverriegelung komplett zu entfernen, das Gewinde am vom Fräser entfernten Teil an zwei gegenüberliegenden Seiten mit einer Feile abzuflachen, sodass das Gewinde beim Fräserwechsel mit einem Schraubenschlüssel festgehalten werden kann.

**Comment by LukasFreeze** [comment]
@drei85 das hier ist die Fräse, die ich in #105 meinte und mit der wir experimentieren könnten - wir haben sie zweimal, eine womöglich reparable auf dem Leiterregal und eine komplett zerstörte im Lager. Bist du Mittwoch da? Dann könnte ich die mal rausholen!

**Comment by LukasFreeze** [comment]
Handheld router Ferm FBF-1050E is repaired and fixed

**Comment by LukasFreeze** [comment]
noch ein Foto zur Vollständigkeit (ich habe nichts weiter zerbrochen, der Kragen **war** so kaputt):

![IMGP4482 (Medium)](https://user-images.githubusercontent.com/19755883/55170499-f5013a80-5176-11e9-85e1-80032bd1c29b.JPG)
