### ISSUE TITLE
Move tools to be repaired to an accessible spot

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#38]
Possibly in the wood workshop? Lukas suggested the ladder shelf which used to hold measurement tools.

**Comment by LukasFreeze** [comment]
We cleared out the shelf tonight and I brought the Ferm router (#37) there before I left.
Other tools and some clear signage along the lines of "broken - can you help to fix anything? - please post progress (also unsuccesful attempts!) in the issue tracker" still need to be added.

**Comment by LukasFreeze** [comment]
Sollte erstmal so passen :-)
