### ISSUE TITLE
soldering fume extraction

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#39]
We need something to take care of harmful soldering fumes.

I like [this idea on Make: Projects](https://makezine.com/projects/re-purposed-power-supply-fume-extractor/), what do you think?

Does anyone have an old PC power supply with a big fan to spare?

**Comment by NitramLegov** [comment]
I have old PC fans at home.

Von: Lukas
Gesendet: Freitag, 6. Juli, 12:05
Betreff: [comakingspace/do-something] soldering fume extraction (#39)
An: comakingspace/do-something
Cc: Subscribed


We need something to take care of harmful soldering fumes.
I like this idea on Make: Projects<https://makezine.com/projects/re-purposed-power-supply-fume-extractor/>, what do you think?
Does anyone have an old PC power supply with a big fan to spare?

**Comment by Pakue95** [comment]
We have a bunch of 12V fans in the eRoom which could be used for something like this. I think even without activated carbon this would help to get the fumes away.

**Comment by LukasFreeze** [comment]
@Johannes09 hat damit angefangen, die Dämpfe nach draußen zu leiten. Genauen Status kenne ich nicht, könnte aber ein paar Festplattengehäuse für einen schweren Standfuß am flexiblen Rohr stiften :-)

**Comment by NitramLegov** [comment]
We got two new soldering fume extractions which are also documented in the [wiki](https://wiki.comakingspace.de/Soldering_Fume_Extraction).
