### ISSUE TITLE
Drehbank (Metall) einrichten

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#4]
Wir haben eine alte Drehbank, die mittlerweile fast einsatzbereit ist! Hier kümmern wir uns um die letzten Schritte:

- [x] Drehstromanschluss
- [x] Schmierung
  - [x] erste Schmierung mit Getriebeöl
  - [x] Hydrauliköl für die Lager besorgen (?)
  - [x] Gleitbahnöl besorgen
  - [x] fehlende Ölnippel und Fettpresse besorgen (sind bestellt)
- [x] ~~*eventuell* Riemenspannung erhöhen (zwei Stellschrauben justieren)~~
- [x] Drehstähle besorgen
- [ ] ~Futterschlüssel mit Spiralfedern sicherer machen: s. [z. B. hier](http://www.hgkoenig.de/tipps-fuer-drechsler/109-futterschluessel)~ **verschoben nach #70**
- [x] Dokumentation im Wiki
  - [x] Drehstähle ([Tool Bits](https://wiki.comaking.space/index.php?title=Tool_Bits&action=edit&redlink=1))
  - [x] Zentrierbohrer
  - [x] Accessoires wie Bohrfutter/Mitlaufkörner erwähnen
  - [x] Sicherheitseinweisung

**Comment by LukasFreeze** [comment]
@beanobeano und ich waren heute im Bauhaus und haben Fett für die Lager mitgebracht - @Pakue95, kann man das jetzt einfach in die Reservoire füllen oder ist da noch etwas zu beachten?

**Comment by Pakue95** [comment]
Sicher das es Fett ist? Normalerweise sollte Öl in die Reservoirs.

**Comment by LukasFreeze** [comment]
Jan hatte "Fett" gesagt glaub ich, gibt natürlich immer verschiedene
Auslegungen von Wörtern aber wir hatten uns beraten lassen und dann das
bekommen.

Ist ein riesiges Lager auf der Tube, aber wenn es nicht gut genug fließt
kaufen wir eben noch was anderes und nehmen das Fett für die CNC-Fräse -
u.a. deshalb habe ich es jetzt nicht einfach eingefüllt sondern rumgefragt
:-)

**Comment by LukasFreeze** [comment]
Vielleicht kann André uns helfen, wenn er am Samstag vorbeikommt. Das Fett ist jedenfalls mit Sicherheit zu dickflüssig...

**Comment by LukasFreeze** [comment]
Ich hab etwas recherchiert - Drehbänke mögen wohl ganz normales Getriebeöl. 

Hier die "offizielle" Empfehlung vom Hersteller: https://www.myford.co.uk/acatalog/VG32-LUBRICATING-OIL---ESSO-NUTO-32---1-LITRE-662.html

Außerdem ein evtl hilfreicher Forum-Thread: http://forum.zerspanungsbude.net/viewtopic.php?f=43&t=12985

**Comment by LukasFreeze** [comment]
Ich hab ca. einen Liter 90er Getriebeöl von meinem Opa bekommen, das ist etwas viskoser als von Myford empfohlen aber dürfte nichts ausmachen. Wenn das ganze später mit dünnerem Öl gemischt wird ist das auch kein Problem :-)

Hat jemand Spritzen oder so womit man das einfüllen könnte?

**Comment by Pakue95** [comment]
Kann welche aus der Apotheke holen.

**Comment by LukasFreeze** [comment]
Ich habe gestern Abend ein paar ml Öl in die Reservoirs gefüllt und die [Wiki-Seite](https://wiki.comaking.space/Metalworking_Lathe) um ein paar Zeilen erweitert.

Leider scheint das linke Teil etwas undicht zu sein, das müssen wir uns nochmal ansehen...

Außerdem fehlt uns eine Ölspritze ("oil gun", Link s. Wiki) mit der man die diversen Ölnippel an der Maschine befüllen kann. Kennt sich damit jemand aus? Die von Myford empfohlene ist ganz schön teuer!

**Comment by LukasFreeze** [comment]
Das linke Ölreservoir ist kein Originalteil und wurde durch die schon angeschnittene Getriebeabdeckung etwas zur Seite gedrückt, deshalb vermutlich das Leck. @Henrik99 hat sich letzte Woche darum gekümmert und die Stelle etwas weiter aufgeflext, sodass es jetzt gerade so passt.

Zu den Nippeln (besserer Suchbegriff als "Ölnippel": **Schmiernippel**) habe ich noch ein bisschen recherchiert, @ragflyer und mir sind an verschiedenen Stellen fehlende aufgefallen und wir müssen wohl welche nachbestellen... Statt neuen englischen dürften welche mit metrischem Gewinde sinnvoller sein, das müsste man dann allerdings an der Maschine neu schneiden - Meinungen? M6 sollte gehen, laut Wikipedia haben die jetzt verwendeten "2BA"-Gewinde einen Außendurchmesser von 4,7 mm. Die gäbe es z.B. [hier](https://www.fk-soehnchen.de/werkstatt/werkstattbedarf/fettpressen-zubehoer/schmiernippel/Kegelschmiernippel-DIN-71412.html) für wenig Geld.

Auf der gleichen Seite gibt es auch **Fettpressen** (weitaus besserer Suchbegriff als Ölspritze, falls es schon jemand versucht hat...), die schon bei 5 € losgehen. Ich bin geneigt, es einfach mal zu riskieren und [so eine](https://www.fk-soehnchen.de/werkstatt/werkstattbedarf/fettpressen-zubehoer/fettpressen/Profi-Stosspressen.html) zusammen mit den Nippeln zu bestellen :-)

https://de.wikipedia.org/wiki/Schmiernippel (EN: https://en.wikipedia.org/wiki/Grease_fitting)
https://en.wikipedia.org/wiki/Grease_gun_(tool)

**Comment by LukasFreeze** [comment]
Ich habe noch einen interessanten Thread zur Schmierung gefunden - der Autor rät allerdings leider von unserer Öl-Wahl ab, weil Getriebeöl Schmutz in der Schwebe hält und nicht, wie in solchen alten Maschinen vorgesehen, absinken lässt :-/ [Zerspanungsbude.net](http://forum.zerspanungsbude.net/viewtopic.php?t=28514)

Jedenfalls eine interessante Lektüre! Wenn wir uns dafür entscheiden, das zu glauben, sollten wir Hydrauliköl für die Lager besorgen und das jetzige auswaschen. Für die Gleitbahn nimmt man wohl spezielles Gleitbahnöl, das haben wir auch noch nicht!

**Comment by LukasFreeze** [comment]
Ich habe mal eine Wiki-Seite angefangen ([die hier](https://wiki.comaking.space/Metal_Lathe)) und da ein paar weitere interessante Websites verlinkt, z.B. einen Restaurationsbericht eines Engländers und mehr Informationen, als auf der Herstellerseite zu finden waren :-)

**Comment by LukasFreeze** [comment]
Fettpresse und Schmiernippel sind bestellt, wir werden versuchen mit einem Sackloch-Gewindeschneider das ganze auf M6 umzustellen...

**Comment by Pakue95** [comment]
Die Schmiernippel haben Lukas und ich heute eingebaut (M6 europäisch). Die Lager und Gleitbahn sind mit dem Motoröl geschmiert; ggf. kann man das durch Hydrauliköl in der Zukunft austauschen, aber mittelfristig sollte das kein großes Problem sein.

Uns ist aufgefallen, dass im zweiten Motorgang (schnellste Übersetzung) der Riemen etwas lose ist und dabei Geräusche macht. Es gibt zwei Stellschrauben an denen man die Riemenspannung einstellen kann. Vor der ersten Benutzung sollte man diese richtig einstellen.

**Comment by Pakue95** [comment]
Hier eine mögliche Quelle für Drehstühle und andres Zubehör: [hier](https://www.paulimot.de/rund-ums-drehen/)

**Comment by LukasFreeze** [comment]
Was die "richtige" Riemenspannung angeht: im Zusammenhang mit Drechselmotoren habe ich den Tipp gelesen, lieber etwas zu wenig Spannung zu haben, damit der Riemen im Notfall rutscht und nicht sonstwas mit dem verkanteten Werkzeug angestellt wird - ich finde das sinnvoll und schlage vor, die Spannung nur zu erhöhen falls wir im Betrieb dadurch Probleme bekommen.

**Comment by Pakue95** [comment]
Ok.

Die Drehstähle die wir brauchen sind 8mm groß. Ich werde mir mal ein [günstiges HSS Set](https://www.paulimot.de/rund-ums-drehen/drehstaehle-sets/hartmetallbestueckt/99/drehstahl-satz-drehmeissel-set-11-teilig-mit-hartmetallplatten-p30-din4976-8-x-8-mm?c=125) besorgen zum Testen.

Eine Zentrierspitze und das passende Bohrfutter brauchen wir auch noch. Der Morsekegel hat einen Eingangsdurchmesser von 17,5 mm also ein 18 mm Kegel sollte passen. Passendes [Bohrfutter](https://www.paulimot.de/bohrfutter/mit-austreiblappen/27/schnellspann-bohrfutter-1-13-mm-mk2) und [Zentrierkegel](https://www.paulimot.de/rund-ums-drehen/koernerspitzen/206/mitlaufende-koernerspitze-zentrierspitze-mk2).

Jan hat den Motorschutzschalter ebenfalls eingebaut, daher sollte alles essenzielle an der Drehbank gemacht sein.

**Comment by LukasFreeze** [comment]
Laut Johannes brauchen HSS-Drehstähle Kühlung, welche mit
Hartmetall-Wechselplatten nicht...wären die höheren Kosten meiner Meinung
nach also wert.

Bevor wir sie dann richtig öffentlich machen sollten wir noch über eine
Feder am Futterschlüssel (gegen versehentliches Steckenlassen) und
Schutzhauben für das Spannfutter und die gesamte Drehachse nachdenken, aber
ich bin auch dafür jetzt mal etwas einfaches zu testen

**Comment by Pakue95** [comment]
Im Zweifel reicht auch etwas Schneideöl zum testen. HSS muss man kühlen damit die Härtung des Stahls nicht rückgängig gemacht wird. Bei manchen Aluminium Legierungen können auch bei Hartmetall Schwierigkeiten machen wenn sie nicht gekühlt werden, da sich das Aluminium auf der Schneide ablagert.

**Comment by LukasFreeze** [comment]
Dann lass dich von mir nicht aufhalten ;-)

**Comment by Henrik99** [comment]
Ich hab mal bei meinem lieblings Shop gestöbert und einige Sachen für die Maschine gefunden:
Wendeschneitplatten mit Haltern:  http://s.aliexpress.com/aYbqMrQV?fromSns
Ersatz Platten für die Halter: 
 http://s.aliexpress.com/Z7ZjQrIR?fromSns
Ich weiß halt nicht wie gut das hartmetall ist aber der Preis ist gut. 

Ich werde auch mal  in der Arbeit fragen  ob ich aussortierte Sachen für die Drehmaschine  mitnehmen kann.

**Comment by LukasFreeze** [comment]
@Pakue95 hat einige Drehstähle mit Wendeplatten gestiftet und auch schon erste Versuche mit dem Selberschleifen von HSS-Meißeln gemacht.

Wenn es zu den Drehstählen ein paar grundlegende Infos im Wiki gibt (["Tool Bits"](https://wiki.comaking.space/index.php?title=Tool_Bits&action=edit&redlink=1)), sollten wir uns bald um die Einweisung und damit um die "Öffnung" der Maschine für Mitglieder kümmern können.

**Comment by Pakue95** [comment]
Am Wochenende habe ich mal die beiden Achsen des Werkzeugschlitten auseinandergenommen, gereinigt und geschmiert. Jetzt sind beide Achsen wieder leichtgängig und das Spiel aus der Radius-Achse ist deutlich geringer.

**Comment by NitramLegov** [comment]
Added the commissioning template.

**Comment by Pakue95** [comment]
Hat jemand was dagegen wenn ich das Issue zu mache? Die Futterschlüssel Feder fehlt noch, aber die Schweißecke (#10) wird noch etwas dauern und die Feder ist meiner Meinung nach kein essentielles Teil zur Nutzung der Drehbank.

Der Futterschlüssel würde dann in ein neues Issue gehen.

**Comment by LukasFreeze** [comment]
Wenn ein neues Issue mehr Überblick schafft, warum nicht? Hauptsache, die
Dreher behalten es im Auge und priorisieren es, sobald es geht :-)

2018-09-20 16:36 GMT+02:00 Patrick <notifications@github.com>:
