### ISSUE TITLE
replace broken scale battery

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#40]
Luca brought us a nice old [scale](https://wiki.comakingspace.de/Scale) that is already usable with a power supply but has a broken battery pack. Apparently, a new original pack costs 80 € which is ridiculous...

If we think it's worth the effort:
- [ ] figure out battery specs
- [ ] make a replacement out of suitable cells (perhaps the charging controller will need an upgrade as well?)

**Comment by lmnl99** [comment]
Habe heute die alte Batterie ausgebaut, und eine neue eingebaut. Die Wage funktioniert wieder ohne Netzteil.
