### ISSUE TITLE
small laser printer

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#41]
Moritz brought us a small HP LaserJet P1102w. There are some issues with it that should be addressable:

 - the rolls wrinkle the paper (too tight?)
 - the toner leaves smears along the length of the page

**Comment by Titan-OX** [comment]
Is this still an issue?

**Comment by NitramLegov** [comment]
In the meantime, we are using the same type of printer as our office printer.

If the office printer fails at some point, we can use this one for spare parts. However, I would not see the need for repairing it :-)
