### ISSUE TITLE
Einstellungen der CNC-Fräse online sichern

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#45]
Irgendjemand oder (hoffentlich...) irgendeine Software hat letzte Woche einen Haufen Einstellungen der CNC-Fräse verändert, sodass sie so gut wie gar keine Befehle mehr angenommen hat bis wir endlich dahinter gekommen sind, was los war.

schlechte Einstellungen (abgerufen mit $$):
$0=10
$1=25
$2=0
$3=0
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=1
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$100=250.000
$101=250.000
$102=250.000
$110=500.000
$111=500.000
$112=500.000
$120=10.000
$121=10.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000

korrigierte Einstellungen (nach Handbuch & @emka s Anpassungen:
$0=10
$1=255
$2=0
$3=3
$4=1
$5=0
$6=0
$10=1
$11=0.020
$12=0.002
$13=0
$20=1
$21=0
$22=1
$23=0
$24=100.000
$25=1000.000
$26=250
$27=3.000
$30=1000
$31=0
$32=0
$100=26.667
$101=26.667
$102=200.000
$110=10000.000
$111=10000.000
$112=10000.000
$120=150.000
$121=150.000
$122=150.000
$130=1300.000
$131=1270.000
$132=120.000

Ihr seht also, da ist einiges verkehrt gewesen, unter anderem die Schritte pro mm und die Ausrichtung(?) der Motoren...ziemlich kritisches Zeug und wir hatten Glück, dass die Fräse gar nichts gemacht hat und nicht gecrasht ist.

@emka hatte vorgeschlagen, ein Skript zu schreiben, das irgendwie vor jedem Start der Fräse abgleicht ob die aktuellen Einstellungen den bewährten entsprechen. Änderungen wären hier im Github-Repository natürlich weiterhin möglich, aber nicht völlig willkürlich und vor allem nicht mehr versehentlich.

- [x] bewährte Einstellungen ins Repo stellen -> https://github.com/comakingspace/WorkBee/blob/master/settings.txt
- [ ] Details zum Skript austüfteln

**Comment by LukasFreeze** [comment]
Oh, was mir gerade noch einfällt: zu $110-112 sind die Anmerkungen im Handbuch nicht ganz klar, da steht jeweils 10000 aber dann sowas wie "go up to 7500" - weiß jemand Bescheid?

**Comment by NitramLegov** [comment]
Wenn ich mir das hier im Handbuch anschaue ist es wohl gar keine so schlechte Idee, die settings bei jedem start zu prüfen...oO
![image](https://user-images.githubusercontent.com/7809163/42526078-21281356-8475-11e8-8bfb-58f1f041ed7e.png)

**Comment by LukasFreeze** [comment]
Zu $110-112 habe ich meine Notizen wiedergefunden und sie [in settings.txt auf 4000 (110 & 111) bzw. 1500 (112) reduziert](https://github.com/comakingspace/WorkBee/commit/90dcbb9fdff4de500ea1d161995c7c87b4c8b4d3). *Sollte* in der Fräse auch schon so sein.

**Comment by NitramLegov** [comment]
Mögliche Punkte zur automatisierung:
- udev Regel, die das python script ausführt, sobald die Fräse da ist
- CNCjs bietet events, die man entsprechend nutzen kann, um aktionen zu triggern: https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-Recording-Triggered-by-Events

**Comment by emka** [comment]
Das Skript zum prüfen der Unterschiede ist jetzt auch im WorkBee repository. Martin schlägt vor, diese Dateien in das GcodeSender repo umzuziehen.
Das Skript lässt sich leicht erweitern, um z.B. die Einstellungen automatisch zu überschreiben (ich würde vorschlagen mit einem optionalen Argument ```--override```).

**Comment by NitramLegov** [comment]
![image](https://user-images.githubusercontent.com/7809163/42688450-8f2939a6-869c-11e8-8b4b-bcffe04bd579.png)
Das sind die verfügbaren Events von CNCjs. Denke da lässt sich was finden. Dann müssen wir nur noch entscheiden, ob die settings auch automatisch überschrieben werden sollen. Persönlich bin ich da ja schwer dafür....Änderungen muss man dann eben manuell machen, kurz bevor man den Job startet. Dauerhafte Änderungen wären dann der "expert mode", müsste man dann eben auf github machen.

**Comment by emka** [comment]
Ich bin auch für Überschreiben, wenn ich an die Fräse gehe würde ich gerne sicher sein, dass die Einstellungen noch dem Stand der Datei auf Github entsprechen.

**Comment by Pakue95** [comment]
Nach dem Umbau habe ich die X & Y Dimensionen an die neue Bauform angepasst.

$130=1270.000
$131=119.000
$132=120.000

**Comment by NitramLegov** [comment]
Höchstwahrscheinlich setzen wir das als Teil von #67 um.

**Comment by LukasFreeze** [comment]
Ich möchte das hier nochmal pushen und dokumentieren, dass am Freitag wieder Einstellungen falsch waren: die Auflösung (steps/mm) der X-Achse, und zwar deutlich!

Das erklärte auch ein paar unrunde Kreise, die letzte Woche noch auf eine klemmende Achse (#100) und ein ggf damit zusammenhängendes Überspringen von Schritten geschoben wurde.

**Comment by NitramLegov** [comment]
@Narquadah Damit muss ich dich nerven ;)

**Comment by NitramLegov** [comment]
@Narquadah hat gestern den code für das CNC-Panel soweit fertiggestellt. Der ist inzwischen auch auf dem Pi Live, der die Fräse kontrolliert.

Die Einstellungen werden überschrieben, sobald sich der Pi mit der Fräse verbindet.
Das passiert bei einem neustart des Pi oder wenn man die Verbindung kurz trennt (also das USB-Kabel aussteckt).
Achtung: Das hat nichts mit dem "Verbindung öffnen" knopf auf der Weboberfläche von CNCjs zu tun. CNCjs ist da ein bisschen kacke!

Die Einstellungen liegen im cnc-panel repository:
https://github.com/comakingspace/cnc-panel/blob/master/settings.json
