### ISSUE TITLE
Bosch ixo battery replacement

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#48]
Our Bosch ixo needs a new battery
Type: 18650
Lithium ion
3,7 volt

**Comment by reisners** [comment]
I could take a look at it. I'll bring my set of fine screwdrivers next time and see if I can access the battery. Does the space already have a replacement battery?

**Comment by NitramLegov** [comment]
We did access the battery once already in order to figure out, which battery type is needed.

The space has an ifixit toolkit, which can be used to open it.

However, there is no replacement battery yet.

**Comment by reisners** [comment]
So I might google for suppliers of the 18650 battery type.
Found this one (if we're not in a hurry): https://smile.amazon.de/HCFKJ-1x3-7V-5000mAh-Li-Ion-Taschenlampe/dp/B0786B6BWW/ref=sr_1_1?ie=UTF8&qid=1535022115&sr=8-1&keywords=HCFKJ+1x3.7V+18650+5000mAh+Li-Ion+Akku+f%C3%BCr+Taschenlampe+Lampe+Taschenlampe

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by Titan-OX** [comment]
Is this dead? Or do you need a battery

**Comment by Pakue95** [comment]
I'm closing this now, as I deemed the screwdriver as not repairable when I looked at it a couple weeks ago.
