### ISSUE TITLE
Bandsäge Belagbänder ersetzen

### ISSUE THREAD

**Issue by khaos8rood** [comakingspace/do-something#49]
Unsere Bandsäge die Metabo BS 1638 W hat zwei gerissenen Belagbänder(Bandagen), welche also neu aufgezogen werden müssten.
Dieses Modell ist wohl baugleich mit der BAS 380 für die es dann aber auch andere, vor allem günstigere, Belagbänder gibt. Die Umlenkrollen haben laut BAS 380 Anleitung einen Durchmesser von 220mm, an der Maschienen in der Werkstatt haben wir 218mm mit Belagband (213mm ohne) gemessen . . . sollte passen. 
Auf der Shopseite sind keine angaben über das Maß der Belagbänder gemacht worden.

[BS 1638W Bandagen](https://www.shopbox24.de/bandage-belagband-fuer-die-bandsaegenmaschine-metabo-bs-1638-w-3-teilig-hochwertig-bindeglied-zwischen-bandsaegemaschine-und-saegeband/a-115981)

[BAS 380 Bandagen](https://www.shopbox24.de/bandage-belagband-fuer-die-bandsaegenmaschine-elektra-beckum-metabo-bas-380-3-teilig-hochwertig-bindeglied-zwischen-bandsaegemaschine-und-saegeband/a-103077)

Die Bandagen für die BAS 380 sind ~14€ billiger und . . . sollten passen.

wenn da keiner Wiederrede hat werd ich mich (aris) und der Lukas die Kosten teilen und die Belagbänder aufziehen.

**Comment by LukasFreeze** [comment]
Tut mir leid dass ich erst jetzt dazu komme, die Bänder sind bestellt! Ich hab mir wieder mal zu viel gleichzeitig vorgenommen...

Ich habe auch gleich noch ein [1400er-Metallblatt](https://www.shopbox24.de/werkzeugstahl-premium-saegeband-1400-mm-x-6-mm-x-0-36-mm-x-14-zaehne-pro-zoll-fuer-weiche-metalle-wie-bronze-kupfer-und-aluminium/a-58501/) für die kleine Bandsäge (#52) mitbestellt.

**Comment by khaos8rood** [comment]
Also, die Bandagen, welche Lukas gekauft hatte wurden aufgezogen. 
In kochendes wasser gelegt und mit Hilfe von zwei Löffeln auf die Umlenkrollen gezogen. Funktioniert super!

Die gekauften Bandagen sind allerdings keine Orginal-Teile und ihnen fehlen die Führungsschienen welche in einer gefrästen Scharte in der Umlenkrolle greifen soll und damit ein Verrutschen der Belagbänder verhindern würde. 
->Das Belagband am Antriebsrad rutscht bei Betrieb nach hinten von der Umlenkrolle, was ein erhebliches Risiko darstellt.
Patrik und ich haben kurzer Hand ein verschraubbare Führungsschiene in Fusion gestalltet (mehr Patrik als ich) welche an die Umlenkrolle angepass wird und die Bandage vor dem herunterlaufen schützen soll.
Mehr dazu am 23.08. hoffe ich ;)

**Comment by NitramLegov** [comment]
Added the commissioning template to the wiki

**Comment by NitramLegov** [comment]
@khaos8rood und @Pakue95 haben heute die Führunsschienen gedruckt und angeschraubt. Damit sollte man die Umlenkrolle nochmal ausprobieren können.

**Comment by LukasFreeze** [comment]
Funktioniert! Hier noch der Link zu den Führungsschienen ("Bandagen retainer") in unseren "CommonFiles": [3DPrintingFiles/Bandsaw](https://github.com/comakingspace/CommonFiles/tree/master/3DPrintingFiles/Bandsaw)

**Comment by LukasFreeze** [comment]
Ich habe gestern nochmal drei Führungsteile gedruckt, damit das Gummi jetzt überall gestützt wird und nicht nur an der Hälfte der möglichen Stellen. Es hatte sich doch nochmal ziemlich geschlängelt, so ist es jetzt bestimmt besser für die Laufruhe und die Lebensdauer der Sägebänder :-)

**Comment by LukasFreeze** [comment]
Nachtrag: an der dritten Rolle (die mit dem Teller) lief heute bei einem 10-mm-Sägeband das Gummi runter. Habe es mit Uhu Kraftkleber fixiert, weil da kein Platz für die schicken 3D-Teile ist.

**Comment by LukasFreeze** [comment]
Heute ist das letzte intakte Originalband kaputt gegangen, weil die Feststellschraube des oberen "Sägeband-nicht-nach-hinten-drücken-lassen"-Kugellagers fehlte und während eines Schnittes die Zähne tief ins Gummi liefen :-(

@SebMakesThings konnte das Neue glücklicherweise mit ein paar Schraubzwingen ohne Hitze-Tricks aufziehen und am Sägeband war kein Schaden zu sehen. Er hat auch gleich einen Nutenstein runtergeschliffen, um die Sägeblattführung zu reparieren!

Damit man jetzt nicht mit mehreren Schlüsseln hantieren muss, haben wir alle Feststellschrauben auf der Seite durch neue ersetzt. Die vorderen (Einstellung der Führungsklötzchen) können mMn gut per Hand angezogen werden, also sind da noch die alten Rändelschrauben.
![20220606_143832](https://user-images.githubusercontent.com/19755883/172299891-7d430b0a-d6ee-4c20-9c4e-dd0b75a9d0e8.jpg)

@Pakue95 Die abgebauten Schrauben liegen im Büro, wo vorher das Gummiband lag :-) die fehlende Schraube + Vierkantmutter dürfte schon irgendein Staubsauger geschluckt haben, am Boden war nichts zu finden...
