### ISSUE TITLE
Mini-Bandsäge in Betrieb nehmen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#52]
Da es sich mit der großen Bandsäge etwas schwieriger gestaltet hat (#49) werden wir wohl zuerst mit der kleinen loslegen...

Es gibt/gab schon ein paar konkrete Dinge am Gerät...

- [x] Schalter blieb selten eingeschaltet - @JohannesGruhler und ich haben die Kontakte wieder richtig gebogen, sollte jetzt gehen
- [x] Kugellager der Sägeblattführungen laufen noch nicht frei, sollten gereinigt und geschmiert werden
- [x] funktionieren sonst alle beweglichen Teile (Stellschrauben usw)?
- [ ] passt unser Staubsauger dran? Ansonsten Adapter drucken (s. #24)
- [x] nach dem Einrichten von @emka, @Pakue95, @beanobeano oder mir abnehmen lassen

... und natürlich wie immer Doku:
- [ ] [Wiki-Seite](https://wiki.comakingspace.de/Bandsaws#CMI_C-S-BS_250) mit Informationen füllen
  - [x] Anleitung verlinken - zu unserem Modell hab ich nichts gefunden, aber eine baugleiche Säge von Westfalia
  - [x] Auffälligkeiten während der obigen Schritte etc
  - [ ] nützliche Daten (z.B. maximale Sägeblatt-Breite)
- [x] [Bandsägen-Einführung](https://wiki.comakingspace.de/Bandsaw_Introduction) fertig definieren
- [x] grundlegende Informationen über (verfügbares und gewünschte) Sägeblätter [hier](https://wiki.comakingspace.de/Bandsaw_Blades) zusammentragen

**Comment by khaos8rood** [comment]
Ist das Sägeband irgendwo rissig? Unbedingt prüfen!

**Comment by LukasFreeze** [comment]
Es kam mir beim Ausmessen gestern sehr solide vor, saubere Lötstelle - die
Schärfe wage ich allerdings noch nicht zu beurteilen :-P

Das Band hängt zusammengelegt oben auf der Säge, die wiederum steht
übrigens seit gestern unter dem "Reparatur-Regal" in der Holzwerkstatt.

**Comment by NitramLegov** [comment]
Added the commissioning template to the wiki

**Comment by LukasFreeze** [comment]
In den letzten zwei Wochen gab es dank Moritz und Ignaz einigen Fortschritt an der Maschine, als nächstes sollen noch bessere (exzentrische) Halterungen für die Kugellager gedreht werden. Doku sollte natürlich wie immer auch nicht fehlen!

**Comment by LukasFreeze** [comment]
So, die Säge ist freigegeben :-)

Einen Staubsaugeradapter hat sie noch nicht, der ist für Metall aber eh erstmal nicht dringend und in der [Liste im Wiki](https://wiki.comakingspace.de/Shop_Vacs#Compatible_Tools) ist sie aufgeführt, falls sich jemand darum kümmern möchte.
