### ISSUE TITLE
Increase the Z-Range of our CNC Router

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#53]
The Z-Range of our CNC Router is fairly limited at the moment, so we should work on increasing it.
@Pakue95 and @LukasFreeze mentioned ideas of how to achieve it:

- Thinner spoilerboard
- flipping the supports of the board (like in this [picture](https://www.facebook.com/photo.php?fbid=10156523324418630&set=p.10156523324418630&type=3&theater&ifg=1))

This issue should be tackled at the same time as #50 and #51

**Comment by NitramLegov** [comment]
@Pakue95 added the following comment to #62:
The router is now apart and the cross beams can be turned 90º. Due to the new position, the aluminium angle plates can only be attached to one side - leaving the bottom free. I'd suggest to make some plates to also attach to the bottom to insure stability.
https://github.com/comakingspace/do-something/issues/62#issuecomment-419591630

**Comment by Pakue95** [comment]
Martin and I spend some time researching where to get these bottom plates. We found following options:

* Buy the ones from [OpenBuilds](https://openbuildspartstore.com/t-joining-plate/). 8 of these would be around 30€ without shipping (around 20€), which is quite expensive.
* Alternatively build them ourself from raw stock (drill holes, eventually cut to size)
  * Already pre-cut pieces of aluminium (~25€)
  * Raw stock for maybe 15-20€

Any opinions?

**Comment by Pakue95** [comment]
Martin found some 2mm steel pieces from Hornbach, which had the right width. Yesterday I cut them to size and started reassembling the base.

**Comment by Pakue95** [comment]
The frame is finished and has increased z range. Once the other [issues](https://github.com/comakingspace/do-something/projects/1#card-11463365) regarding the upgrade are closed, we should keep an eye on the rigidity of the machine in case more struts are needed.
