### ISSUE TITLE
Tag der offenen Tür im CoMakingSpace

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#56]
*Diese Beschreibung bitte immer mal wieder aktualisieren, so haben wir eine einigermaßen brauchbare Zusammenfassung!*
----

Am 16. September werden wir unser einjähriges Jubiläum im CoMakingSpace feiern! Dazu möchten wir einen Tag der offenen Tür veranstalten.

Wir haben schon überlegt, dass der Gemeinschaftsraum zur Ausstellung von Projekten und vielleicht für kleine Workshops genutzt werden könnte und die Werkstätten in Begleitung von Mitgliedern besichtigt werden können. Je nach Wetter könnten auch ein, zwei Tische vor die Tür gestellt werden, unsere Fassade ist ja nicht gerade die schönste...

Habt ihr Lust, im Vorfeld oder am Tag selbst mitzuhelfen? Hier schonmal ein paar Ideen wo man sich einbringen könnte, aber die Liste kann natürlich auch gerne noch erweitert werden (der Makerspace Rhein-Neckar in Ludwigshafen hatte neulich zum Beispiel auch sein Einjähriges mit interessantem Programm):

- [x] Poster gestalten (Druck-Deadline 30.8., dann können wir sie auf den Kultursäulen der Stadt unterbringen)
- [ ] Aussteller/Maker organisieren
  - [x] Lötkurs? -> @Johannes09 & Erik
  - [x] 3D-Schnupperkurs? -> @Lmnl99 & ???
  - [x] Bambus-Kugelschreiber basteln -> @khaos8rood 
  - [ ] Vorträge?
  - [x] Projekt Aussteller (Liste von Mitgliedern/externen Maker, die gerne etwas zeigen würden, und wie viel Platz sie bräuchten)
      - @NitramLegov - Musikbox
      - Susanna - Cosplay-Rüstung
      - @LukasFreeze - diverse Spiele, ca. halber Tisch
      - Ideen für externe s. Juliens Mail
- [x] Aufräumen/Vorbereiten (@LukasFreeze würde sich am **15.9.** zwischen 11 und 23 Uhr über Hilfe freuen)
- [ ] Artikel in RNZ/Stadtblatt/Bahnstadt-Info
- [ ] PR in social media, Newsletter etc.

**Comment by Pakue95** [comment]
Wir könnten noch unsere Nachbarn mit dem Barbecue-Truck fragen, ob sie sich an dem Tag auf dem Parkplatz aufbauen wollen (ohne dass wir sie irgendwie buchen/pauschal was zahlen!)

**Comment by Pakue95** [comment]
Frank hat leider keine Zeit für einen Löt-Workshop.

**Comment by khaos8rood** [comment]
Am Mittwoch 15.8. bin ich(aris) bis ca. 16:00 zum Aufräumen verfügbar.

**Comment by NitramLegov** [comment]
Glaube das sollte 15.9. heißen.

Da wäre ich übrigens verfügbar.

Von: khaos8rood [mailto:notifications@github.com]
Gesendet: Montag, 13. August 2018 23:02
An: comakingspace/do-something <do-something@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [comakingspace/do-something] Tag der offenen Tür im CoMakingSpace (#56)


Am Mittwoch 15.8. bin ich(aris) bis ca. 16:00 zum Aufräumen verfügbar.

**Comment by LukasFreeze** [comment]
Mist - genau, das sollte 15.9. heißen, also direkt der Tag vor der
Veranstaltung. Hast du vielleicht trotzdem Zeit oder Ideen für die
Tagesgestaltung? :-)

Wir sollten spätestens morgen auch mal über die ML schreiben, hier haben es
bestimmt noch keine 10 Leute mitbekommen...

@Johannes09 weißt du mittlerweile ob du Zeit für den Lötworkshop hättest?

**Comment by LukasFreeze** [comment]
@lmnl99 hat ein einfaches Design in Tinkercad vorbereitet und wird anbieten, unter seiner Anleitung einfache Änderungen vorzunehmen (eigenen Namen eingeben, evtl etwas drehen/abrunden etc.) und sich ein kleines Schild mit unserem Logo und seinem Namen zu drucken!

So ein Druck wird ca. 40 min dauern und Luca würde sich noch über eine/n weitere/n Helfer/in freue/n ;-)

**Comment by LukasFreeze** [comment]
Wir haben vorhin 75 Poster bestellt (50 kosteten nur 5 € weniger):
![grafik](https://user-images.githubusercontent.com/19755883/44494411-e516fa80-a66b-11e8-94e6-4c3a87e46bb6.png)

Vielen Dank @NitramLegov, @Pakue95 und vor allem @reisners für eure Mitwirkung! Es ist hoffentlich zur Zufriedenheit aller, eine Abstimmung war jetzt zeitlich nicht mehr drin :-P

Ich hoffe, bis Ende der Woche noch einen Newsletter und einen Facebook-Post raushauen zu können aber dann bin ich erstmal zwei Wochen lang offline...

**Comment by khaos8rood** [comment]
geht voll klar! . . . nur die Uhrzeit fehlt. . . 
Wann kommen die fertigen Plakate an?

**Comment by Pakue95** [comment]
28./29. wahrscheinlich.

**Comment by LukasFreeze** [comment]
Oh, das mit der Uhrzeit ist uns allen nicht aufgefallen, die muss bei der Suche nach geeigneten Stellen irgendwie "zu viel" gewesen sein und wurde dann vergessen...

Ich glaube aber dass es gar nicht so schlimm ist, es ist ja tatsächlich quasi den ganzen Tag geplant. Und wer unsicher ist, findet hoffentlich unseren Kalendereintrag oder Facebook-Event **mit** Uhrzeit :-P

**Comment by NitramLegov** [comment]
Plakate sind abgegeben, hängen dann ab dem 6.09

**Comment by NitramLegov** [comment]
Wie siehts denn eigentlich mit dem Punkt " Artikel in RNZ/Stadtblatt/Bahnstadt-Info" aus?
Denke wenn man das wirklich machen will sollten die Artikel demnächst erscheinen. Ist ja nicht mehr lange hin...

**Comment by NitramLegov** [comment]
Bezüglich Werbung sind wir jetzt übrigens sowohl im Kalender der Make als auch im Veranstaltungskalender der Stadt Heidelberg gelistet
https://www.heise.de/make/kalender/Jubilaeum-Tag-der-offenen-Tuer-4144718.html
https://www.heidelberg.de/hd,Lde/HD/Erleben/veranstaltungskalender.html

**Comment by LukasFreeze** [comment]
Danke @NitramLegov für die Kalendereinträge! Für einen Zeitungsartikel ist
es mittlerweile wohl zu spät (müsste ja auch erstmal jemand schreiben...)
aber ich versuche in den nächsten Tagen noch,uns zumindest mit einer kurzen
Notiz in der RNZ zu platzieren. Vielleicht kommt dann ja auch jemand am
Sonntag vorbei, um zu berichten :-)

On Sep 3, 2018 2:17 PM, "NitramLegov" <notifications@github.com> wrote:

Bezüglich Werbung sind wir jetzt übrigens sowohl im Kalender der Make als
auch im Veranstaltungskalender der Stadt Heidelberg gelistet
https://www.heise.de/make/kalender/Jubilaeum-Tag-der-
offenen-Tuer-4144718.html
https://www.heidelberg.de/hd,Lde/HD/Erleben/veranstaltungskalender.html

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/comakingspace/do-something/issues/56#issuecomment-418098510>,
or mute the thread

**Comment by NitramLegov** [comment]
Schneller als Johannes

**Comment by LukasFreeze** [comment]
Das Poster (mit Open Office Impress zusammengestellt) liegt jetzt in [CommonFiles](https://github.com/comakingspace/CommonFiles/blob/master/Posters/Poster%20Open%20Day%202018.odp) und könnte als Grundlage für dieses Jahr dienen - idealerweise nimmt sich aber jemand ein paar Minuten Zeit für neue Bilder und eine andere Überschrift als "*2* Jahre offene Werkstatt in Heidelberg" :-P

**Comment by ErikSchatz** [comment]
Hab´s gemacht!

**Comment by Pakue95** [comment]
Cool. Kannst du mir das Plakat schicken damit es in den Druck kann?

**Comment by ErikSchatz** [comment]
Kann´s nicht hochladen, dann per mail geschickt, erst mit fail; ist Patrick@comaking.space die richtige Adresse?

**Comment by Pakue95** [comment]
Jop, kam an. Martin und ich haben es nochmal etwas überarbeitet.

Aktuelles Issue is #148
