### ISSUE TITLE
Oszilliersäge verfügbar machen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#59]
Ich hab gerade schonmal eine [grundlegende Seite](https://wiki.comakingspace.de/Oscillating_Tool) angefangen, es fehlen aber noch einige Schritte (s. #42) - hat jemand Lust, ein bisschen was zu dokumentieren um den Prozess zu beschleunigen? :-)

**Comment by NitramLegov** [comment]
Würde das ganz gerne nutzen, um mal auszuprobieren, ob das neue Template (siehe #42) wirklich nützlich ist.

**Comment by NitramLegov** [comment]
Ich denke über die [Introduction](https://wiki.comakingspace.de/Oscillating_Tool_Introduction) kann schonmal jemand drüber schauen, die sollte hoffentlich soweit passen.

Der eigentlichen [Wiki-Seite](https://wiki.comakingspace.de/Oscillating_Tool) habe ich ein bisschen Struktur spendiert, hier braucht es eigentlich nur noch jemanden, der mal schaut, was wir an Zubehör haben.
Danach kann man es denke ich verfügbar machen. Würde mich auch direkt für die EInführung anstellen, die Teile sind ziemlich nützlich ^^

**Comment by NitramLegov** [comment]
I added pictures of the available attachments to the wiki page.
This evening I will print the QR-Code. After this, the only thing missing is that the introduction is still marked as incomplete. @Pakue95 and @LukasFreeze already added their improvements, so I assume they are fine with the current version. In case it is fine, some manager could remove the incomplete notice and then the tool would be available.

**Comment by LukasFreeze** [comment]
Thank you for improving the documentation, but let me slow you down a
little on an important point - in general, there should be no
assumptions/rushing regarding the introduction pages! Often there is still
something important missing besides what those who have made additions so
far knew of. Of course, I would not want to discourage asking *why* a given
introduction is not complete yet ;-)

We have decided that all four managers need to review them in order to be
on the safe side, so if just one or two have had time to go over an
introduction it may still be risky for a tutor to give it. We are tracking
this review internally and try to be as quick but also as thorough as
possible, so sometimes it can take a while.

Besides, even the two that have added to the content may still feel there
is something missing - for instance, I've done some minor edits on the
rotary tool introduction but am NOT considering it done yet. I just haven't
had time to include more info on dangers besides the abrasive cutting
function.


Anyway...in this case, you are actually correct as the final review
happened to be last night and the "incomplete" note was just forgotten. I
took it down and I agree we can call the commissioning "done" for this tool
once the QR code is printed!

**Comment by NitramLegov** [comment]
QR-Code is printed and the commissioning template is now removed. I´m closing the issue now. Thank you :)
