### ISSUE TITLE
file handles

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#6]
We've got a bunch of files in the metal workshop but none of them has a handle right now...

- [ ] put handles on the files (-> [here's how](https://wiki.comakingspace.de/Project:File_Handles))
- [x] work out a storage solution
  - drill a hole in each handle's end and add a loop for hanging on the wall?
  - a box similar to this one? 
![imgp2016 large](https://user-images.githubusercontent.com/19755883/46259662-9d8e5480-c4dc-11e8-9b13-8f1a51a07d97.JPG)

**Comment by LukasFreeze** [comment]
I was given three handles today and am hoping to make more as a beginner woodturning project (once we have the appropriate lathe).

**Comment by LukasFreeze** [comment]
@Pakue95 brought in another four handles and I just put them on files, five remain to be turned once the wood lathe (#7) is set up.

**Comment by LukasFreeze** [comment]
I made one as my first woodturning project and was actually amazed how well it turned out! Here's a [wiki page explaining (hopefully) everything](https://wiki.comakingspace.de/Project:File_Handles), I highly recommend making some of these to everyone interested in woodturning :-)

**Comment by LukasFreeze** [comment]
Die große Raspel tut jetzt nicht mehr so weh ;-)

**Comment by LukasFreeze** [comment]
@Lmnl99 hat heute einer Rundfeile ihren neuen Griff verpasst und einige gute Drechselerfahrungen dabei gemacht - für alle Einsteiger sehr zu empfehlen ;-)

**Comment by LukasFreeze** [comment]
Am Wochenende hat jemand das Lagerungsproblem gelöst! Vielen Dank :-D

![IMG_20200115_230024](https://user-images.githubusercontent.com/19755883/72475313-f1fd3680-37ea-11ea-8214-268daa9b8f21.jpg)

**Comment by o-liver** [comment]
ist das hier noch immer relevant? Wollen wir vll einen neuen Issue aufmachen für was noch übrig ist, und den hier schließen?

**Comment by LukasFreeze** [comment]
Das einzige noch offene müsste [mein letzter Kommentar](https://github.com/comakingspace/do-something/issues/6#issuecomment-948296650) sein: für die kleinen Feilen könnte man Sektkorken als Griffe nehmen, müsste dann aber noch die Wandhalterung verbessern.

**Comment by LukasFreeze** [comment]
Hab den letzten drei Feilen Sektkorken-Griffe verpasst.

Im Büro gibt es eine Kiste mit weiteren Griffen und Korken :-)
