### ISSUE TITLE
kaputte Lampen im Space

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#60]
Im Common Room tropft regelmäßig etwas (Kondenswasser?) von einer der Leuchtstoffröhren über dem großen Tisch. Die Lampe hängt genau über der Tischkante die zur Raummitte zeigt und tropft auf die Ecke des Tisches.

- [x] Herausfinden woher das Wasser (?) kommt 
- [ ] Problem beheben ~~(neuen Starter einbauen)~~ (neue Lampe oder eine umhängen)

**Comment by LukasFreeze** [comment]
Die Lampe ist auch kaputt, das ist noch nicht lange so?!

**Comment by NitramLegov** [comment]
Update zur Doku: Es war der Starter, das Ding heißt ST111

**Comment by LukasFreeze** [comment]
Die Starter gibt es sehr günstig bei Amazon, denke wir sollten gleich ein paar nehmen und versuchen, andere kaputte Lampen wieder gängig zu machen: [10-er Pack](https://smile.amazon.de/St%C3%BCck-Osram-ST111-Starter-4-65/dp/B00I9CNGDY/ref=sr_1_1?ie=UTF8&qid=1534850945&sr=8-1&keywords=10+St%C3%BCck+Osram+ST111+Starter+4-65+Watt)

Vor meinem Urlaub werde *ich* das allerdings nicht mehr anfangen :-P

**Comment by NitramLegov** [comment]
Habe zwei von den Startern in einer alten Lampe gefunden und bringe die am Mittwoch mit.

**Comment by NitramLegov** [comment]
Es ist schon wieder ein Tropfen an der Lampe. Issue ist also doch noch nicht gelöst

**Comment by Johannes09** [comment]
[Zielscheibe.docx](https://github.com/comakingspace/do-something/files/2408334/Zielscheibe.docx)

**Comment by LukasFreeze** [comment]
Kai hat den Verdacht geäußert, dass da PCBs austreten, und ich halte das nicht für unwahrscheinlich:
Diese Substanzen wurden bis vor einigen Jahren in Vorschaltgeräten von Fluoreszenzlampen verwendet und sind ölig-gelb -> [1](https://en.m.wikipedia.org/wiki/Electrical_ballast), [2](https://en.m.wikipedia.org/wiki/Transformer_oil), [3](https://en.m.wikipedia.org/wiki/Polychlorinated_biphenyl)

Das Zeug ist echt nicht lecker, und ein en auslaufenden Trafo werden wir auch nicht reparieren können - das Vorschaltgerät sollte also zügig raus und nur mit adäquaten Handschuhen berührt werden!

**Comment by NitramLegov** [comment]
Soooo, Update:
@Johannes09 und ich haben heute die Lampe abgebaut.
Das Kunststoffgehäuse war innendrin komplett nass. Sieht aus als wäre da drin nochmal ein dicker Kondensator gewesen, der geplatzt ist (sieht zumindest für mich geplatzt aus ^^) .
Weiterhin hat @Johannes09 ein pdf gefunden, das PCB-haltige Kondensatoren beschreibt:
https://www.elektropraktiker.de/ep-2003-04-278-281.pdf?eID=tx_nawsecuredl&falId=6258&hash=222401bf103d28f0925587ccf712ed93
Unter Punkt 7 steht hier:

> Bei den Buchstabenkombinationen MP, MKK, MKP, MPP, MKV, MFV, MPK sowie LK und LP kann davon ausgegangen werden, dass diese Kondensatoren kein PCB enthalten. 

Zur weiteren Referenz sind hier noch Bilder angehängt. Außerdem liegt die abgebaute Lampe auf der Fensterbank.
![dsc_0385](https://user-images.githubusercontent.com/7809163/46031875-642fa080-c0fa-11e8-98cd-38246d04225d.JPG)
![dsc_0383](https://user-images.githubusercontent.com/7809163/46031879-64c83700-c0fa-11e8-82a7-84de3f33c9d3.JPG)
![dsc_0382](https://user-images.githubusercontent.com/7809163/46031880-64c83700-c0fa-11e8-9ecf-4957aabdb479.JPG)
![dsc_0381](https://user-images.githubusercontent.com/7809163/46031881-6560cd80-c0fa-11e8-8a65-0e6c8925b5bd.JPG)
![dsc_0375](https://user-images.githubusercontent.com/7809163/46031882-6560cd80-c0fa-11e8-9d98-3ef46ba74f5a.JPG)

**Comment by NitramLegov** [comment]
Zur weiteren Erleichterung deutet dieser [Brief](https://www.die-wuestens.de/iz/PCB1.pdf) darauf hin, dass da reines Mineralöl drin ist.
Bezüglich Ersatz durch andere Lampen bin ich bei dir. Vor allem, da die jetzt abgehängte Lampe ja direkt über dem Tisch hing. Da wäre Licht schon cool ^^

Die Lampen sind auch nicht an die Decke geschraubt sondern nur geklippt. Lassen sich also mit vergleichsweise geringem Aufwand umhängen.

**Comment by LukasFreeze** [comment]
Das wäre natürlich noch besser, kannst du das machen oder abnehmen? Ich
traue mich an Netzspannung nicht ran...

2018-09-25 23:24 GMT+02:00 Patrick <notifications@github.com>:

**Comment by Pakue95** [comment]
Einbauen prinzipiell schon, aber abheben muss das ein Elektriker.

**Comment by LukasFreeze** [comment]
Wir haben noch zwei kaputte abmontiert, es liegen jetzt also drei auf der Fensterbank, und @Johannes09 bringt wahrscheinlich einige Kondensatoren mit.

Der ganze Sinn der Aktion gestern Nacht war ja eigentlich, wieder zwei funktionierende Lampen an den "Haupt-Lichtschaltern" zu haben, aber als wir eine funktionierende an die freie Stelle von der ursprünglich tropfenden Lampe gehangen haben ging sie plötzlich auch nicht mehr. Wahrscheinlich nur Pech mit einem (vorher) gerade noch so funktionierenden Kondensator, aber irgendwann war es dann zu spät um noch mehr zu versuchen...

**Comment by NitramLegov** [comment]
Gestern Abend hat sich @Johannes09 auch mal die Lampen im Außenbereich vorgenommen. Diese scheinen das gleiche Problem zu haben. Wenn die wieder funktionieren wäre das natürlich super, dann muss man nicht mehr einen Strahler aufhängen, wenn man mal draußen arbeiten muss.
![dsc_0412](https://user-images.githubusercontent.com/7809163/47138407-9d9e9a80-d2b9-11e8-800a-5e30545deaa8.JPG)
![dsc_0413](https://user-images.githubusercontent.com/7809163/47138408-9e373100-d2b9-11e8-92f1-85fe749cd725.JPG)
![dsc_0414](https://user-images.githubusercontent.com/7809163/47138409-9e373100-d2b9-11e8-8210-7ee0eb770664.JPG)

**Comment by Johannes09** [comment]
ich bin der Meinung das die Kondensatoren erstmal weggelassen werden können 
Einkaufsliste:	

- [ ] Leuchtstoffrohren 150cm
- [ ] Starter

**Comment by LukasFreeze** [comment]
Röhren bringe ich am Donnerstag einige vorbei, [Starter](https://smile.amazon.de/St%C3%BCck-Osram-ST111-Starter-4-65/dp/B00I9CNGDY/) sind auch bestellt und kommen nächste/übernächste Woche.

Wenn das ohne Kondensatoren geht wärs natürlich nett, aber hauptsache wir beheben das ganze langsam mal :see_no_evil:

**Comment by emka** [comment]
@Johannes09 hat inzwischen alle Starter

**Comment by Johannes09** [comment]
Ich habe jetzt ein Großteil der Lampen repariert.
Die wichtigsten stellen im Space sind jetzt wieder gut ausgeleuchtet.
Funktionierende Lampen in den einzelnen Räumen 

- Commen Room (11/12) bei der kaputten Lampe ist die Spule kaputt und muss ersetzt werden 
- CNC Room (1/2)
- Flur (2/2)
- E- Room (3/3)	
- Comaking Bech Room (5/5)
- Woodworking Room (13/13)
- Metall Room (5/7) vermutlich Probleme mit dem Kondensator (austauschen der Rohre und des Starters hat nichts gebracht)
- Outside (2/3)
