### ISSUE TITLE
P1 Printer has a damaged PEI sheet

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#61]
The P1 Printer has a small hole in the PEI bed from a crash. Initially not a huge problem, but the sheet seems to come off at that place. It may need a new bed, or at least a new PEI sheet.

**Comment by emka** [comment]
You can get individual sheets for replacement, no need to get a new bed. We could try closing the hole first by dissolving the surrounding PEI in acetone.

**Comment by NitramLegov** [comment]
Just in case somebody wants to buy a replacement:
https://shop.prusa3d.com/en/3d-printer-parts/146-replacement-pei-sheet-for-mk2s-ultem.html

Prusa actually also has a quite detailed description of how to replace the sheet:
https://manual.prusa3d.com/Guide/Replacing+the+PEI+sheet/133#_ga=2.52974440.1939930302.1533810647-1681040799.1532537312&_gac=1.53465434.1533810647.Cj0KCQjwzK_bBRDDARIsAFQF7zMclfJNMevb6G66vgMjTannaGURRNM-KEENa1n8mG0JzK05VrELn3IaAqn0EALw_wcB

The use Limonene, which seems to be quite expensive. However, in the comments people mention some replacements which provided good results as well.

**Comment by LukasFreeze** [comment]
I'd try the Kapton idea before replacing the entire sheet.

Didn't you also mention something about limonene which might work better
than acetone? Not sure if we want to mess with too many solvents though...

**Comment by Pakue95** [comment]
Luca said he‘ll bring some Kapton tape. Here an example of somebody using the tape to fix a bed 
https://youtu.be/8tf5RqTQXQg.

**Comment by Pakue95** [comment]
Kapton tape is attached and the corners are slightly sanded off. I'm printing something right now for testing, but so far it looks fine.
