### ISSUE TITLE
CNC Router - Issue with homing

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#62]
New issue as @Chris0812 commented in #8 
"The Homing does not work properly: The Z-endstop doesn't seem to trigger"

As far as @Pakue95 told me yesterday, there is also an issue with the router loosing steps when moving too far to the left. @Pakue95 can you add more details?

**Comment by Chris0812** [comment]
Interesting...in its current state, the Machine is rather non-functional, so of course no objections here.

**Comment by NitramLegov** [comment]
"We need to make a list (wiki?) with all the things to change/upgrade in order to plan ahead."

We do have the "WorkBee CNC" Project on github:
https://github.com/comakingspace/do-something/projects/1#card-12366605
Is that enough of a list? Anything in there not labeled as "IT" can be done.

Ideally, the currently heaviest users of the CNC Router should coordinate and plan this. Therefore, @Chris0812  could take this up with Michael, plan the changes, make them and update any needed documentation accordingly. @Chris0812 What do you think?

**Comment by Chris0812** [comment]
Totally agree on doing everything I can, to get it back to work - but for coordination etc. I would not decide and DO anyting without Patrick or Mitja. 
Maybe on wednesday we might have time to talk about it further and find a date

**Comment by NitramLegov** [comment]
https://openbuildspartstore.com/micro-limit-switch/

This would be such a switch. Maybe it makes sense to search for a cheaper source

**Comment by NitramLegov** [comment]
So what´s the plan? Do we have a list of stuff we need in order to fic the router?
Is there any estimated time which would be needed so that we can agree on a date to start?

**Comment by NitramLegov** [comment]
We de-assembled the end-stop today. The switch it ok, the problem is with the cable, so we just need a new cable.

**Comment by Pakue95** [comment]
The router is now apart and the cross beams can be turned 90º. Due to the new position, the aluminium angle plates can only be attached to one side - leaving the bottom free. I'd suggest to make some plates to also attach to the bottom to insure stability.

**Comment by NitramLegov** [comment]
When disassembling the router and checking the end-stop we discovered that the isolation of the cable was broken at multiple places. Therefore, the existing cables (the thin ones) should be considered not suitable for the environment they are used in. As of that, I recommend replacing them with higher quality ones.

**Comment by Pakue95** [comment]
I’ve got silicon cables at the space which could be used to wire the endstops.

**Comment by Pakue95** [comment]
Yesterday I removed the old Z endstop cable and replaced it with a new silicon one. Right now its just fed through the cable guide and still needs some cable management. The endstop has to be soldered on and mounted back under the Z axis.

**Comment by Pakue95** [comment]
The endstop is installed back into the Z axis and is functional again.
