### ISSUE TITLE
Router Table

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#64]
I got my hands on a router table from Westfalia [(Art-Nr. 64 56 97)](https://www.westfalia.de/service/dat_down.php?datei_id=128278) which I will bring to the space next time I show up.

For commissioning, I would have add the following questions:
- Do we need an introduction? Should it be included to the overall router Introduction?
- My proposal would be to include the documentation into the overall Router wiki page. Is that fine?

I also got a Kingcraft KBF-1050E Router which should fit to the table. However, I would rather try if the existing Routers fit as well. If they do, I´ll keep the kingcraft for the moment ;)

**Comment by LukasFreeze** [comment]
There should definitely be an addition to the existing introduction as
there are new dangers/precautions when using the table.

For the documentation I would prefer a separate page, the table is not just
some small accessory but really transforms the tool for completely
different uses in my opinion. The table could be mentioned as an option in
the "Routers" intro text and also linked under "used with" for every
compatible router.

**Comment by NitramLegov** [comment]
Alright. I create a [seperate wiki page](https://wiki.comakingspace.de/Router_Table) for it.
of course, the commissioning template applies here as well.

**Comment by NitramLegov** [comment]
We should also buy a pedal stop similar to what we have at the table saw.
The table saw uses a tfs-402 which can take up to 15A.

The Router needs 4,5A max. Therefore, something like this should be suitable (even this still has a lot of buffer):
https://www.ebay.de/itm/Fusschalter-Schutzhaube-Trittschalter-Industrie-Fuspedal-Schalter-Fernschalter/282928533586?hash=item41dfdad052:m:mSttquFW4ObaMtrxxJsxBJw

**Comment by LukasFreeze** [comment]
Do you mean the first one for ~5 €? The shipping costs about the same, so
it might be worth it to collect orders and buy two or three switches (or
something else we already need) at once. The shop looks like it could be
interesting for many member's projects or the CNC router control panel
(#67), doesn't it?

**Comment by NitramLegov** [comment]
I was thinking about the second one for 7€.
However, I am not quite sure about the type of switch these ones have. It doesn't really say whether you have to keep the switch pressed in order to turn the machine on.
Therefore, I don't think anymore that we should order these 🙈
Instead, I am now thinking about those:
https://www.ebay.de/itm/FS-01-Fusschalter-250-V-AC-10-A-1-Pedal-1-Wechsler-Kabellange-1-m-offene-67815/173473193329?hash=item2863cedd71:g:FMAAAOSwe4xbdCj4

Here it says it is a "Wechsler", so we would just need to change the wiring. Additionally, we would need power plugs for it.

Unfortunately it seems that the shop offers only 1. In general I am in favor of ordering multiple ones. I could see them being useful for the scroll saw, the bandsaw, the wood and metal lathe and possibly many more tools.

Von: Lukas
Gesendet: Montag, 17. September, 17:23
Betreff: Re: [comakingspace/do-something] Router Table (#64)
An: comakingspace/do-something
Cc: NitramLegov, Author


Do you mean the first one for ~5 €? The shipping costs about the same, so
it might be worth it to collect orders and buy two or three switches (or
something else we already need) at once. The shop looks like it could be
interesting for many member's projects or the CNC router control panel
(#67), doesn't it?

**Comment by NitramLegov** [comment]
Yes, very good idea!
How many foot switches would we need? The list of machines I could see this being useful for would be:
Router Table
Metal Lathe
Wood Lathe
Scroll Saw

@Johannes09 mentioned the Drill press as well. @LukasFreeze what would you think?

I would personally vote for ordering 5 switches. Especially since we also need to order "Schukostecker" and "Schukokupplungen" and I found an offer for 5 of them (without shipping costs)
https://www.ebay.de/itm/5-Paar-Schukokupplung-Schukostecker-IP44-230V-16A-Spritzwasser-geschutzt-Gummi/282402975543?hash=item41c0876f37:g:NgkAAOSwRjNXNvHW

Overall, my basket is now at 64,03, though I expect it to go down to 59,13 due to the combined shipping.
![image](https://user-images.githubusercontent.com/7809163/45677173-d8cf7180-bb33-11e8-9a78-85fb8296ade9.png)

**Comment by NitramLegov** [comment]
I ordered two pedal switches (for the router table and the band saw), 2 "Schukokupplung" and the Schütz. It should arrive early next week so I can bring it next wednesday.

**Comment by NitramLegov** [comment]
Pedal switch attached. I am closing this issue. The commissioning template should be removed by a manager :)

**Comment by drei85** [comment]
Einer der Kabelbinder ist gebrochen, sodass ein Plastikteil der Spindelverriegelung gebrochen ist. Ich habe versucht das Plastikteil zu kleben und das Metallgehäuse wieder mit Kabelbinder zusammen zu halten. Das geklebte Plastikteil habe an die Maschine geklebt und an den Platz für defekte Werkzeuge gestellt.

Auf dem Heimweg kam mit die Idee, ob es eventuell möglich ist das defekte Metallgehäuse und den Mechanismus der Spindelverriegelung komplett zu entfernen, das Gewinde am vom Fräser entfernten Teil an zwei gegenüberliegenden Seiten mit einer Feile abzuflachen, sodass das Gewinde beim Fräserwechsel mit einem Schraubenschlüssel festgehalten werden kann.

Christoph
