### ISSUE TITLE
belt sander

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#66]
@beanobeano brought in his belt sander a while ago and we thought it might be broken as it quickly got stuck, but massaging the old belt seemed to help - new ones should work just fine!

Let's commission it before we buy more belts (which ones would make most sense?), here's its [wiki page](https://wiki.comakingspace.de/Belt_Sander) where you could help with the process!

**Comment by LukasFreeze** [comment]
@lokowandg took the dust bag home tonight in order to sew on a new zipper. He might also bring some new belts the next time he comes :-)

**Comment by kenomaerz** [comment]
The ball bearings gave up the ghost when I used the sander on Wednesday. @Pakue95 and @LukasFreeze  disassembled it and are ordering a new set. The belt sander is not functional until then.

**Comment by Pakue95** [comment]
I installed a new 608Z bearing I had laying around and it seems to work fine now. The next person to use it should report back if it is working when used for a prolonged time.

**Comment by kenomaerz** [comment]
Ill probably get to it on Wednesday and let you all know

**Comment by LukasFreeze** [comment]
commissioning restart :-P

There's a new belt sander in the house, apparently the old one went out with a bang: https://wiki.comakingspace.de/Belt_Sander

**Comment by Pakue95** [comment]
The belt sander needs a new cable before it can be made accessible. I'll probably get to it next week.

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by Titan-OX** [comment]
Können wir das issue zu machen? Ich hatte es so verstanden das wir kein handheld belt sander unterhalten wollen
