### ISSUE TITLE
Multimaterial 3D Drucker verstopft (P6)

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#68]
Die Düse war wahrscheinlich durch das Holzfilament (UniCoFil) verstopft.

**Comment by Pakue95** [comment]
Kai und ich haben versucht die Düse wieder mit einer Akupunkturnadel super zu machen, jedoch so wie es aussieht ist das Filament im Hotend verkantet und lässt ich auch nicht mehr herausziehen. Bis man das Hotend einmal auseinander genommen hat und das Filament entfernt wurde.

**Comment by LukasFreeze** [comment]
Ich finde, wir sollten nach der Reparatur nicht mehr erlauben, Holzfilament
(oder ähnliches mit Fasern) mit 0,4-mm-Düsen zu drucken. Mitja, Ciaran und
soweit ich mich erinnere auch André von UniCoFil(!) sind der Meinung, dass
dafür eine 0,6-mm-Düse geeigneter wäre.

Ein weiterer Vorteil von diesem Umbau wäre, dass einer der Drucker dann
generell schneller wäre! Müsste man natürlich klar kennzeichnen, damit die
Leute merken was sie an den Slicer-Einstellungen ändern müssen.

2018-09-15 15:09 GMT+02:00 Patrick <notifications@github.com>:

**Comment by NitramLegov** [comment]
Kai hat gestern Aufbewahrungen für die Düsen gedruckt, die wir noch so haben (scheinen ja einige Größen zu sein). Weiterhin hat er mal vorgeschlagen, mehrere Drucker auf verschiedene Größen umzubauen, um entsprechend mit einer kleineren Düse genauere Drucke bzw. mit einer großen Düse schnelle Drucke zu ermöglichen (z.B. für die Staubsaugeranschlüsse)

Dazu müsste man noch am Slicer verschiedene Profile einrichten, das ist aber easy machbar. Für 0,25 und 0,6 liefert Prusa die Settings sogar schon mit, die muss man nur aktivieren. Und wie Lukas schon erwähnt hat muss man die Drucker natürlich entsprechend kennzeichnen.

Persönlich find ich das eine gute Idee. Nach der Aussage in #46 stellt sich mir aber die Frage, wie weit wir die Drucker modifizieren wollen ;)

**Comment by Pakue95** [comment]
Der Extruder des Multi-Filament Druckers ist wieder frei. Ich hab die Düse und die Heatbreak abgeschraubt; das Filament war in letzterer Stecken geblieben. Das sollte eigentlich nicht passieren, da die Heatbreak aktiv gekühlt wird. Ich habe die PTFE tube rausgenommen und die Heatbreak mit dem Heißluftfön warm gemacht. Danach ging das Filament raus. Es waren noch Reste vom Holzfilament drin (siehe Bild). Meine Vermutung ist, dass durch den niedrigeren Schmelzpunkt des Holzfilaments dieses sich im Übergang von der Heatbreak zum Hotend festgesetzt hatte.

Der Drucker hat jetzt noch einen Vermerk bekommen "Prosa Filament only".

![img_1938](https://user-images.githubusercontent.com/19751734/46075483-e5367880-c18a-11e8-8246-03c523d9fa2f.jpeg)
