### ISSUE TITLE
Bandsägen-Parallelanschlag & Schleiftisch

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#69]
Zur großen Metabo-Bandsäge gehören eigentlich noch (mindestens) ein Parallelanschlag für Längsschnitte und ein Tisch, der die Benutzung der Tellerschleifer-Funktion ermöglicht. Leider sind die allerdings bei unserer gebrauchten Säge nicht mehr dabei, wir sollten sie also nachrüsten!

Inspiration gibt es wie Sand am Meer, einfach mal Suchbegriffe wie "bandsaw fence" oder "disc sander" bei Instructables und YouTube ausprobieren ;-)

**Comment by Manu444** [comment]
Ich habe gestern abend angefangen, den Parallel-Anschlag zu bauen. Dazu habe ich bisher ein paar Stücke Siebdruckplatten zurecht gesägt, sie liegen unter der Bandsäge. 

Ich möchte versuchen, das Design möglichst einfach zu halten, der horizontale Winkel soll aber verstellbar sein. Der Anschlag selbst besteht aus zwei Brettern im Abstand von 8cm mit Querverstrebungen zur Stabilisierung. 
Zur Fixierung würde ich versuchen, Schraub-Klemmen zu bauen, die auf der Tisch-Unterseite greifen, und zwar auf der Vorder- und Rückseite des Tisches.

**Comment by LukasFreeze** [comment]
Wir haben uns dagegen entschieden, Parallelanschlag und Schleiftisch in einem Stück zu bauen, weil dann der ursprüngliche Sägetisch nicht mehr unbedingt gekippt werden kann. Der Schleiftisch muss außerdem leider jedes Mal entfernt werden, wenn man das Gehäuse der Säge öffnet :-(

**Comment by LukasFreeze** [comment]
Ich nehme mir den Schleiftisch mal vorsichtig für morgen Abend vor. Zur Montage bräuchte man 2 Stangen mit 9 mm Durchmesser, in meinem beschaulichen Sammelsurium befindet sich aber leider nur eine relativ kurze...vielleicht geht es aber mit Gewindestangen?

Ein paar Elemente, die ich gerne in unserem Tisch vereinen würde:
- Nut, die mit dem Gehrungsanschlag der Tischkreissäge kompatibel ist (wie [in diesem Instructable](https://www.instructables.com/id/Lathe-Mounted-Disc-Sander/))
- Neigungsmöglichkeit (mit Skalierung!)
  - [Instructable, vermutlich komplizierter](https://www.instructables.com/id/Benchtop-Disc-Sander/)
  - [Instructable, vermutlich einfacher](https://www.instructables.com/id/12-Inch-Lathe-Disk-Sander/)
  - [Wood Archivist - schöne Skizzen, aber besondere Hardware verwendet](http://woodarchivist.com/3613-diy-disk-sander/)
  - [ibuildit.ca - ähnlich 1. Instructable](https://ibuildit.ca/projects/12-inch-disk-sander/)
- Schutz/Blockade der falschen Schleiftellerseite (in diesem Fall rechts)?

**Comment by LukasFreeze** [comment]
Es lohnt sich leider doch nicht wirklich, Arbeit in den Tellerschleifer der Säge zu stecken - stattdessen sollten wir lieber einen ganz neuen bauen --> #119 

Probleme:
- Sägeband dient als "Riemen" zum Schleifen
  - das volle Wissen um das Einstellen der Säge wäre also zum Schleifen nötig - eine ganz schön lange Einweisung!
  - hohe Abnutzung zu erwarten, wenn "nur schnell" geschliffen werden soll und das Band schlampig eingestellt wird
- Gehäuse der Säge kann mit dem Tisch nicht geöffnet werden - das ist aber ständig zum Einstellen nötig!
- auf Rohren/Stangen aufgehangener Tisch würde nicht so stabil werden wie eine solide Holzbox auf der Drechselbank
- ...und selbst die Größe ist nicht so berauschend und könnte anderswo höher ausfallen!

@Manu444 ist bei dem Parallelanschlag akut noch etwas zu machen (außer einer kleinen "Anleitung" im Wiki)? Dann könnten wir hier bald zumachen :-)

**Comment by LukasFreeze** [comment]
Anschlag im Wiki: https://wiki.comakingspace.de/Bandsaw_Fence

Er hat heute Nacht auch noch einen Platz an der Wand bekommen, danke @Titan-OX :-)
