### ISSUE TITLE
Drechselbank (Holz) einrichten

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#7]
Ich hab eine Drechselbank gekauft (danke @Henrik99 fürs Entdecken!) und möchte die bald in die Holzwerkstatt stellen :-)

Was davor (mindestens) noch erledigt werden muss - [*english version in the wiki*](https://wiki.comaking.space/Wood_Lathe):
* [x] säubern & äußerlich inspizieren
* [x] Gehäuse aufschrauben und Verkabelung anschauen/verbessern
* [x] auf eine geeignete Werkbank montieren
* [x] Sicherheit: Spalten zum Motor- bzw. Riemenbereich mit Kantholz schließen
* [x] Schutzvisier (z.B. [sowas](https://www.dictum.com/de/werkzeuge/holzbearbeitung-metallbearbeitung/werkstattzubehoer-werkzeugsaetze/arbeitsschutz/707903/bionic-schutzvisier)) kaufen (2x)
* [x] Drechselwerkzeuge kaufen (erstmal [einfaches Set](https://www.stabilo-fachmarkt.de/guede-drechselbeitel-drechseleisen-satz-5-tlg/a-914817/))
* [ ] Werkzeuge schärfen lernen und Schärf-Hinweise zur [Wiki-Seite](https://wiki.comaking.space/Woodturning_Tools) hinzufügen
* [x] Klemmhebel für die Werkzeugauflage ~(einfach einen Griff an die Mutter schweißen?)~
* [x] Werkzeugauflage fest an ihrer Stange montieren (kippelt und ist schräg!)
* [ ] Dokumentation im Wiki
  * [x] Drechselwerkzeuge (*angefangen* unter ["Woodturning Tools"](https://wiki.comaking.space/Woodturning_Tools))
  * [ ] Schärfvorrichtung(en)/sharpening jig(s)
  * [x] [Sicherheitseinweisung](https://wiki.comakingspace.de/Woodturning_Introduction) (fast fertig)

**Comment by LukasFreeze** [comment]
Hab das Handbuch gefunden und im Wiki verlinkt, außerdem überlege ich für den Anfang erstmal die "dazugehörigen" Billig-Drechseleisen von Güde zu kaufen: [z. B. Stabilo](https://www.stabilo-fachmarkt.de/guede-drechselbeitel-drechseleisen-satz-5-tlg/a-914817/]. Keine Angabe zum Material (HSS wäre nett) und sie sehen ganz schön kurz aus, aber für den Preis... knapp 15 € für ein 5er-Set ist nicht zu schlagen, anständige Röhren kosten pro Stück mindestens 40 €.

Gibts hier jemanden mit Drechselerfahrung der das für eine komplett bescheuerte Idee hält? Sonst schlage ich bald mal zu, was sich abnutzt kann man dann durch schöne Werkzeuge ersetzen und wahrscheinlich braucht man eh 3 von 5 Formen so gut wie nie...

**Comment by LukasFreeze** [comment]
Wir haben das Teil gestern Abend in die Holzwerkstatt gebracht und ich habe an diversen Stellen etwas Rostlöser versprüht. Sah aber alles eher oberflächlich aus, den Mitnehmer konnte man auch mit etwas milder Gewalt von der Spindel abmontieren.

Der Unterbau wird dann wohl langsam konkreter! :-)
Was ich bisher so im Kopf habe:
* stabil sollte er natürlich sein
* hohes Gewicht reduziert Vibrationen; Höhe der Spindel ca. Ellenbogenhöhe ([thespruce.com](https://www.thespruce.com/buy-and-use-a-wood-lathe-3536927))
* ein bisschen mehr Abstand zur Platte als von Güde vorgesehen könnte gut sein, um anständig an die Klemmhebel vom Reitstock (vorhanden) und Werkzeugauflage (aktuell nur eine Mutter...) zu kommen

**Comment by LukasFreeze** [comment]
Moritz und ich haben gestern die Drechselbank auf eine unserer neuen Werkbänke montiert. Macht bisher einen sehr soliden Eindruck, aber wenn sie mal eine Weile gelaufen ist wird man schauen müssen ob sich etwas losvibriert hat.

Die Tür zu den Riemenscheiben ist wieder angenietet und wird von einem Festplattenmagneten geschlossen gehalten. Durch unser leichtes Aufbocken mit Holz kann man jetzt allerdings von unten in den Riemen-/Motorbereich fassen - dieses Sicherheitsrisiko sollte noch mit passenden Holzstücken gelöst werden, auch wenn man schon sehr unvernünftig sein muss um seine Finger dort reinzustecken.

**Comment by LukasFreeze** [comment]
Wir sollten als nächstes Mal in das Gehäuse schauen, die Zugentlastung vom Netzkabel ist kaputt wenn ich mich richtig erinnere und das sollten wir lieber beheben.

Übrigens - Micha hat uns gestern eine Planscheibe und ein Vierbackenfutter mitgebracht! 🥇

**Comment by LukasFreeze** [comment]
Ich habe mit dem Schreiben der Sicherheitseinweisung begonnen: https://wiki.comakingspace.de/Woodturning_Introduction

Die [Seite über die verschiedenen Werkzeuge](https://wiki.comakingspace.de/Woodturning_Tools) reift auch *langsam* zu etwas brauchbarem heran.

**Comment by LukasFreeze** [comment]
Ich habe die Zugentlastung aus einer alten Lampe ausgeschlachtet und hoffe, sie morgen Abend in die Drehbank einbauen zu können.

**Comment by LukasFreeze** [comment]
Zugentlastung sitzt und die Maschine ist jetzt sauber, wo mans nicht sieht ;-)

**Comment by NitramLegov** [comment]
Added the commissioning template to the wiki.

**Comment by LukasFreeze** [comment]
Ich habe heute eine Wandhalterung für die Drechseleisen gebaut, funktioniert ganz gut und kann noch deutlich erweitert werden.

Falls die Werkzeuge im Gebrauch doch mal umfallen sollten, könnten wir in den unteren Teil noch mehrere dreieckige Stücke kleben sodass es pro Griff eine Vertiefung gibt (oben hat schon jedes Eisen einen Begrenzung)

**Comment by LukasFreeze** [comment]
@Johannes09 und ich haben gestern ein bisschen geschweißt. Die Reitstock-Schraube hat jetzt zwei Knubbel, damit sie nicht mehr durchdreht sondern sich anständig an der Oberseite verkantet.

Einen Hebel an die Mutter der Werkzeugauflage zu schweißen hat nicht sooo gut funktioniert, allerdings könnten sich zwei Hebel bei kleinen Werkstücken auch gegenseitig blockieren - also habe ich die bestehende Hebel-Mutter jetzt einfach an der Werkzeugauflage montiert, die man bei jedem Projekt mehrmals justiert, und der Reitstock, der seltener verändert wird, braucht jetzt eben Werkzeug.

Ein größer werdendes Problem ist gerade die wacklige (und meistens schräge!) Werkzeugauflage, das wäre die nächste wichtige Reparatur...

**Comment by LukasFreeze** [comment]
Die Werkzeugauflage ist jetzt bombenfest - Patrick hat das Loch für die Madenschraube aufgebohrt und stattdessen ein Gewinde in die senkrechte Stange geschnitten, sodass jetzt der obere Teil mit einer Schraube fest herangezogen wird statt nur in Position geklemmt zu werden. Das sollte halten, vielen Dank!

bleiben hier nur noch die Verbesserungen rund ums Schärfen :-)

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by LukasFreeze** [comment]
Anständige Drechselbank - 2000 € 😆

Nee, also dieses Issue ist hauptsächlich noch eine Erinnerung dass wir
immer noch nicht wirklich schärfen können und braucht hauptsächlich Doku
statt Geld

**Comment by LukasFreeze** [comment]
das Thema "Schärfen lernen" bekommt ein neues Issue, da die ursprünglich hier beschriebene Drechselbank nicht einmal mehr im Space residiert und es gerne aus dem Titel erkennbar sein dürfte worum es geht :-P
