### ISSUE TITLE
Projector not working

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#72]
We need a new one

**Comment by NitramLegov** [comment]
At least today it did not want to work with the mac of @Pakue95 . However, this might have been an adapter issue.
In general, I basically opened this issue in order to track and coordinate a replacement (@beanobeano mentioned he might get a donated one. If not, @Chris0812 has one he could possibly sell to the space).

**Comment by LukasFreeze** [comment]
It also failed for me on a VGA port without adapter the other day, and it
looks like there are overheating issues that cause it to shut down. We
definitely need a new one soon...

@Chris0812 could you tell us more about your projector?

**Comment by LukasFreeze** [comment]
The donated one that Ciaran was able to get seems to work fine :-)

It's bigger and definitely needs a better ceiling mount than we have now, I'll see if there is time to build something like [this](https://makezine.com/projects/build-six-axis-positioning-platform-stuff-can-buy-hardware-store/) tomorrow evening! There should also be a steel cable "failsave" with an independent anchor.

**Comment by NitramLegov** [comment]
The [wiki](https://wiki.comakingspace.de/Projector) now contains information about network control of the projector.

**Comment by NitramLegov** [comment]
I ordered some network cable in order to connect the projector with our internal network. It should arrive until tomorrow evening.
Since this will use the last free port of our router, we should consider adding a switch next to it.
I think I saw a switch in the storage room last time I was in there ;)

**Comment by NitramLegov** [comment]
The projector is now added to our network. It seems to work fine so far.
