### ISSUE TITLE
Bring the wood back to the workshop

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#74]
Before the open day, a lot of wood was moved out of the wood workshop due to missing space.
We should think about how to bring this back and then bring it back.

**Comment by emka** [comment]
If I remember correctly we needed a clean storage option. Until there is a material cart built to neatly organize it, the current position seems like the most clean solution.

**Comment by NitramLegov** [comment]
Yes, I totally agree. This issue was created during the plenum just in order to track the topic :)
Basically it was part of the discussion of what could be done during a do-something session. As you mentioned, building a proper storage solution and then bringing back the wood would be a good thing to work on.

**Comment by LukasFreeze** [comment]
After seeing how quickly the wood corner became a huge mess and how large pieces had next to zero turnover, I don't think it should be our goal to bring *all the wood* back out.

Maybe some of it, but not until we have finished the shelf (#19) and/or another effective storage solution. The large sheets should never be stored in the woodshop again in my opinion, if someone really needs them it should be fine to coordinate with one of us managers to get it out (still easier than buying a new one).

The most important consideration for building a lumber cart should be "where will **that** fit?" Even something large enough to hold hust all the medium sized pieces would have to be larger than the clamp cart...

**Comment by NitramLegov** [comment]
Since most of the Wood will most likely stay on the shelf (#19) and the rest will stay in the storage until somebody really needs it, I would say we don´t really need this issue anymore.
