### ISSUE TITLE
PC in the Electronics Room mounts SD-Cards as read-only

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#75]
The PC in the electronics room currently mounts the SD-Cards from the printers as read-only
We formatted them on friday, but that did not help. Other PCs (running Windows or MacOS) do not seem to have a problem with the cards.

When checking the output of 'mount', it indicates there was an error during mounting and it therefore mounted it as ro. Checking the logs might give an indicator about what is wrong.
Other than that, @Pakue95 proposed to just reinstall ubuntu. This would most likely also solve the issue.

Maybe it is best to leave the decision to the 3D-printer area patrons.

**Comment by p---** [comment]
Fixed. 2 SD cards were write-protected by the lock switch. SD cards were checked by disk utility tool (https://askubuntu.com/questions/69932/is-there-an-sd-card-diagnostic-utility#69937). 
Blue sd card reader was broken and has been discarded. White sd card reader working.
