### ISSUE TITLE
kaputte Schraubzwingen reparieren

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#76]
@lmnl99 hat gerade drei Zwingen, bei denen der untere Teil immer wieder vom Stab gerutscht ist, mit Blindnieten repariert.

Drei weitere brauchen neue Griffe und liegen unter der Drechselbank, im Lager sind außerdem noch welche die wir schweißen müssten.

Wir haben außerdem einige, die man mehr oder weniger nutzen kann aber denen der Teller fehlt - Ideen, wie man die wieder hinkriegen könnte?

**Comment by Pakue95** [comment]
*momentan liegen 4 mit kaputten Griffen bei der Drechselbank. 

Bei zwei habe ich mal die Pins rausgehämmert, die die Metal-Endkappe am Gewindeende festhalten. Die anderen muss man wahrscheinlich aufbohren weil der Pin zu fest sitzt.

**Comment by LukasFreeze** [comment]
Der Drechselkurs war in dieser Hinsicht heute sehr produktiv! Zusammen mit dem Griff vom Bahnstadtfest konnten wir 3 Zwingengriffe reparieren, fehlt nur noch einer :-)

Es haben allerdings immer noch sehr viele Zwingen keinen "Teller" mehr - vielleicht könnte man die (zumindest für die hochwertigen/großen Zwingen mit solidem Kugelkopf) als Einsteiger-Drehprojekt aus Metall fertigen und mit etwas Hitze aufpressen?

**Comment by NitramLegov** [comment]
Wir haben inzwischen ja eine recht ansehnliche Zwingensammlung. Ist dieses issue etwas, was wir trotzdem noch weiterverfolgen oder sollten wir hier eher zumachen?

**Comment by LukasFreeze** [comment]
@Pakue95 hat in letzter Zeit einige kaputte ins Büro geholt glaube ich, was
ist da der Plan? Falls die nicht gemeinsam repariert werden sollen,
brauchen wir natürlich auch dieses Issue nicht mehr

**Comment by kenomaerz** [comment]
Falls es hier Bedarfe gibt, die wir sinnvoll als Spende formulieren können: Bitte hier die benötigten Bauteile und deren Preis listen und mich verlinken. Neue Werkzeuge können wir über betterplace.org als Spende durch Mitglieder finanzieren.

**Comment by Pakue95** [comment]
> @Pakue95 hat in letzter Zeit einige kaputte ins Büro geholt glaube ich, was ist da der Plan? Falls die nicht gemeinsam repariert werden sollen, brauchen wir natürlich auch dieses Issue nicht mehr
> […](#)

Sehe dazu nicht wirklich den Bedarf. Noch haben wir genug Zwingen, und die Resonanz war jetzt nicht wirklich groß, dass sich Leute zur Reparatur meldeten.
