### ISSUE TITLE
passendes Gewinde für Drechsel-Backenfutter

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#78]
Micha hat uns vor einer Weile ein Vierbackenfutter für die Güde-Drechselbank mitgebracht, das Gewinde darin ist allerdings etwas zu klein.

M18 würde passen, @Johannes09 hat diese Woche auch Gewindeschneider dafür mitgebracht, also müsste das zu beheben sein!

- [ ] nachschauen, ob das Gewinde wirklich nur in der "Montageplatte" ganz hinten am Futter sitzt
- [ ] neue Montageplatte mit M18-Gewinde drehen
- [ ] alte Platte mir oder direkt Micha geben

**Comment by NitramLegov** [comment]
Die Güde ist ja inzwischen nicht mehr im Space. Und die neue hat ein passendes Vierbackenfutter :)

Darum mache ich hier mal zu. Falls es hier doch noch etwas zu tun gibt: Gerne nochmal öffnen.
