### ISSUE TITLE
Halterungen für Lappen

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#79]
Wir haben an verschiedenen Orten (z.B. Holzwerkstatt, Bad, Küche) viele Lappen, bei denen unklar ist wofür sie vorher verwendet wurden. Dafür könnte man an den drei Orten ein Organisationssystem bauen, zum Beispiel ein (wasserfestes?) Brett mit Klammern und Platz für eine Beschriftung über der Klammer.

Dann kann man jeden Lappen mit Beschriftung aufhängen und weiss wofür er gedacht ist. Die Klammern sollten so weit auseinander sein, dass sich die verschiedenen Lappen nicht berühren.

**Comment by emka** [comment]
Kims Idee: eine Wäscheleine oder ein Draht (z.B. zwischen 2 Schrauben) mit Klammern.

**Comment by LukasFreeze** [comment]
klingt gut, Holzwäscheklammern kann man auch einfach direkt beschriften

**Comment by emka** [comment]
Patrick ist dafür, Lappen nach der Benutzung wegzuwerfen.

**Comment by NitramLegov** [comment]
Ich auch
________________________________

**Comment by LukasFreeze** [comment]
Um Lappen zum Wegwerfen kann sich ja jeder selbst kümmern, ich dachte es
geht hier um die Putzlappen vom Space?

Ich bin dafür, wenigstens die etwas nachhaltiger zu nutzen und habe auch
keine Lust dauernd neue zu kaufen...

**Comment by NitramLegov** [comment]
Naja, selbst bei den Putzlappen vom Space finde ich eine Mehrfachbenutzung fraglich. Das Handtuch in der Küche zum Beispiel möchte ich nicht mehr anfassen. Danach ist man gefühlt dreckiger als zuvor.

Lappen mehrfach zu benutzen ist ja sicherlich sinnvoll, aber dann bin ich eher dafür, dass man irgendwo eine Wäschesammlung einrichtet, in die Lappen nach der Benutzung bitte direkt reinfliegen sollen (wenn nicht gerade jemand Öl damit aufgewischt hat). Die kann man dann ja immer wenn Bedarf ist mal bei 90° durch die Waschmaschine jagen und gut ist.

Fänd ich besser als ein ausgeklügeltes Lagerungssystem bei dem man sich nie sicher sein kann, ob sich die Leute auch dran halten.

**Comment by Pakue95** [comment]
Hat sich hierzu inzwischen was getan?

**Comment by LukasFreeze** [comment]
Mit dem Platz der durch #85 frei wird wollte ich eine Wäschekiste realisieren.

**Comment by Pakue95** [comment]
Ich spiele mal Stalebot, da sich bei dem Issue seit fast 2 Jahren nichts getan hat.
