### ISSUE TITLE
CNC router

### ISSUE THREAD

**Issue by Pakue95** [comakingspace/do-something#8]
We've got a [WorkBee CNC router](http://ooznest.co.uk/3D-Printer-CNC-Kits-Bundles/WorkBee-CNC-Machine/WorkBee-CNC-Full-Kit) from Ooznest with the 1500x1500mm belt drive.

To get it up and running a few things need to be done:

- [x] Build mechanical part of the CNC router
- [x] Assemble electrical parts
- [x] Test it!
- [x] Cable Management 
  - Trim to length 
  - attach ring terminals 
  - get and install 5 m USB cable for control
    - alternative: install raspi to the router and control the router via it. Access via WiFi. 
- [x] Build table
  - for easier access and storage room
- [x] Find best workflow
  - [x] CAM (e.g. Fusion360)
  - [x] Controller/GCode sender
- Build dust collection
 - [x] attachment for router
 - [ ] flexible hose
 - [ ] cyclone dust separator (#15)

**Comment by LukasFreeze** [comment]
Moritz suggested a frame consisting of dimensional lumber for the table structure. If we make sure the wooden frame is in line with the aluminum extrusions of the machine's frame we might not even need a tabletop! That would save quite a bit of money.

**Comment by LukasFreeze** [comment]
started a (very basic) wiki page: [CNC Router](https://wiki.comaking.space/CNC_Router)

**Comment by Pakue95** [comment]
@emka and I finished the router yesterday and it works so far nicely. The cables are not yet cut to length and should receive some ring terminals. A final adjustment of the frame and rollers should be done once the machine is on it’s table.

**Comment by Pakue95** [comment]
The current plan for the table is to use 3 of the workbenches from Bauhaus, bolt them together and mount the third one on the wall. This should result in a quick and stable table for the router. 

We can either wait for the tables from EMBL to arrive and replace the tables in the CoMaker room with them, or just take out 3 and get the router up and running quicker.

**Comment by LukasFreeze** [comment]
I would say the router should be the top priority.

How about taking the front left and both middle CoMaking benches, and
bringing in one of the self-built common room tables for the time before
the EMBL tables arrive? That would also make the common room a bit more
open, I think there are too many tables right now (blocking screws and
future locker locations)

**Comment by Pakue95** [comment]
Sounds good to me.

> Am 15.02.2018 um 10:07 schrieb Lukas <notifications@github.com>:
> 
> I would say the router should be the top priority.
> 
> How about taking the front left and both middle CoMaking benches, and
> bringing in one of the self-built common room tables for the time before
> the EMBL tables arrive? That would also make the common room a bit more
> open, I think there are too many tables right now (blocking screws and
> future locker locations)
>

**Comment by Pakue95** [comment]
Table is now build and the router is in place. I designed some part to level the frame on the table. If any of you is in the space for 2 hours you could start the print. It is on P3 in my folder called RouterLevel.

**Comment by sbillaudelle** [comment]
Yesterday, I shortened most of the wires and routed them more cleanly.

I will try to extend the router's cable tomorrow or on Sunday. Maybe I will manage to mount the waste board and level the whole thing. We'll see…

**Comment by emka** [comment]
Universal Gcode Sender 2.0 (stable nightly) works well.

We build a basic dust collection that works with the vacuum cleaner attached. Splitting out the cyclone dust separator in a separate issue.

**Comment by Chris0812** [comment]
The Homing does not work properly: The Z-endstop doesn't seem to trigger

**Comment by NitramLegov** [comment]
I moved the comment from @Chris0812 to a new issue: #62  since this issue here was already closed and I don´t think we should reopen it.
