### ISSUE TITLE
Do-Something am 10.11.

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#81]
@Johannes09 und ich würden am Samstag gerne einen do-something day machen.

Fokus wäre die Metallwerkstatt, aber wie immer sind wir da natürlich flexibel.

- Fensterbank aufräumen
- Platz für die Sachen auf der Fensterbank finden
- Gewindebohrer ggf. aufräumen
- Platz für die Doppelschleifer finden / schaffen
- Den alten Sägetisch / neuen Schweißtisch(??) aufräumen
- idealerweise vor der Tür nach draußen aufräumen (Schränke die da seit Wochen stehen könnte man ggf. mal wegwerfen..........🙊)
- Der precious plastics shredder müsste auch nicht unbedingt mitten im Raum stehen.

Das ist jetzt nur mal quick & dirty aufgeschrieben was mir so einfällt. Es gibt bestimmt noch mehr.

Zeitlich sind wir flexibel und könnten anfangen, sobald ein Manager verfügbar ist :)

**Comment by NitramLegov** [comment]
Je nachdem, wie viele Leute wir sind und welche Skills entsprechend vorhanden sind könnte man sich auch noch um folgende issues kümmern:
#9 
#6 
#70 
[hier](https://github.com/comakingspace/do-something/issues?q=is%3Aissue+is%3Aopen+label%3A%22metal+workshop%22) sind alle issues mit label metal workshop.

**Comment by Johannes09** [comment]
- stahllager bauen 

- spänewanne bauen 

- schrotte entsorgen (späne vom drehen)

**Comment by Pakue95** [comment]
Ich hätte am Samstag ab 13 Uhr für do-something hours Zeit. Die Metallwerkstatt hat etwas Organisation durchaus nötig ;D.

**Comment by LukasFreeze** [comment]
Ich kann diesen Samstag leider nicht, aber ich würde vorschlagen dass ihr den Termin auch noch so bald wie möglich über die Liste schickt, wird hier ja leider nicht von allzu vielen Leuten gesehen.

Noch ein paar Gedanken zu den Plänen:
> Platz für die Doppelschleifer finden / schaffen 

Ich wäre dafür, eine "Schärfstation" direkt neben der Tür, wo gerade noch der Schweißtisch steht, aufzubauen. Der kleine Doppelschleifer neben der Drehmaschine wurde ganz am Anfang mal dort gewünscht, stört er jetzt?

> idealerweise vor der Tür nach draußen aufräumen (Schränke die da seit Wochen stehen könnte man ggf. mal wegwerfen...)

Ich habe den Schrankbesitzer angeschrieben, dachte auch das Teil sollte da nur kurz stehen... er hat wohl am Wochenende ein Auto und holt ihn ab.

Die Fahrräder gehören @beanobeano und er möchte daran was schweißen, wenn #10 fertig ist.

> Der precious plastics shredder müsste auch nicht unbedingt mitten im Raum stehen.

absolut, der wurde scheinbar nach dem Treffen neulich vergessen :-/ Allerdings wird durchaus bald etwas Platz für Precious Plastic benötigt werden (vielleicht vor den Fenstern, links von der Strahlkabine?), Armin wollte einen Tisch konstruieren.

> stahllager bauen

Was soll denn da gelagert werden? Genau wie beim Holz können wir eh nicht alles auf Lager haben was gebraucht wird und sollten meiner Meinung möglichst wenig Bodenfläche verbrauchen und höchstens ein paar **sehr** häufig gebrauchte Teile bevorraten.

**Comment by NitramLegov** [comment]
> Ich kann diesen Samstag leider nicht, aber ich würde vorschlagen dass ihr den Termin auch noch so bald wie möglich über die Liste schickt, wird hier ja leider nicht von allzu vielen Leuten gesehen.
Ist schon in meinen Entwürfen, kommt bald :)

> > Platz für die Doppelschleifer finden / schaffen
> 
> Ich wäre dafür, eine "Schärfstation" direkt neben der Tür, wo gerade noch der Schweißtisch steht, aufzubauen. Der kleine Doppelschleifer neben der Drehmaschine wurde ganz am Anfang mal dort gewünscht, stört er jetzt?
Stören nicht wirklich. Ähnlich wie du fände ich eben eine "Schärfstation" cool. Da würden für mich dann beide Doppelschleifer hingehören. Aber wie gesagt, der stört da wo er ist auch nicht wirklich. Können wir dann ja am Samstag kurz drüber sprechen. Was mich persönlich stört ist der "neue" Schleifer, der einfach mitten auf dem Tisch steht. Der sollte meiner Meinung nach an einen Platz kommen, wo er auch erstmal bleiben kann. 
 
> > idealerweise vor der Tür nach draußen aufräumen (Schränke die da seit Wochen stehen könnte man ggf. mal wegwerfen...)
> 
> Ich habe den Schrankbesitzer angeschrieben, dachte auch das Teil sollte da nur kurz stehen... er hat wohl am Wochenende ein Auto und holt ihn ab.
> 
> Die Fahrräder gehören @beanobeano und er möchte daran was schweißen, wenn #10 fertig ist.
Da steht ja noch mehr. Da steht auch der "Schmelzofen" von @lmnl99  und @Chris0812.
Ich will das nicht päpstlicher sehen als der Papst, aber für mich ist eben auch der Platz hinter dem Space kein Lagerplatz für persönliche Projekte. Wäre aber für Samstag auch nicht unbedingt eine Top-Priorität.

> > stahllager bauen
> 
> Was soll denn da gelagert werden? Genau wie beim Holz können wir eh nicht alles auf Lager haben was gebraucht wird und sollten meiner Meinung möglichst wenig Bodenfläche verbrauchen und höchstens ein paar **sehr** häufig gebrauchte Teile bevorraten.

Naja, momentan liegt der Stahl auf dem Tisch hinten in der Ecke auf dem auch die Strahlkabine steht. Ein Teil davon ist meines Wissens nach auch etwas länger als der Tisch und schaut in den Raum hinein. Das muss ja nicht wirklich sein. Wenn man das hochkant lagert kann man da ja viel Platz sparen und recht viel Stahl auf wenig Fläche lagern. Größtenteils sind das ja keine Bleche, sondern eher Stäbe. Und wenn wir es nicht platzsparend in der Metallwerkstatt lagern können sollte es eben wie das Holz entsprechend wo anders hin kommen. So wie es jetzt ist ist es ungeschickt.

**Comment by LukasFreeze** [comment]
Ich bin da überall voll bei dir, wollte auch nichts bremsen sondern nur sicher gehen dass möglichst nachhaltige Verbesserungen gemacht werden :-)

Was die Doppelschleifer angeht hätte ich persönlich nichts dagegen beide zusammen zu haben, man braucht ja eh oft mehrere verschiedene Körnungen für das gleiche Werkstück. Aber es gibt (oder zumindest gab) auf jeden Fall auch Gründe für die jetzige Position des kleinen grünen, ging damals glaube ich um das Schleifen von Drehmeißeln? @Pakue95 @Johannes09 das könnt ihr wahrscheinlich am besten bewerten.
Warum ich aber vor allem gestutzt hatte, als ich beide Geräte auf der to-do-Liste gesehen habe: eine schöne Schärfstation dürfte mehr Planung erfordern als bis Samstag möglich sein wird und da wäre ich der Meinung, dass der alte Schleifer erst abmontiert werden sollte wenn ein neuer Platz feststeht, an dem er nicht nur in zweiter Reihe geparkt wird. Der geliehene von Micha sollte natürlich möglichst bald einen Platz bekommen, auch wenn es nur ein provisorischer Tisch ist!

Für eine Schärfstation mit möglichst vielen Funktionen würde ich gleich mal ein [Wiki-Projekt](https://wiki.comakingspace.de/Project:Sharpening_Station) aufmachen, wenn ich mich richtig erinnere gibt es da auch gute Beispiele in meinem "Workshop Idea Book" im Gemeinschaftsraum :-)

Thema Metalllager: klar ist das unter dem Tisch keine Dauerlösung, dachte nur es geht um eine Erweiterung der Kapazitäten statt einer Neuordnung 😅

**Comment by Pakue95** [comment]
Zum Drehmeißel schleifen ist es eigentlich ziemlich egal wo im Raum der Schleifer steht. Wenn die Drehbank etwas vom Metallstaub geschützt ist schadet das auch nicht.

**Comment by NitramLegov** [comment]
Auch bei etwas geringerer Beteiligung als die letzten Male konnten wir gestern doch einiges erledigen:
-	Die Metallwerkstatt ist wieder aufgeräumt
-	Der Metallschrott wurde entsorgt
-	Es gibt nun ein Lager für Stahlbleche/Stäbe/Profile in der Ecke. Wichtig: Alles was kürzer als 30cm ist fällt durch und soll bitte entsorgt werden.
-	Das Flexzubehör hängt nun an der Wand
-	Die Doppelschleifer stehen nun in einer anderen Ecke, etwas weiter von der Drehmaschine weg (die vertragen sich nicht wirklich)
-	Der Ofen hat einen neuen Platz gefunden neben der Strahlkabine und (hoffentlich bald) dem Precious Plastic Shredder

Außerdem wurde das neue Lager für die Holzschrauben fertiggestellt und das zugehörige Issue #14  geschlossen.

![dsc_0455](https://user-images.githubusercontent.com/7809163/48318456-9ab97000-e601-11e8-8826-076469519f7e.JPG)
![Uploading DSC_0456.JPG…]()
![Uploading DSC_0457.JPG…]()
![Uploading DSC_0458.JPG…]()
![Uploading DSC_0459.JPG…]()
![Uploading DSC_0461.JPG…]()
![Uploading DSCPDC_0003_BURST20181111020429229_COVER.JPG…]()
