### ISSUE TITLE
Metallregal im E-Workshop aufräumen

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#82]
Im Metallregal im E-Workshop stehen einige ziemlich volle Boxen rum, in denen diverses Zeug ist.
Teilweise Kabel, Netzteile, andere Elektronik, aber ggf. auch Zubehör für die 3D-Drucker.

Ich denke das sollte gemeinsam mit den Eckpaten (@Johannes09  und @lmnl99 )mal durchgesehen werden um zu entscheiden, was davon noch sinnvoll nutzbar ist und was weg kann.

**Comment by Johannes09** [comment]
können wir das issue schließen?

**Comment by NitramLegov** [comment]
Jep
