### ISSUE TITLE
Do-Something Day im Dezember

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/do-something#83]
Hallo zusammen,

ich würde im Dezember gerne wieder einen do-something day machen.
Da es aktuell ja noch der Verfügbarkeit eines der Manager Bedarf: @emka , @Pakue95 @LukasFreeze @beanobeano : Wie siehts denn bei euch aus? Meine Vorschläge wären:
Samstag der 08.
Sonntag der 09.
Samstag der 15.
Sonntag der 16.
Samstag der 22.

Als Fokuspunkt schlage ich dieses mal die Elektronikwerkstatt vor. Von issue #82 bis zu Museumsreifen Werkzeugen neben dem Slic3r PC sowie dem aufräumen und ordnen der E-Bench ist da doch einiges zu tun.

Falls Zeit ist könnten wir auch den CNC Raum mal aufräumen. Der hat es auch nötig :)

@Johannes09 und @lmnl99 wie sieht es denn bei euch als Eckpaten aus?

Grüße,
Martin

**Comment by lmnl99** [comment]
Ich finde die Idee nicht schlecht. Ich hätte an allen Terminen Zeit. Wenn wir alle anpacken geht es schneller.



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: NitramLegov <notifications@github.com>
Datum: 25.11.18 16:48 (GMT+01:00)
An: comakingspace/do-something <do-something@noreply.github.com>
Cc: lmnl99 <Luca.nelius@hotmail.com>, Mention <mention@noreply.github.com>
Betreff: [comakingspace/do-something] Do-Something Day im Dezember (#83)


Hallo zusammen,

ich würde im Dezember gerne wieder einen do-something day machen.
Da es aktuell ja noch der Verfügbarkeit eines der Manager Bedarf: @emka<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femka&data=02%7C01%7C%7C48d1e3aed20f4fb64ac108d652ed65bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636787576892517744&sdata=azwXuVc8nLKOELqNzcIMK73nK%2BIEwotnbVCoRT9Zigg%3D&reserved=0> , @Pakue95<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPakue95&data=02%7C01%7C%7C48d1e3aed20f4fb64ac108d652ed65bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636787576892517744&sdata=9i0ZSmB%2BMdFuTxJUF%2F9QrWFNOj946IxKJQ2UFDQEDdo%3D&reserved=0> @LukasFreeze<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLukasFreeze&data=02%7C01%7C%7C48d1e3aed20f4fb64ac108d652ed65bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636787576892517744&sdata=sqitko%2B9TmTkuEre3w1GuNrbNSCPcA91OU9GocfVKlc%3D&reserved=0> @beanobeano<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbeanobeano&data=02%7C01%7C%7C48d1e3aed20f4fb64ac108d652ed65bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636787576892517744&sdata=TxzlHB6Xs5DtZJu7v4XMfyENUg7mbeR%2F0N2HzBYWvuU%3D&reserved=0> : Wie siehts denn bei euch aus? Meine Vorschläge wären:
Samstag der 08.
Sonntag der 09.
Samstag der 15.
Sonntag der 16.
Samstag der 22.

Als Fokuspunkt schlage ich dieses mal die Elektronikwerkstatt vor. Von issue #82<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcomakingspace%2Fdo-something%2Fissues%2F82&data=02%7C01%7C%7C48d1e3aed20f4fb64ac108d652ed65bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636787576892517744&sdata=oeJawIWmg8Sp03ewc4ZY2VTj3ujpuSKLxOcBpRQkD%2FQ%3D&reserved=0> bis zu Museumsreifen Werkzeugen neben dem Slic3r PC sowie dem aufräumen und ordnen der E-Bench ist da doch einiges zu tun.

Falls Zeit ist könnten wir auch den CNC Raum mal aufräumen. Der hat es auch nötig :)

@Johannes09<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJohannes09&data=02%7C01%7C%7C48d1e3aed20f4fb64ac108d652ed65bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636787576892517744&sdata=gAPm0F3cC6Vf4HBJ9wSQnbQsv14Qsh74jLJVKJ%2Bcjeo%3D&reserved=0> und @lmnl99<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flmnl99&data=02%7C01%7C%7C48d1e3aed20f4fb64ac108d652ed65bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636787576892517744&sdata=Uhe4xMlsu51DgEyixMuL%2FIcWpKa7KHA1Ft%2BY%2FJFgxWQ%3D&reserved=0> wie sieht es denn bei euch als Eckpaten aus?

Grüße,
Martin

**Comment by Johannes09** [comment]
Kann nur am 8. nicht

**Comment by LukasFreeze** [comment]
Ich bin leider raus, keine freien Wochenenden in der Vorweihnachtszeit :-P

Falls ich unter der Woche mal Zeit für die Schweißecke habe werde ich das aber auch gerne als "do-something hours" ankündigen...

**Comment by Chris0812** [comment]
+1 für den 16.12

**Comment by beanobeano** [comment]
I'm not available.

**Comment by NitramLegov** [comment]
Since December is over now, i´m closing this one.

It would be great if we would be able to host do-something days ourself soon..
