### ISSUE TITLE
anständige Müllsackhalter im Gemeinschaftsraum

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#85]
Wir brauchen eine Lösung für das Müll-Chaos, jetzt wo wir mehr Leute werden: Müllsäcke/-kisten/-eimer quellen oft über und es wird nicht allzu gut getrennt.

Mit besseren Müllsackhaltern könnten wir das hoffentlich verbessern, meine Ideen:
- alle drei Sorten (Papier, Restmüll, gelber Sack) direkt nebeneinander - auf einen Blick sichtbar
  - unter der Arbeitsschutz-Wand? Dann mit Fallschutz, damit nichts versehentlich im Müll landet
- stabile Halter, nicht die provisorischen Kleiderbügel wie bisher
  - vielleicht sogar direkt mit begrenzter "Einwurföffnung"
- Papier lose in möglichst leichtem, transportablem Behälter
- gelber Sack in gelben Säcken (gibt es kostenlos in jedem Bürgeramt)
- Restmüll in etwas kleineren Säcken, da es sonst schnell stinkt
- "Spender"/Halter für die neuen Müllsäcke - schafft Übersicht und macht Platz im Küchenschrank
- klare Beschriftungen:
  - was gehört wohin?
  - "voll? Bitte raus in die Tonne!"
  - "zu groß? Bitte direkt nach draußen in die Tonne!"
  - etc.

**Comment by LukasFreeze** [comment]
weitere Ideen, z.B. für den Außenbereich, im [Protokoll vom heutigen Plenum](https://wiki.comakingspace.de/Plenum/Meeting_minutes/2018-12-05) :-)

**Comment by LukasFreeze** [comment]
Ich habe am Freitag/Samstag noch mit der Ecke angefangen, bin allerdings noch nicht sonderlich weit gekommen. Also bitte nicht wundern, dass es noch *etwas* provisorisch aussieht ;-)

Eine Holzwand steht schon, daran kann man jetzt mit relativ wenig Aufwand (und vor allem ohne Ausbrechen/Wandern der Bohrlöcher) Müllsackhalter bauen. Zuerst würde ich aber eine Art Regalbrett unter die Sicherheitsausrüstung schrauben, damit schlecht aufgehangene Sachen lieber darauf als im Müll landen...

**Comment by NitramLegov** [comment]
Wir haben jetzt ja kleine blaue Regentonnen gekauft für die Mülltüten. Können wir damit das issue hier zumachen? :)

**Comment by LukasFreeze** [comment]
Für diese Räumlichkeiten reicht es jetzt auf jeden Fall :-)
