### ISSUE TITLE
alte Laptops zum Laufen bringen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#87]
@Chris0812 hat uns zwei Laptops mitgebracht! Die müssten halt ca. 5-10 Jahre alt sein, aber als Wiki-Terminals noch locker reichen.

- Twinhead Durabook
  - braucht Netzteil (20 V, 3 A)
    - @lokowandg hat uns erstmal eins geliehen, das ist aber zu schwach (reicht zum Akku laden, aber nicht für Volllast)
  - braucht Maus
  - nicht sicher, ob schon WLAN-fähig - Treiber müssen ggf über LAN geladen werden
  - OS: @lokowandg hat eine Festplatte gespendet und Xubuntu darauf installiert

- Lifebook T Series
  - braucht Netzteil (19 V, 4.22 A)
    - @LukasFreeze hat ein passendes, das er mitbringen *will*
  - braucht Festplatte
 
Soweit erstmal, was wir schon wissen - vielleicht kommt da mit der Zeit aber natürlich noch was zu ;-)

**Comment by Johannes09** [comment]
Twinhead Durabook
 Das Netzteil von @lokowandg ist nicht zu schwach es liefert nur die falsche Spannung (1V zu wenig) kann aber mit einem Widerstand behoben werden (6kohm) 
 WLAN funktioniert einwandfrei

**Comment by LukasFreeze** [comment]
Danke, gut zu wissen! Am Netzteil rumzubasteln lohnt sich leider
wahrscheinlich trotzdem nicht, weil wir das nicht behalten können...nur
eine kurze Leihgabe um den Laptop zu testen.

@lokowandg meinte am Mittwoch übrigens noch, dass er mal nach einem
RAM-Upgrade schauen würde, weil das Durabook mit ein paar offenen
Browser-Tabs sehr langsam ist.

**Comment by NitramLegov** [comment]
Also wenn das RAM-Upgrade billig ist kann man das durchaus machen. Wenn wir allerdings jetzt schon in Performance Probleme laufen kann man auch überlegen, auf Arch umzusteigen und LXDE als window manager zu nutzen oder - wenn es ein Kiosk-system sein soll - komplett auf den Window Manager zu verzichten bzw. sowas wie Matchbox zu nutzen. Dann sind die Teile halt nur fürs Browsen nutzbar...

**Comment by lokowandg** [comment]
Ich habe noch zwei Speicherriegel rumliegen, von denen hoffentlich einer passt. --> RAM Upgrade müsste billig sein. 
Beim Window-Manager ist es schon xfce drauf, lxde könnte man auch mal probieren, vieleicht bringt es was. 
Irgendwann brauche ich aber mein Netzteil zurück, da sehe ich den größten Kostenfaktor.

**Comment by SystemOverlord** [comment]
Wenn ein Browser laufen soll ist zwischen LXDE und XFCE kaum mehr ein Unterschied, die 30 MB mehr freier RAM fallen bei den 300MB die Firefox im idle braucht nicht mehr auf.

**Comment by NitramLegov** [comment]
Ich schätze hier wird niemand mehr Aufwand reinstecken.
