### ISSUE TITLE
Strahlkabine herrichten

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#9]
Wir haben eine Strahlkabine zum Sandstrahlen bekommen! Bevor wir damit loslegen können ist aber wie so oft noch einiges zu erledigen:

* [ ] Wiki-Seiten anlegen (möglichst mit Fotos und grundlegenden Informationen)
  * [ ] [blast cabinet/*Strahlkabine*](https://wiki.comaking.space/Blast_Cabinet)
  * [ ] [blast media/*Strahlmittel*](https://wiki.comaking.space/Material:Blast_Media)
  * [ ] [abrasive blasting/*Sandstrahlen*](https://wiki.comaking.space/Category:Abrasive_Blasting)
* [ ] Staubsauger-Adapter mit seitlichem Loch basteln, damit kein zu hoher Unterdruck entsteht (sonst platzen die Handschuhe) - dabei sollte die Zyklon-Abscheide-Tonne mitbenutzt werden
* [ ] Erdungsarmband
* [ ] alten, kaputten "Sauger"-Schlauch abklemmen oder notfalls zulöten (aktuell steckt irgendein Metallteil als Stopfen drin, das zum Projektil werden könnte
* [ ] große, stabile Gummihandschuhe kaufen und ein Paar anbringen

Nen passenden Kompressor bringe ich im Frühling vorbei, ein bisschen Korund als Strahlmittel haben wir schon :-)

Falls jemand Ahnung hat oder etwas praktisches beitragen kann, am besten hier kommentieren oder direkt ins Wiki schreiben! Das gute Stück steht im Moment in der Metallwerkstatt in einer Kiste in der Ecke.

**Comment by LukasFreeze** [comment]
Der Kompressor ist mittlerweile in der Metallwerkstatt und betriebsbereit: https://wiki.comaking.space/Compressor :-)

**Comment by NitramLegov** [comment]
Added the commissioning template to the wiki

**Comment by Pakue95** [comment]
Andre braucht die Sandstrahlkabine wieder selbst und hat seine Leihgabe beendet. Von daher kann das Issue hier zugemacht werden.
