### ISSUE TITLE
3D Drucker P5 bleibt zum zweiten mal wärend des Drucks stehen

### ISSUE THREAD

**Issue by Kai1977** [comakingspace/do-something#93]
Hallo,

der 3D Drucker **P5** ist nun zum zweiten mal während des drucks stehen geblieben.
Das letze mal war es ein anderes Modell. Am Gcode liegt es also wahrscheinlich nicht.
Hotend und Heizbett blieben dabei  auf Temperatur (Bild 1 und 2).
Als ich ins Menü vom Drucker gegangen bin, wurde mir Resume angeboten. Nach dem drücken von Resume wird jedoch das Hotend nicht mehr beheizt. Es kühlt ab (Bild 3). Der 3D Drucker wartet die ganze Zeit. Ich bin dann auf Pause gegangen und habe manuell auf Preheat PLA gestellt. Nach dem aufheizen fährt der Drucker die Nozzle ins Bett. Ich bin sofort auf Abbruch gegangen. Auf dem Heizbett kann ich keine neuen Kratzer erkennen.

![img_20190114_190040](https://user-images.githubusercontent.com/46687384/51133566-a6a9f400-1835-11e9-9b4a-f2dc6a168d64.jpg)
![img_20190114_190050](https://user-images.githubusercontent.com/46687384/51133567-a6a9f400-1835-11e9-8dbb-64f74cc18efa.jpg)
![img_20190114_190116](https://user-images.githubusercontent.com/46687384/51133569-a6a9f400-1835-11e9-984b-7db181db9b0c.jpg)

Issue Nummer hängt am Drucker.

**Edit1:**
Der gcode auf der SD Karte sieht auch gut aus. Ich hatte vermutet das eventuell die SD Karte einen weg hat.
Was ich seltsam finde ist, dass der Drucker bei Z59.9 stehen geblieben ist. Gedruckt wurde mit 0.2mm Schichthöhe. Nach Z59.800 kommt im gcode Z60.000, mal abgesehen vom kurzen anheben der Z Achse auf Z60.400 nach dem Schichtwechsel.

**Edit2:**
Ich hatte mich gestern in den Dateinamen geirrt. Auch wurde mit Schichthöhe 0.35mm gedruckt.
Ich habe daher den gcode von meinem USB-Stick und dem gcode auf der SD Karte mit sha512sum überprüft. Es gibt keinen Fehler.

```
SD-Karte P5:
comakingspace@3DP-PC:/media/comakingspace/351A-C378/kai$ sha512sum "Steckdosenhalter.gcode" 
0ef72d69459e780ba674a72e56b0edd50966de46d893937e4bf4eea3126e9433d07b2cef6396760d1302eb2075d9a03dadf126daebeb7af855999458f0fa5533  Steckdosenhalter.gcode

USB-Stick:
comakingspace@3DP-PC:/media/comakingspace/LIVE-SYSTEM/3D-Druck/drucken$ sha512sum "Steckdosenhalter.gcode" 
0ef72d69459e780ba674a72e56b0edd50966de46d893937e4bf4eea3126e9433d07b2cef6396760d1302eb2075d9a03dadf126daebeb7af855999458f0fa5533  Steckdosenhalter.gcode
```

Der gcode sieht im Texteditor auch korrekt aus, sofern ich es beurteilen kann.

Viele Grüße

Kai

**Comment by Kai1977** [comment]
Hallo Lukas,

das weiß ich nicht mehr. Ich hatte vor ein paar Tagen einen Deckel ohne Probleme gedruckt, der jedoch weniger als 1 cm hoch war.

**Comment by Pakue95** [comment]
Anscheinend ist das Problem auch bei [anderen](https://shop.prusa3d.com/forum/others-archive--f82/printer-stops-mid-print--t3827.html) aufgetreten. Vielleicht liegt es an der SD Karte, dass die manchmal Aussetzer kriegt.

**Comment by NitramLegov** [comment]
Ich hab mal 6 neue MicroSD-Karten bestellt und bau die Freitag in die Drucker ein. Dann ist überall das gleiche drin.
________________________________
Von: Patrick <notifications@github.com>
Gesendet: Dienstag, 5. Februar 2019 11:47
An: comakingspace/do-something
Cc: Subscribed
Betreff: Re: [comakingspace/do-something] 3D Drucker P5 bleibt zum zweiten mal wärend des Drucks stehen (#93)


Anscheinend ist das Problem auch bei anderen<https://shop.prusa3d.com/forum/others-archive--f82/printer-stops-mid-print--t3827.html> aufgetreten. Vielleicht liegt es an der SD Karte, dass die manchmal Aussetzer kriegt.

**Comment by NitramLegov** [comment]
Die neuen SD Karten (https://smile.amazon.de/Intenso-Micro-Class-Speicherkarte-SD-Adapter/dp/B00195G388) sind angekommen und in die Drucker eingebaut (ich hab sie vorher zum formatieren durch den shredder gejagt).

Vielleicht hilft das ja, ansonsten haben jetzt immerhin alle Drucker die gleiche Art von Micro-SD Karte mit Adapter. Die Karten haben auch Aufkleber für P1-P5.

**Comment by Johannes09** [comment]
bei P5 muss der der Abstand zwischen Prope und Heizbett neu eingestellt werden

**Comment by NitramLegov** [comment]
@lmnl99 ist das Thema nochmal aufgetaucht? Wenn das was @Johannes09 erwähnt hat (Abstand neu einstellen) gemacht ist könnte man hier finde ich zumachen..

**Comment by LukasFreeze** [comment]
Ich habe Mittwoch und Freitag ohne Probleme auf P5 gedruckt...

**Comment by LukasFreeze** [comment]
Das Problem ist lange nicht mehr aufgetreten, es lag also wahrscheinlich echt an den SD-Karten! Der Abstand Bett->Probe wurde auch schon lange angepasst.
