### ISSUE TITLE
Projektseiten sichtbarer machen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/do-something#96]
Mittlerweile gibt es schon recht viele Projektseiten im Wiki, was ich echt cool finde! Das "bewerben" der Seite ist allerdings eine zusätzliche Hürde, egal ob ausgedruckt an der "Project Wall" oder digital durch aktives Verlinken. Wenn ich Zeit habe dokumentiere ich auch lieber ein neues Projekt, als irgendwelche Verweise auf unansehnlichen und daher vermutlich kaum frequentierten Seiten wie [Projects](https://wiki.comakingspace.de/Projects) zu hinterlassen...und wenn sich alle dort im "oberen" Teil verlinken, haben wir auch nichts weiter als zwei hässliche Linklisten zu allen Projekten :-P

Ich hatte daher die Idee, so etwas wie Martins [QR-Code-"wikicrawler"](https://github.com/comakingspace/CommonFiles/tree/master/Printouts/QRCodes) für das halbautomatische Generieren von [Wiki-Navigationsgallerien](https://wiki.comakingspace.de/Project:Navigation_Galleries) zu entwickeln. Als erste Anwendung wären die Projektseiten ideal, aber man kann sich zahlreiche weitere Möglichkeiten vorstellen, auch mit alternativem Output für anschauliche Website-Bereiche (z.B. Übersicht aller "Holzbearbeitungsgeräte" o.ä.)

Wer von den Codern findet das ganze denn auch sinnvoll und hätte Lust, mitzumachen? Hier schonmal meine bisherigen Überlegungen:

----

Ziel: Ausgabe aller einigermaßen dokumentierten Projektseiten mit Bildern, Links und captions in "Gallery"-Wikisyntax  => ProjectInfoBox erforderlich

Eingabeparameter:
- Begrenzung der auszugebenden Seiten - zB Namespace, Kategorie(n)
- (optional) Gallery-Parameter - können genausogut auch später 1x händisch geändert werden, da gibt's auch preview
- (optional) Sprache - könnte z.B. bei Ausrüstungs-Infoboxen das erste Synonym nach "DE: " ausspucken anstatt des Titels
- (optional) randomisierte Ausgabereihenfolge

"Logik":
- Script geht durch alle Seiten, die *alle* Begrenzungs-Parameter erfüllen, und fügt die Seitennamen einer Liste hinzu
- das jeweilige Bild in der InfoBox (Parameter "image") wird ebenfalls der Liste zugeordnet
  - Seiten ohne InfoBox fliegen raus
  - Seiten ohne eigenes Bild ("[Project-default.png](https://wiki.comakingspace.de/File:Project-default.png)") fliegen raus
  - Seiten mit totem Link als "Bild" fliegen raus (etwas schwerer als die anderen Kriterien, nehme ich an)
- der jeweilige Titel der InfoBox (Parameter "project title") wird ebenfalls der Liste zugeordnet
- Ausgabe wird generiert nach diesem Muster:

```
<gallery mode=packed-hover heights=150 caption="Navigation Gallery">
File:image1.JPG|link=[[Seitenname1]]|project title 1
File:image2.JPG|link=[[Seitenname1]]|project title 2
File:imageXY.JPG|link=[[SeitennameXY]]|project title XY
</gallery>

''[[Project:Navigation Galleries|Navigation gallery]] generated with <script-link> on <date>. If you think this page needs an update, please add a missing entry manually or run the script again!''
```

**Comment by Pakue95** [comment]
Gute Idee. Man könnte bei der Gelegenheit auch eine Art "recently added" Kategorie/Gruppe machen. Damit neu hinzugefügte Projekte etwas prominenter positioniert werden.

**Comment by LukasFreeze** [comment]
Ich hab mich mal selbst dran versucht, könnte zwar noch deutlich robuster und vor allem flexibler werden aber [für die Projektseite hats schonmal ganz gut geklappt](https://wiki.comakingspace.de/Projects#Gallery) :-)

Code folgt wenn noch ein paar Schwachstellen beseitigt sind und/oder jemand Interesse hat!

**Comment by LukasFreeze** [comment]
> 
> 
> Gute Idee. Man könnte bei der Gelegenheit auch eine Art "recently added" Kategorie/Gruppe machen. Damit neu hinzugefügte Projekte etwas prominenter positioniert werden.

Finde ich gut, ich würde allerdings wahrscheinlich über den letzten Edit gehen und damit eher die zurzeit "aktiven" Projekte als nur die zuletzt kreierten Seiten (wo ggf noch gar nicht viel steht) hervorheben 👍

**Comment by LukasFreeze** [comment]
Da Interesse bekundet wurde (über [unsere Telegram-Gruppe](https://wiki.comakingspace.de/Telegram_Group)), hier jetzt der aktuelle Code :-)

https://github.com/comakingspace/Navigation-Galleries

**Comment by NitramLegov** [comment]
Einfach weil ichs immernoch ziemlich geil finde:
Die beste Maßnahme, um die Projektseiten sichtbarer zu machen war glaube ich, dass die Project Wall endlich ernsthaft existiert :)

**Comment by LukasFreeze** [comment]
Ja, innerhalb des Spaces auf jeden Fall! Hiermit hatte ich aber auch an die
Außenwirkung gedacht und werde es darum parallel weiterentwickeln, wenn mal
wieder Zeit ist ;-)

**Comment by NitramLegov** [comment]
Da wir inzwischen SemanticMediaWiki aktiviert haben und automatisierte Gallerien auf unseren Werkstattseiten bereits erfolgreich nutzen habe ich die Gallerie auf https://wiki.comakingspace.de/Projects mal in eine automatisierte Gallerie umgewandelt.

Diese zieht sich die Bilder und Beschreibungen aus den ProjectInfoBoxes. Dabei fällt jetzt auf, dass wir leider einige Projketseiten haben, die mehr Ideenbeschreibungen sind und insofern nicht in der Gallerie auftauchen sollten. Ich denke ich werde daher noch einen "Exclude" parameter einfügen :)

Was meint ihr?

**Comment by NitramLegov** [comment]
Da hier kein Feedback mehr kam nehme ich an, dass mein Lösungsvorschlag in Ordnung ist und mache zu :)

**Comment by LukasFreeze** [comment]
Oh ja, die Grundidee hier ist mittlerweile veraltet - ich hoffe da kam
zumindest mündliches Feedback ;-)

Ist natürlich viel sinnvoller über SMW, und vielleicht kommt ja auch doch
nochmal ein Update womit wir das alte Erscheinungsbild wiederherstellen
könnten (ohne hässlichen Rahmen um jedes Bild) - hatte da im Rahmen von
#161 mal angefragt, fingers crossed!

**Comment by LukasFreeze** [comment]
Eine weitere kleine Verbesserung, die grob hierzu passt: man kann jetzt ganz unkompliziert zufällige Projekte anzeigen lassen :-)
![Screenshot_20240324_223400_Firefox](https://github.com/comakingspace/do-something/assets/19755883/aaef6f85-2636-491a-9aa9-5dd9c2f8ee09)

Wenn man dabei auf etwas cooles stößt, das noch zu versteckt ist: gerne beim Verlinken helfen!
