### ISSUE TITLE
Arduino day 16.3.2019

### ISSUE THREAD

**Issue by emka** [comakingspace/do-something#97]
Am Samstag, 16.3.2019 ist wieder Arduino Day, mag jemand was organisieren? Zum Beispiel ein Seminar, oder einfach gemeinsames Arduino hacking im common room.

Registrierung bis 3.3. auf https://day.arduino.cc/

**Comment by NitramLegov** [comment]
Uuuuuuh, coole Sache!
Ich hab glaube ich einen Arduino Nano zuhause rumliegen, den kann ich gerne mitbringen.
Bin auch gerne bereit, etwas zur Arduino programmierung mit PlatformIO zu zeigen und generell beim Event mitzuarbeiten.

Außerdem haben wir inzwischen ja auch das Sensor Kit im Electronics Room liegen. Da können wir ja sicher was cooles draus machen.

Ich weiß, dass letztes Jahr @Johannes09 den Arduino Day im DAI gemacht hat. Da hab ich den nämlich kennengelernt :D Wenn wir Michael fragen könnte ich mir gut vorstellen, dass der auch das ein oder anderen beitragen würde

**Comment by Pakue95** [comment]
Ich hätte auch noch das Material vom Arduino day von 2016 falls das helfen würde. 
Die Dokumente sind noch mit dem DAI Makerspace logo (dem Ersten), aber das ist ja schnell aktualisiert.

Die Stationen von damals waren mit den Basics von Arduino:
* Blink LED
* Buzzer 
* LCD Shield
* PWM
* RC circuit
* RGB LED
* Seriel interface
* Servo

Zum zusammenstecken hatte Frank einige Breadboard Shields mitgebracht. Die bekommt man auch noch gut auf [Aliexpress](https://de.aliexpress.com/item/Newbrand-Prototyping-Prototype-Shield-ProtoShield-Mini-Breadboard-for-Arduino-Free-Shipping/32279103685.html?). Falls jemand mit den Docs + Arduino code was anfangen kann, schicke ich die gerne weiter.

**Comment by NitramLegov** [comment]
Falls hier wirklich jemand was tun will:
das make magazin hat in der Ausgabe 1/2019 einen Artikel über einige Umweltsensoren und deren Verwendung mit dem Arduino drin. Den Code gibts auf GitHub:
https://github.com/makemagazinde/2019.01_umweltsensoren

Den zugehörigen Artikel kann ich auch organisieren, falls gewünscht.

**Comment by NitramLegov** [comment]
Ich mach dann mal zu
