### ISSUE TITLE
Chopsaw is Broken

### ISSUE THREAD

**Issue by harrybiddle** [comakingspace/do-something#98]
The chopsaw cannot be used as the safety guard is dismantled!

[Five Whys](https://en.wikipedia.org/wiki/5_Whys):

 - **Why** is the safety guard dismantled?
   - Because Harry took it apart and didn't know how to put it back together.
     - **Why** did Harry not know how to put it back together?
       - It wasn't part of the training
     - **Why** did Harry take it apart?
        - He was trying to tighten up the blade
          - **Why** was he trying to tighten up the blade?
            - It was slipping on his wood he was cutting and he thought it was loose
               - **Why** was the blade slipping?
                  - Unclear: maybe it had loosened because it was blunt

Root causes: a blunt blade and Harry's lack of training on how to change a blade on the chopsaw.

Harry

**Comment by LukasFreeze** [comment]
I was not fully able to fix it today, the blade guard can get stuck in some positions and I suspect there is a washer in the wrong spot at the moment so there is too much room on one side and too little on the other. It never worked really well, but surely better than this...

Good news though: the blade still seems to be sharp, it was just dirty and gunked up from a year of use. Cleaned it by soaking in "Alles Reiniger" and hot water, then scrubbing with a sponge and a thin strip of scrap wood.

**Comment by LukasFreeze** [comment]
Fixed! And I dare say the blade guard works better than before after adding a lock nut and bending the ends of the spring coil a little :-)

A test cut through hardwood looked good, but please do report if you get any signs of a dull blade again!

**Comment by harrybiddle** [comment]
Amazing, thank you so much Lukas :)
